### ISSUE TITLE
What format is sent to VLC player

### ISSUE THREAD

**Issue by nsmith1024** [streamlink/streamlink#1021]
Hello,

I need to stream the output from streamlink to a new "player" of sorts.

For example i type "streamlink twitch.tv/etojordi best" this opens up VLC and it starts playing. Nice, but i want to send this data to a new player so i include --stdout and then it starts sending the data to standard output.

Now i can capture this data with my new player, but i got no clue what kind of data this is and the format,

1. Is it mp4 video format or something else? can i force it to output mp4
2. How do i decode the live stream data so that i can play it in mp4/ogg player?

thanks!

**Comment by nsmith1024** [comment]
If i save the stream using "-o file.mp4" it saves the stream data into that file. I can double click on that file  and it plays in windows, but if i drag the same file into a browser it wont play, but if i drag a regular mp4 into the browser it plays.

So there is something special about the file streamlink saves in that it can be played but its not a regular mp4 file.

Anybody knows what kind of data format is being streamed to VLC form streamlink and also what is the format of the saved data stream?

Thanks

**Comment by beardypig** [comment]
Generally speaking the format is the same as the original stream, and the same data goes to VLC as goes to a file. The container format of the stream depends on the provider and the stream type. HLS (which is what twitch uses) is TS (transport stream, could also be mp4 but that isn't supported in streamlink), rtmp and HDS are flv, HLS multi audio is repacked in to an mkv. Always the video and audio code remain unchanged (except in specific cases and the use of the transcode options).

**Comment by nsmith1024** [comment]
hello beardypig,
Thanks so much for your comment, so i have a custom "in house" player that can only play mp4 and ogg, is there a program or programs, that can read the stdout of streamlink, and transform that to mp4 or ogg on the fly so it can be streamed to mp4 or ogg player?

**Comment by Vangelis66** [comment]
@nsmith1024 wrote: 

> If i save the stream using "-o file.mp4" it saves the stream data into that file

... When you manually specify an ".mp4" file extension, that doesn't mean that 
streamlink will use the MP4 container, because streamlink doesn't do any remuxing 
by default; as beardypig said, 

> the format is the same as the original stream, and the same data goes to VLC as goes to a file.  

If you install MediaInfo (`https://mediaarea.net/en/MediaInfo`) you can then inspect, say, a 5min stream capture to discover its details (raw streams + media container).

> I can double click on that file and it plays in windows

That is because it so happens the media player associated with MP4 files on your Windows setup can also handle the MPEG-TS container (and video/audio codecs inside it...). 

> is there a program or programs, that can read the stdout of streamlink, 
> and transform that to mp4 or ogg on the fly so it can be streamed to mp4 or ogg player? 

I don't want to step into beardypig's shoes, but: 

A local MP4 file (playable by your custom player) is a different thing to an MP4 file streamed to your custom player:
 In order for an MP4 file to become streamable, it must have its moov atom placed in the start of the file; 
I can imagine using ffmpeg to remux the AppleHLS MPEG-TS stream losslessly to the MP4 container, 
but making it streamable requires a second pass with the `moveflags faststart` switch, also unsure if that is even possible with live streams. 

As for the OGG container, I'm afraid it may be incompatible with the audio/video codecs used natively in twitch.tv streams; you may have to implement transcoding for both the video (to theora?) and audio (to ogg vorbis?) for that to work, which is a resource hog on the streaming machine...

**Comment by nsmith1024** [comment]
Vangelis66 thanks for your awesome comment. I really know absolute ZERO about video (excepting for watching it), but i read somewhere that ffmpeg can convert the HLS TS to mp4

ffmpeg -i input.ts -acodec copy -vcodec copy out.mp4
(https://stackoverflow.com/questions/33108105/converting-an-hls-m3u8-to-mp4)

So im guessing streamlink is sending the TS data out, so maybe i just need to capture that, then somehow search that data in realtime for the start of each TS frame, then save each TS frame as a ts file, then run ffmpeg to convert that to mp4, then stream those little mp4 files to my mp4 player. Keep doing all that like mad over and over ..... LORD!!!

Does that sound like it could work? im desperate!!!!

**Comment by bastimeyer** [comment]
As @Vangelis66 said:

> unsure if that is even possible with live streams

The following command is basically what you want, but [ffmpeg needs a second pass](https://www.ffmpeg.org/ffmpeg-formats.html#Options-8) to process the data, so it's not going to work while using the live stream as input:
```bash
streamlink --stdout <URL> best | ffmpeg -i pipe:0 -c:v copy -c:a copy -f mp4 -movflags faststart pipe:0 | vlc -
```
```
[mp4 @ 0x562726d368e0] muxer does not support non seekable output
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
```
Saving the stream to the filesystem and remuxing it afterwards works fine:
```bash
streamlink --force --output /tmp/foo.ts <URL> best \
&& ffmpeg -i /tmp/foo.ts -c:v copy -c:a copy -f mp4 -movflags faststart -y /tmp/foo.mp4 \
&& vlc /tmp/foo.mp4
```

**Comment by nsmith1024** [comment]
bastimeyer - so streamlink --output commands saves individual ts files? I thought there were many little ts files that are sent during a live stream? so somehow need to separate each ts file, and convert each with ffmpeg to mp4 and re-stream each mp4 file

**Comment by beardypig** [comment]
The small `MPEG-TS` files can be combined by concatenating them in to a single stream, which is what streamlink does for both file output and player output. `MP4` has some extensions that make it more suitable for streaming, that @bastimeyer touched on. Depending on your version of `ffmpeg` this may work for you (worked for me with `3.3.1`):

```
streamlink <url> best --stdout | ffmpeg -i pipe:0 -c copy -bsf:a aac_adtstoasc -f mp4 -movflags empty_moov+separate_moof+frag_keyframe pipe:1 | player
```

**Comment by nsmith1024** [comment]
beardypig, so your telling me that the command you posted will convert the streamlink output into an mp4 stream?

**Comment by beardypig** [comment]
Yes, but it will leave the video and audio codecs as they were in the original stream - for twitch this is h264 and aac, the standard for HLS.

**Comment by nsmith1024** [comment]
ok, is leaving the video and audio in its original form a good thing (i got no idea)? I just want to be able to play the stream with my simple mp4 player.

**Comment by beardypig** [comment]
I have no idea about your simple mp4 player, if it plays h264 and aac I guess that's good for you - if not then it's not good for you and you'll need to transcode it using `ffmpeg`. Of course, if you need to transcode you'll use a lot of CPU doing it so you might as well use a different player that can actually play MPEG-TS. Why are you using whatever simple mp4 player anyway?

**Comment by Vangelis66** [comment]
@nsmith1024 wrote: 

> Vangelis66 thanks for your awesome comment. 
> I really know absolute ZERO about video (except for watching it)

... You are welcome, but with all due respect, _you do need to start from somewhere_, as have most people 
here... You should start by searching and learning the basic things about terms such a: 
1. Audio and video codecs
2. Media containers
3. Audio/video codecs supported for a specific media container
4. Streaming of media content
5. Current streaming methodologies, like the HTTP protocol based AdobeHDS, AppleHLS and MPEG-DASH
6. Basics of a media player, including support for streams
7. And since FFmpeg is probably the Holy Bible of media manipulation, it won't hurt learning basic commands for that, too! 

You don't have to become an authority on the subject, just work your way through basic stuff; I couldn't compose myself the solution command offered by beardypig, but knowing basic ffmpeg/MP4 container stuff, I can read and understand most of it ... 
 Please be also aware that although streamlink can find the path for your ffmpeg binary (the one provided with the installer), your Windows OS may not be able to, unless you add it to PATH.

This is a well-intended comment on my part; I am always of the opinion that if you give a person a fish once, you can keep his/her stomach full for one day, teach him/her to fish (and cook it) and he/she won't be hungry anymore...

> Why are you using whatever simple mp4 player anyway?

My thoughts exactly; why the need to re-invent the wheel?
Remember, your "issue" isn't a "streamlink" issue per se, just support request for your custom player, whatever that is... You should double-thank beardypig for his precious developer time (for which he goes unpaid) spent in assisting you... Again, thanks beardypig for all your efforts!

**Comment by nsmith1024** [comment]
Awesome, thanks!!
