### ISSUE TITLE
youtube live can't get 1080p60 video

### ISSUE THREAD

**Issue by wwng2333** [streamlink/streamlink#1036]
only can get 1080p

**Comment by gravyboat** [comment]
We've discussed this a number of times before in various issues. 60 FPS videos on Youtube use DASH which we don't support (as noted here: https://github.com/streamlink/streamlink/pull/225#issuecomment-263821938). I'm going to close this out. If you want to open a bounty to get support added feel free to do so, otherwise someone will pick it up when they have time. It's a big undertaking.
