### ISSUE TITLE
Should we set up a Twitter account to notify people about new releases?

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1042]
The title pretty much says it all, is this something we want to do? Someone is already using twitter.com/streamlink, and I'm not sure if it's worth our time, but it might be nice to have for new releases. Potential downsides I see are people asking questions that we aren't going to answer because no one is monitoring it, but I guess we could have a disclaimer.

**Comment by bastimeyer** [comment]
> Potential downsides I see are people asking questions

People are already asking questions in the /r/streamlink subreddit which is not being administrated by anyone here.

I'm not sure if it's necessary to add a Twitter account, but maybe it can help increasing the user base, who knows. Which name would you suggest, since `@streamlink` is already taken?

A little script could be added to the build config that automatically tweets on a new release, so nobody has to do it manually. Should be pretty simple to implement.

**Comment by sync5** [comment]
@streamlinkUpdates
@streamlinkNews
etc...

**Comment by MickelCL** [comment]
Yes Twitter is the best way for marketing, People/ Companies use Twitter cards to advertise. but the content you are advertising should be unique and engaging.

**Comment by bastimeyer** [comment]
There hasn't been a response in over half a year. I guess this can be closed now...

@gravyboat if you want to set up a Twitter account, we can add the automatic release-tweet I was talking about, but I don't know how useful it'd be. People can also subscribe to an atom feed for getting notified about new releases:
https://github.com/streamlink/streamlink/releases.atom

**Comment by gravyboat** [comment]
@bastimeyer Ehh I don't think it's worth it. Just another avenue people will try to approach for support and I don't want to moderate it.
