### ISSUE TITLE
No information in docs about how to install plugins

### ISSUE THREAD

**Issue by medialove** [streamlink/streamlink#1044]
There is no information in the docs about how to install plugins. I expected something like 
```
streamlink --plugin search xyz
streamlink --plugin install xyz
```
How to install plugins? Or are all plugins bundled with the streamlink distribution?
This should be then explained in the docs, thank you very much!

**Comment by bastimeyer** [comment]
I think the plugin matrix on the website should cover this question:
https://streamlink.github.io/plugin_matrix.html

> This is a list of the currently built in plugins and what URLs and features they support. Streamlink's primary focus is live streams, so VOD support is limited.

Installations of external plugins is covered by the docs here:
https://streamlink.github.io/cli.html#sideloading-plugins

>Streamlink will attempt to load standalone plugins from these directories:
>Platform	Location
>Unix-like (POSIX)	$XDG_CONFIG_HOME/streamlink/plugins
>Windows	%APPDATA%\streamlink\plugins

But let's hear what others have to say about this. A brief line could be added to the install or CLI docs, because this is what most users will read, but personally, I think it's unnecessary.

I also highly doubt that the average user will ever come in contact with external plugins of third parties. For creators who are writing new plugins, it should be self-explanatory what to do and where to add new plugin files (plugin API docs exist though).

**Comment by bastimeyer** [comment]
Can we close this thread?
