### ISSUE TITLE
Possibility of simultaneous viewing and recording of stream?

### ISSUE THREAD

**Issue by flijloku** [streamlink/streamlink#105]
It would be good to implement possibility of simultaneous viewing and recording of stream (to save bandwidth). Or this possibility already exists?

**Comment by scottbernstein** [comment]
Someone already implemented this for the main livestreamer build, but of course since there have been no releases, it's still sitting as a pull request.


Perhaps someone could either integrate into streamlink, or they could contact the original coder to ask him to integrate here?


https://github.com/chrippa/livestreamer/pull/1204


[https://avatars1.githubusercontent.com/u/4093184?v=3&s=400]<https://github.com/chrippa/livestreamer/pull/1204>

Add a record option by grazzolini · Pull Request #1204 · chrippa/livestreamer<https://github.com/chrippa/livestreamer/pull/1204>
github.com
I have been using livestreamer for a while now and it is a excellent piece of software. One thing I missed on it was the ability to play a stream while at the same time recording it to a file. This...




________________________________

**Comment by bastimeyer** [comment]
You can use the `-O` parameter that outputs the stream data to stdout and then pipe it into `tee`, which then writes the data into a file and pipes it further into your video player...

```bash
streamlink -O STREAM best | tee recording.ts | mpv -
```

**Comment by flijloku** [comment]
@scottbernstein Thanks, I'll try!
@bastimeyer This is for linux? Is there an analogue for windows?
