### ISSUE TITLE
Plugin request found Soundcloud

### ISSUE THREAD

**Issue by volt4ire** [streamlink/streamlink#1077]
### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ x] I have read the contribution guidelines.

### Description
I would love plugin support for Soundcloud. Is there any possibility of this being added? Thanks!

**Comment by gravyboat** [comment]
Streamlink is designed for video streaming sites, not audio track sites (though we do support audio only options) so this doesn't really fall into our scope and as far as I'm aware they don't do any live streaming. On top of that Soundcloud is about to go bankrupt so it seems like it would be a bit of a waste to build something for it. There are also already quite a few excellent applications for Soundcloud out there such as: https://github.com/grobie/soundcloud2000. I'm going to close this one out for now as it's definitely out of scope. If someone feels otherwise we can discuss it further.

**Comment by bastimeyer** [comment]
In addition to @gravyboat's comment:

Streamlink definitely violates the soundcloud TOS...
https://developers.soundcloud.com/docs/api/terms-of-use#general

Then there's also an API rate limit which is set per clientID and which is reset daily. This makes a potential implementation even more questionable.

**Comment by gravyboat** [comment]
Yep good notes by @bastimeyer. It's been a while since I wrote any code to interface with the Soundcloud API and I forgot how crappy their TOS are when it comes to the API.
