### ISSUE TITLE
Is Streamlink ready for a 1.0.0?

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#1115]
Since forking the project I've noticed that streamlink (aka livestreamer) works *extremely* well within its __core__.

The only changes I see implemented are updates to the plugins.

Is Streamlink ready for a 1.0.0 release / milestone?

We can perhaps coincide this with tweets / blog posts / etc.

RIP @chrippa 

Ping @gravyboat @beardypig @melmorabity @bastimeyer

**Comment by scottbernstein** [comment]
I like the idea of 1.0.0

________________________________

**Comment by bastimeyer** [comment]
Yeah, it's probably time for a bump to `1.0.0`. To be honest, I was surprised that Streamlink started at `0.0.1` instead of bumping Livestreamer's major version and continuing from there.
http://semver.org/

----

We should also discuss whether switching to a different versioning scheme could make sense, as this has been suggested many times now. Something like `year.month.day`, so that updates can be published faster, similar to yt-dl. This makes more sense if only plugins have been updated, but *real* major version bumps are not possible by using this scheme and it also loses its semantic meaning.

----

But before the major version gets bumped or the versioning scheme gets changed, some remaining issues should be revisited or possibly even resolved. This is an incomplete list of issues that *could* require a major version bump, and yes, I know, some of them are currently out of scope...

- revamp cli params / cli #8 
- Support VOD seeking #134
- --player-external-http only supports one connection #180 
- cli: please remove deprecated warning messages #573
- installer: build a Windows XP compatible installer #680
- Auto-detect file extension for output file #791
- Streamlink 0.6.0 fails to play streams on PotPlayer #916
- Add a Record option #920
- Enable certificate verification for Twitch #966
- Fallback selection for --stream-sorting-excludes #1055

**Comment by gravyboat** [comment]
I would also be in favor of this. I'm not a huge fan of the `year.month.day` format simply because of what @bastimeyer has pointed out, it's much harder to rationally say what is a big update versus a plugin fix build. Regarding open issues I believe that the following would be the most important from the list @bastimeyer has kindly curated (and I think those are most of the big ones):

- #134 
- #180 
- #573 
- #920 
- #966 
- #1055 

While I believe that #8 is important, it's a huge undertaking at this time. #680 I've already weighed in on and don't believe we should support XP, it is EoL, if you're still using it you are a security risk, by supporting it we are supporting people that are potentially members of botnets and other shady activities, there is no excuse not to upgrade at this point (obviously I feel strongly about this but am as always willing to discuss it). #791 would be nice to have, but how many people are realistically going to use this? In addition I'm still not a fan of people using Streamlink to download videos. #916 isn't that big of a deal to me, what percentage of our user base is even using this player? It doesn't even have the source available somewhere as far as I can tell. Past those I think most of the others are important enough to consider blocking for a 1.0.0 release. There are some other minor ones that would be nice, but this list is already a pretty big undertaking no matter how many we cut.

**Comment by beardypig** [comment]
I think we should stick to the current versioning schema, perhaps we should be more strict - but most releases add plugins which should increase the minor version, we hardly do any bug fix only releases. 

As for the specific issues, I have made some notes. 

[#8 revamp cli params / cli](https://github.com/streamlink/streamlink/issues/8), I think this is way too big to work on right now :)

[#134 Support VOD seeking](https://github.com/streamlink/streamlink/issues/134) is big, realistically I don't see that making it in for a 1.0.0 release :)

[#180 --player-external-http only supports one connection](https://github.com/streamlink/streamlink/issues/180), there hasn't been anything decided about _how_ this should work or what the user's expectation is. It might be assumed that multiple connections are simple as you just write the stream to multiple clients, and anyone joining the stream would be getting the same data as other clients. This will not work for most stream types and would need to be customised to support each stream type. Even HLS (MPEG-TS) would be tricky as you'd have to start the stream from the start of a segment. The only way I can see to implement this is to open a new stream for each client, so they wouldn't be synchronised and you'd use X times the number of bandwidth. 

[#573 cli: please remove deprecated warning messages](https://github.com/streamlink/streamlink/issues/573), I think we should just remove the deprecated messages and leave it as it is. The options are not included in the help or the documentation, the `--http-header` etc. options should be used instead but backwards compatibility is maintained. 

[#680 installer: build a Windows XP compatible installer](https://github.com/streamlink/streamlink/issues/680), I agree with @gravyboat that we should not have to support XP, it's a choice between supporting more users and not supporting (philosophically, not technically) Windows XP.

[#916 Streamlink 0.6.0 fails to play streams on PotPlayer](https://github.com/streamlink/streamlink/issues/916) is important I think, it points to an underlying issue with the retries rather than an incompatibility with PotPlayer.

[#920 Add a Record option](https://github.com/streamlink/streamlink/issues/920), just needs some final review :)

[#966 Enable certificate verification for Twitch](https://github.com/streamlink/streamlink/issues/966), lets just turn it back on! 

[#1055 Fallback selection for --stream-sorting-excludes](https://github.com/streamlink/streamlink/issues/1055), I can see why @bastimeyer would be pushing for this one ;) It's a nice to have feature.  

I have created a [Project for 1.0.0](https://github.com/streamlink/streamlink/projects/4), we should add the issues we want resolved (either implementing them, or closing as `wont-fix`) for version 1.0.0. I have created 4 columns, `Screening`, `Todo`, `In Progress`, and `Done`. `Screening` should contain issues that we want to discuss and decide if they should go in to or be resolved before 1.0.0. `Todo` is issues that we have decided should be resolved for 1.0.0. `In Progress` and `Done` are pretty self-explanatory :) What are you guys' thoughts on this approach?

**Comment by skulblakka** [comment]
>what percentage of our user base is even using this player? 

I'm not sure if this is limited to potplayer. As reported in #975 a very similar problem happens on windows quite regularly where streamlink closes after the player connected via http disconnects.

**Comment by cdrage** [comment]
@beardypig Yeah, https://github.com/streamlink/streamlink/issues/8 is a dream / epic. In the far future when I have time I'll take a look at it, but it'll be a lot of work for little-to-no-return. So let's scratch that out :+1: 

IMO, I say our only blocker is https://github.com/streamlink/streamlink/pull/920 since https://github.com/streamlink/streamlink/issues/1055 is a feature request rather than an incompatibility change (which usually constitutes a blocker for a 1.0.0)

**Comment by bastimeyer** [comment]
One thing I forgot to mention was the Streamlink logo...
I think a 1.0.0 release should require a logo that's at least *a bit* professional. 😜 😆 

If you guys are okay with this, I'll open a new thread for suggestions (so that this thread doesn't get spammed unnecessarily).

**Comment by gravyboat** [comment]
@bastimeyer I'm fine with that, I have a friend we might be able to commission but I'm not sure how much he'll charge or if he has time to work on it (his Github is https://github.com/christabor if we want to tag him) unless someone else knows somebody who can work on this and provide something semi-professional.

**Comment by cdrage** [comment]
Hey @gravyboat @bastimeyer 

Should we push a 0.8.0 instead for the time-being? Lot's of plugins have broken / been updated. I don't think we're in a rush to release 1.0.0 so pushing another release IMO would be okay :+1:

**Comment by gravyboat** [comment]
Yeah I think we should push a 0.8.0 release for sure @cdrage.

**Comment by cdrage** [comment]
@gravyboat @bastimeyer I've gone ahead and released 0.8.0!

**Comment by fishscene** [comment]
Howdy all. I was wondering where we were at with this. I apologize for really not having much to contribute to streamlink and I've been away for a few months. But if I can help get the ball rolling, well, that's a good thing, right? :) 
Note: I realize the holidays are rolling through, so no rush of course, just didn't want to see the 1.0 release die.

**Comment by gravyboat** [comment]
@fishscene We just did a 0.9.0 release and a good number of the issues we noted are still open (we also don't have a new logo which we own).

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/pull/2199
