### ISSUE TITLE
Is it safe to use RTMPDump?

### ISSUE THREAD

**Issue by Ro-Den** [streamlink/streamlink#1148]
### Checklist

- [x] This is a question.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

It may look like a little bit paranoid, but nevertheless:

1. Look into the [ReadMe](https://github.com/streamlink/streamlink/blob/725e137fb5ed6022a6d8991ab3099880b8fa3260/win32/rtmpdump/README) of the version bundled with Streamlink:

> These binaries have been compiled from the unmodified source
available at git://git.ffmpeg.org/rtmpdump (commit: df6c51884243ef2bd12931e6c617b2be7520ca26).

Then visit https://git.ffmpeg.org/rtmpdump - there is no such a commit. The last commit is fa8646daeb19dfd12c181f7d19de708d623704c0

Let's hope it's just a mistake, so nothing to get worried about.

2. Look into https://git.ffmpeg.org/rtmpdump again.

RTMPDump has not being maintained for more than a year and a half. Though the program may be almost perfect. Why should anyone worry about it?

Also, the project was put on halt after 7 vulnerabilities had been reported by LMX (limingxing) of Qihoo 360 (a Chinese internet security company) Codesafe Team and then fixed by Howard Chu (a co-author of  RTMPDump).

Just a pure coincidence, let's forget about the project's troubled past and go further.

3. There was another parallel project, the so called [KSV patches](https://github.com/K-S-V/Scripts/releases), which is widely acknowledged for being able to do the job where the official release fails. It is also widely advertised here.

The last version was released on the 15th of December, i.e. 8 days before the above mentioned vulnerabilities were patched. Then the author(s) immediately lost any interest in the project, though [he/she/they was/were pretty active thoughout the year](http://stream-recorder.com/forum/customized-rtmpdump-binaries-patch-file-t16103.html).

The K-S-V's version is not vulnerable, is it? I don't think so.

Is there an updated K-S-V's version with the above mentioned vulnerabilities being patched? I have failed to find any.

And the most important question. Why does the K-S-V's version manage to do the job where the official "unvulnerable" version fails? Is it because of its advantages? Or because of [insert your favourite conspiracy theory] ?

And finally, has anyone tried to apply KSV patches to the latest official version to check, if it's still working flawlessly?

**Comment by rebelvg** [comment]
Also, rtmpdump kills connection after it downloaded 4 GBs. Fix is described here.
http://lists.mplayerhq.hu/pipermail/rtmpdump/2013-May/002309.html

**Comment by johnthecracker** [comment]
http://stream-recorder.com/forum/showpost.php?p=93030&postcount=10

**Comment by Ro-Den** [comment]
[Just noticed:](http://stream-recorder.com/forum/showpost.php?p=92855&postcount=2)

> RTMPDump v2.4 GIT-2015-12-23 (Compiled by KSV)

So, @K-S-V is using the latest version himself. Never bothered to release it to the public or at least warn that his latest public release may contain vulnerabilities. Is it time for your favourite conspiracy theory?

**Comment by bastimeyer** [comment]
If you look at the file history of [`win32/rtmpdump/rtmpdump.exe`](https://github.com/streamlink/streamlink/commits/master/win32/rtmpdump/rtmpdump.exe), you'll see that this binary file has been added by Chrippa (in Livestreamer) on Sep 28th 2013 (eb26d8c0c384e976c6ba0b065c62843121493d47) and has not been modified since.

On Github, you can still find forks of rtmpdump with the commit ID (`df6c51884243ef2bd12931e6c617b2be7520ca26`) that was added to the readme:
https://github.com/search?q=df6c51884243ef2bd12931e6c617b2be7520ca26&type=Commits

**Comment by Ro-Den** [comment]
@bastimeyer thanks!

It's my fault, I've used Google and found almost nothing.

Finally, I've got it on [https://git.ffmpeg.org/rtmpdump](http://git.ffmpeg.org/gitweb/rtmpdump.git/commit/df6c51884243ef2bd12931e6c617b2be7520ca26). It dates back to
> Sun, 30 Dec 2012 20:52:04 +0000 (22:52 +0200)

Then, why does everyone complain that it's not working?

So, it's the same vulnerable version, if the "feature" was added before that date.

Is Streamlink (Livestreamer) a part of the conspiracy, too?

**Comment by johnthecracker** [comment]
http://stream-recorder.com/forum/showpost.php?p=93358&postcount=438

**Comment by Vangelis66** [comment]
@Ro-Den 
I honestly think this "conspiracy" thing you're suggesting is far fetched; but little do I know...
@K-S-V suggests trying to apply his latest public patch ([Patch.diff](https://github.com/streamlink/streamlink/files/1206299/Patch.diff.txt)) onto latest official rtmpdump snapshot (git-fa8646d) and compile; Have you tried that? 

 It is clear from `I haven't looked into rtmpdump project for a longtime` that he's unwilling to revisit his rtmpdump fork; so when the sites supported by the KSV fork (e.g. chaturbate?) change things and no longer work, it's doubtful he'll come to the rescue... 

If you're overly concerned about the security of the rtmpdump binary supplied with streamlink, there you go: 
[rtmpdump-2.4-20151223-gfa8646d-GnuTLS_3.5.12-win32-static.27-May-2017.zip](https://github.com/streamlink/streamlink/files/1206327/rtmpdump-2.4-20151223-gfa8646d-GnuTLS_3.5.12-win32-static.27-May-2017.zip) 

(If the streamlink devs want me to remove that personal - but redistrtibutable - win32 binary, compiled from official source without modifications, chime in and I'll oblige... )

**Comment by gravyboat** [comment]
I'm just going to weigh in here with relation to the RTMPDump dev not working on it any more. Why should they? It's the same reason Chrippa stopped working on livestreamer, at some point there is no incentive to do so. No one pays you to work on these projects, you get tired of answering questions and dealing with issues. It doesn't provide you any financial security to dedicate time to it even though there are 10s of 1000s of downloads a month, and you could spend that time more productively elsewhere, so why continue?

Who cares if you let some random person down, or that the software has vulnerabilities? You're not being reimbursed to work on it and you're spending your limited time, so there's no reason to do so. It happens to every developer at some point unless they get hired by an organization to work on the software, and even then they'll likely leave at some point.

So before we start talking about conspiracies, let's just approach it as sensible humans, you want to be rewarded for your work in a way that enhances your situation, 99% of open source projects do not receive this support, and thus people stop contributing, it's as simple as that.

**Comment by johnthecracker** [comment]
@Vangelis,

If your compilation was useless you would not have it.

It works differently than latest official one, command.txt ignored, but rtmpsuck does the job where
latest official rtmpsuck fails, at least on one site I tested.

This is hostile environment to discuss rtmpdump, and I suggest you post your link
if you have any on stream-recorder forum.

**Comment by johnthecracker** [comment]
If it was all about $$$, there would be no Linux.

Linus Torvald did say in public however that he did not start with Linux project for public good.

**Comment by Vangelis66** [comment]
@johnthecracker 

My uploaded win32 rtmpdump binaries have nothing to do with the KSV fork; I don't have a clear idea what you meant by "**latest official one**"...

> I suggest you post your link on stream-recorder forum.

I don't have a "link"; those binaries were natively compiled on a Windows Vista SP2 x86 host last May 27th (2017), with the excellent [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite).

> With your permission I'll post it.

If nothing is altered in the package and you deem people will find it useful, be my guest; FWIW, anyone can recompile it for themselves with the _m-ab suite_...

BTW, it might be better if you re-upload to a hosting service than link directly to here; I might remove my upload if it causes trouble for the streamlink repo (increased bandwidth consumption and such...).

**Comment by johnthecracker** [comment]
Is this good link to go to stream-recorder forum:

https://github.com/streamlink/streamlink/files/1206327/rtmpdump-2.4-20151223-gfa8646d-GnuTLS_3.5.12-win32-static.27-May-2017.zip

**Comment by Vangelis66** [comment]
> Is this good link to go to stream-recorder forum:

NOPE! It is linking directly to this streamlink issue; re-read what I posted already: 

**it might be better if you re-upload to a hosting service than link directly to here; I might remove my upload if it causes trouble for the streamlink repo (increased bandwidth consumption and such...).**

(I have no affiliation with the service, but frequently use `http://www.datafilehost.com/` ; upload there, 
then share the link in `stream-recorder forum` )

**Comment by johnthecracker** [comment]
I'll try that.

Cheers.

**Comment by Ro-Den** [comment]
@gravyboat, then why does someone start an open source project in the first place? And there was enough [volunteers to continue the project](http://lists.mplayerhq.hu/pipermail/rtmpdump/2015-August/002472.html). Also, the developement of RTMPDump in the commercial software has never stopped. Is it another plausible conspiracy theory?

@johnthecracker are you sure that command.txt was ever used in an official release? I suppose it's K-S-V's own invention. Just check his patch.diff And I'm not aware of any official version of RTMPSuck which fails on that goddamn israeli web site. It's only for K-S-V's patches, too.

@Vangelis66 you are right! The official version is almost useless. As for appling the patch and compiling myself, I've never tried this, 'cause I don't have the required tools. But what obstacles prevented @K-S-V from posting [the latest version he had compiled for himself](http://stream-recorder.com/forum/showpost.php?p=92855&postcount=2)?

**Comment by johnthecracker** [comment]
@Ro-Den

I'm curious.. in what commercial software I can find their own version of rtmpdump?

**Comment by gravyboat** [comment]
@Ro-Den Because you don't think it's going to gain that much traction, you just wrote it for yourself then other people started using it and you have to support them. Just because there are volunteers doesn't mean you can hand the project off without issue, you have to ensure you can trust the person, you have to hand over management, repos, documentation has to be written, etc. and sometimes that's just too much work to be worth doing. There is no conspiracy, just a tired developer who doesn't care enough any longer to continue working on a hugely successful project where they saw none of the success benefiting them.

**Comment by johnthecracker** [comment]
@gravyboat 

I cannot not to respond on this.
You are an American and you see all as $$$.
The reason of decline of rtmpdump is lack of rtmp streams on the internet.
Linux is not about $$$ to millions.

**Comment by gravyboat** [comment]
@johnthecracker But is that decline due to the the lack of continued development? I don't know, nor does it really matter. All I am saying is there is no conspiracy, just a tired developer who doesn't want to work on or maintain a project because it isn't worth their time.

**Comment by Ro-Den** [comment]
@johnthecracker

Internet Download Manager, I guess.

Jaksta used RTMPDump for sure.

TubeDigger by Xeebo. By the way, Xeebo is a very interesting person in this story. He is the "author" of the Handshake 10 hack, that launched version 2.5 developement. Later [he filed DMCA notice](http://lists.mplayerhq.hu/pipermail/rtmpdump/2012-August/002070.html) of the hack for reasons unknown. [Steven Penny also claims](https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=1177) that Xeebo is [the "anonymous" who shared some good patches with K-S-V](http://stream-recorder.com/forum/customized-rtmpdump-binaries-patch-file-t16103.html).

**Comment by johnthecracker** [comment]
I installed Internet Download Manager, tubedigger and jaksta and uninstalled them after 1 minute,couldn't find rtmpdump there. 

There is ffmpeg to be found in jaksta and tubedigger.

As those commercial packages are concerned I would look at their rtmpdump only.

Tubedigger is active member on stream-recorder forum under that name and I suspect under one another name as well.

About svnpenn ban, there is no effect to ban anybody there, anybody can post under any name.

Somebody is paying for that for who knows what reason and I don't care who and why as long as I get information

that I cannot get better anywhere else. You can send me PM at j_cool on forum if we talk beyond streamlink.

**Comment by beardypig** [comment]
Perhaps it's time to update the bundled version of `rtmpdump` at least to the latest commit in the ffmpeg repo. It's a different discussion wether we include the KSV patches.

**Comment by johnthecracker** [comment]
Is this what would enhance functionality of rtmpdump / ffmpeg and at the same time of streamlink?

https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=533

Whas this "handshake 10" ever implemented anywhere?

**Comment by johnthecracker** [comment]
@Vangelis66 ,

Your github compilation of rtmpdump package is near perfect.

I am missing only one thing: Command.txt

KSV's patch has 4066 lines. 

Would you know how to modify that patch to exclude each and every function 
and to leave only one and that is the one for rtmpsuck to create Command.txt ?

As streamlink is concerned, every possible rtmpdump can be used with streamlink for who wants it to.

Simply replace streamlink's rtmpdump with another after installation.

Here is how I compile rtmpdump like yours on ubuntu:

you may comment out or leave patch as desired:

sudo apt-get update
sudo apt-get install build-essential checkinstall git libssl-dev
git clone --depth 1 git://repo.or.cz/rtmpdump.git
cd rtmpdump
wget -c https://github.com/K-S-V/Scripts/releases/download/v2.4/rtmpdump-2.4.zip
unzip rtmpdump-2.4.zip
rm -R *.exe *License.txt librtmp.dll
# patch -p0 -i Patch.diff	
# make VERSION="v2.4\ KSV-2015-12-14"
sudo checkinstall --pkgname rtmpdump --pkgversion "2.4+git$(date +%Y%m%d)" --backup=no --fstrans=no --default
sudo ldconfig
rtmpdump

j@j:~/rtmpdump$ rtmpdump
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playpath") containing a hostname
j@j:~/rtmpdump$

**Comment by Vangelis66** [comment]
@johnthecracker 

Hello 😄 
I am quite surprised you have bumped this old issue... What I have already posted last year in https://github.com/streamlink/streamlink/issues/1148#issuecomment-320799109 and https://github.com/streamlink/streamlink/issues/1148#issuecomment-320820006 is still valid 😉 ; however, [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite) has moved away from Vista compatibility (I... _haven't_!), so I'm not sure I could recompile that RTMPDump code again in this machine... :disappointed:

One year on, RTMPDump development is not only dead, it's been _fossilised_ ! Most media providers have shifted to HTTP(S) protocol streaming (HTML5, without Adobe Flash plugin needed for RTMP streams), mainly **HLS**+**MPEG-DASH** (sadly, very often coupled with DRM)... 😢 Having said that, I still rely on RTMPDump for certain streams, like Live+VOD ITVHub content...

> Your github compilation of rtmpdump package is near perfect.
> I am missing only one thing: Command.txt
> KSV's patch has 4066 lines.
> Would you know how to modify that patch to exclude each and every function
> and to leave only one and that is the one for rtmpsuck to create Command.txt ?

I see you're the same person (**@j cool**) that posted  
`http://stream-recorder.com/forum/showpost.php?p=96210&postcount=447`
but that post was removed shortly after I started writing this reply (???) 

I am not a coder myself, so it's unlikely you'll get from me a finalised patch/diff file... 
I see you're on Linux Ubuntu, this fact alone should mean you're more equipped than me 
in the areas of source code manipulation, taking also into account native coding utilities found 
in Linux (patch, diff, sed, awk, gawk etc), unavailable by default to a Windows user like myself... 

K-S-V's patch file has been attached previously in this thread; so you could have at least tried 
to browse those _**4066 lines**_ with a text editor and search for answers there;
especially since the coder has inserted very helpful comments to his patch!
`Command.txt` is being written by both `rtmpsrv` and `rtmpsuck`; if you search the code for the
`/* Save command to text file */`
comment, you'll immediately identify the two blocks of code relevant to its creation!

```diff
line 3182:
diff --git rtmpsrv.c rtmpsrv.c
index 5df4d3a..eccaa9c 100644
--- rtmpsrv.c
+++ rtmpsrv.c
line 3593:
@@ -742,7 +941,21 @@ ServeInvoke(STREAMING_SERVER *server, RTMP * r, RTMPPacket *packet, unsigned int
 	      server->filetime = now;
 	      free(server->filename.av_val);
 	      server->filename = argv[argc++];
-	      spawn_dumper(argc, argv, cmd);
line 3608:
+
+              /* Save command to text file */
+              FILE *cmdfile = fopen("Command.txt", "a");
+              fprintf(cmdfile, "%s\n", cmd);
+              fclose(cmdfile);
 	    }
```
and 
```diff
line 3661:
diff --git rtmpsuck.c rtmpsuck.c
index e886179..0abdba4 100644
--- rtmpsuck.c
+++ rtmpsuck.c
line 3840: 
@@ -362,19 +416,104 @@ ServeInvoke(STREAMING_SERVER *server, int which, RTMPPacket *pack, const char *b
       /* hope there aren't more than 255 dups */
       if (count)
         flen += 2;
line 3908:
+      /* Save command to text file */
+      char *cmd = NULL, *ptr = NULL;
+      AVal swfUrl, tcUrl;
+
+      cmd = calloc(4096, sizeof (char));
+      ptr = cmd;
+      tcUrl = StripParams(&server->rc.Link.tcUrl);
+      swfUrl = StripParams(&server->rc.Link.swfUrl);
+      ptr += sprintf(ptr, "rtmpdump -r \"%.*s\" -a \"%.*s\" -f \"%.*s\" -W \"%.*s\" -p \"%.*s\"",
+                     tcUrl.av_len, tcUrl.av_val,
+                     server->rc.Link.app.av_len, server->rc.Link.app.av_val,
+                     server->rc.Link.flashVer.av_len, server->rc.Link.flashVer.av_val,
+                     swfUrl.av_len, swfUrl.av_val,
+                     server->rc.Link.pageUrl.av_len, server->rc.Link.pageUrl.av_val);
+
+      if (server->rc.Link.usherToken.av_val)
+        {
+          char *usherToken = strreplace(server->rc.Link.usherToken.av_val, server->rc.Link.usherToken.av_len, "\"", "\\\"", TRUE);
+#ifdef WIN32
+          usherToken = strreplace(usherToken, 0, "^", "^^", TRUE);
+          usherToken = strreplace(usherToken, 0, "|", "^|", TRUE);
+#endif
+          ptr += sprintf(ptr, " --jtv \"%s\"", usherToken);
+          free(usherToken);
+        }
+
+      if (server->rc.Link.Extras.av_len)
+        {
+          ptr += sprintf(ptr, "%.*s", server->rc.Link.Extras.av_len, server->rc.Link.Extras.av_val);
+        }
+
+      if (StartFlag == -1000)
+        ptr += sprintf(ptr, "%s", " --live");
+      ptr += sprintf(ptr, " -y \"%.*s\"", server->rc.Link.playpath.av_len, server->rc.Link.playpath.av_val);
+      ptr += sprintf(ptr, " -o \"%s\"\n", file);
+
+      FILE *cmdfile = fopen("Command.txt", "a");
+      fprintf(cmdfile, "%s", cmd);
+      fclose(cmdfile);
+      free(cmd);
+
       out = fopen(file, "wb");
       free(file);
       if (!out)
```
With the code blocks posted above you should be able to manually patch source files `rtmpsrv.c` + `rtmpsuck.c` and recompile to, hopefully, create binaries with the behaviour you desire... 

I am not savvy enough to provide any further assistance on this issue of yours, please take it elsewhere where, hopefully, real coders can come up with real solutions... 😜 You and I both have abused this tracker's hospitality, so let us end this OT discussion here... 

> As streamlink is concerned, every possible rtmpdump 
> can be used with streamlink for who wants it to.
> Simply replace streamlink's rtmpdump with another after installation.

True (and possibly the only **streamlink related** content in your latest comment...)!

Best of luck!

**Comment by bastimeyer** [comment]
Can we close this issue? I'm getting headaches reading this thread with all the deleted and edited posts. The original question has been answered a long time ago and the whole thread has evolved into off topic talk.

If you want to replace the rtmpdump binary, then you have to do it yourself. IMO, it is not worth upgrading it, since more and more platforms are moving to proper streaming protocols, as already mentioned here. We have also talked about it many times now that replacing or pushing new binary files to the Streamlink repo is a bad thing, because it is unnecessarily bloating it up. We first have to rewrite the installer/packaging build steps, so that all binaries can get retrieved from an external place/repo. I don't think that it's worth spending any time on that just for a dependency that's rarely used, but is still working fine in most cases where it is needed.

And if one desperately needs another version, they can still replace it themselves as a user quite easily. In any other case, feel free to contribute the necessary changes here with proper CI build steps for compiling the (patched) rtmpdump executable.

**Comment by gravyboat** [comment]
Yes I will close and lock it, it's quite old any way.
