### ISSUE TITLE
Augment Documentation / Website with a section "Primer / How To develop plugins"

### ISSUE THREAD

**Issue by WolfganP** [streamlink/streamlink#117]
Just as proposed on https://github.com/chrippa/livestreamer/issues/1187 , I believe this will incentive contributions to the project.

After submitting my analysis on a streaming site to help create a plugin (https://github.com/chrippa/livestreamer/issues/1156) that didn't get any traction, I was looking at the code and searching around for documentation on how to develop a plugin myself, but with no luck other than a short answer at the forums (https://groups.google.com/d/msg/livestreamer/TmVKnud0KRc/hDvURFUjrM0J) and it felt a little overwhelming to reverse engineer the plugin and related code code.

I believe that with a little help / article on plugin development, it will be possible for many contributors to add additional community plugins (albeit simple ones). Other option may be take a plugin and post it as a sample with full code comments (ie which functions are mandatory to be developed for a new site to be supported, what those functions should return to core code, etc)
Thx, Wolf

**Comment by beardypig** [comment]
I've written a fair number of plugins, and previously submitted a fairly large number of commits to livestreamer (under a different moniker).
I can give writing up an intro to writing plugins ago :-)

**Comment by gravyboat** [comment]
@beardypig That would be awesome. I looked at the plugins recently and realized that we don't really test any of them. I know it's more to ask, but if you wanted to write up the docs for both writing a plugin and writing plugin tests that would be cool. If not I totally understand.

**Comment by beardypig** [comment]
I can take a look :-)

**Comment by WolfganP** [comment]
That would be awesome. Thx a lot!

**Comment by dgoiko** [comment]
Hello.

We've to implement plugins for 30~ websites, all Spanish radios and televisions. I could find no documentation on plugin creation.

Did anyone posted the mentioned docs? I dont think I'll be allowed to create the plugins if I've to spend several hours reverse-enginering the thing, right now we're using m3u's directly, and will probably stick to that dirty and manual way in order to avoid studying SL code in depth. However, we've allways posted bugfixes or improvements made on well-documented programs.

Thanks in advance.

**Comment by voltagex** [comment]
I was going to open a new issue for this, but it's not clear from https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md how to set up a development environment for streamlink, especially if you're relatively new to Python.

**Comment by gravyboat** [comment]
@voltagex Yeah sadly this is something that we've been pretty neglectful of. You should be able to create a new virtual environment, source it, do the manual installation steps from the main readme file, and be all set to go to start development.

**Comment by voltagex** [comment]
sudo pip install -e . inside a git checkout worked for me in a pinch, but I didn't want to add instructions that include running stuff as root that doesn't need to.

**Comment by gravyboat** [comment]
Ahh yeah, I always run inside a virtual environment for development to avoid making my main installation a mess and then I don't need elevated permissions.

**Comment by bastimeyer** [comment]
If you're having trouble setting this up, just take a look at the TravisCI config:
https://github.com/streamlink/streamlink/blob/1.1.1/.travis.yml#L27-L45

And install it in a virtual env, as described here:
https://streamlink.github.io/install.html#virtual-environment

Don't install it globally (via sudo), as it will cause problems on your system sooner or later due to package management conflicts.
https://streamlink.github.io/install.html#source-code

**Comment by WolfganP** [comment]
It seems this request was never fulfilled and still get interest from some (casual) devs to write their own plugins, without the need to reverse engineer what's needed to get it working (ie https://github.com/streamlink/streamlink/issues/3195 not mentioned above).

If writing a primer takes too much time / effort, is it possible to choose a simple plugin and augment the code with comments to use as a guide / template? (ie mandatory functions needed, arguments taken, caller function indication, results to return, any other useful comment, ...)

Thx (again) in advance!
