### ISSUE TITLE
Should we consider removing (and not supporting) recording?

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1175]
### Description

Recently we've been seeing a lot of people using Streamlink for recording content, and this means they are creating issues related to recording. I am torn on supporting these users as I see very few reasons we should support recording as an application dedicated to streaming (especially the people asking us to support a site or asking for help where they are clearly stealing content). I know that we will still continue to support some forms of recording simply due to how piping can work, but I think we should discuss not supporting these users directly both in question issues, and plugin requests. The number of issues continues to grow with people asking for support or additional plugins and I feel as though the scope of the project is growing in an unsustainable fashion based on our team size. Without additional contributors/maintainers we need to keep a tight focus on what we want to maintain. I don't want to get burnt out but I've definitely been feeling it recently with the constant onslaught of issues, especially those related to recording which seem to have some of the most demanding users.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
I personaly won't be affected if recording goes.

streamlink.exe https://www.youtube.com/watch?v=y60wDzZt8yg 480p --stdout | ffmpeg.exe -i pipe:0 -c:v copy -c:a aac c:\SKY_%d%.flv

**Comment by scottbernstein** [comment]
I personally find the -o option to write files to be the number one most useful option for Streamlink

On Aug 16, 2017, at 9:17 PM, johnthecracker <notifications@github.com<mailto:notifications@github.com>> wrote:


I personaly won't be affected if recording goes.

streamlink.exe https://www.youtube.com/watch?v=y60wDzZt8yg 480p --stdout | ffmpeg.exe -i pipe:0 -c:v copy -c:a aac c:\SKY_%d%.flv

**Comment by johnthecracker** [comment]
I don't say I am against recording.

**Comment by karlo2105** [comment]
With switch -o streamlink is already able to record vod and live videos. Vlc also has an option to record while streamlink is launched, it's ctrl+r. It's enough to me.

**Comment by Techwolf** [comment]
I use to legally record a stream for offline viewing when I can watch it. Basically, a DVR. Also recording allows one to watch a show over a really bad or slow link by "buffering" an one hour at a datacenter and then send over the bad link that takes two-three hours to transfer said one hour show.

**Comment by WolfganP** [comment]
I would be against removing recording options as it's an useful functionality, but saying so and looking at the support efforts for those features, I would suggest to downplay them; ie
- stating clearly that this project is focused on live streaming, 
- that Recording issues will be treated as low priority (ie in a template when creating issues),
- document recording tips/usage in a wiki article and point to other projects (-ie youtube-dl-)

**Comment by jbarry786** [comment]
The "-o" option is an integral part of what makes streamlink great. I use it a lot to just _record_ streams at a much higher bitrate than I would be able to if I tried to just stream them.  Basically, for me "recording" is part of the streaming, because for lower bandwith users, recording the stream may give them a better viewing experience. Like @Techwolf says you can also just think of it as a DVR at times. It's very different when you are streaming something and when you are playing it offline. 

I'd like to believe that the vast majority of users who use streamlink, do it for personal use and certainly not to make money off it or something.  And the ones who use it to steal/profit from some content they watch... they are probably smart enough to figure out other ways to record said streams... in fact they may already be using the other applications. 

This is a complicated issue because streamlink is by definition used to "convert CPU-heavy flash plugins to a less CPU-intensive format". And that works and makes a huge difference - so you'd always think that more sites would be supported and newer plugins released. At the same time... if you can stream it... then you can probably also record it. I just don't see how you can have one without the other. 

The paradox here is this one... even if streamlink just 'sticks to streaming', while streamlink isn't stealing content... it is taking users away from websites. It is reducing the number of visits, clicks, the number of people who view ads. So even just "streaming", you can imagine that if streamlink ever became 'mainstream', that would cause issues... because websites want clicks and they want people to visit them. That is probably a bigger risk than some random users who record whatever and make some bucks off it.

The ones who create and maintain streamlink are entitled to make the changes they feel they should. They have no obligation to provide anything. Only them will truly know how much pressure they are put under. That isn't questionable. 

The vast majority of users just use streamlink for the basic - watch some tv. Close stream. Done. Or even if they record. It's for themselves. No malice. No matter the good intentions when creating something. And no matter that 90+% of users don't abuse it... there will always be some people who abuse stuff. So it's always the case of whether that minority is bad enough to spoil it for everyone. 

Based on the description on the opening post, 

> I don't want to get burnt out but I've definitely been feeling it recently with the constant onslaught of issues, especially those related to recording which seem to have some of the most demanding users.

I suppose a start could be to just put an emphasis on not supporting anyone who makes requests about how to record x or y. Like you say, maintain a tight focus on the basics. On what you feel are the "pure reasons" for the creation of streamlink - improving the streaming experience for users.

**Comment by bastimeyer** [comment]
@gravyboat 
I'd suggest to not remove any kind of downloading logic, as it is an essential part of Streamlink. Even if it would be removed, people who are using Streamlink to illegally download and redistribute streams will still be able to use other methods.

What we should do is adding a statement to the docs (or somewhere else) that we distance outselves from any kind of illegal activities. AFAIK, we're currently only asking users to use paid subscriptions of the streaming services that they are using, to compensate missing ad revenues, etc.

**Comment by Truanifan** [comment]
I know I've asked for help with sites or videos a lot, but I personally use the -o because my connection is so lousy that streaming videos to watch is difficult. Certainly not to share them or save them forever. If I can download the streams I can watch them without several minutes at a time of lag while the video buffers or having to watch the lowest quality possible because it's the only one that'll play without issues. I can't get a better connection either so I'm stuck which is why saving with -o is such a huge help. I understand the concerns for users misusing it to steal content. I can only speak for myself and say I don't download to save forever or share. I buy my media when it's available (much to the dismay of my finances). However, sometimes there are services that have digital content you can buy yet don't allow you to download for offline viewing or there are certain shows which are only available streaming. I would ask that you don't as offline viewing makes watching what are usually stream tolerable, but I'm not the one working on streamlink so I also understand it's not my call and I'll support whatever you choose.

If the problem is too many plugin requests or not wanting to support those who misuse streamlink maybe make a rule for those submitting issues that they can only submit errors and/or plugin requests/help, but that help with saving from a particular site or a video that's not currently supported by current features of plugins will not be answered and plugin requests will be considered however there won't be any guarantee that those requested plugins will added and if they are/will be it'll be based upon the discretion of those maintaining streamlink and at their leisure. Maybe that way any pressure can be taken off and hopefully that'll limit the number of "saving video" help requests?

I'm not sure, but I understand where you're coming from. Anyway, that concludes my two cents. Thanks for hearing me out.

**Comment by hpmueller1971** [comment]
@gravyboat 
Focus your development-resources on the core-function and let all the specific recording funktions die. There is no real plus on having internal recording-functions, but it's kinda asking for trouble (streaming sites dont like people viewing their streams without them using the website with ads, but they really HATE people recording their streams, because this is always a premium-function, if available at all).

Also, most people who are smart enough to install a solution like this are usually also smart enough to know what a pipe is, so for >99.9% it would not change anything, and the remaining 0.1% someone can tell them the closely guarded secret about pipes ;).

/my2cents

**Comment by johnthecracker** [comment]
@hpmueller1971,

webmasters HATE me in every possible way, no way thay tollerate me living and existing on this planet
in any possible way you can imagine.

And YES, there ARE conspiracies agains guys like me.

Cheers.

**Comment by foxx1337** [comment]
`-o` should be left there. It's a very nifty feature and it's trivial to have it supported; on the other hand it's pretty useless to have to transcode in any way, via pipe into ffd, VLC, etc, that which streamlink produces.

**Comment by dehesselle** [comment]
Reading through the comments above, it looks like recording a stream without Streamlink doing the actual file-writing [is trivial](https://github.com/streamlink/streamlink/issues/1175#issuecomment-322942132), even on Windows.

**"Write programs that do one thing and do it well."**
- Leave the file-writing to others and concentrate on your core functionality.
- Recording may be a nice feature, well, allow me to call it a "gimmick" (no offense intended) for the sake of my argument, but it is out of scope for this project. The only reason it's there is because it's Livestreamer-heritage. I know this is hard to swallow for the people who actually use it and got used to it, but think of it this way: if Streamlink did not have a recording option today and someone would request this feature, would you implement it or would you show him/her how trivial it is to pipe Streamlink's output into a program that can do just that?

Do not reinvent the wheel / reimplement features that are readily available by simply piping output from program A to program B.

**Comment by mtcjayne** [comment]
I guess I don't understand this concern. What exactly is so hard about writing to a file as opposed to piping to a process, and what extra support issues are being produced that would go away if writing to a file stopped being an option?

**Comment by johnthecracker** [comment]
@dehesselle,

Thank you for giving me a little credit in this issue #1175 with your link. 

Letters colored blue, is trivial, is about my comment.

I wish somebody could answer one my trivial question in one quickly closed issue.

If you can answer, please do.

https://github.com/streamlink/streamlink/issues/1242

**Comment by gravyboat** [comment]
@johnthecracker Please don't crosslink unrelated discussion like (#1242). Thanks!

**Comment by johnthecracker** [comment]
@gravyboat,

link removed.

**Comment by gravyboat** [comment]
@johnthecracker I don't think you can, don't worry about it.

**Comment by johnthecracker** [comment]
@gravyboat,

I have linked post to post this time rather than issue to issue.

Please reply if this is acceptable or not.

It is easy to revert blue [trivial](https://github.com/streamlink/streamlink/issues/1242#issuecomment-331740513) word back to black **trivial** word again if this is not appropriate attitude from my side.

**Comment by gravyboat** [comment]
@johnthecracker I'd still prefer if that wasn't part of the discussion here. My issue isn't the link itself but the fact that it doesn't have anything to do with the discussion on this issue if that makes sense. The conversation should make sense for someone just opening the issue, and I wouldn't want someone to get lost looking at other issues and becoming confused when they aren't related. Hopefully that makes sense!

**Comment by back-to** [comment]
There is no need to remove the download feature,
you can just bypass it https://github.com/streamlink/streamlink/issues/1175#issuecomment-322942132
or just use an old fork, before it gets removed

---

I think the issue here is, there are a lot of **open issues that could be closed**

if there would be some rules for plugin requests

- dead websites #874
- dash #848
- out of date #811
- stolen content #1126
- drm #336

there are more issues like this, but thats what i mean.

---

maybe add something like in [youtube-dl](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)

**Comment by thejustsoul** [comment]
Do not try to remove the recording function and it does not matter how the users use it. This is a useful functionality as well as playback. I for example use it to save the audio tracks to some streams, then to listen offline.

**Comment by h1z1** [comment]
Don't think it's the recording sites care about so much as the archiving and redistribution.  Aka, professional pirates.  Especially on cam sites people have and are entitled to privacy too.

It's also not unique to adult sites either, there are many which rip twitch for example and serve no other purpose but to extort / shame streamers - oddshot was/is a perfect example.    It's interesting to read when people think they're _entitled_ to content though.  Further ironic this "project" is pushing for donations..  

It may be trivial for some to add recording even if the option was removed, point is you'd need to know how or at least where to look.  It should never be point and click.   Unless of course some of your are trying to turn this into another Kodi legal nightmare.

**Comment by johnpolite** [comment]
@h1z1,

I read your post and struggle to understand how streamlink should work to please you.

Can you please say something again and be specific about what streamlink should do and how ?

**Comment by Jenriksen** [comment]
I do not use the recording feature myself, but I see it as a useful feature :) Maybe useful for recording streams and rewatching while on poor connections or for rewatching games in tournaments.

**Comment by TheSneakySniper** [comment]
What good would removing this option now bring you?

**Comment by johnthecracker** [comment]
Option -o should stay as is and in my humble opinion, and here is why:

with -o switch I save the stream as is without any processing, simply by naming it anything 
without any file extension.

Vlc calls this "dump" stream.

If I am wrong about this being a "raw" stream with streamlink,
I would like to hear about that here.


streamlink.exe hlsvariant://%url% best -o mystream

**Comment by johnthecracker** [comment]
This works but it is the same as using VLC on its own:

streamlink.exe --player-passthrough=http httpstream://%url% best -o - | vlc.exe pipe:0 --demux=dump --demuxdump-file=stream.dump -

How to do dump the stream with streamlink + VLC without -o switch ?

**Comment by johnthecracker** [comment]
Why think about that?

Streamlink will not open this url, neither will any player:

http://www.dailymotion.com/video/x29atae	( This is i24 NEWS LIVE )


C:\MISC\STREAMLINK>streamlink.exe httpstream://http://www.dailymotion.com/video/x29atae best
[cli][info] Found matching plugin http for URL httpstream://http://www.dailymotion.com/video/x29atae
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][info] Starting player: C:\P\VLC\vlc.exe
[cli][info] Stream ended
[cli][info] Closing currently open stream...


Now, surprise:

This will open and play the stream:


C:\MISC\STREAMLINK>streamlink.exe --player-passthrough=http -p mpv.exe httpstream://"http://www.dailymotion.com/video/x29atae" best
[cli][info] Found matching plugin http for URL httpstream://http://www.dailymotion.com/video/x29atae
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][info] Starting player: mpv.exe


I want to dump the stream and would like to use these arguments with streamlink:


mpv.exe %url% --stream-dump=file


This works but it is a story for another forum:

youtube-dl.exe -q -f hls-480 "%url%" -o - | ffmpeg.exe -hide_banner -i pipe:0 -c:v copy -c:a aac c:\i24_%d%.flv

**Comment by johnthecracker** [comment]
Streamlink will open and play this stream:

set url=http://www.dailymotion.com/video/x29atae

streamlink.exe --player-passthrough=http -p "mpv.exe -vf scale=854:480" httpstream://%url% best

This is i24 NEWS LIVE and I want to dump the stream.

How this can be done in this case?

No youtube-dl solution please, this is streamlink forum.

**Comment by gravyboat** [comment]
@johnthecracker Why are you asking questions in this thread when it is totally unrelated? I'm closing and locking this, we've had plenty of discussion on it.
