### ISSUE TITLE
picarto.tv broken again?

### ISSUE THREAD

**Issue by klendrop** [streamlink/streamlink#1193]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
After an update to the site the picarto.tv plugin seems to no longer work
...

### Expected / Actual behavior
Expected:
me$ streamlink picarto.tv/Skech best
-> vlc window opens and the stream is played

Actual:
me$ streamlink picarto.tv/Skech best
->Error messages 
This happens with streams that are part of a multi-stream and those which aren't.

### Reproduction steps / Explicit stream URLs to test
1. me$ streamlink picarto.tv/Skech best
2. ???
3. [cli][info] Found matching plugin picarto for URL picarto.tv/Skech
[plugin.picarto][error] The channel Skech does not exist
error: No playable streams found on this URL: picarto.tv/Skech
(as of writing this report the stream in question was live. I had a browser window of it open.)

###Version
$streamlink -V
streamlink 0.7.0

**Comment by skulblakka** [comment]
It looks like the problem here is https://github.com/streamlink/streamlink/blob/5ed7833426493256c382a73a11392de8fd4f56ea/src/streamlink/plugins/picarto.py#L91 
Looking at the page source every page contains ```<!-- User does not exist -->``` and thus triggers the "Channel does not exist" error. 

Removing line 91-93 in the plugin will make it work as expected. The only issue is that not existing channels will return a "Channel is currently offline" instead of the "Channel does not exist" message.

**Comment by klendrop** [comment]
I commented out those lines and it works again.
This feels more like a band-aid than a proper solution though (and I don't have the technical knowledge to propose one).
So what's the policy here? Should I close this issue or should I leave it open for a developer to close it properly?

**Comment by gravyboat** [comment]
@klendrop Leave it open so we can get the actual plugin fixed please.

**Comment by gravyboat** [comment]
Closing since the associated PR is merged, thanks for the report and discussion.
