### ISSUE TITLE
pysocks is missed in dependency

### ISSUE THREAD

**Issue by craftwar** [streamlink/streamlink#1217]
After upgrading to steamlink 0.8.1 from pip.
I need install pysocks manually to make streamlink work.

**Comment by gravyboat** [comment]
This is an issue with how pip handles deps unfortunately. We have an issue where we have been discussing it here: https://github.com/streamlink/streamlink/issues/1195 The pip team is aware and are working on a resolution with a plan to have it fixed by the end of the summer which is pretty much here. If they don't have something relatively quickly we'll probably modify it and do a small release. Would you agree @beardypig?

**Comment by beardypig** [comment]
@gravyboat I do agree :-)
