### ISSUE TITLE
streamlink is not recognized as an internal or external command, operable program or batch file...&... failed to open source output

### ISSUE THREAD

**Issue by dannYves** [streamlink/streamlink#1221]
When I was installing the exe it did say that Python was shutting down with an unexpected error but I ignored it.. when using command prompt it then said 'is not recognized as an internal or external command' so I uninstalled it and installed the latest version of Python... that still didn't work. 

**EDIT:**
So I downloaded latest version of Streamlink Portable instead, it now works... but... now I get an error code of: 
error: Failed to open source output: desktop/video.mp4 ([errno 2] No such file or directory: desktop/video.mp4)

 I am following this command:
streamlink LINK OF VIDEO best -o  "desktop/video.mp4"

Am I doing something wrong?

**Comment by gravyboat** [comment]
Unless that desktop path exists (which I highly doubt it does) then you're going to get that error because it can't open the file, you need to put in a path that is valid on your local machine. (such as `C:\Users\User\Desktop\file.mp4` on Windows, `/home/(your user name)/Desktop/` on Linux, or whatever the equivalent is on your OS since based in the  Since this isn't a Streamlink issue but a local path issue we can't provide support for I'm going to close this.
