### ISSUE TITLE
Use of Kodi video/pvr addons feasible?

### ISSUE THREAD

**Issue by hpmueller1971** [streamlink/streamlink#1225]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Kodi has a lot of streaming-plugins (like ie a (working) zattoo, ustvnow, teleboy) that streamlink does not have. Kodi-addons are also written in python. Is it feasible to write a "meta-plugin" that can use all the addons that use the kodi-addon-api or at least the kodi.pvr-api?

### Expected / Actual behavior

Dump a kodi-addon into a specific subdirectory, run the setup.py again to install everything. The different entires/options in the Kodi-GUI could be represented by different streams/stream-qualities.

/hp

**Comment by sdfwv** [comment]
PVR Addons in Kodi are written in **C++ not python**
- https://github.com/rbuehlma/pvr.teleboy
- https://github.com/rbuehlma/pvr.zattoo

---

For the **Python Addons** in Kodi,
you can't just `import xbmc` outside of Kodi
since every plugin has this somewhere in the code,
it's **not possible without a lot of changes**.

it's faster to create a streamlink plugin,
than rewriting the whole Kodi Plugin without `import xbmc`

**Comment by gravyboat** [comment]
Yeah this is definitely out of scope for something we would work on. If people want those plugins immediately they should just use Kodi as it's a fantastic application.

**Comment by hpmueller1971** [comment]
@sdfwv i was not aware that the pvr-addons are c++. Never mind, sorry for the noise :)
