### ISSUE TITLE
Streamlink add to previously recorded stream with same name

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#1242]
- [x] This is a feature request.

When a stream ends, I believe it would be a nice addition to have an "add to" option added to the rewrite options; or to have an "add to" stream flag.

`[cli][info] Opening stream: 720p60 (hls)
File test.mp4 already exists! Overwrite it? [y/N] `
and instead add to that something like 
`File test.mp4 already exists! Overwrite it or add to it? [y/n/a]`

Or if this suggestion is not liked, then if it's possible it would be nice to have a flag that allows adding to previously cut off streams.

**Comment by gravyboat** [comment]
The file that is written out has specific frame data, so it would somehow have to pick that up which seems prone to errors and outside the scope of the project. What's the issue with just using whatever video editing software you have to splice them together? I guess I'm not seeing the use case here that isn't addressed by simply creating a new file or editing them together.

**Comment by bastimeyer** [comment]
We already had this question here: #1035

You can't simply glue video/audio streams together. This is highly dependent on the used codec, its parameters and container format of both streams. See this ffmpeg wiki page and see how complex this is:
https://trac.ffmpeg.org/wiki/Concatenate

I don't think it is Streamlink's job to concatenate streams. Even if it was supported here, I still have to doubt its usefulness, because concatenating live streams with interruptions between them doesn't make any sense. And if you still want to do this, you can achieve this by using the stdout parameter and ffmpeg.

**Comment by johnthecracker** [comment]
@bastimeyer,

you are right about everything you say but I still wanted sometime to concatenate stream chunks "on the go"
with fmpeg and you are the first to give a hint it is possible with ffmpeg without concat parameter "afterwards".

Can you please write here one working line of code with ffmpeg and stdout?

I don't care about interruptions within stream.

**Comment by gravyboat** [comment]
I'm going to close this for now since the main topic has been resolved.

**Comment by bastimeyer** [comment]
I don't know how to do this with ffmpeg in one go while having a proper video/audio container. This is a question you need to ask elsewhere, as it's a ffmpeg related question with file inputs, stdin inputs and writing to the same input file again. Also, as I've said, this is highly dependent on the input formats.

If you're recording HLS streams, then you can simply concatenate all MPEG-TS segments (which is what streamlink is doing, anyway). This will result in a file with broken timestamps though, so you need to fix it with ffmpeg afterwards. I'm remuxing it here to mp4, because writing the input file is not possible.

```bash
# append the new concatenated MPEG-TS segments to the previous recording
streamlink --stdout URL QUALITY >> recording.ts
# remux to mp4 (and fix)
ffmpeg -i recording.ts -c copy recording.mp4
```

That's all I can do to help you.

**Comment by johnthecracker** [comment]
@bastimeyer,

Thank you for the reply. I appreciate it.

**Comment by gri1n** [comment]
> @bastimeyer,
> 
> you are right about everything you say but I still wanted sometime to concatenate stream chunks
> "on the go"
> with ffmpeg and you are the first to give a hint it is possible with ffmpeg without concat parameter "afterwards".
> 
> Can you please write here one working line of code with ffmpeg and stdout?
> 
> I don't care about interruptions within stream.
> 
> http://ffmpeg.gusari.org/viewtopic.php?f=13&t=3621

Did you ever figure out how to do this?

**Comment by johnthecracker** [comment]
I didn't try much because I didn't need it really.
One example is filmon plugin. It does precisely that, at least with BBC.
It may be easier to learn Python and analyse filmon plugin 
rather than struggle with ffmpeg.
For now I don't have an answer for ffmpeg playing chunks without interruptions.

**Comment by johnthecracker** [comment]
@gri1n ,


just noticed..
looks like a few new switches, I cannot think of better reference for ffmpeg:

http://ffmpeg.org/ffmpeg-protocols.html#http

-reconnect_at_eof
If set then eof is treated like an error and causes reconnection, this is useful for live / endless streams.

-reconnect_streamed
If set then even streamed/non seekable streams will be reconnected on errors.

-reconnect_delay_max
Sets the maximum delay in seconds after which to give up reconnecting
