### ISSUE TITLE
tvcatchup plugin broken

### ISSUE THREAD

**Issue by kark445** [streamlink/streamlink#1254]
tvcatchup.com/watch/dave
they encoded their source with base64

```
function b64DecodeUnicode(str) {
  // Going backwards: from bytestream, to percent-encoding, to original string.
  return decodeURIComponent(atob(str).split('').map(function(c) {
    return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
  }).join(''));
}
var a7b5b2a9d1f72b8d2202fc725e95a9b58 = "aHR0cHM6Ly9zMTQ3LmNkbi50dmNhdGNodXAuY29tL3BzaGlmdF9zZXNzX2VjMGNkNTBhODM1ODkvZGF2ZV9hZHAubTN1OD9jbGllbnRLZXk9MTk5MzhiODkxYTRmN2UzZjZlNTNjMWU1ZTFmZjhhYmMtTVRVd056QTJNRE0wT0E9PSZkZXZpY2U9d2ViJmNoYW5uZWxpZD0yMCZjaGFubmVsPTIwJmVhPVRXOTZhV3hzWVM4MUxqQWdLRmRw";

jwplayer('playerrpKPIEPXXyLT').setup({
  file: b64DecodeUnicode(a7b5b2a9d1f72b8d2202fc725e95a9b58),
  width: '100%',
  //height: '480',
  aspectratio: '16:9',
  autostart: 'true',
  stretching: 'exactfit',
  cast: {}
});
```

**Comment by bastimeyer** [comment]
I've fixed your unformatted code example. Please use proper markdown next time, so people can actually read and understand it. We are already requesting this in the issue template (which you've ignored btw) and have linked a tutorial for newcomers it in the guidelines. I'm complaining a bit here, because I'm constantly fixing those kind of malformed issue texts here in the Streamlink issue tracker. It's getting quite annoying after a time, just because people don't want to take one extra minute of their time. You are requesting a plugin fix, so please be as helpful as possible for the developer(s) who want to fix this plugin. Thank you.

**Comment by beardypig** [comment]
@kark445 Dave is no longer available on tvcatchup.com, as far a I can tell - correct me if I am wrong though.
