### ISSUE TITLE
Can streamlink unmute twitch VODs?

### ISSUE THREAD

**Issue by wewedf** [streamlink/streamlink#1314]
----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I've heard that livestreamer could be used to unmute VODs but moments ago I tried with streamlink and the VOD was still muted.

If steamlink is unable to, is there any other way to unmute twitch VODs now? Thanks for reading!

### Reproduction steps / Explicit stream URLs to test

1. stream the VOD with --player -passthrough hls:
streamlink --twitch-oauth-token ######################### https://www.twitch.tv/videos/188092006?t=1h58m00s 360p --player-passthrough hls

### Environment details

Operating system and version: Win10

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
I had a quick go, but I couldn't see any way to play the unmuted stream.

**Comment by dojima** [comment]
A few years ago this was possible, since Twitch only 'soft' muted the VODs.  As of a few months ago when I last looked into it, they now remove the audio stream from the VOD itself.  Within the first 48 hours or so of the original stream, they actually host both the muted and unmuted streams simultaneously.  If you're quick, you could grab the m3u8 playlist using the --stream-url command line option, then open it and delete the 'muted' references from the playlist to view the unmuted VOD, but these are soon deleted or otherwise obfuscated, leaving only the muted VODs.

**Comment by gravyboat** [comment]
We aren't going to bypass whatever mechanisms they have in place to do this, it's asking them to come down on us hard and screw us when they have been very passive up until this point. If someone uploads an unmuted VOD (why you would do so to steal views from the creator I can't understand) and it was tied back to us with a DMCA claim and Twitch was informed it could be a huge issue. I'm going to close this, if you want to view the live stream that doesn't have audio muted that is fine, but purposefully bypassing their muting system is something I'm pretty sure violates their TOS, or at least puts us (further) on their shit list.
