### ISSUE TITLE
dynamic quality adjustemnt

### ISSUE THREAD

**Issue by plexigras** [streamlink/streamlink#1318]
### Checklist

- [x] This is a feature request.
- [x] I have read the contribution guidelines.

### Description

adjust quality to the amount of available bandwidth.

### Expected / Actual behavior

i would like to switch to a worse quality rather then have the stream buffer or crash.

**Comment by gravyboat** [comment]
As far as I know (correct me if I am wrong @beardypig) Streamlink has no mechanism for this, and we don't plan to add such a mechanism as it would require all sorts of network inspection and a variety of other nonsense that isn't really worth doing. You could probably write some sort of wrapper, but once the connection is established it has to stop because we are pulling specific streams for the quality settings. I'm going to close this for now, if someone comes along and proves me wrong we can discuss it, but this is way out of scope to me.

**Comment by beardypig** [comment]
@gravyboat is correct. We could add a dynamic quality, but it would only work with some stream types, and would only work with `player-passthrough`. So, it's probably not something anyone will work on for a while - it would probably be a significant amount of work.

**Comment by plexigras** [comment]
i don't know how streamlink works under the hood, i thought it would be cool to have something like this.

**Comment by beardypig** [comment]
@plexigras I agree :) One day, maybe :)
