### ISSUE TITLE
Plugin contributions

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1343]
I want to contribute plugins, but I would find really useful if there is a template or some documentation on how to make one following API properly. I looked at https://streamlink.github.io and docs subfolder but didn't find anything.

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

**Comment by bastimeyer** [comment]
Thanks for considering plugin contributions.
There's a discussion about the lack of proper plugin documentation over here (#117), so this thread is technically a duplicate.

For now, you have to take a look at already existing plugins and how they extend the base plugin class:
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py

Maybe the [API reference](https://streamlink.github.io/api.html#) is a bit of help, but some stuff hasn't been changed since the fork (#1141)

**Comment by WolfganP** [comment]
I did a similar request a while ago at https://github.com/streamlink/streamlink/issues/117, but the guide/docs never move forward AFAIK.

**Comment by Twilight0** [comment]
Thank you, feel free to close this issue if necessary.

**Comment by beardypig** [comment]
@Twilight0 if you want some help, I am will to help - either on https://gitter.im/streamlink/streamlink or via email (my username `@protonmail.com`).

**Comment by gravyboat** [comment]
@Twilight0 Since people have already chimed in a bit here I'm going to close this one out and mark it as a duplicate just to try and keep the issues a bit cleaner. Thanks for your interest in contributing!
