### ISSUE TITLE
What about adding a new option for updating plugins

### ISSUE THREAD

**Issue by fozzysec** [streamlink/streamlink#1347]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

The plugins for this project changes frequently because of the changing of stream websites. While the release of the new version is slower than the plugin change. Should we add an option to update plugins from the master branch of github repository? I think to implement it we need an indexing file to manage the checksums of plugin files. After the option added, users can easily update their plugins by a `streamlink --update-plugins`.

### Expected / Actual behavior

`streamlink --update-plugins`

```
updating plugins/a.py
updating plugins/b.py
...
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Hmm, while this is possible I have concerns around potential exploitation, as well as large numbers of requests against GitHub that could potentially get us in trouble. We also have the nightly builds that users can download if they need the latest release of a plugin. Do you feel as though nightlies do not resolve this to a satisfactory degree?

**Comment by fozzysec** [comment]
I think just downloading from the main repositories will not have serious security problems because the PRs are reviewed and any potential malicious code will not be merged into the plugins. And we can make streamlink check for plugin updates manually. Just requesting a simple indexing file on GitHub should not result in serious problem because it is not designed to check for updates every time it starts. The nightly buildings have some limitions, reinstalling streamlink is a bit annoying, especially on Windows. Also there may some custom plugins under the directory, a update plugins option should be much better.

**Comment by fozzysec** [comment]
I think the only problem with it is that when contributer modifying or adding a new plugin, they need to run a script to update the index file of plugins.

**Comment by RosadinTV** [comment]
Another possible problem is that with the addition / update of plugins new dependencies or changes in the program code (cli) may be required.
Something that could speed up the update of Plugins is the removal of the folder "win32" from the main directory of Streamlink.
The size of [master.zip](https://github.com/streamlink/streamlink/archive/master.zip) would be 1.75 MB (instead of the actual size of 57.5 MB), being able to quickly extract all updated plugins from "streamlink/src/streamlink/plugins".
The folder "win32" could be moved to a new repository or included directly in the Releases (installers / portable versions) ... although we should also think about this situation in the installation with pip.

**Comment by fozzysec** [comment]
@RosadinTV I think only a simple update on plugins works in most cases. As for those plugins that rely on new features added in the main framework, they should reinstall the whole streamlink, this can reduce many works on updating the whole program, because there are many environments, such as Win32, pip on Windows and etc.

**Comment by RosadinTV** [comment]
@fozzysec Yes, i like the idea of this addition.
Some ideas to implement it could be:
1) Your index file idea.
Pros: Get all plugins checksum at once without limit.
Cons: Updating the index file of plugins
2) Rely on Github API to index the files ([link](https://api.github.com/repos/streamlink/streamlink/contents/src/streamlink/plugins))
Pros: Get all plugins checksum at once without the need of updating an index file.
Cons: There is a rate limit of 60 request per hour for unauthenticated requests.
3) My idea of shrinking main repository.
Pros: Replace whole plugins folder to the latest one at once (avoiding the need to compare the checksum of each plugin and download them one by one) without limit.
Cons:  You couldn't known when plugin updates really exist, since only the ETag of the master.zip would be taken into account.
4) Use simple HTTP requests (without using the API) to get data (like we do with mostly all the Plugins).
Pros: No limits and can be combined with other methods/ideas.
Cons: It may stop working if Github changes the website design.

Sure there are many other ideas, but this is what I can think of at the moment 😆

**Comment by fozzysec** [comment]
@RosadinTV But there are also some condition that users have their own plugin in the plugins directory, replacing the whole directory may result in losing of those plugins. For example, I have some modified plugins to record streams when it is available. I think the Github APIs is ok, 60 requests per hour is enough for checking plugin updates. Do you have any idea on how to solve the problem with custom plugins without using GitHub API and an updating on index file?

**Comment by RosadinTV** [comment]
@fozzysec I think we can detect the plugins that were modified by the user with "last modified date" attribute.
All the files have the same "last modified date" (the commit date) .. so any plugin that had a different date could be assumed as modified.
But once the plugins are updated following that logic they will be detected as modified plugins 🤣

**Comment by beardypig** [comment]
@fozzysec what kind of modifications are you making to the plugins? Additional plugins can be loaded from a separate directory, see [Sideloading Plugins](https://streamlink.github.io/cli.html#sideloading-plugins).

**Comment by fozzysec** [comment]
Now that custom plugins can be placed into a directory under user's home, it has no affect on updating the whole `plugins` directory. Should we updating the whole project by downloading a master.zip and replacing the old ones to avoid the problems caused by plugin dependencies on new code or just updating the `plugins` directory to make the work simple? I think using the GitHub API to update the `plugins` is enough for doing that.
What do you think of it?

**Comment by back-to** [comment]
you could just use `git` if you want an updated version

or for windows the nightly exe

**Comment by bastimeyer** [comment]
I am against implementing such a feature as described here. This would turn Streamlink into some kind of package manager, and this doesn't belong here. There is too much which could go wrong.

The only thing which could be done to improve the situation of rapidly changing plugins is having a different release model. Since the semver notation is compatible with the ISO8601 date notation, automatic releases could be built on a weekly basis instead of manually doing this every couple of months.

Apart from that, you could just install the latest version from the git master branch by using pip or setuptools or use the nightly builds on Windows if you don't want to manually build Streamlink.

**Comment by back-to** [comment]
doesn't seems like this will be added.
