### ISSUE TITLE
picarto.tv plugin broken

### ISSUE THREAD

**Issue by NHOrus** [streamlink/streamlink#1354]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Picarto.tv plugin erroneously reports channel offline

### Expected / Actual behavior

Command: streamlink https://picarto.tv/RedAxis best
causes player to open, stream to start in it.

Actually reports [plugin.picarto][error] The channel RedAxis is currently offline

When channel physically online and can be viewed in browser.

### Reproduction steps / Explicit stream URLs to test

1. Try open any picarto.tv stream
2. Fail
3. Check that stream works in browser

### Environment details

Operating system and version: Windows 7, OpenSUSE Tumbleweed
Streamlink and Python version: streamlink-script.py 0.8.1 for windows, streamlink 0.9.0 for Linux, Python 3.6

### Comments, logs, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by zootboy** [comment]
OK, I've been digging into this a bit. It seems like the changes are mostly to the html of the Picarto stream page, and the plugin uses some semi-fragile regexes to scrape that page. Should be fairly simple to fix.

The only backend change I've noticed is the load balancer API page. It seems to now return json instead of just a url:

`$ curl https://picarto.tv/process/channel -d loadbalancinginfo=twokinds`

`{"edges":[{"label":"US East","id":"us-east1","ep":"edge5-us-east.picarto.tv"},{"label":"US West","id":"us-west1","ep":"edge5-us-east.picarto.tv"}],"preferedEdge":"us-east1","techs":[{"type":"application\/x-mpegurl","label":"HLS"},{"type":"video\/mp4","label":"MP4"},{"type":"rtmp\/mp4","label":"RTMP Flash"}]}`

In watching the behavior of the web client, it seems like the token field is just "public", so the token extraction code can probably be removed. Did this token serve any purpose previously?

**Comment by wjtk4444** [comment]
Not sure if that will help in any way, but afaik Picarto is (done?) testing their new API. I have contacted their support some time ago, and they fowarded me to use `https://api.picarto.tv/v1/channel/name/$channel_name` when I wanted to get info about a channel (status, title, etc)
They _may_ have a new API that could be used in streamlink.

Sorry for wasting your time if my comment is irrevelant. My knowledge about python and how streamlink works is close to none, it was just a random thought I had while reading this issue and viewing plugin's source code (`API_CHANNEL_INFO` url does not contain `/v1/` part, so it may be outdated)

**Comment by zootboy** [comment]
Oh, this is very helpful. I didn't know they had a documented API. I'll see about incorporating this into my updates.

**Comment by NHOrus** [comment]
I would be very glad if minimal viable fix gets in first and API-based rework second. Possibly with next release.

Currently using your branch as temporary substitute, waiting for update. Your patch, as it is now, appears to be working.

**Comment by zootboy** [comment]
Thanks for testing it. I just pushed one more update to my branch that uses the official APIs. If you could test it and report your results on the pull request ( #1359 ), that would great.

**Comment by NHOrus** [comment]
Works, thank you.
