### ISSUE TITLE
ZDF Mediathek-Plugin not working anymore

### ISSUE THREAD

**Issue by lawli3t** [streamlink/streamlink#138]
The ZDF Mediathek got a relaunch with a change of url structure and a new API. The plugin needs to be adapated to meet the changed platform.

As I am an avid user of this plugin myself, I will definitely take a look into it, but it might take awhile as I never wrote one before.

Is the original developer of this plugin present by chance?

**Comment by bastimeyer** [comment]
> Is the original developer of this plugin present by chance?

https://github.com/streamlink/streamlink/blame/master/src/streamlink/plugins/zdf_mediathek.py
@skulblakka

**Comment by lawli3t** [comment]
Oh, could have looked that up myself - sorry. Didnt take a look at the existing plugin yet, cause i reckon you can't reuse much of it.

**Comment by skulblakka** [comment]
@bastimeyer I don't mind ;)

I basically know how to get the streams and everything however I can't wrap my head around the validation stuff @chrippa  implemented into the plugins (that wasn't there when I made the original ZDF plugin).

**Comment by skulblakka** [comment]
I tried my best to get this working. You can take a look over [here](https://github.com/skulblakka/streamlink/blob/b315f995b4c6a25e6910807599d8b7ad2f3d171f/src/streamlink/plugins/zdf_mediathek.py). 

There are a view issues however:
* Because I still not fully understand how the validation works, my solution might not be very beautiful
* I kept using HDS and HLS like in the previous version which results in streams being displayed with resolution (HLS) and others with bitrate (HDS)
* Livestreams don't work, because we cannot detect the video ID from the URL (I don't know if we can fix this as all streams are displayed on the same page without the URL changing)

**Comment by lawli3t** [comment]
If we want to stop from showing bitrate AND resolution, then we would probably drop one of those (except if we translate them, if there is a fixed resolution for each bitrate - but i guess not) - but i dont think it's worth.

I don't see a problem with the validation.

You can click on the program to open a specified page that shows the livestream, i just tried with [maybrit ilner](https://www.zdf.de/politik/maybrit-illner/maybrit-illner-vom-10-november-2016-102.html)

This works as is with your current solution. Might add some newlines in the get_streams so it doesnt look so filled up. Also you can remove the parantheses at line 85. I will create a pull request in your fork for that.
