### ISSUE TITLE
YouTube stream recording freezes after exactly 6 hours

### ISSUE THREAD

**Issue by Matasx** [streamlink/streamlink#1380]
Hi,

YouTube stream recording freezes after exactly 6 hours. I happened to me twice already. As you can imagine, it is difficult to investigate in reasonable ammount of time. Unfortunatelly I do not have any logs handy that might help. The recorded video is exactly 6h long which is strange, but the recording process does not quit, it rather hangs.

Any ideas? Am I missing some settings? I tried to go through all the settings but nothing seemed to be related.

Any help would be much appreciated. Thanks.

**Comment by gravyboat** [comment]
This isn't something on our end. We've had some previous discussion on this before: https://github.com/streamlink/streamlink/issues/1058 with another service and it's most likely that Youtube is just invalidating some key that is associated with the stream after 6 hours per connection, they close connections that have been open for 6 hours, or that the URL of the stream changes after 6 hours (there are a few youtube livestreams that do this) and the one you have is no longer live. I'm going to mark this as out of scope and won't fix since we can't do anything about it. You could try to write a small wrapper around Streamlink so that it just runs another Streamlink command call to the stream when it is finished and stacks them up as an option though.

**Comment by Matasx** [comment]
I have such wrapper in place, the problem is that streamlink does not quit when this occurs so detecting this case on my end is difficult.

**Comment by gravyboat** [comment]
What does the log output say at the end of the 6 hours if you run the command with `-l debug` and `-v` for debug output and verbose logging?

**Comment by Matasx** [comment]
Ok I will try to do that, but will take me a while to get back with results...

**Comment by Joshfindit** [comment]
Spitballing: is it possible your drive is running in to a max file-size problem?

At common bitrates, 6hr is very close to 4GB.

**Comment by Matasx** [comment]
No, it is already over 4GB and I am using NTFS.

**Comment by back-to** [comment]
type `streamlink https://www.youtube.com/watch?v=9c_Bac-17Rk best --json`

inspect the url, there should be something like this.
`expire/1515120411`

https://duckduckgo.com/?q=unix+time+1515120411&ia=answer

the youtube url is just **6h valid**

---

requesting a new and replacing the old url after **X time** could solve this,
 but i don't know if there is a decent way to do it in streamlink.

**Comment by Matasx** [comment]
It turned out that streamlink is exiting "properly" after 6h. The issue was on my part. So no issue here, if exiting after source expiration is considered to be correct.
