### ISSUE TITLE
Caching external

### ISSUE THREAD

**Issue by willbrow** [streamlink/streamlink#1401]
I keep getting latency/glitching when using --player-external-http but i have to use this as player is external.The stream source is HLS and i have increased both --hls-live-edge and --hls-segment-threads.

Is there anyway to cache with --player-external-http ?

I believe the issue is because there is no caching so any slight delay in fetching any of the segments is causing slight glitch also the stream is aes-128 with no drm so maybe there is delay in decoding the segments but would be happy for any other recommendations or fixes.

Thanks

**Comment by back-to** [comment]
@willbrow 

**nobody can help you without more details,**

- which **url** does you want to open?
- what is your **device**?
- can it play the bitrate?
- can your streaming pc handle the bitrate?
- does it happen with a lower bitrate?
- is your network stable enough?

**Comment by willbrow** [comment]
I have tried to play on multiple devices with the same issue and thw issue is there also if i lower the bitrate on streamlink with regards to the network i have done iperf3 speedtestcli and mtr.

When i have the issue in vlc messages it shows normally that there is about 15ms video missing or delivered late.

As mentioned above it seems that i need to enable a cache is this possible as im guessing this will let the player skip ahead abit download segements and decode the aes 128.

Thank you for everyones help

**Comment by back-to** [comment]
@willbrow 

**run a debug command** `-l debug` with your commands
https://streamlink.github.io/cli.html#cmdoption-l

and copy the output _here_ or https://gist.github.com/

make sure your _latency/glitching_ is in it

---

**but this alone won't help, because you don't share any details!**
- **url / website?** does this website even give you a 100% stable playback?
- **bitrate and resolution**?
- **your player device?** can it play the stream?
- **your streaming device?** can it handle the stream?
- **same network or is one device somewhere else?**

**Comment by skulblakka** [comment]
>As mentioned above it seems that i need to enable a cache

If you are using the --player-external-http you are starting the player manually after streamlink opened the stream right? If that's the case you can simply enable caching in your player. How to do that depends on the player you are using. (You mentioned VLC. If you are opening the stream via the "Open network stream" dialog you can click "Show additional options" on the bottom and increase the buffer there)

**Comment by back-to** [comment]
not enough details

**closing**
