### ISSUE TITLE
Best format for downloading & watching at the same time?

### ISSUE THREAD

**Issue by cog-videogames** [streamlink/streamlink#1426]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hello! Great tool :)

I have a stream that I love to watch, but I frequently need to attend to a health matter while it's live. I sometime also need to walk away entirely and watch it later.

I'd like to download the stream to a file, and watch it at the same time - ideally, allowing me to pause and walk away for a few minutes, then come back and turn up the playback speed to catch up. So far, I've tried `-o name.mp4` with `mp4`, `mvk`, and `flv` formats, but when I catch up to live, VLC closes.

1. Which formats or flags should I use to let myself catch up without VLC closing?
1. Which flags should I set to have a large pause buffer? Can I just `--ringbuffer-size 2048M`, or is there more to it? I have plenty of system memory.

### Expected / Actual behavior

Expected: I can use file as a live buffer, pause, and catch up to live as desired

Actual: VLC closes, presumably thinking it's reached the end of the file

### Reproduction steps / Explicit stream URLs to test

1. Currently, all I've done is things like `streamlink --loglevel debug --ringbuffer-size 100M -o twitch.mp4 --twitch-disable-hosting twitch-URL best` to try out different download formats.

### Environment details
```
$ streamlink --version
streamlink 0.9.0

$ python --version
Python 3.6.2
```

Windows 7 SP1, 64-bit with a MINGW64 Bash environment

### Comments, logs, screenshots, etc.

Thank you for building streamlink, it's awesome!

**Comment by bastimeyer** [comment]
> I'd like to download the stream to a file, and watch it at the same time

See https://github.com/streamlink/streamlink/issues/105#issuecomment-256678800 and the related questions which are linked there at the bottom of the thread.

There's also #920 which implements a record option (write to file and launch player at the same time), but this pull request still has some unresolved issues and hasn't been merged yet.

> So far, I've tried -o name.mp4 with mp4, mvk, and flv formats, but when I catch up to live, VLC closes.

These are just file name extensions and have no impact on the actual stream data, namely the container and its video/audio streams. If you're watching Twitch streams, you'll get a MPEG-TS streams (HLS protocol) containing h264 video and aac audio data.

> Which formats or flags should I use to let myself catch up without VLC closing

If you want to pause and resume a live stream later on, you should set a larger caching value in the player. This of course depends on the player and the transport method used by Streamlink.

In VLC (see its [command line parameters](https://wiki.videolan.org/VLC_command-line_help/)), you can define custom `--file-caching` or `--network-caching` values. I don't use VLC, so this might be wrong, but I think this is what you're looking for:

```bash
$ streamlink --player vlc --player-args '--file-caching 300000 {filename}' URL QUALITY
or
$ streamlink --player vlc --player-args '--network-caching 300000 {filename}' --player-passthrough http URL QUALITY
```

> Can I just --ringbuffer-size 2048M

This should only work if the player doesn't read any data from Streamlink while being paused. I wouldn't use this method, as you won't be able to jump around in the timeline of the resumed live stream, since your player didn't actually cache the data, but instead Streamlink, which will just continue to feed the data to the player from where it stopped. Don't quote me on that, though.

The `--ringbuffer-size` parameter desperately needs a better documentation...

**Comment by silentbrains** [comment]
Another option which may or may not be useful is the VLC command line option `--play-and-pause` , which will pause when it reaches the end of the file. To resume, you have to rewind a few seconds or so before trying to play again, though. Also, occasionally VLC will lock up.

**Comment by beardypig** [comment]
Assuming bash on MinGW64 has `tee`, you might be able to do 
```
streamlink -O --twitch-disable-hosting twitch.tv/blah best | tee twitch.ts | vlc - 
```

Using the option `-O` to pipe the video to `stdout`, `tee` will write the data to a file (`twitch.ts`) and then pipe it back out to `stdout`, where it can be played by `vlc` (use `-` to read from `stdin`).

**Comment by cog-videogames** [comment]
Thanks to everyone who replied!

> This should only work if the player doesn't read any data from Streamlink while being paused. I wouldn't use this method, as you won't be able to jump around in the timeline of the resumed live stream, since your player didn't actually cache the data, but instead Streamlink, which will just continue to feed the data to the player from where it stopped. Don't quote me on that, though.

That makes sense, thank you. In my case though, to catch back up to live I just turn up the playback speed in VLC, rather than scrubbing. So it sounds like either your VLC method or just a very large ringbuffer will do what I want, but the VLC option seems cleaner.

> Assuming bash on MinGW64 has `tee`

Yes, MinGW64 has a full coreutils. You get when installing the standard [Git](https://git-scm.com) distribution, I heartily recommend it to anyone who wants to Bash on Windows :)

---

The stdin option mentioned by @bastimeyer and @beardypig seems to work well. I put together a small script, it could still use a switch the the VLC buffer instead of streamlink, but it's great for me so far:

```bash
#!/usr/bin/env bash
set -euo pipefail

# Save and buffer a stream to a file, while allowing for asynchronous viewing

if [ "$#" -ne 1 ]; then
	echo "Usage: watch.sh [url]"
	exit 1
fi

URL="$1"
channel=$(basename "$URL")
datestamp=$(date +%Y-%m-%d--%H-%M-%M)
filename="$channel-$datestamp.mkv"

streamToPipe() {
	CMD+=(
		# Allow for long pausing? Maybe?
		--ringbuffer-size 400M

		# Only watch when primary
		--twitch-disable-hosting

		# Closer to live, just pause for a sec if it buffers
		--hls-live-edge 1

		# Output stream to stdout
		-O
	)

	streamlink "${CMD[@]}" $URL best
}

# The natively-downloaded video has a problem with keyframes (?)
# This will mean that scrubbing in VLC will result in a gray smear.
# Easily fixed by ffmpeg!
fixup() {
	# Switch to this version to just save anyway
	# tee "$filename"

	tee >(ffmpeg -i - -c:v copy -c:a copy "$filename")
}

# VLC is not in my system path. You may want to adjust or remove this part.
vlc="/c/Program Files/VideoLAN/VLC/vlc"

set -x
streamToPipe | fixup | "$vlc" -
```

Maybe this will be useful to someone, maybe not. Improvements accepted :)

**Comment by cog-videogames** [comment]
To clarify, the ffmpeg part is entirely optional. The downloaded file will not scrub well (nothing to do with streamlink, the encoding just doesn't have good keyframes I think), and an ffmpeg re-contain solves this with near-zero CPU usage. If folks don't have that tool they can just comment it out and use the other `tee` example.
