### ISSUE TITLE
When I try downloading a nightly I get a .tmp file not the .exe one

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#1452]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
In chrome when I try downloading any nightly recently the file that is downloaded is like 2D11.tmp or DCBC.tmp  always 4 random letters and numbers and .tmp.  I have to right click and select download link as to get the proper .exe file.
...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details
Chrome 57, Win7 64bit
Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
How is this supposed to be an issue of Streamlink?
Google Chrome simply writes data of unfinished downloads into temp files, so that its users are not able to "open/execute" them by accident until they are finished. Since you're on Windows and I'm guessing you're using an anti virus software or something of that kind, there's a lot of which could theoretically prevent Chrome from renaming the finished download to the intended name. But that's just a guess. You have to solve your issue yourself.

There is nothing wrong with the uploaded files themselves or even the file hoster. Closing the thread...

https://www.google.com/search?q=chrome+download+.tmp+file
https://crbug.com/155612
