### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by DragonzMaster** [streamlink/streamlink#148]
Hi,
Want to ask if there is any chance to get nightly builds ??

**Comment by gravyboat** [comment]
We're not currently doing nightly builds.

**Comment by karlo2105** [comment]
That's what misses me the most from Livestreamer.

**Comment by lawli3t** [comment]
You can always clone the git-repository on the master branch and pull new changes. Then just install streamlink by runnning `python setup.py install`. Its not automatically, but at least you can get the newest changes sooner.

**Comment by gravyboat** [comment]
Feel free to make a PR to perform the nightly builds in an automated fashion. Right now we aren't pushing so many changes that nightly builds are super critical. I'm not going to argue against them mostly because I don't really care one way or the other, but if you would really like to see them we'll be happy to review and merge a PR that automates how they are built.

**Comment by DragonzMaster** [comment]
Thanks for replay.
It will be nice to see nightly builds available.

**Comment by RosadinTV** [comment]
@DragonzMaster 
Probably this week i will release a automated build generator for Windows (Vista SP2 or later only)
Today i have started programming it.
Of course the program itself and generated build will be portable.

**Comment by thinkpad4** [comment]
RosadinTV, thank you very much.  How big will the program be big and will it build the latest version when I run it?

**Comment by RosadinTV** [comment]
@thinkpad4 The application that build the release is about 10mb (included depedencies) and the release is about 16mb.
And yes, is basically two clicks and you will have the latest build (i mean with the latest commit)
The bad part is that Vista SP2 or later is required (for Python 3.5.2 and for .NET Framework 4.5 because i made the app with VB)

**Comment by thinkpad4** [comment]
that is fine @RosadinTV wasn't gonna use it on a machine below Vista SP2 anyway.

**Comment by DragonzMaster** [comment]
After 0.1 release, nightly builds are live, You can find it here
https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe
