### ISSUE TITLE
Kanal 7 does not show

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#1481]
## **Checklist**

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

##  **Description**

 i cant see anything at kanal 7.com . i have test it with this links but i became black screen 

## **Reproduction steps / Explicit stream URLs to test**

#SERVICE 5002:0:1:1DE6:C544:7E:460000:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//new.10gbps.tv%3a443/live/kanal7LiveDesktop/index.m3u8
#DESCRIPTION KANAL 7 
#SERVICE 5002:0:1:1DE6:C544:7E:460000:0:0:0:http%3a//127.0.0.1%3a8088/http%3a//www.kanal7.com/canli-izle
#DESCRIPTION KANAL 7
#SERVICE 5002:0:1:1DE6:C544:7E:460000:0:0:0:http%3a//127.0.0.1%3a8088/http%3a//www.izle7.com/canli-yayin-frame?air=1
#DESCRIPTION KANAL 7

**Comment by dreamboxco** [comment]
its not fixed! 

I have tested it with 

#SERVICE 5002:0:1:1DE6:C544:7E:460000:0:0:0:http%3a//127.0.0.1%3a8088/http%3a//www.kanal7.com/canli-izle
#DESCRIPTION KANAL 7

**Comment by gravyboat** [comment]
@dreamboxco What would make you think that it is fixed? No one has worked on it in any way, shape, or form. If someone wants to work on it they will.

**Comment by dreamboxco** [comment]
in the synopsis it stands as a functioning plugins then out so if it does not work

**Comment by gravyboat** [comment]
@dreamboxco I understand that and that's why the issue was created, but adding additional comments to the issue when no one has even looked at or worked on the issue does nothing. If someone decides to work on it they will, if not they won't. This is an open source project and people are spending their free time (unpaid) to contribute so you'll need to be patient and have some empathy for the team and what they choose to work on.

**Comment by dreamboxco** [comment]
its a streamlink plugin which not work 

look here 

https://streamlink.github.io/plugin_matrix.html


kanal7 | kanal7.com | Yes | No |  
-- | -- | -- | -- | --

**Comment by dreamboxco** [comment]
here kanal 7 link http://www.izle7.com/canli-yayin-frame?air=1
