### ISSUE TITLE
tvizle plugin

### ISSUE THREAD

**Issue by thawtes** [streamlink/streamlink#1498]
hi,

plugin request for https://www.izletv.us/sinematv-11-izle
system HLS stream

check https://www.izletv.us/sinematv-11-izle with chrome browser

please adding thank you

**Comment by gravyboat** [comment]
Sorry but that's not enough details for us to add this site, what kind of content is it? Are these streams that are legal and original and not restreams?

**Comment by thawtes** [comment]
public, national kids channels and original streams

**Comment by puncy** [comment]
@thawtes 

if they believe you that that site is legit, then i dont see why watchnrl.com cannot be added as well

**Comment by back-to** [comment]
website with **malware popups**

Closing

**Comment by thawtes** [comment]
@back-to 
this bullshit, what has to do with the plugin?

**Comment by puncy** [comment]
@thawtes 

this project has become a bloody joke now, too many people bending over and taking it in the ass.

**Comment by bastimeyer** [comment]
@puncy 
Here, press this button. Then you can write all the plugins and features you can ever imagine for yourself or share them with the world without any consequences
![screenshot from 2018-02-23 08-36-20](https://user-images.githubusercontent.com/467294/36583145-ac50a7b2-1874-11e8-9f24-8fe4210a2617.png)

And for now I've set you on the blocked users list here, so that the people here who sacrificed their time and forked the Livestreamer project after it had died because its creator didn't want to continue anymore, probably because of people like you, can continue their work without your annoying presence.
