### ISSUE TITLE
How to Record Stream Properly -movflags +faststart?

### ISSUE THREAD

**Issue by aykuter** [streamlink/streamlink#1527]
It's not an issue so i remove the template i hope it's okay. I can record a stream easly with this code : 
`streamlink STREAMURL best -o test.mp4`

But i can't edit that file on any editing program. Cuz it doesn't have proper info i guess. It has a sync issue. I should render it with this code on ffmpeg to fix it  : 
`ffmpeg -i test.mp4 -movflags +faststart -crf 22 -pix_fmt yuv420p output.mp4`

But it's take too much time. How can i record it properly so i can save some time ?

And i'm wondering one more thing. Is there any option to always save best quality ? cuz "best" parameter doesn't work always. For example stream has 1080p option but best records it on 720p.

 Thanks you soo much for help!

**Comment by back-to** [comment]
if you want to use ffmpeg directly

some examples
- https://github.com/streamlink/streamlink/issues/1175#issuecomment-322942132
- https://github.com/streamlink/streamlink/issues/1021#issuecomment-309597399
- https://github.com/streamlink/streamlink/issues/1021#issuecomment-309726744
- https://streamlink.github.io/cli.html#cmdoption-stdout


---

> is there any option to always save best quality ? 

is this a streamlink plugin or just a m3u8 url? if it's a streamlink plugin it should be the best

**Comment by aykuter** [comment]
@back-to Thank you for your reply. I will check ffmpeg posts you sent. 
________
I'm using streamlink on twitch but it's not saving with best quality. Streamer has 1080p option but my video is 720p i have no idea why. Here is ss : http://prntscr.com/imd60z
I tried source instead of best but it's not working either :)

**Comment by bastimeyer** [comment]
Just a stupid question, and I have to ask, since you didn't answer the questions of the issue template, are you using Livestreamer by accident?

That non-matching stream quality issue was fixed right after Streamlink was forked from Livestreamer and was caused by Twitch's new stream quality naming scheme which introduced optional fps values in the quality names, which broke the old regexp. Your screenshot looks like it doesn't match qualities with fps values.

These are all commits affecting the regexp since the fork
https://github.com/streamlink/streamlink/commit/5ef06735ec188db30c3b3b6cae36d3ef5933ee9d#diff-dc12d29f5b1be621df2b857139dbec16R40
https://github.com/streamlink/streamlink/commit/e1b6677a2a8659c823c1b846980342f0e766f3fc#diff-805dc2fac848cb5f82dd28259090acf1R44
https://github.com/streamlink/streamlink/commit/09899ee468bb98e3cd87e6904175d1988865259e#diff-805dc2fac848cb5f82dd28259090acf1R47

If you're using Streamlink, the only way I can think of this happening is if you've set the [`stream-sorting-excludes`](https://streamlink.github.io/cli.html#cmdoption-stream-sorting-excludes) parameter. If `160p, 360p, 720p, 720p60, 1080p60` are the available streams, `best` should be the alias for `1080p60`, unless you've filtered the list via this parameter.

**Comment by aykuter** [comment]
Ooopppss silly me. I'm glad you asked me that "stupid" question ahaha. I'm old livestreamer user so.. Old habits.. Thank you so much for detailed explanation. I don't have any problem with streamlink it's perfectly recording 1080p60. I'm closing this one thanks again!
