### ISSUE TITLE
can we add inputstream.adaptive

### ISSUE THREAD

**Issue by kark445** [streamlink/streamlink#1565]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.
Can we add inputstream.adaptive function to streamlink to watch manifest streams
hxxps://github.com/peak3d/inputstream.adaptive

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We've talked about DASH support many times before (https://github.com/streamlink/streamlink/pull/225#issuecomment-263821938 and just search DASH and you can find tons of issues on this). It's not much of a priority now because it's a lot of work to implement. If you're interested in tackling it we'd be happy to review a PR however. For the time being I'm going to close this since it's a duplicate.
