### ISSUE TITLE
[Feature request] Adaptive Bitrate

### ISSUE THREAD

**Issue by 3Passer** [streamlink/streamlink#1589]
### Checklist

- [ ] This is a bug report.
- [X] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

If a stream lags due to bandwith the bitrate should change to the next lower bitrate.

Or is this already possible.

### Expected / Actual behavior
Available Streams 360p,720p,1080p
A stream is started with best (1080p). due to bandwith the stream begins to lag.
Streamlink should automagically switch stream to to 720p until it lags.

**Comment by beardypig** [comment]
Unfortunately this is not possible at the moment, and would require considerable work to add it. Somewhere along the lines of the amount of work require to add proper seeking support. 

The reason it won't work is because typically videos don't change resolution mid stream (the bitrate isn't so much a problem), the way VLC (and other players) see the stream coming from streamlink is the same as a file on disk which are not designed to switch to accommodate variable bandwidth requirements. If you were to switch the resolution during the stream you'd likely just generate an error on the player. 
It might be possible to do something with ffmpeg, but it would still be a lot of work to get streamlink to switch streams - it's not setup to consider multiple qualities at all - you pick one and that's it :)
