### ISSUE TITLE
help, can't login in pixiv account

### ISSUE THREAD

**Issue by hatabbich** [streamlink/streamlink#1607]
I'm not a programmist, so.. trying all what comes to my mind and still only fails
Yea, im making this script in python and save in plugins folder in name pixiv.py
can you give me correct examp what to put in, for authentication

i'm trying this streamlink --pixiv-****@yahoo.com --pixiv-*****ghRa https://.pixiv.net/0d0f2057-7752-47d9-bf64-921de2320091 

and this, streamlink --pixiv-username=****@yahoo.com --pixiv-password=*****ghRa https://.pixiv.net/0d0f2057-7752-47d9-bf64-921de2320091 

still argument is incorrect... :(

**Comment by back-to** [comment]
1. your url looks weird, only streams from https://sketch.pixiv.net/lives will work
2. you only need the **login** if you use the **profile url** instead of the video url
3. it **won't work** with the **stable** version 0.11.0, you need the **Development version**
 you can get it for windows here
 https://bintray.com/streamlink/streamlink-nightly/streamlink#files
 

duplicate https://github.com/streamlink/streamlink/issues/1566
