### ISSUE TITLE
HLS Playlist doesn't reload often enough if there's a single segment in the playlist.

### ISSUE THREAD

**Issue by mrawji** [streamlink/streamlink#1614]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
If an HLS playlist doesn't have more than one 'chunk', then there is a guaranteed underrun because the next reload of the playlist will occur at 'target duration' (https://github.com/streamlink/streamlink/blob/2f994acbe5bac2642c0267638fbdfdb7a48a275a/src/streamlink/stream/hls.py#L215)

Which means we will have already run out of content.

### Expected / Actual behavior
Actual: Small stream underrun since we run out of data before we reload the playlist.

Expected: reload the playlist at 1/3 of the 'target duration' if we're playing the last segement in the playlist.

### Reproduction steps / Explicit stream URLs to test
Streams are private, unable to share. if required, i can probably mimic.

In the logs below, the target duration is 11 seconds
```
#EXT-X-TARGETDURATION:11
```
* at 21:37:37, we get the chunks, load a single 'segment'. Download finishes at 21:37:38,990.
* at 21:37:48, we reload the playlist, however, i've already run out of content to play at this point.

### Logs
Sanitized Logs
```
2018-04-21 21:37:37,303 urllib3.connectionpool: DEBUG https://XXX:443 "GET /YYY/chunks.m3u8?wmsAuthSign=ZZZZ HTTP/1.1" 200 1263
2018-04-21 21:37:37,376 streamlink  : DEBUG [stream.hls][debug] Adding segment 8 to queue
2018-04-21 21:37:37,432 urllib3.connectionpool: DEBUG https://XXX "GET /YYY/l_7267045_25681936_8.ts?&wmsAuthSign=ZZZ HTTP/1.1" 200 2475960
2018-04-21 21:37:38,990 streamlink  : DEBUG [stream.hls][debug] Download of segment 8 complete
2018-04-21 21:37:48,377 streamlink  : DEBUG [stream.hls][debug] Reloading playlist
2018-04-21 21:37:48,422 urllib3.connectionpool: DEBUG https://XXX "GET /YYY/chunks.m3u8?wmsAuthSign=ZZZ HTTP/1.1" 200 1263
2018-04-21 21:37:48,462 streamlink  : DEBUG [stream.hls][debug] Adding segment 9 to queue
2018-04-21 21:37:48,507 urllib3.connectionpool: DEBUG https://XXX "GET /YYY/l_7267045_25691946_9.ts?wmsAuthSign=ZZZ HTTP/1.1" 200 2547776
2018-04-21 21:37:50,570 streamlink  : DEBUG [stream.hls][debug] Download of segment 9 complete
```

### Comments, screenshots, etc.
A super quick and dirty patch at line 219:
```
        #if not self.playlist_changed:
        self.playlist_reload_time = max(self.playlist_reload_time / 3, 1)
```
Seems to work to always reload the playlist at 1/3 of the target duration, but this isn't the most efficient if there's enough data in the playlist.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Thanks for reporting this @mrawji, are you able to share a redacted version of the playlist? I'm interested to see if the `EXTINF` duration is 11 for each segment too.

**Comment by beardypig** [comment]
@mrawji What if you change src/streamlink/stream/hls.py#219 to 
```python
if not self.playlist_changed or len(sequences) == 1:
    self.playlist_reload_time = max(self.playlist_reload_time / 2, 1)
```
So that is reloads in half the time if there is only one segment. 

The code that queues up the reloads and the downloading of the segments doesn't know how much has been downloaded, or how much has been played. 
You might be able to get the same result by increasing the buffer size on your player too.

**Comment by mrawji** [comment]
Thanks. I've playing with a couple of code changes, but this isn't as simple as I'd hoped.

Looks like checking the len(sequences) doesn't quite work... The first time through the reload time get set correctly, however, we're now 'at the edge', i.e. playing the last (only) segment in the sequence. The next time the playlist reloads, it loads with the both sequences (the original one, and the new one). The segment that's being downloaded is the last one, and the reload time is now set to 11 seconds since there are now 2 segments in the playlist.

I'll keep playing with it.

Thanks for the help.
Marc

**Comment by Billy2011** [comment]
I'm not an HLS specification expert, but I think your HLS playlist is not valid:

**The playlist duration is to short:**

> The server MUST NOT remove a Media Segment from a Playlist file
   without an EXT-X-ENDLIST tag if that would produce a Playlist whose
   duration is less than three times the target duration.  Doing so can
   trigger playback stalls.

[Source: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#page-39](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#page-39)

**The playlist reload time is calculated correctly:**

> When a client loads a Playlist file for the first time or reloads a
   Playlist file and finds that it has changed since the last time it
   was loaded, the client MUST wait for at least the target duration
   before attempting to reload the Playlist file again, measured from
   the last time the client began loading the Playlist file.

>  If the client reloads a Playlist file and finds that it has not
   changed then it MUST wait for a period of one-half the target
   duration before retrying.

[Source: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#page-45](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#page-45)

**Comment by mrawji** [comment]
Hey Billy. Thanks for clarifying. I'll close this ticket... I am not sure there's anything to do from streamlink's point-of-view here. If I come up with something clever, i'll create a pull request. 

Thanks for the help!
