### ISSUE TITLE
Streamlink default download folder & automatic file name? for -o command

### ISSUE THREAD

**Issue by hatabbich** [streamlink/streamlink#1621]
Hello, can you please help me
my goal is:
1) Save all downloads to a custom path: "E:\StreamLink" not in Default video folder

2) Automatically generate filename for new downloads, at the new download path. 

im trying use this command complex in console (windows) , but its not work T_T 

C:\Users\Baraduk121>streamlink https://sketch.pixiv.net/@luciahreat/lives/5917595670370
129833 best -o 1234141.flv --download-dir S:/Recording Livecli/

**Comment by bastimeyer** [comment]
You are not using Streamlink, but instead livecli, another fork of it. You should open an issue over there and not here...

Streamlink doesn't have a `--download-dir` parameter. See the CLI documentation here:
https://streamlink.github.io/cli.html

> S:/Recording Livecli/

When you are using parameter values with a space somewhere in between, you either need to escape the space character, or wrap the entire value in quotation marks, so that your shell can interpret the command correctly and pass the right parameters to Streamlink.

If you want dynamic file names, you have to set them via another shell command. This question has been answered multiple times here in this issue tracker already.
