### ISSUE TITLE
itvplayer still not working

### ISSUE THREAD

**Issue by anniman** [streamlink/streamlink#1626]
Checklist
  This is a bug report.
  This is a feature request.
  This is a plugin (improvement) request.
  I have read the contribution guidelines.

Description
streamlink was opening itvplayer on all channels until the other day. i have updated to the latest version 0.11.0. this is on ubuntu 14.04
computer is located in the uk so should work uk.

I have made the changes as refered to in https://github.com/jpts/streamlink/commit/c6a2f8074f8310197590a4284926a9a5029e8c24
but still the same result. has anybody tested this succesfully and why does it give this error ?

Expected / Actual behavior
actual behavior error is
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin itvplayer for URL www.itv.com/hub/itv2
error: Unable to open URL: http://mercury.itv.com/PlaylistService.svc?wsdl (403 Client Error: Forbidden for url: http://mercury.itv.com/PlaylistService.svc?wsdl)
...

Reproduction steps / Explicit stream URLs to test
...www.itv.com/hub/itv2
...
...
Logs
Logs are always required for a bug report, use -l debug (help)
Make sure to remove username and password
You can upload your logs to https://gist.github.com/ or
```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Works OK for me with the latest itvplayer script, are you definitely using the corrected version?

**Comment by anniman** [comment]
here we go again with the installation issues. i get this error when trying to uninstall or install

dpkg: error processing package linux-signed-generic (--configure):
 dependency problems - leaving unconfigured
Setting up streamlink (0.9.0+1really0.7.0-1~webupd8~trusty0) ...
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by anniman** [comment]
ok so i run apt-get autoremove and that removed the problem files and reinstall them. i then use apt-install streamlink and it installs but trying commands now gives me error 
-bash: /usr/local/bin/streamlink: No such file or directory

is that the directory it installs to ?

**Comment by back-to** [comment]
are you sure you are using **apt** for streamlink? https://github.com/streamlink/streamlink/issues/1417

make sure your session of the terminal is reloading

---

you will only get the **dev version** with a `pip` / `python install`

**apt won't be uptodate**

---

**dev version**

https://streamlink.github.io/install.html#source-code
and maybe https://streamlink.github.io/install.html#installing-without-root-permissions

---

or just sideload the new file with your older version of streamlink

https://streamlink.github.io/cli.html#sideloading-plugins

**Comment by bastimeyer** [comment]
@anniman 
If you're using your system's package manager, you'll get the Streamlink version packaged by your distro's package maintainer. This is not the development version, but most likely (almost definitely) the latest stable release. @back-to has already posted a link where you can read how to install the development build of Streamlink, which includes all of the latest changes. As an alternative, you can also side-load plugins, if you're just interested in plugin changes. See the CLI documentation for that.

**Comment by beardypig** [comment]
@anniman is this issue still persisting?

**Comment by back-to** [comment]
the **apt-get** version for `Ubuntu 14.04 LTS (Trusty)` is old

`streamlink (0.9.0+1really0.7.0-1~webupd8~trusty0)`

there is a solution here and in the other issue,
how you can get the latest version via `pip`

---

closing

**Comment by maanich** [comment]
streamlink https://www.itv.com/hub/itv2
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv2
error: Unable to open URL: https://magni.itv.com/playlist/itvonline/ITV2 (403 Client Error: Forbidden for url: https://magni.itv.com/playlist/itvonline/ITV2)
 i got this error on uk based server

**Comment by beardypig** [comment]
@maanich some IP addresses are blocked even if they are inside the U.K. Can you check it works in the browser?

**Comment by maanich** [comment]
yes working in browset


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 02/07/2018  19:55  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [streamlink/streamlink] itvplayer still not working (#1626) 
@maanich some IP addresses are blocked even if they are inside the U.K. Can you check it works in the browser?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #1626: @maanich some IP addresses are blocked even if they are inside the U.K. Can you check it works in the browser?"}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1626#issuecomment-401900565"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/streamlink/streamlink/issues/1626#issuecomment-401900565",
"url": "https://github.com/streamlink/streamlink/issues/1626#issuecomment-401900565",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] itvplayer still not working (#1626)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1626,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1626#issuecomment-401900565"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 328852863\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by maanich** [comment]
working in browser well

**Comment by bastimeyer** [comment]
@beardypig He just got banned by Github for opening another issue with lots of links, which triggers their spam detection system... Same happened two days ago again with another user. I'm not sure who it was, but since the Gitter hook for certain issue events has been set up last month, those issue links are still in the log of the streamlink Gitter channel.

**Comment by maanich** [comment]
i m here buddy just message back to github and released.

**Comment by beardypig** [comment]
@maanich can you open a new issue with a debug log included?

**Comment by maanich** [comment]
should i add log as text or its fine live log in new ticket

**Comment by maanich** [comment]
looks like ip banned might be ovh . with proxy all working
