### ISSUE TITLE
Oxygen/MSNBC/Bravo/E! Network Live - f4m Encryption?

### ISSUE THREAD

**Issue by ischmidt20** [streamlink/streamlink#1650]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

When trying to record a stream from Oxygen Live (and other NBC channels referenced in the title), with pvswf parameter passed in, I get an "unknown tag type error." It tells me this stream might be encrypted, but it records fine with youtube-dl so I know it is not impossible to crack. All 4 channels seem to use the same player and all lead to the same error.

### Expected / Actual behavior

Stream should play to desired player or output to file with `-o`. Instead, an error occurs.

### Reproduction steps / Explicit stream URLs to test

1. The stream can be found at `http://www.oxygen.com/live`. Use a TV provider login to play the stream. Make sure to enable Flash.
2. Use URL snooper to find `manifest.f4m` file, along with swf player to pass in as pvswf parameter. Please note that the `manifest.f4m` file expires pretty quickly.

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
streamlink -l debug "hds://http://tveoxygenwest-lh.akamaihd.net/z/nwoxygenwest_1@119649/manifest.f4m?hdnea=st=1526082307~exp=1526082367~acl=/z/nwoxygenwest_1@119649*~id=01b8f5c1-cc8a-4d48-9ac4-80deb53963de~hmac=77b6b6ebdfe10aa4dfb446bdc13f68043ce10e01eff41b4d1a9c2a46deb4004f&hdcore=3.5.0 pvswf=http://pdk.theplatform.com/5.6.19/pdk/swf/flvPlayer.swf" best
[cli][info] Found matching plugin hds for URL hds://http://tveoxygenwest-lh.akamaihd.net/z/nwoxygenwest_1@119649/manifest.f4m?hdnea=st=1526082307~exp=1526082367~acl=/z/nwoxygenwest_1@119649*~id=01b8f5c1-cc8a-4d48-9ac4-80deb53963de~hmac=77b6b6ebdfe10aa4dfb446bdc13f68043ce10e01eff41b4d1a9c2a46deb4004f&hdcore=3.5.0 pvswf=http://pdk.theplatform.com/5.6.19/pdk/swf/flvPlayer.swf
[cli][info] Available streams: 296k (worst), 496k, 796k, 1296k, 1896k, 2596k, 4296k (best)
[cli][info] Opening stream: 4296k (hds)
[stream.hds][debug] Updating bootstrap
[stream.hds][debug] Live edge buffer 10.0 sec is 2 fragments
[stream.hds][debug] Current timestamp: 1526082336.0
[stream.hds][debug] Current segment: -1
[stream.hds][debug] Current fragment: 254347056
[stream.hds][debug] First fragment: 254346228
[stream.hds][debug] Last fragment: 254347057
[stream.hds][debug] End fragment: None
[stream.hds][debug] Adding fragment 1-254347056 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hds][debug] Adding fragment 1-254347057 to queue
[stream.hds][error] Unknown tag type found, this stream is probably encrypted
[stream.hds][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HDSStream('http://tveoxygenwest-lh.akamaihd.net/z/nwoxygenwest_1@119649/', '4296_789fed1465cce3c2-p_', 'http://tveoxygenwest-lh.akamaihd.net/z/nwoxygenwest_1@119649/4296_789fed1465cce3c2-p.bootstrap', metadata=<ScriptData name=onMetaData value=ScriptDataECMAArray([('width', 1920.0), ('height', 1080.0), ('framerate', 29.970029970029966), ('videocodecid', 7.0), ('audiosamplerate', 44100.0), ('audiosamplesize', 16.0), ('stereo', True), ('audiocodecid', 10.0), ('description', 'Live Stream'), ('keywords', 'anvato,live'), ('rating', 'NR'), ('title', 'Live Stream'), ('presetname', 'Custom'), ('videodevice', 'dvin'), ('encoder', 'Anvato-HF-2.1'), ('audiodevice', 'dain'), ('videokeyframe_frequency', 2.0), ('audiochannels', 2.0), ('audioinputvolume', 100.0), ('avcprofile', 100.0), ('avclevel', 40.0), ('aacaot', 2.0), ('audiodatarate', 96.0), ('videodatarate', 4200.0), ('duration', 0.0)])>, timeout=60)> (No data returned from stream)
error: Could not open stream <HDSStream('http://tveoxygenwest-lh.akamaihd.net/z/nwoxygenwest_1@119649/', '4296_789fed1465cce3c2-p_', 'http://tveoxygenwest-lh.akamaihd.net/z/nwoxygenwest_1@119649/4296_789fed1465cce3c2-p.bootstrap', metadata=<ScriptData name=onMetaData value=ScriptDataECMAArray([('width', 1920.0), ('height', 1080.0), ('framerate', 29.970029970029966), ('videocodecid', 7.0), ('audiosamplerate', 44100.0), ('audiosamplesize', 16.0), ('stereo', True), ('audiocodecid', 10.0), ('description', 'Live Stream'), ('keywords', 'anvato,live'), ('rating', 'NR'), ('title', 'Live Stream'), ('presetname', 'Custom'), ('videodevice', 'dvin'), ('encoder', 'Anvato-HF-2.1'), ('audiodevice', 'dain'), ('videokeyframe_frequency', 2.0), ('audiochannels', 2.0), ('audioinputvolume', 100.0), ('avcprofile', 100.0), ('avclevel', 40.0), ('aacaot', 2.0), ('audiodatarate', 96.0), ('videodatarate', 4200.0), ('duration', 0.0)])>, timeout=60)>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[stream.hds][debug] Closing worker thread
```

Once again, I know this stream can be recorded—I just prefer to use streamlink, and would like to have a solution for others as well.

Thanks!

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
@Ike348, what command did you use to download it using `youtube_dl`? If it's possible with `youtube_dl` then we should be able to support it. I don't have a US TV provider account, so it might take a bit of co-ordination to debug :)

**Comment by Ike348** [comment]
`youtube-dl -v -f best "http://tveoxygeneast-lh.akamaihd.net/z/nwoxygeneast_1@119646/manifest.f4m?hdnea=st=1526171018~exp=1526171078~acl=/z/nwoxygeneast_1@119646*~id=d823a397-7f6b-4be7-85c1-600da4873e3d~hmac=fcb7e894231b6db7ce2bdc262fcbc878bed10a11ded40d68fe713a41129f70ff&hdcore=3.5.0"` works.

However, I have come to the realization that it might just be downloading the encrypted file. I was never able to play it, but I assumed that was because since there's no way to cleanly exit a youtube-dl download, I would always just get an unplayable `.part` file. I just saw the downloading line appear and got excited.

This weakens my optimism somewhat, but I am still hopeful that this can be recorded.

**Comment by gravyboat** [comment]
Hmm, it seems like if you're just getting a part file then it most likely is just downloading the file. I'm not super familiar with youtube-dl but I wonder if one of their features is simply to do a fallback and download whatever the file may be even if it can't do something with that file. If the streams are encrypted like that there won't be much we can do unfortunately. Let us know if you figure anything out in your investigation, and maybe check to see if youtube-dl does have that kind of fallback behavior.

**Comment by Ike348** [comment]
Youtube-dl does have fallback behavior, which is what worries me. I once downloaded a 4 GB protected YouTube movie only to not be able to play the file because of the encryption. All of this leads me to believe that the file may be encrypted (Streamlink telling me so, not being able to play what youtube-dl downloads) but I'm still hopeful. And if it is encrypted, I wonder if there's a way to decrypt it with a some kind of key and a cookie (see [here](https://github.com/streamlink/streamlink/issues/1107)).

**Comment by gravyboat** [comment]
A lot of it depends on what sort of encryption they're using as some systems allow for workarounds like in that linked issue. We've also encountered a fail number of services where trying to get around the encryption wasn't possible at all so it's really hit or miss.

**Comment by back-to** [comment]
You could try to get a `m3u8` url with a mobile **User-Agent** _iphone / android_

---

A copy of the `f4m` file could specify which encryption they use

you can get a copy with the **Network Monitor** in your **Browser**

_This example is for Firefox, Chrome should have the same_

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#Network_request_details

under **Response**

and copy the output to https://gist.github.com/

**Comment by Ike348** [comment]
@back-to I've tried to use different user agents to get other types of streams as m3u8s in the past but it's never worked. [Here](https://gist.github.com/Ike348/f97197e8ef2951b5270173ba1537b230) is a copy of the f4m file.

@gravyboat Yeah, that's what I'm fearing. An example of something that probably can't be cracked is TNT's online streaming format, it looked so bad I didn't even bother to make a ticket.

**Comment by Ike348** [comment]
Just another update on this... The stream is definitely NOT encrypted as I am able to successfully record to FLV using this [AdobePHP](https://github.com/K-S-V/Scripts/wiki) script, and then convert to a playable MP4 using ffmpeg. Any other thoughts as to how to get Streamlink to successfully play/record these streams?

**Comment by beardypig** [comment]
Ah right, yeah... that's the funky Akamai encryption, it has been on my todo list for a while. The problem is it means touching the flash parsing code, which is not so fun. Maybe I'll bump it up the list, but I'll need some streams to test - I cannot test this one as I don't have a cable subscription.

**Comment by Ike348** [comment]
@beardypig Sounds good. I personally am unwilling to share my cable information (it's technically not mine), but hopefully someone else is. I wouldn't make this too high of a priority right now because there is now a known way of recording these streams, but it would be nice at some point to get this working with Streamlink. Thanks!

**Comment by gravyboat** [comment]
@beardypig Do you really want to mess with the flash code? I say just let it die. If they're not willing to use something decent that's on them. Plus we've discussed cable logins a number of times before and our stance has been to not support them because there are way too many random issues that can crop up.
