### ISSUE TITLE
MPC-HC buffer issue on mobile streams

### ISSUE THREAD

**Issue by ZMOT7S** [streamlink/streamlink#1661]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Twitch streams being broadcast from mobile phones, launched with MPC-HC starts frozen, has very slow buffer. Video starts, video pauses but audio is fine. About 10-20 seconds later, video frame will change and freeze again. Repeats. Audio is fine. Works fine with VLC player though. 

If I keep closing and launching, eventually it will play fine. I've tried reinstalling MPC-HC and Streamlink and Streamlink GUI but the problem still happens. 

### Expected / Actual behavior

To play normally like VLC player. 

### Reproduction steps / Explicit stream URLs to test

1. MPC-HC as player in settings
2. Launch a stream that is streaming from mobile. (examples AlecLudford, TrainwrecksTV, Reynad, Hyubsama)

### Logs

I ran the command but can't find the log file in installation or appdata. Where is it?

**Comment by bastimeyer** [comment]
There's nothing which Streamlink can do in order to fix your issue. Streamlink just concatenates the MPEG-TS segments of the HLS stream provided by Twitch. How the video is being decoded and rendered entirely depends on the implementation of your chosen player and its used decoders.

> About 10-20 seconds later, video frame will change and freeze again

Video encoders for mobile streams usually set different encoding parameters for the stream, because it's a different and more difficult environment. What you're describing sounds like a video keyframe decoding issue.

If one of your players is having decoding issues, then you need to make sure that it is working correctly on its own. VLC comes with is own built-in decoders, so that may be the reason why you're seeing different results on your system when using it instead of MPC-HC, which is using your system's codecs and their configuration.

> I ran the command but can't find the log file in installation or appdata. Where is it?

I'm confused... Did you by any chance use the `--loglevel debug` parameter on the Twitch GUI (you mentioned you were using it)? In either case, the log output is directly being displayed in your terminal. If you were using the Twitch GUI's log, it is useless and unrelated here (this is the Streamlink issue tracker).

However, I don't think that the log output won't help here anyway, since you were saying that audio is working fine, which means that you didn't encounter any stream download interrupts.

https://streamlink.github.io/cli.html

```bash
streamlink --loglevel debug URL QUALITY
```

**Comment by ZMOT7S** [comment]
I used the "-l debug" command after launching a stream, like this, "streamlink twitch.tv/alecludford -l debug" It showed the log in terminal but how can I save that and upload it? I thought it would make a log file somewhere. 

So you think it's just an issue with MPC-HC decoding mobile streams?

**Comment by gravyboat** [comment]
MPC-HC has a bunch of issues we've encountered previously (https://github.com/streamlink/streamlink/issues/263, https://github.com/streamlink/streamlink/issues/769). Bastimeyer provided some good troubleshooting steps but before even going as far as that I would recommend trying a different video player such as VLC or MPV.

**Comment by johnpolite** [comment]
v1.7.13 is released and farewell

https://mpc-hc.org/

**Comment by johnthecracker** [comment]
@ZMOT7S 

Here is still something going on:

https://sourceforge.net/projects/mpcbe/

https://portableapps.com/apps/music_video/mpc-be-portable

You may try this one if you like, and tell us how it goes.

https://en.wikipedia.org/wiki/Media_Player_Classic

**Comment by ZMOT7S** [comment]
I am already using 1.7.13 @johnpolite 

I will give BE a try @johnthecracker

**Comment by johnthecracker** [comment]
After having a closer look at wikipedia, just noticed..

https://github.com/clsid2/mpc-hc/releases

1.7.16

**Comment by johnthecracker** [comment]
@gravyboat,

Would it be possible to send you one email somewhere to tell you something that 
is not possible to be public?

It wouldn't be anything insulting, in fact you will enjoy reading it !

If you don't want to post your contact details, you can send me one email at jadran1@mail.com

**Comment by johnthecracker** [comment]
@bastimeyer, @beardypig, @back-to,

Is it possible to contact one of you somewhere else or you contact me at 

jadran1@mail.com for no joke conversation ?

**Comment by beardypig** [comment]
@johnthecracker I'm always available via email and gitter.

**Comment by johnthecracker** [comment]
Thank you for prompt reply.

I replied to your email.

**Comment by back-to** [comment]
this is more of a **player / encoding issue**,
than a streamlink issue.

closing as it's not a streamlink issue

_there are some more informations above._
