### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink#1704]
Is it possible to send a television channel to chromecast with streamlink? supposing that it could be, what command should I execute? If it could not be, do you have any plans to add it?

**Comment by beardypig** [comment]
I had some success using [pychromecast](https://github.com/balloob/pychromecast). I don't have the script any more (or access to the Chromecast right now), but I think what I did was start streamlink using --player-http-external, and use the web address for that (on my LAN IP) to send to the Chromecast to play.

**Comment by Daniel41550** [comment]
Another workaround to doing this is using [Soda Player](https://www.sodaplayer.com/) for Windows and Mac, it has built in chromecast support and works with the direct links to twitch videos, I don't know if it supports the http or piping option though. Playing 1080p60 made the video have to be transcoded, but that issue might be solved if you have a chromecast ultra. All you would need to do is go to your streamlink configuration and change the uncommented player option to the path of sodaplayer.

**Comment by DjUnknown** [comment]
@beardypig 
I do not have linux nor mac.

@Daniel41550
It is the player that I use but it does not work with some channels with streamlink, nor does it allow m3u files.

**Comment by sbernsteinHBO** [comment]
VLC Player 3.0 supports casting now.  You can start the video in VLC and cast it under the "Playback" menu, there is a "Render" submenu that allows you to choose what device to cast to

**Comment by back-to** [comment]
if you want to use **Kodi** and a **m3u** file,
I could get you a Guide for `Kodi v18 "Leia" nightly`

but thats maybe not what you want.

**Comment by back-to** [comment]
well, the OP user account is deleted.

closing, as this will most likely require third party apps.

**Comment by warren-bank** [comment]
hi, sorry to bump a closed issue.. but this touches on the exact topic that I was hoping to solve..

I've been playing around with an old Chromecast lately.. brought out of retirement because I've modified a [Chrome extension](https://github.com/warren-bank/crx-webcast-reloaded) and been having great success in being able to push nearly every random video available on websites to the Chromecast with a few mouse clicks.

The issue I wanted to [solve](https://github.com/warren-bank/HLS-proxy) was when an .m3u8 and its .ts chunks are protected (weakly) by restrictive CORS headers. Meaning, a web browser (including the one embedded in Chromecast) will refuse to download content from a server that includes a header response that says the content can only be played on a particular website. This proxy tries to solve that by downloading the .m3u8 and rewriting all of its internal URLs inflight so they point back to the proxy.. and it also injects very permissive CORS headers. It works well.. but I noticed that maybe Streamlink could be used in a similar way..

I chose an .m3u8 randomly from the wild.. one that doesn't use CORS headers, and started a Streamlink server:
`streamlink --player-external-http --player-external-http-port 8080 --default-stream best --http-ignore-env --http-no-ssl-verify --url "https://XXX/video.m3u8"`

It seems to work great.. it shows client connections and responds with a data stream. The only problem is.. no clients seem to understand what the data stream is sending.. and then close the connection after a few seconds.

Specifically.. I tried:
* going to one of my [WebCast players](https://warren-bank.github.io/crx-webcast-reloaded/external_website/3-theoplayer/index.html)
* loading the video from [Streamlink](http://192.168.XXX.XXX:8080/)
  * when that failed, I also tried adding a [path that ends with a file extension](http://192.168.XXX.XXX:8080/video.m3u8), but same result

So, my questions would be:
* what is the format of the video being served by `--player-external-http`?
  * incidentally, adding `--player-passthrough "hls"` causes Streamlink to crash in the process of starting the server
* any ideas how this video stream could be played in a native HTML5 video tag?

Thanks all :)

**Comment by warren-bank** [comment]
PS) as a quick test, I removed `ffmpeg` from `PATH` and Streamlink didn't seem to notice or care.. which makes me think that it's not using it when it is in `PATH`. Ideally (for my purpose), the stream wouldn't be transcoded anyway.. since I'm only interested in proxying streams that are in a format already supported by Chromecast. But it seemed like a relevant observation.

**Comment by warren-bank** [comment]
After a bit more reading.. I have a hypothesis.. and maybe somebody who knows Streamlink can confirm or reject (please) :)

in issue #1434 .. it was stated that Streamlink serves a progressive http stream.. which (according to [this](https://www.brightcove.com/en/blog/2009/03/progressive-download-versus-streaming) article) would lead me to believe that it's a "progressive download" rather than an actual stream.

Does that sound about right?.. and would you assume __that__ is the reason that HTML5 video players reject the data being served?

**Comment by warren-bank** [comment]
Are you sure it isn't progressive? If it is, then this [answer](https://stackoverflow.com/questions/28154828) seems helpful..

PS) "change in the links"?

**Comment by warren-bank** [comment]
added observations:

* officially Chromecast does [support](https://developers.google.com/cast/docs/media#delivery-methods-and-adaptive-streaming-protocols) progressive downloads (without adaptive switching)
* `Streamlink\streamlink_cli\utils\http_server.py` sets: `conn.send(b"Content-Type: video/unknown\r\n")`
  * not sure if that's important.. but it does seem concerning

**Comment by warren-bank** [comment]
added observations:

* the remote .m3u8 video stream seems to be served locally as an .mp4
  * when I load the URL of the local Streamlink server in the browser, I'm prompted to save its data to a file
  * if I cancel the download after a few MB and rename the file to .mp4, then it plays in VLC
* I tried playing around with response headers, adding various combinations of:
  ```python
            conn.send(b"HTTP/1.1 206 Partial Content\r\n")
            conn.send(b"Accept-Ranges: bytes\r\n")
            conn.send(b"Content-Type: video/mp4\r\n")
            conn.send(b"Content-Length: 1000\r\n")
            conn.send(b"Content-Range: bytes 0-999/*\r\n")
  ```
  but I can't figure out what's needed to make an HTML5 client (native video, HTML5 video player, Chromecast) play the "stream".. they all close the connection after about a second

notes (mostly for myself).. code trace of the error:
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L1007
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L574
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L419
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L161
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L186
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L117
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L225
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L320
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L323
* https://github.com/streamlink/streamlink/blob/d7ec5767376264a6e9cee3f75cd42045a7012313/src/streamlink_cli/main.py#L352
  * "output" (fka: "server") is an instance of "HTTPServer"
  * "output.write()" throws an Exception

* https://github.com/streamlink/streamlink/blob/9409fd741ce26c227ceadbfb69fcb8d281031b77/src/streamlink_cli/utils/http_server.py#L104
  * "self.conn" is null

**Comment by beardypig** [comment]
For the HLS streams supported by streamlink the output is an MPEG-TS (`.ts`) file. It is a stream, because that's how MPEG-TS (that's MPEG Transport *Stream*) works, there is no header like in `.mp4`/`.mov`. You might be able to send the `video/MP2T` content type.

**Comment by warren-bank** [comment]
interesting..

that makes me wonder if the following could work:
* start a local httpd
* serve an .m3u8 playlist that references a single url: that of the Streamlink server (including a path that ends with a .ts file extension)

..going to run a quick test and report back

**Comment by warren-bank** [comment]
no joy..

* the .m3u8 is accepted by the player
  * it indicates a "live" stream
  * its loading indicator goes around and around
  * nothing plays
* the Streamlink server shows that the .ts URLs are being followed by the player
  * requests keep coming in
  * connections are still being closed almost as quickly as they're opened

le sigh..

**Comment by jlsalmon** [comment]
@warren-bank I'm trying to achieve the exact same thing, did you ever manage to get it working?

**Comment by warren-bank** [comment]
@jlsalmon : no, I gave up trying after that final test failed.. 

I didn't realize that I was so verbose in this thread.. apologies.. I hate that. Long story short: I was trying to use streamlink as a proxy that could download an HLS video from a remote server and serve the same video content on the LAN to client(s) that would load the video content into an HTML5 video element.  (ex: web browsers, Chromecast)

VLC was able to consume the video content from the streamlink "proxy" server, and it was also able to render this content to a Chromecast on the LAN (without any transcoding). However, HTML5 video elements were completely unable to render this video content directly (without using VLC as an additional "proxy" server).

At the time, I was actively developing my ["HLS-Proxy"](https://github.com/warren-bank/HLS-Proxy) project, which works great and has many more options to conditionally modify the request/response on the fly (ie: a debugging HLS "proxy"). I had just learned about streamlink and was playing around with it as a possible alternative. For my use case, I considered the tests to have failed.. and gave up (on streamlink) at that point.

**Comment by jlsalmon** [comment]
Ah ok, I figured as much. Thanks for the info. If it's still relevant/useful, I managed to get the same thing working with [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module). I also ended up giving up on streamlink due to the limitations of `--player-external-http`. It would have been great if it served a proper HLS endpoint rather than just a MPEG-TS stream.
