### ISSUE TITLE
Installation Failure Recommonmark

### ISSUE THREAD

**Issue by Severus157** [streamlink/streamlink#1706]
Hey,
I have just tried to install Streamlink, but somehow I am always running in an error.
```
==> Extracting sources...
  -> Creating working copy of streamlink git repo...
Cloning into 'streamlink'...
done.
==> Starting pkgver()...
==> Updated version: streamlink-git 0.12.1.r58.g757861d9-1
==> Starting build()...
running build_sphinx
creating /tmp/yaourt-tmp-severus/aur-streamlink-git/src/streamlink/build
creating /tmp/yaourt-tmp-severus/aur-streamlink-git/src/streamlink/build/sphinx
creating /tmp/yaourt-tmp-severus/aur-streamlink-git/src/streamlink/build/sphinx/doctrees
creating /tmp/yaourt-tmp-severus/aur-streamlink-git/src/streamlink/build/sphinx/man
Running Sphinx v1.7.4
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 13 added, 0 changed, 0 removed
reading sources... [ 30%] changelog                                                                 
Extension error:
Could not import recommonmark.parser (needed for source parser) (exception: No module named 'recommonmark')
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build streamlink-git.
==> Restart building streamlink-git ? [y/N]
```

This are the last lines of the commandline.
Does someone know this error?

**Comment by back-to** [comment]
`python-recommonmark` was added **yesterday** in https://github.com/streamlink/streamlink/pull/1667

https://aur.archlinux.org/packages/streamlink-git/ is not updated yet

---

**workaround**

install it manually

```
sudo pacman -S python-recommonmark
```

https://www.archlinux.org/packages/community/any/python-recommonmark/

**Comment by bastimeyer** [comment]
This issue is affecting the AUR `-git` package. If there are any issues with AUR packages, you have to notify the package maintainer and not the software maintainers upstream. This is how it works for all package repositories.

I have commented on the AUR package with the missing `python-remarkdown` make dependency. The package maintainer should be notified about that. In any case, let me ping @mmetak here as well.

And btw, don't use yaourt, it's the worst AUR helper and is also unmaintained/discontinued:
https://wiki.archlinux.org/index.php/AUR_helpers

**Comment by Severus157** [comment]
Thank you. That info for recommonmark was great. I could install and now steamlink is finally working.
Thanks for your help.
