### ISSUE TITLE
How to config any sound(or text) for stream start ?

### ISSUE THREAD

**Issue by agentqwe** [streamlink/streamlink#176]
my internet is bad, so i want immidiatly close other downloads if streamlink starts download

**Comment by gravyboat** [comment]
This isn't something Streamlink supports and would be very difficult to do as we would have to dynamically determine what is using bandwidth and close those applications. I would suggest instead that you wrap the call to Streamlink in another script that checks if other apps you use are running and then closes them.

**Comment by RosadinTV** [comment]
@agentqwe What do you mean to close other downloads? Do you mean for example browsers and stuff like that?

**Comment by Vangelis66** [comment]
I think @agentqwe's query is related to his previous issue https://github.com/streamlink/streamlink/issues/170#issuecomment-260884443

> i want to automaticly found streams if there will be in my twitch followings, and start writing in file

What he probably wants is a sound or visual notification when one of his followed streams goes live 
and streamlink starts dumping it to file; he would then pause/exit other bandwidth-hungry processes 
(e.g. standalone downloaders, video/audio streamed in browser etc) to make all his line available to streamlink...

E.g., I frequently run a video converting batch file of mine, that usually takes 10min to complete; 
when all the commands are executed, a sound notifies me accordingly... 
This is because I've included this line 
`rundll32 user32.dll,MessageBeep MB_ICONWARNING`
towards the end of the file, followed by `PAUSE`

There are probably solutions that he can include in his wrapper script 
(the one that monitors for twitch streams and starts recording them) 
to generate a system sound when the recording begins, 
but I agree this is beyond the scope of Streamlink itself...
