### ISSUE TITLE
[plugin request] http://thvli.vn/live/thvl1-hd/aab94d1f-44e1-4992-8633-6d46da08db42

### ISSUE THREAD

**Issue by 314pi** [streamlink/streamlink#1762]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This issue doesn't contain anywhere near enough information for us to do anything with it, we'll need more details before we can consider it. I also have no idea if this site is legitimate. Looking at it this appears to be a site containing a bunch of Vietnamese TV shows from different areas and doesn't seem legitimate, but I'm not familiar enough with Vietnamese TV to say otherwise, and I can't find an entry for this site on Wikipedia.
