### ISSUE TITLE
How to resume last failed download?

### ISSUE THREAD

**Issue by balalaXD** [streamlink/streamlink#1806]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

When i download a **_Youtube_** video, say maybe 100GB, then at 50GB the download was failed, complaining `[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://manifest.googlevideo.com/*`
How could i resume this download instead of overwrite?
The command line i used was
`streamlink -Q --hls-live-edge 9999999 --hls-segment-threads 5 -o "TV.ts" URL best`

### Donation
[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
i don't think you can easily resume the file,
it fails because **youtube has a timelimit of 6 hours.**

---

but there are two other options

---

**1.** use a script where `"TV.ts"` will have a **timestamp** in  the name, with this you will get different files.

---

**2.** **custom plugin** that will reload your error and the download won't fail

*of course your internet connection is not allowed to drop for longer than some seconds*

- Download this file 

https://raw.githubusercontent.com/back-to/plugins/master/plugins/hlssession.py

- and **sideload** it

https://streamlink.github.io/cli.html#sideloading-plugins

youtube will error after 6h, so you need to set the option to less than 6h,
also you will have to use the prefix

**example for 3h reload**

```
streamlink --hlssession-time 03:00:00 hlssession://https://www.youtube.com/watch?v=K3o8-1jXseY best
```

**Comment by balalaXD** [comment]
Thanks for the reply, FIXED :+1: 
btw, you can add line  `export $XDG_CONFIG_HOME=~/local` at your  `~/.bash_profile`

**Comment by S-ed** [comment]
Greetings.
I'm getting this error while loading the plugin:

```
streamlink --hlssession-time 03:00:00 hlssession://https://www.youtube.com/watch?v=K3o8-1jXseY best
[Streamlink for Windows v0.14.2 - Git 215d789]
Failed to load plugin hlssession:
  File "imp.py", line 235, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Net\Download\streamlink\Streamlink\streamlink\plugins\hlssession.py", line 13, in <module>
    from streamlink.utils.args import num
ModuleNotFoundError: No module named 'streamlink.utils.args'

usage: Streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --hlssession-time best
[End of Streamlink for Windows with ExitCode 2]
```

**Comment by tombh** [comment]
Very old thread I know, but it was the first I found when searching for "streamlink resume". So now in 2024 this is natively supported with `streamlink --hls-start-offset [[XX:]XX:]XX[.XX] | [XXh][XXm][XX[.XX]s] ...`
