### ISSUE TITLE
Piping video into Chrome

### ISSUE THREAD

**Issue by BullHorn7** [streamlink/streamlink#1807]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

The Streamlink readme says "Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC, **or alternatively, a browser**." 

There is no documentation explaining how to actually pipe flash videos through a browser. Is it even possible right now?

### Expected / Actual behavior

Documentation for streaming through a browser could be helpful, unless it's not currently possible in which case the readme is misleading.

### Comments, screenshots, etc.

I think this was possible with VLC and Chrome a few years ago, before Google ended support for NPAPI plugins and killed the VLC Chrome extensions, but after Googling for a few hours I wasn't able to find any current alternative.

**Comment by beardypig** [comment]
This is probably referring to `--player-external-http`. Which, in theory, you could use to play in a browser. I’m not aware of any other method that would allow you to do it ...

**Comment by gravyboat** [comment]
@beardypig That line of documentation hasn't been updated since we started maintaining the project as far as I know, I'm wondering if it just hasn't been updated and is either referring to what you noted, what @BullHorn7 noted with NPAPI, or somehow using Flash player when it used to be built into many browsers by default. I would consider that functionality dead at this point @BullHorn7 and we should update the documentation to remove that note.
