### ISSUE TITLE
[Question] NBC Streaming

### ISSUE THREAD

**Issue by sazrocks** [streamlink/streamlink#1864]
- [x] This is a Question

### Description

I can't figure out how to stream from nbc.com/live. I'm pretty sure I need a cookie of some kind since I have to log in through my TV provider (DISH) when I visit the site. The problem is I have absolutely no idea which cookie it is that I need to provide. If someone could show me what cookie it is or better yet, how to figure out which cookie it is, that would be awesome.

### Expected / Actual behavior

Expected: Streaming would work

Actual:
Console outputs: 
`streamlink --retry-streams 10 nbc.com/live best`
`[cli][info] Found matching plugin nbc for URL nbc.com/live`
`[cli][info] Waiting for streams, retrying every 10.0 second(s)`
And obviously the stream doesn't work.

### Reproduction steps / Explicit stream URLs to test

run `streamlink --retry-streams 10 nbc.com/live best`

**Comment by Ordval** [comment]
I can understand that you'd prefer very good quality, 
but would you be content with the USTV Plug-In ? 
#1772 (in the midst of the thread I talk about "Video Download Helper", 
**aykuter** creates new e-mail accounts), #1705 "plugin to support ustvnow.com"
and #911. 
I'm just a member suggesting.

**Comment by back-to** [comment]
streamlink supports only vods for `nbc.com`

there is no plan in adding support for cable logins

---

you could try to use **every** cookie from your webbrowser
https://streamlink.github.io/cli.html#cmdoption-http-cookie

but you will most likely need the direct URL `https://....m3u8?...` not `nbc.com/live `

**Comment by gravyboat** [comment]
As @back-to noted we don't support cable logins so I'm going to close this out.

**Comment by Ike348** [comment]
Just to follow up on this if I could... Streaming from NBC Sports live is giving me a very odd error. I can find the m3u8 URL with my snooper, and I can both download that m3u8 file from the browser and also download it from my command line with wget. However, when I try to use streamlink, I get a 403 forbidden error. The killer is that I can also download the individual .ts files on their own (again, both in browser and with wget) and play them just fine, meaning that the stream is in no way encrypted. So what's up here? The playlist file is accessible without cookies, and the stream itself is also accessible without cookies. So why is streamlink returning a 403 error? This is only for the NBC streams, not with any other networks.

Of course, I wouldn't mind opening a new issue with formal logs and everything like that. I just saw this issue here and thought I'd hop on.

**Comment by bastimeyer** [comment]
> The playlist file is accessible without cookies, and the stream itself is also accessible without cookies

Are you using a vpn/proxy server (different IP address) or different HTTP request headers when downloading the files via your browser or via wget? Often times the `User-Agent` or `Referer` request headers are being used for blocking requests and returning a `403` error.

**Comment by Ike348** [comment]
@bastimeyer I'm not using a proxy server. My wget command is a simple default `wget 'link'` and it works just fine. Then running `streamlink "hlsvariant://link"` fails. It's really weird, but since I figured out a workaround to get the stream otherwise, I didn't bring it up on here until now. The link also works with `youtube-dl -F 'link'` and even `ffmpeg -i 'link'` seems to be working (and I've never gotten a stream to work directly through ffmpeg).

**Comment by bastimeyer** [comment]
When happens when you add a custom user agent http header?

```
--http-header "User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.25 Safari/537.36"
```

**Comment by Ike348** [comment]
That works! Odd that that would be required. Thanks for the help!

**Comment by bastimeyer** [comment]
Streamlink doesn't add the User-Agent header by default. In plugins this is done manually by the plugin author, but just using a HLS playlist as URL requires you to also set the header. Could be improved, though. The current user agent situation needs to be fixed anyway, so maybe adding a default header could be considered.
