### ISSUE TITLE
Problem with live.russia.tv

### ISSUE THREAD

**Issue by remek30** [streamlink/streamlink#1872]
I have  Problem with the Plugin live.russia.tv : 
```
#SERVICE 4097:0:1:0:0:0:224:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//live.russia.tv/index/index/channel_id/76:Москва 24 HD
#DESCRIPTION Москва 24 HD
#SERVICE 4097:0:1:0:0:0:449:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//live.russia.tv/index/index/channel_id/1:Rossija 1 HD
#DESCRIPTION Rossija 1 HD
#SERVICE 4097:0:1:0:0:0:445:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//live.russia.tv/index/index/channel_id/82:Rossija RTR HD
#DESCRIPTION Rossija RTR HD
#SERVICE 4097:0:1:0:0:0:447:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//live.russia.tv/index/index/channel_id/3:Rossija 24 HD
#DESCRIPTION Rossija 24 HD
```
The Channels not working on streamlink - from PC work the channels ok.

**Comment by remek30** [comment]
I wanted to watch the following Russian channels via streramlink available at https://live.russia.tv:


Rossija 1
Mockba24
Rossiya RTR

and others available on this page. And then I pasted into the channel list and I have neither image nor sound - channels just do not work.

**Comment by bastimeyer** [comment]
You have to provide the debug log which the issue template is asking for, otherwise it is impossible for anyone else to understand your issue. What you have posted is no Streamlink log output.

Here is the issue template again:
https://raw.githubusercontent.com/streamlink/streamlink/master/ISSUE_TEMPLATE.md

> And then I pasted into the channel list and I have neither image nor sound - channels just do not work.

?
Are you even using Streamlink, or are you using something else?
