### ISSUE TITLE
Improve RTVE plugin

### ISSUE THREAD

**Issue by DjUnknown** [streamlink/streamlink#1915]
Hello, you can possible when the channels of rtve cannot be streamed online for copyright reasons let's see this video?
```
http://mvod.lvlt.rtve.es/resources/TE_NGVA/mp4/0/0/2200000000000.mp4
```

I hope you have understood me, I do not speak English, it has been translated by Google.

**Comment by beardypig** [comment]
You post Spanish and English translation. 
puedes escribir español e inglés traducido

**Comment by DjUnknown** [comment]
He intentado preguntar en ingles 
"Si es posible cuando un programa de RTVE no pueda emitir por internet por derechos de autor se nos aparezca en el reproductor este video... 
```
http://mvod.lvlt.rtve.es/resources/TE_NGVA/mp4/0/0/2200000000000.mp4
```

Sería grandioso si lo consigue beardypig

**Comment by bastimeyer** [comment]
Yes, I understand this, but if a requested resource cannot be played, eg. when it's blocked or geo-restricted, Streamlink should return an error message and exit with an error status code. Playing a static error video in these cases is not the job of the plugin, as it would make Streamlink return a different resource and would make it exit with a success code instead. This would not only be inconsistent, but also an incorrect behavior. That's why you have to write a wrapper script, so you can extend Streamlink with your needs.

----

*Sí, lo entiendo, pero si un recurso solicitado no se puede reproducir, por ejemplo, cuando está bloqueado o con restricciones geográficas, Streamlink debe devolver un mensaje de error y salir con un código de estado de error. Reproducir un vídeo de error estático en estos casos no es tarea del plugin, ya que haría que Streamlink devolviera un recurso diferente y lo haría salir con un código de éxito en su lugar. Esto no sólo sería inconsistente, sino también un comportamiento incorrecto. Es por eso que tienes que escribir un script de envoltura, para que puedas ampliar Streamlink con tus necesidades.*

**Comment by DjUnknown** [comment]
youtube-dl does try to show the mp4 video when I execute the command "youtube-dl http://www.rtve.es/directo/la-2/ -o - | ffplay" but it is not displayed because of this error...

[http @ 0000000000574c80] HTTP error 400 Bad Request
http://mvod.lvlt.rtve.es/resources/TE_NGVA/mp4/0/0/╩ÿu?$JrY´┐¢´┐¢´┐¢:

**Comment by Ordval** [comment]
He visto que a veces se muestra el final de algún programa de TV y luego, 
(I've seen sometimes the end of some TV-program is shown and then,)
a menudo, eso cartel/ letrero de que está hablando, (con la ayuda del plug-in)
(often that sign your talking about. [with the aid of the Plug-In] ),
pero, ¿ es tan esencial ?
(but is it that important ?) 

Thanks for the translator **bastimeyer**.

**Comment by DjUnknown** [comment]
To me if I think it's important, it's the only platform that uses this apart, the others have it in their m3u8, it would be nice if it was implanted, the player stays loading for a long time and you don't know if it's down or if the server is overloaded.

**Comment by DjUnknown** [comment]
@Ordval

Your way of comment confuses me when he writes English and Spanish together.

This type of link (m3u8) creates a loop when a content cannot be broadcast over the internet, so I use the normal one, it would be fantastic if you added the rtve mp4 so that you can see us in the player in case a content cannot be broadcast over the internet, as it is now creates confusion whether it is one thing or another, 

I use several programs, I don't use one in question.

**Comment by Ordval** [comment]
Seguiré escribiendo como lo hago, tal vez prefieras más espacios entre las frases ?  

(I will continue writing like I do, maybe you would prefer more spaces between the sentences ?)
  
Sin embargo, no voy a hacer párrafos (textos) separados, 
el texto de arriba habría sido demasiado grande escrito de esta manera).
 
(I won't make separate paragraphs though, the text above would have been too large written like this).

**Comment by DjUnknown** [comment]
I'm not forcing you to write in one way, do recommend because it confuses people if you put the two languages together, having to read between the lines is unacceptable, don't take this the wrong way, it's advice, examples....

English:
...............................
...............................
...............................

Spanish:

...............................
...............................
...............................

**Comment by Ordval** [comment]
As you **Moderators** can see, we're now ridiculously off topic 
but if any of you should happen to know of how to make a half line spacing
instead of a complete, don't hesitate to give me a tip.
