### ISSUE TITLE
NewTek NDI

### ISSUE THREAD

**Issue by JonnyTech** [streamlink/streamlink#1954]
[NDI](https://www.newtek.com/ndi/) / [Network_Device_Interface](https://en.wikipedia.org/wiki/Network_Device_Interface) allows streaming of media across a network and seems like an ideal candidate for streamlink to support. It can be implemented into VLC, OBS, ffmpeg, etc, via plugins and there is a [SDK](https://www.newtek.com/ndi/sdk/) available. What are the chances of seeing this implemented?

**Comment by beardypig** [comment]
I don't think there is any chance of this ever being added. It's completely out of scope. You can probably output the stream from `streamlink` in to VLC and use the plugin to send it, or if there are other tools available for other platforms, I'm sure they can be used too.

**Comment by RockNRollGeek** [comment]
Would like to +1 this idea. Seems like streamlink calling the ndi library to convert to an NDI source that any ndi player/ndi ingest can grab, rather than the messy way of sending to vlc, then sending NDI out from there which creates additional resource usage from the vlc gui running and like JonnyTech mentioned has been prone to some jitter or lag.
