### ISSUE TITLE
Issue template improvements

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#1961]
Ever since the issue template has been split into multiple topic-templates, it feels like even more *bad issues* or issues without any useful information at all have been submitted than before. I didn't count them, so I may be wrong here, because a couple of *bad issues* have been created by a few people who were spamming the tracker lately, but still, I hope everyone can agree that the quality of new issues is not what was expected from this change. What is the reason for this?

**Is the template list too confusing?**
I'm not sure, but there are still lots of issues which are using the wrong template. Maybe the order should be changed and the descriptions be improved. It could also be the fault of some popular mobile apps. FastHub(-Libre) for example doesn't support multiple issue templates.

**Are the individual templates too complicated and overwhelming?**
I think a couple of things need to be removed, so the overall template size can be reduced, which will make it easier to understand. Maybe it's the HTML comment tags which are confusing. The first comment block on each template is pretty big. This could make people think that the whole template is just a single large comment and can be ignored. People who don't know HTML comments/tags or Markdown could also be intimidated or confused by this.

It's not a dramatic issue, but since there are a couple of new threads each day, I think this should be addressed, so that the amount of time unnecessarily spent on the issue tracker here can be reduced.

**Comment by gravyboat** [comment]
I agree that the quality of new issues has decreased. I went and looked back at some old issues, and it seemed like there were still a large number of bad issues. I think the main problem is that in the past we would let bad issues slip by because we only had the one template. Now that we have multiple templates our expectations around issues have gone up which is making these low effort issues more prevalent.

****Is the template list too confusing?***

I'm not sure either. It seems to me that people simply are not reading the templates (or even the titles which is crazy to me). We can modify the order but we would have to prefix the titles with a numerical value or some other kind of identifier to force the order. Regarding descriptions, I'm not sure what we can be more clear on here. They are pretty concise and to the point, and if people aren't even reading the template titles, what will make them read longer descriptions? I'm open to trying any of these ideas however.

***Are the individual templates too complicated and overwhelming?***

I'd be fine with removing more content. It's worth noting that a fair amount of notation was removed/moved when the templates were recreated to try and help with this as people still weren't reading. If we can cut more let's try it, worst case we revert. It could be the HTML tags? I'm really not sure. I agree the first comment block is pretty large and people are ignoring it, but I'm not sure how else we get them to actually read the contributing docs. We specifically note to look at the preview option.

I agree it's not a dramatic issue, but it annoys me every single day and I hate wasting time on these issues. Depending on what is discussed here I would actually propose a more aggressive method:

- Create example issues (which are closed) of each template and link those. We add these to each template and the description, as well as the contributing documentation.
- A new tag is created along the lines of `does not meet issue requirements`, and we create a few default GitHub replies that link to the docs as well as the example template.
- We close and lock any issue that doesn't meet the requirements and paste in the reply.

I'm getting pretty sick of repeated low effort issues and if people can't learn, or aren't willing to take the time to figure out how to create an issue asking us for free work then it isn't worth our time. It doesn't help that we've now got a lot of major sites covered with Streamlink, so many of the requests/issues we're seeing are for smaller sites, or weird configurations.
