### ISSUE TITLE
How to livestream with streamlink

### ISSUE THREAD

**Issue by rookpkm** [streamlink/streamlink#2023]
Hi, I am having a wonder that whether streamlink can combine with ffmpeg to livestream or not, or just streamlink alone can do it.
I usually use ffmpeg to restream, can I use streamlink to restream from pages like ustream or youtube?
If streamlink can do that, please show me the example code.

Thanks so much.

**Comment by bastimeyer** [comment]
This question has already been answered a couple of times here on this issue tracker. However, we don't want to support these use cases, as most people who are doing this are doing it for illegitimate reasons. And since this is not directly related to Streamlink but instead ffmpeg or other tools, you should ask this question somewhere else, as it doesn't really belong here.
