### ISSUE TITLE
How to open Vaughnlive on PotPlayer

### ISSUE THREAD

**Issue by lianquan** [streamlink/streamlink#2028]
Hi,
I use the following code:
`streamlink --player "C:\Program Files\DAUM\PotPlayer\PotPlayer64.exe" https://vaughnlive.tv/newzviewz best`
And I get this message from PotPlayer: https://i.imgur.com/OrcXZdW.png

And there is a problem with the Vaughnlive plugin, there are some channels I can't open them
`streamlink https://vaughnlive.tv/channel best`
`[cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/channel`
`[plugin.vaughnlive][info] Stream powered by VaughnSoft - remember to support them.`
`error: Unable to open URL: https://mp4.vaughnsoft.net/live?stream=live_channel&app=live&port=2935 (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))`

Thanks.

**Comment by gravyboat** [comment]
The first one there's nothing we can do about. It works fine for me in MPV so there must be some issue with PotPlayer itself. The second one isn't something we can do anything about either. `'Connection aborted.', RemoteDisconnected('Remote end closed connection without response'` means that you likely weren't able to reach the server, or that it didn't respond for some reason so that's a service issue with Vaughnlive. I'm going to close this out since neither of these issues are related to Streamlink.
