### ISSUE TITLE
Run Stramlink in background

### ISSUE THREAD

**Issue by grandemestre** [streamlink/streamlink#2044]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I am using streamlink in php script on a local xampp server in a Windows 10. I am trying to make the streamlink run in the background so that the script is not blocked waiting for a response.

### Expected / Actual behavior

Using ffmpeg I can use this:
start /B ffmpeg -hide_banner -loglevel verbose -n -i LINK -c: v copy -acodec copy -bsf: a aac_adtstoasc 1> log.txt 2>&1 video.mp4 and it works. Ffmpeg is in the background and the script continues execution

But when I use this in streamlink it does not work
start /B streamlink hls: //LINK best --hls-segment-threads = 10 --http-no-ssl-verify -o video.mp4

How do I get the expected result using streamlink?

**Comment by bastimeyer** [comment]
This question doesn't really belong here, as it is a Windows batch scripting related question and not a Streamlink related question.

However, you might want to try executing the python executable directly (python.exe or pythonw.exe) and using streamlink.py or streamlink-script.py as its first parameter, because right now, you seem to be executing a wrapper executable which could be causing the problem here.

**Comment by gravyboat** [comment]
Agreed @bastimeyer, closing.

**Comment by dogancelik** [comment]
There's a working solution but you need an external software named [NirCmd](https://www.nirsoft.net/utils/nircmd.html)

Then you can do:
```
nircmd execmd <path to streamlink.exe> <stream url> <quality>
```

Also, if you are using [winpython](https://winpython.github.io/), you need to load `env.bat` before calling streamlink.exe, otherwise it won't work.
```
call <path to winpython3>\scripts\env.bat
```

I really don't know why I need to call that Batch file before nircmd but I think it may be because streamlink searches for some environment variables then it fails, etc.
