### ISSUE TITLE
BT Sport

### ISSUE THREAD

**Issue by slimy1234** [streamlink/streamlink#2045]
- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ x] I have read the contribution guidelines.

### Description

BT sports not working showing no streams was working fine before. Not sure if something has been changed.
streamlink --player-continuous-http --player-external-http --player-external-http-port=11111 --btsports-email EMAIL --btsports-password PASS https://sport.bt.com/btsportplayer/bt-sport-3-01363992468652 best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin btsports for URL https://sport.bt.com/btsportplayer/bt-sport-3-01363992468652
error: No playable streams found on this URL: https://sport.bt.com/btsportplayer/bt-sport-3-01363992468652

**Comment by bastimeyer** [comment]
Since you didn't provide a full debug log, we can't tell whether you are using the latest Streamlink version. A full debug log is required for all bug reports, as the template already suggests (you have also chosen the wrong one).

https://github.com/streamlink/streamlink/issues/new?template=plugin_issue.md
