### ISSUE TITLE
twitch-viewer

### ISSUE THREAD

**Issue by h1rule** [streamlink/streamlink#2049]
## Feature Request

- [ ] This is a feature request and I have read the contribution guidelines.

### Additional comments, screenshots, etc.

Does Twitch-viewer work with this?
https://github.com/ohyou/twitch-viewer

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by skulblakka** [comment]
While it is not only third party software that is not maintained by streamlink (you should ask that question over at the repo you linked), I highly doubt what that script is doing is something streamlink wants to actively support doing

**Comment by bastimeyer** [comment]
This program you've linked is violating the TOS of Twitch by spawning many instances of *Livestreamer* in order to view-bot certain streams.
https://github.com/ohyou/twitch-viewer/blob/master/twitch-viewer.py#L54

You can do whatever you want with that script, but this has nothing to do with Streamlink.
Closing...
