### ISSUE TITLE
Twitch OAuth authorization not working

### ISSUE THREAD

**Issue by TacticalCode** [streamlink/streamlink#2053]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Using the `--twitch-oauth-authenticate` switch, the default browser opens but shows a 404 error generated by Twitch servers instead of showing the form to generate a new OAuth token.

### Expected / Actual behavior

Expected: Twitch page to authorize the app shows
Actual: Twitch 404 Error shows

### Reproduction steps / Explicit stream URLs to test

1. Run `streamlink --twitch-oauth-authenticate`
2. Twitch returns 404

### Log output

```
~$ streamlink --loglevel debug --twitch-oauth-authenticate
Attempting to open a browser to let you authenticate Streamlink with Twitch
```

### Additional comments, screenshots, etc.

Ubuntu 18.04, Firefox, Streamlink  0.10.0+dfsg-1 (from ubuntu repository, issue present in master branch too!)

URL shown in browser on 404 page:
`https://id.twitch.tv/oauth2/authorize/?response_type=token&client_id=pwkzresl8kj2rdj6g7bvxl9ys1wly3j&redirect_uri=https://streamlink.github.io/twitch_oauth.html&scope=user_read+user_subscriptions`

Twitch Documentation (https://dev.twitch.tv/docs/authentication/getting-tokens-oidc/)
```
Use this request:
GET https://id.twitch.tv/oauth2/authorize
    ?client_id=<your client ID>
...
```
Note the additional slash in my browser's URL (before ?response_type=token). Deleting the slash shows the proper Twitch Token authorization page.

The URL is defined here: https://github.com/streamlink/streamlink/blob/master/src/streamlink_cli/main.py#L612
It looks like an outdated URL is used (domain `api.twitch.tv` instead of `id.twitch.tv`), and Twitch redirects to the wrong destination

### Suggested Fix

Replace `https://api.twitch.tv/kraken/oauth2/authorize` with `https://id.twitch.tv/oauth2/authorize`

**Comment by bastimeyer** [comment]
> Twitch returns 404

No it doesn't, I just tested it and it worked without any issues.

The `https://api.twitch.tv/kraken/oauth2/authorize` URL is the old OAuth2 authentication URL (for the "Implicit Code Flow") and can still be used until the kraken v5 API will be shut down at the end of december this year. Until then, all requests should be redirected, otherwise, they would break their deprecated but still supported APIs, which doesn't make sense, even for Twitch. If something doesn't work, it's on their end and probably temporary.

The only thing that's wrong with the URL generated by Streamlink are the `redirect_uri` parameter, which isn't URL-encoded properly, and the missing `force_verify` parameter, which lets the user confirm the authentification in case they were already logged in before making the request.
I'm also getting issues on Python 3.7 with the webbrowser module for opening the URL in the system's browser, but that's a different story.

**Comment by TacticalCode** [comment]
Weird, I certainly get a 404 Error: https://gist.github.com/TacticalCode/ed6555d0259e0279b005462f56d03830
(Tested on a new Firefox profile)

**Comment by unforgiving** [comment]
I've getting the same issue here.

[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/faceittv
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-oauth-token=******** (oauth_token)
[plugin.twitch][debug] Getting live HLS streams for faceittv
[plugin.twitch][info] Attempting to authenticate using OAuth token
error: Unable to open URL: https://api.twitch.tv/kraken/user.json (401 Client Error: Unauthorized for url: https://api.twitch.tv/kraken/user.json?as3=t&oauth_token=MyT0k3nR4nd0mH45hH3r3)

**Comment by back-to** [comment]
> Ubuntu 18.04, Firefox, Streamlink 0.10.0+dfsg-1

this is the **main issue here**, your version is to old.

> Deleting the slash shows the proper Twitch Token authorization page

This was fixed in https://github.com/streamlink/streamlink/pull/1856/files (streamlink 0.14.2)

> domain api.twitch.tv instead of id.twitch.tv

Basically a duplicate of https://github.com/streamlink/streamlink/issues/1346
but this could be updated separately. 

> I'm also getting issues on Python 3.7 with the webbrowser module

Python 3.7 + Firefox works for me.

---

@unforgiving 

Remove `Streamlink` from https://www.twitch.tv/settings/connections and get a new Key

```
streamlink --twitch-oauth-authenticate
```

it should work on `0.14.2` and make sure that there are no spaces behind the Key when you copy it.

**Comment by unforgiving** [comment]
It worked, was my fault, I missed some steps, removing and granting premissions again to Streamlink made the trick. thank you.

**Comment by TacticalCode** [comment]
0.14.2 works as expected, thanks for the hint @bastimeyer
