### ISSUE TITLE
Only getting 30fps videos from youtube even though the youtube video supports 720p@60

### ISSUE THREAD

**Issue by Victolabs** [streamlink/streamlink#213]
I made a video of this happening, since that is probably a better way to explain it than me typing: https://my.mixtape.moe/fyhsnx.mp4

Note: [This little window](http://i.imgur.com/bjRQjjc.png) here that you see later in the video is youtube-dl with a little gui.

**Comment by Vangelis66** [comment]
This is just a duplicate of your previous #200 

The youtube video in your screencast is [[Overwatch] - The Most Useless Exploit Ever](https://www.youtube.com/watch?v=yQs_OXTkk9s)
Using the gear (settings) button, you can investigate available resolutions: 

Adobe Flash Youtube player: 144p, 240p, 360p, 480p, 720p, 1080p
HTML5 Youtube player: 144p, 240p, 360p, 480p, 720p60, 1080p60

I am using Firefox with the [YouTube™ Video and Audio Downloader addon ](https://addons.mozilla.org/el/firefox/addon/youtube-video-and-audio-dow/?src=api), using that you can verify the high 
resolution variants (1080p30, 1080p60, 720p30, 720p60, but also the other resolutions: 480p, 360p, 240p - all available in both VP9/h264 flavours) are being streamed via separate video + audio streams 
in a method known as [MPEG-DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) streaming. 

Using youtube-dl.exe, indeed you can see: 
`youtube-dl -F "https://www.youtube.com/watch?v=yQs_OXTkk9s"` => 

```
[youtube] yQs_OXTkk9s: Downloading webpage
[youtube] yQs_OXTkk9s: Downloading video info webpage
[youtube] yQs_OXTkk9s: Extracting video information
[youtube] yQs_OXTkk9s: Downloading MPD manifest
[info] Available formats for yQs_OXTkk9s:
format code  extension  resolution note
249          webm       audio only DASH audio   57k , opus @ 50k (48000Hz), 7.69
MiB
250          webm       audio only DASH audio   77k , opus @ 70k (48000Hz), 9.93
MiB
171          webm       audio only DASH audio  125k , vorbis@128k (44100Hz), 16.
49MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.4
0.2@128k (44100Hz), 19.02MiB
251          webm       audio only DASH audio  145k , opus @160k (48000Hz), 18.7
8MiB
278          webm       256x144    DASH video  110k , webm container, vp9, 30fps
, video only, 14.52MiB
160          mp4        256x144    DASH video  118k , avc1.4d400c, 30fps, video
only, 16.72MiB
242          webm       426x240    DASH video  262k , vp9, 30fps, video only, 33
.12MiB
133          mp4        426x240    DASH video  262k , avc1.4d4015, 30fps, video
only, 36.93MiB
243          webm       640x360    DASH video  574k , vp9, 30fps, video only, 61
.13MiB
134          mp4        640x360    DASH video  640k , avc1.4d401e, 30fps, video
only, 90.86MiB
244          webm       854x480    DASH video  944k , vp9, 30fps, video only, 11
0.92MiB
135          mp4        854x480    DASH video 1176k , avc1.4d401f, 30fps, video
only, 167.93MiB
247          webm       1280x720   720p 1748k , vp9, 30fps, video only, 221.58Mi
B
136          mp4        1280x720   720p 2348k , avc1.4d401f, 30fps, video only,
332.99MiB
302          webm       1280x720   DASH video 2928k , vp9, 60fps, video only, 38
3.43MiB
248          webm       1920x1080  1080p 3055k , vp9, 30fps, video only, 394.12M
iB
298          mp4        1280x720   DASH video 3570k , avc1.4d4020, 60fps, video
only, 483.16MiB
137          mp4        1920x1080  1080p 4429k , avc1.640028, 30fps, video only,
 629.34MiB
303          webm       1920x1080  DASH video 4906k , vp9, 60fps, video only, 65
3.21MiB
299          mp4        1920x1080  DASH video 5875k , avc1.64002a, 60fps, video
only, 836.88MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3,  mp4a.40.2
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```
All those streams (video-only/audio-only) marked as DASH 
cannot (at least for the time being) be streamed/dumped by streamlink, 
as @beardypig already told you in #200. 

BTW, you should not expect streamlink to turn into a youtube-dl clone app; 
youtube-dl is a very versatile python app with a very big dev team and 
it focuses mainly on VOD download (AFAIK live streams are also supported). 
It can handle the DASH streams because it also uses the external tool FFmpeg 
to mux & sync the separate V+A streams into a format most players can cope with. 

You can read more about streamlink vs youtube-dl in #7 

Hope you now understand things better :wink:

**Comment by gravyboat** [comment]
I'm going to close this one out.
