### ISSUE TITLE
UDP Multicast support?

### ISSUE THREAD

**Issue by K1ish** [streamlink/streamlink#2149]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ x] I have read the contribution guidelines.

### Description

UDP and RTP multicast aren't supported.
Multicasting is very important and I can only use multicast because if i didn't i would have to have a streaming server with a 10 gbit connection to get streams to local network.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Do you want to broadcast RTP streams? You will need to use an external application and pipe the output from streamlink in to that to broadcast. I think VLC will do that for you.

**Comment by JTMaher2** [comment]
I know this is an old issue, but I just wanted to say that I think this is an important feature request. I want to use --player-external-http, but in UDP mode instead of HTTP mode. The reason for this is that my media server only accepts UDP and SRT streams, not HTTP streams. I can't use --stdout, because that would defeat the purpose of --player-external-http. I want to save bandwidth by only downloading the stream when it's requested. So, if there were a --player-external-udp or --player-external-srt option, that would be great!
