### ISSUE TITLE
Disney Channel

### ISSUE THREAD

**Issue by ltonn02** [streamlink/streamlink#2150]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Disney Channel is a German tv channel for kids. They have a website where your can watch their show live from your browser. On the website you can watch the current stream or selected episodes. It would be great if it were possible to watch the livestreams in mp4 etc.
You'll find the livestreams if you click on the first link or on the website click on **Disney Channel**

### Example stream URLs

1. https://tv.disney.de/disney-channel
2. https://tv.disney.de/sehen/the-impatient-patient-578da338f760eae3ee4b34f9

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Since this is mostly VODs it's not something we're interested in supporting: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink Thanks for the request though.

**Comment by beardypig** [comment]
Isn't that what TV is? ;) If it's a single continuous stream, then I don't see the problem in supporting it.

**Comment by gravyboat** [comment]
@beardypig My concern is that you can watch all of the episodes one by one if you want instead of the livestream. I'm just worried about this being used as an example for justifying other sites that may be more questionable in terms of legality because "but it is a livestream!" where it's just constantly streaming stolen content.

**Comment by gravyboat** [comment]
@beardypig My concern is that you can watch all of the episodes one by one if you want instead of the livestream. I'm just worried about this being used as an example for justifying other sites that may be more questionable in terms of legality because "but it is a livestream!" where it's just constantly streaming stolen content.

**Comment by malvinas2** [comment]
I am not sure if I understand the discussion properly, but is there a difference between VOD (=internet media library) or a livestream as long as it is not DRM-protected and not obviously illegal stuff? 
In both cases Streamlink tries to get the source of an obfuscated link, doesn't it?

**Comment by back-to** [comment]
website is gone, they use **youtube** now.

https://tv.disney.de/disney-channel-app
https://www.youtube.com/disneychannelde
