### ISSUE TITLE
Read timeout when downloading an hls-stream despite setting parametrs

### ISSUE THREAD

**Issue by beta2k** [streamlink/streamlink#2154]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I want to download an hls-stream by providing an m3u8 file, but despite setting various parameters always run into a timeout.

### Expected / Actual behavior

The URL points to a server in China. Hence, the connection is not very fast. After downloading for a few minutes, I always get this error:

```
error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

I use several parameters to increase timeouts and retry-attempts, but still it doesn't work. It seems to me that the parameters have no effect. What am I doing wrong?

### Reproduction steps / Explicit stream URLs to test

1. Use the following command to start the download:

```
streamlink "hls://http://7dcdn.ivideo.sina.com.cn/7d.ivideo.sina.com.cn/app/record/subIndex/live_1713429_0_24864_1480654200_1480680600_web_sina_sd.m3u8?fid=1-1540912585486-1221-d4008b60bef4&sid=1713429_null_1540978916089_3510_9060" best -o filefile.ts --hls-segment-timeout 600 --hls-segment-attempts 1000 --stream-segment-timeout 600 --stream-timeout 600 --stream-segment-attempts 1000 --hds-segment-attempts 1000 --hds-segment-timeout 600
```

2. After a few minutes I get this error:

```
Error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Logs

```
[download][filefile.ts] Written 95.4 MB (37s @ 87.5 KB/s)[stream.hls][debug] Adding segment 422 to queue
[stream.hls][debug] Download of segment 401 complete
[download][filefile.ts] Written 95.6 MB (40s @ 82.6 KB/s)[stream.hls][debug] Adding segment 423 to queue
[stream.hls][debug] Download of segment 402 complete
[stream.hls][debug] Adding segment 424 to queue
[download][filefile.ts] Written 95.8 MB (42s @ 77.7 KB/s)                                                              
[stream.hls][debug] Download of segment 403 complete
[stream.hls][debug] Adding segment 425 to queue
[download][filefile.ts] Written 96.1 MB (44s @ 97.9 KB/s)                                                              
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment]
```
--hls-segment-timeout 600 --hls-segment-attempts 1000
```

if a segment fails, your are waiting for 10 minutes of the 5 sec video part,
with this settings it can fail 1000 times

of course it will timeout after 60 sec

https://streamlink.github.io/latest/cli.html#cmdoption-hls-timeout

> The URL points to a server in China. 

I don't know if you are in china or not, but you might want to skip segments.

---

change the global timeout, this can be changed to 600 or more instead of the segment timeout

https://streamlink.github.io/latest/cli.html#cmdoption-hls-timeout

you don't need to change the segment timeout to a big number, 10s is fine or use 20s

https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-timeout

if you don't want to skip a failed segment change this setting to 10

https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-attempts

use `--hls-segment-threads 10` for a faster download speed, if your connection can handle this.

https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-threads

---

you can remove all the other settings, it is just a misconfiguration on your side.

**Comment by beta2k** [comment]
Thanks for your info. I will test it and report back.

Just one question regarding this:
> I don't know if you are in china or not, but you might want to skip segments.

I am not in China, but why would I want to skip segments? Skipping segments means that the resulting video will be incomplete right?

**Comment by back-to** [comment]
> I am not in China,

a connection from outside of china is always pretty bad

> but why would I want to skip segments?

so you don't stuck on an invalid or not available segment

> Skipping segments means that the resulting video will be incomplete right?

might be

---

closing as this is just some user configuration issue
