### ISSUE TITLE
Artifacts/"stuck video" when seeking downloaded twitch video

### ISSUE THREAD

**Issue by akhilkedia** [streamlink/streamlink#2163]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

*Edit* - This seems to be `vlc` issue instead of a streamlink one - using `mpv` as player, seeking is smooth across both versions of the video.
I guess the problem is how vlc deals with some video metadata output by streamlink (which ffmped changes to one acceptable to vlc)? Perhaps this issue should be closed here?

### Description

When downloading twitch vods to file, opening it from vlc, and seeking, the video image seems to be "stuck" for a second. Copying the file again via ffmpeg removes this issue, and seeking is smoother and much more responsive.

### Expected / Actual behavior

Seeking should be smooth without the video image getting temporarily "stuck". There are also sometimes rendering artifacts while seeking.
This effect is fixed on recopying the video via ffmpeg.

### Reproduction steps / Explicit stream URLs to test

1. Download a twitch vod, for example `streamlink  https://www.twitch.tv/videos/335267321 best --hls-segment-threads 10 -o ./video.mp4`
2. Open the vod in `VLC`, and seek using `shift+right arrow` or by clicking at any time in the video bar on the bottom. The seeking is "slow" and "stuck-ish"
3. Recopy the same file via `ffmpeg` - `ffmpeg -i ./video.mp4 -c copy video-fixed.mp4`
4. Open the fixed video file in VLC, and seeking is much more smooth and fast.

### Log output

https://gist.github.com/akhilkedia/a8301edb21a7d0198d609f4e639210c6

### Additional comments, screenshots, etc.

I have observed this issue for a long while now, across multiple versions.
VLC version - 3.0.4
CPU - Intel i7-7820HK
GPU - Nvidia GTX 1070

**Comment by bastimeyer** [comment]
> This seems to be `vlc` issue instead of a streamlink one - using `mpv` as player, seeking is smooth across both versions of the video.
> I guess the problem is how vlc deals with some video metadata output by streamlink (which ffmped changes to one acceptable to vlc)? Perhaps this issue should be closed here?

Twitch streams are regular HLS streams, which means that all what Streamlink is doing here is concatenating MPEGTS segments. There is no remuxing being done.

> `ffmpeg -i ./video.mp4 -c copy video-fixed.mp4`

You are remuxing the MPEGTS stream into an MP4 container with proper headers.
https://stackoverflow.com/a/11792919

VLC 3 has a lot of issues with playing certain formats. The known issues list on the Streamlink website has to be improved a bit to point this out...
https://streamlink.github.io/players.html#known-issues-and-workarounds

There are also considerations regarding changing Streamlink's default player to MPV because of this:
#2144
