### ISSUE TITLE
Next release planned ?

### ISSUE THREAD

**Issue by amurzeau** [streamlink/streamlink#2196]
Hi,

The last version is 0.14.2 which was released on 29 Jun.

As Debian freeze is approaching (12 Jan 2019), I would like to package a newer one so the Buster stable has a more recent streamlink package.

So the question is: is there a new release planned not too far away ?

I'm using streamlink with twitch almost exclusively and didn't have any issue with 0.14.2. Maybe that one is still the one that should go to the next Debian stable.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We've been slacking on getting a new release out there. We wanted to get some icon changes and updates in for a 1.0 release (https://github.com/streamlink/streamlink/pull/2165) but I haven't had time to work on the PR in the past few weeks. We could do an updated release that isn't 1.0 as there are a bunch of changes/improvements since the last one if I can't get to it though.

**Comment by cdrage** [comment]
@amurzeau @gravyboat 

I created an extensive changelog / update for a 1.0.0 release here: https://github.com/streamlink/streamlink/pull/2199 :+1: 

We could always make it a non-1.0.0 release, but there's been so many new milestones since our last release it seems fitting to do a 1.0.0.

**Comment by amurzeau** [comment]
Ok fine :)
I've made a packaging test of current master and got no issue :+1: 
I'm closing this as I got responses and the 1.0.0 PR is now here =)
