### ISSUE TITLE
Infinite retry

### ISSUE THREAD

**Issue by panhartstuff** [streamlink/streamlink#2227]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I'm looking for the right set of options to completely ensure that Streamlink never disconnects. My internet is pretty unstable so, I had a lot of issues with this. 

### Expected / Actual behavior
This is the set of options I put together:
`--hds-segment-attempts 999999 --hds-segment-timeout 999999 --hds-timeout 999999 --hls-segment-attempts 999999 --hls-playlist-reload-attempts 999999 --hls-segment-timeout 999999 --hls-timeout 999999 --http-stream-timeout 999999 --rtmp-timeout 999999 --stream-segment-attempts 999999 --stream-segment-timeout 999999 --stream-timeout 999999 --http-timeout 999999`

So I have a couple of questions about this:
1. This should work regardless of what livestream service you're connecting to right? Am I missing some other options?
2.  I'm getting buffer overflow error (I'm sorry I forgot to copy the exact error message, since I closed it). I'm guessing I set the number too high? What would be the recommended number for this?

### Reproduction steps / Explicit stream URLs to test

1. streamlink -o filename.mp4 --hds-segment-attempts 999999 --hds-segment-timeout 999999 --hds-timeout 999999 --hls-segment-attempts 999999 --hls-playlist-reload-attempts 999999 --hls-segment-timeout 999999 --hls-timeout 999999 --http-stream-timeout 999999 --rtmp-timeout 999999 --stream-segment-attempts 999999 --stream-segment-timeout 999999 --stream-timeout 999999 --http-timeout 999999 https://stream.com/url best

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by sbernsteinHBO** [comment]
While I didn't write it, and I'm not a developer, I've had a look at the retry code before and the problem is that instead of looping, the code is written to retry in a recursive manner.  Python does not allow for infinite recursion -- the limitation varies depending on your OS, but through testing and research I have found that on Windows it was just under 1000.

See this article:
https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it

The retries COULD be in theory refactored such that they do not use recursion if someone wanted to take a stab at it, but it won't necessarily be easy.

**Comment by scottbernstein** [comment]
While I didn't write it, and I'm not a developer _**on this project**_, I've had a look at the retry code before and the problem is that instead of looping, the code is written to retry in a recursive manner. Python does not allow for infinite recursion -- the limitation varies depending on your OS, but through testing and research I have found that on Windows it was just under 1000.

See this article:
https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it

The retries COULD be in theory refactored such that they do not use recursion if someone wanted to take a stab at it, but it won't necessarily be easy.

**Comment by scottbernstein** [comment]
So if you Google "python maximum recursion depth" for your OS, you will find the max value  you can use.  I use 950 for "attempts" and "retries".  This is clearly different from the timeout values, though.

**Comment by panhartstuff** [comment]
Thanks, I'll give it a go with those values next time and see if it works out. What would be the recommended timeout values, it also prone to the same kind of errors?

**Comment by scottbernstein** [comment]
The timeout values can be high (as long as they don't overflow the value of an integer in Python) and they will not cause the program to crash -- BUT there may be drawbacks to very very high timeout values if there is truly a segment or multiple segments that cannot be retrieved from the stream as all of your request threads could be taken up waiting for a very long time for a segment, thereby causing it to miss future segments.  But in general, I think you're on the right track as I also tend to set my retries and timeouts to very high values.
________________________________

**Comment by beardypig** [comment]
@scottbernstein do you know where recursion is used for retries, I don't remember seeing any recursive retries - but, I might have missed it. 

@panhartstuff I wouldn't recommend setting the timeout values very high, better to set it lower and retry more often. With a high timeout value you'll likely cause more problems than you'll solve. I'd recommend leave it at the default value, or if you really do have issues increase it in smaller increments, eg. try 20, 30, etc.

**Comment by panhartstuff** [comment]
Thanks for the advice.
Yeah I realized that what I was doing was probably a bad idea, streamlink got stuck on a 404 segment multiple times forcing me to restart it.
So is there a way of preventing streamlink from exiting because of a timeout/error without it getting stuck like that? Should I leave out all segment timeout options like this:
`--hds-segment-attempts 999999 --hds-timeout 999999 --hls-segment-attempts 999999 --hls-playlist-reload-attempts 999999 --hls-timeout 999999 --http-stream-timeout 999999 --rtmp-timeout 999999 --stream-segment-attempts 999999 --stream-timeout 999999 --http-timeout 999999`
Would segment-attempts cause it getting stuck too?

**Comment by scottbernstein** [comment]
Definitely do not see the retries / attempts for more than 970.

@beardypig I will track down the recursive retries. I know I traced them once before when I got a very strange stack trace after a segment was unavailable and it sprawled out into an "endless" loop of retries until max recursion was reached and the application stopped.

@beardypig while I'm at it, one thing I've been wondering is why the --stream-segment-threads (and other thread options) max out at 10? Seems like an arbitrary number...

Scott
On Jan 4, 2019, at 12:18 AM, panhartstuff <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the advice.
Yeah I realized that what I was doing was probably a bad idea, streamlink got stuck on a 404 segment multiple times forcing me to restart it.
So is there a way of preventing streamlink from exiting because of a timeout/error without it getting stuck like that? Should I leave out all segment timeout options like this:
--hds-segment-attempts 999999 --hds-timeout 999999 --hls-segment-attempts 999999 --hls-playlist-reload-attempts 999999 --hls-timeout 999999 --http-stream-timeout 999999 --rtmp-timeout 999999 --stream-segment-attempts 999999 --stream-timeout 999999 --http-timeout 999999
Would segment-attempts cause it getting stuck too?

**Comment by beardypig** [comment]
@scottbernstein it seems like 10 is a limit from the `livestreamer` codebase, why it's set to 10 I don't know. For live streams anything higher than the `live-edge`  values isn't going to help, and you need to wait for the first segment to complete before anything will play. In the normal live streaming case 1 is OK and 3 would be a sensible maximum.

**Comment by ArturStoeber** [comment]
@panhartstuff I've had a similar problem, but not wanting to try and learn all parameters that may or may not have influence on retries and such, I used a simpler solution.

My problem is/was that I have streamlink installed on my Raspberry PI, which I then remote control via handy app. (SSH Client)
But due to bad wlan or whatever, the stream ends often times early, sometimes as early as 5-10seconds, so I have to restart the stream every couple of seconds at worst. Which is bad enough, but even worse on a phone.

So I switched to a bash script, which I called twitch.


`#!/bin/bash`
`for i in {1..50}`
`do`
`        streamlink twitch.tv/$1 best -np "omxplayer -o hdmi"`
`        echo $i`
`done`


So I just use "twitch mathil1" (you could replace the whole "twitch.tv/$1" with $1 and wouldnt be bound to just twitch), and if the connection crashes, streamlink basically restarts up to 50 times.

Windows supports similar possiblities via batch scripts

**Comment by zxosazx** [comment]
I use bash script for this, only twitch. 
Sorry, i know english very bad. 

#!/bin/bash
#переменные адреса стрима, качества, место записи
rec_adress="www.twitch.tv/hellyeahplay"
quality="1080p60"
location="/home/user/"
#insert OAuth  here (www.twitchapps.com/tmi/), delete "oauth:" 
OAuth_token="******************************"
now=$(date +%Y-%m-%d-%HH-%MM)

#формирование имен файла
rec_login=${rec_adress:14}
filename_rec=$location$rec_login$now".flv"
filename_block=$location"block.conf"
OAuth_header="Authorization: OAuth $OAuth_token"
stream_header="https://api.twitch.tv/helix/streams?user_login=$rec_login"
streamlink_header="$rec_adress $quality -o $filename_rec"

#запрос информации стрима
read block_rec < $filename_block
if [ $block_rec = "1" ]
  then
    exit
fi

client=$(curl -s -H "$OAuth_header" https://id.twitch.tv/oauth2/validate | jq '.client_id')
client=${client:1:${#client}-2}
stream=$(curl -s -H "Client-ID: $client" -X GET "$stream_header" | jq '.data[] | .type')
stream=${stream:1:${#stream}-2}
#обработка записи
cd $location
if [ $stream = "live" ]
 then
  read block_rec < $filename_block
  if [ $block_rec = "1" ]
   then
    exit
   else
    echo $now Stream online: REC! File blocked
    echo 1 > $filename_block
    streamlink $streamlink_header
    echo Stream offline pause 5min
    sleep 5m
    echo 0 > $filename_block
    now=$(date +%Y-%m-%d-%HH-%MM)
    echo Stop Rec. File unblock $now
   fi
 else
  exit
fi

**Comment by panhartstuff** [comment]
Thanks for the help guys
I made my own version based on your scripts
```
#!/bin/bash
STREAM="streamer's URL"
ID="streamer's name"
DIR="your/download/directory/"$ID
SUFFIX="1"
NOW=$(date +%Y-%m-%d)
NOW_INIT=$(date +%Y-%m-%d)
NAME=$ID"_"$NOW"_"$SUFFIX".mp4"
FILE=$DIR"/"$NAME
cd "$DIR"
while :
do
while test -f "$FILE"; do
    SUFFIX=$((SUFFIX+1))
    NAME=$ID"_"$NOW"_"$SUFFIX".mp4"
    FILE=$DIR"/"$NAME
done
echo "streamlink -o $NAME $STREAM best"
sleep 5s
NOW=$(date +%Y-%m-%d)
if [ "$NOW" != "$NOW_INIT" ]; then
    NOW_INIT=$(date +%Y-%m-%d)
    SUFFIX="1"
    NAME=$ID"_"$NOW"_"$SUFFIX".mp4"
    FILE=$DIR"/"$NAME
fi
done
```

If I did something wrong/weird let me know, I don't know bash that well
