### ISSUE TITLE
Muted Twitch videos and the HLS option

### ISSUE THREAD

**Issue by JohnDoh666** [streamlink/streamlink#2236]
## Plugin Issue

- [ x] This is a plugin issue and I have read the contribution guidelines.

### Description

Some Twitch vods have muted parts because of DMCA claims. My issue is that the video freezes in the muted part. This might be related to VLC, but I guess one of you wizards can clarify that for me. 

When I try to view the vods with Streamlink/VLC and the " --player-passthrough=hls" option, the muted parts of the vod will freeze the video. It works with the " --player-passthrough=http", but that means that I cant skip around in the timeline of the vod.

### Reproduction steps / Explicit stream URLs to test

streamlink --player-passthrough=hls https://www.twitch.tv/videos/360497158 best
Fast forward to 01:43:00 for the muted part.

### Log output

streamlink --player-passthrough=hls --loglevel debug https://www.twitch.tv/videos/360497158 best
[cli][debug] OS:         macOS 10.14.1
[cli][debug] Python:     2.7.10
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/360497158
[plugin.twitch][debug] Getting video HLS streams for xqcow
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC

### Additional comments, screenshots, etc.

I have the same issues on both macOS and Windows 10.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> --player-passthrough=hls

This passthrough method just means that Streamlink will use the Twitch-stream's URL as your player's first launch parameter. You can do the same by running `/path/to/player "$(streamlink --stream-url "${URL}" best)"` in BASH. Streamlink won't do anything then after that and just keeps running until you close the player.

If you encounter any issues related to downloading, buffering or demuxing the stream and its video/audio data, it's caused by the player alone. I don't know which VLC version you're using, but 3.0 is known to be buggy. Try a different player like MPV or try to use the latest 2.x version.

> --player-passthrough=http

That passthrough method doesn't do anything, since Twitch doesn't provide any progressive HTTP streams. It gets ignored and Streamlink will do its normal thing, which is downloading the HLS stream, concating its segments and piping the data into your player's standard input. Since it's working on your system with VLC 3, I guess VLC's own HLS implementation or its demuxer are broken.

**Comment by JohnDoh666** [comment]
Thanks for the fast reply. I downgraded VLC from v3.x  to v2.2.8, and it seems to work as expected. Again, thanks, I'm not well versed in these issues and I'm sorry If bother you guys with problems that's not related to Streamlink direcly.

**Comment by bastimeyer** [comment]
It's fine, no problem at all...
Let's close the thread.
