### ISSUE TITLE
Stream.me plugin does not allow Source quality to be selected

### ISSUE THREAD

**Issue by ssolidus** [streamlink/streamlink#2254]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

The `streamme` plugin, for https://stream.me/, only allows `streamlink` to select the qualities that the website has transcoded. It does not allow `streamlink` to select the **Source** option, which is the usually HD and the highest quality.

### Reproduction steps / Explicit stream URLs to test

1. Run the following on any https://stream.me/ :
```bash
$ streamlink https://stream.me/theralphretort
```
2. Observe the qualities available

### Log output

```
$ streamlink --version       
streamlink 0.14.2+201.g965c375

$ streamlink stream.me/theralphretort
[cli][info] Found matching plugin streamme for URL stream.me/theralphretort
Available streams: 144p (worst), 240p, 368p (best)
```

**Comment by TildeSlashC0re** [comment]
Since I've ran into the same issue (with the same stream infact) here's an insight into the situation for anyone that's capable of circumventing this gracefully. 

TheRalphRetort ist the biggest livestream going on on Stream.Me, pulling in about 2000 viewers a night. 
That's roughly 9- to 20-fold of what the most popular streams over there get.
Seemingly Stream.Me stopped advertising the 720p (or highest available source for that matter) link via the API by manual intervention. One can only assume that is an attempt of saving bandwith on their CDN, which I really can't blame them for. 
This being a pro-active measure for **one** streamer (effectively breaking expectations on API results) rubs me the wrong way though. 

All of this is not to say that the source-quality stream is not available at all, because it very much is. One just has to actively select it. 

In API terms their approach was to exclude the 720p(effecitvely source quality) from the `formats.mp4-hls.encodings` array in the `mainfest.json` to the corresponding stream. 
There IS the `formats.mp4-hls.origin` object though that provides the link to the 720p stream. 

In more general terms the source-quality stream can be extracted via the following formula (calling the api-user endpoint):
`_embedded.streams[0]._links.rtmpmp4`**+**`/hls/live/`**+**`_embedded.streams[0].publicId.`**+**`/index.m3u8`

I hope someone more capable than me (when it comes to python) can pick this up and implement a function to parse this as an always available option. 

kind regards
c0re

**Comment by ssolidus** [comment]
> Since I've ran into the same issue (with the same stream infact) here's an insight into the situation for anyone that's capable of circumventing this gracefully.
> 
> TheRalphRetort ist the biggest livestream going on on Stream.Me, pulling in about 2000 viewers a night.
> That's roughly 9- to 20-fold of what the most popular streams over there get.
> Seemingly Stream.Me stopped advertising the 720p (or highest available source for that matter) link via the API by manual intervention. One can only assume that is an attempt of saving bandwith on their CDN, which I really can't blame them for.
> Effectively they just went ahead and set a default of 480p for every incoming viewer until they opt-in for source-quality on their web-player.
> 
> This being a pro-active measure for **one** streamer (effectively breaking expectations on API results) rubs me the wrong way though.
> 
> All of this is not to say that the source-quality stream is not available at all, because it very much is. One just has to actively select it.
> 
> In API terms their approach was to exclude the 720p(effecitvely source quality) from the `formats.mp4-hls.encodings` array in the `mainfest.json` to the corresponding stream.
> There IS the `formats.mp4-hls.origin` object though that provides the link to the 720p stream.
> 
> In more general terms the source-quality stream can be extracted via the following formula (calling the api-user endpoint):
> `_embedded.streams[0]._links.rtmpmp4`**+**`/hls/live/`**+**`_embedded.streams[0].publicId.`**+**`/index.m3u8`
> 
> I hope someone more capable than me (when it comes to python) can pick this up and implement a function to parse this as an always available option. **edit:** friendly ping to @sbstp :)
> 
> kind regards
> c0re

Very dedicated fan. Thanks for the info - I am good enough with Python to be able to implement it, but I probably don't have the time.
