### ISSUE TITLE
Youtube : Error with Python 2.7.15

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#2255]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I updated manually Youtube plugin. I am using streamlink 0.14.2.

### Reproduction steps / Explicit stream URLs to test

```
streamlink "https://www.youtube.com/c/InternetTVHrvatskogasabora/live"
Failed to load plugin youtube:
  File "c:\program files\python27\lib\site-packages\streamlink\plugins\youtube.py", line 14, in <module>
    from streamlink.utils.encoding import maybe_decode
ImportError: No module named encoding

```

### Additional comments, screenshots, etc.

Above is livestream which airs daily live sessions from Croatian Parliament. 

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
As you can see, it can't find the `streamlink.utils.encoding` module, because it didn't exist yet in `0.14.2`.
https://github.com/streamlink/streamlink/tree/master/src/streamlink/utils
https://github.com/streamlink/streamlink/tree/0.14.2/src/streamlink/utils

You can't simply copy plugins from the master branch and use them in an older release. You have to use the latest version of Streamlink that was built from the current head of the master branch.
https://streamlink.github.io/install.html
