### ISSUE TITLE
Streamlink - Callback or Other Signal at End of Process/Recording?

### ISSUE THREAD

**Issue by frisch1** [streamlink/streamlink#2257]
## Issue

- [X] This is not a bug report, feature request, or plugin issue/request.
- [X] I have read the contribution guidelines.

### Description

This is a case where I am guessing I'm looking for the incorrect term. We want to know when streamlink is finished recording... aka the stream ends. We use streamlink as part of a pipeline that starts up dozens of these processes daily.

Right now, we police a ps aux dump 1x/min on a cron, but it's pretty inefficient. We scoured the docs, but there doesn't seem to be any reference to a callback, signal or other method whereby, when the process is complete, it can send a signal out, which we can then feed into the messaging queue to trigger the next phase of the pipeline.

Does this exist in streamlink and, if so, I'm clearly referring to it wrong. Any assistance or pointers would be useful, even if just confirming it isn't part of the application. Thank you.

### Expected / Actual behavior

Expectation is: the script can send an exit or other confirmation upon successful completion (or unsuccessful) that can feed into a messaging queue

### Reproduction steps / Explicit stream URLs to test

N/A

### Logs
N/A

```
N/A
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
I don't know anything about your intentions of the stuff you're using Streamlink for, but from your description - a system that automatically mass-downloads streams - it sounds like you're breaking ToS of the streaming service(s) you're gettings the stream from. You might even be doing illegal things with the redistribution of your recorded streams. [As I've said in this related thread](https://github.com/streamlink/streamlink/issues/1649#issuecomment-388262000), this is not what Streamlink (or Livestreamer back then) was built for and we don't want to support anything in this regard.

But to answer your question, Streamlink is done when its process has terminated. Depending on the returned status code, you know whether it's been successful or not. Parsing stdout/stderr is also an option. If Streamlink's CLI doesn't serve your needs, you can use the provided Python API and write your own logic around that. Since you've mentioned that you're using cron-jobs to filter the system's process tree just to check whether a process is still running, you must be doing something seriously wrong in your scripts.

I'll leave this thread up for someone else to close, in case I'm misinterpreting too much here.

**Comment by frisch1** [comment]
Hi, it's a fair point. Just to clarify, we're working with U.S. government streams e.g. houselive.gov. Under 17 U.S.C. § 105 (Copyright Act), '"a work prepared by an officer or employee" of the federal government "as part of that person's official duties"' are not subject to copyright and are in the public domain. We're ingesting these to transcribe and analyze, which is legal and does not violate ToS.

And to your point, you pointed me in a good direction. We were firing these up to run in the background and thinking from a JS perspective e.g. call me when done. It sounds like just, fundamentally, we were approaching / thinking about it incorrectly. 

But I def did want to clarify: not asking anyone for advice on how to violate ToS or the law. My profile is public with my contact info... I'm very easy to track down (and it's super easy to figure out what we do in that event to validate what's stated above).

**Comment by bastimeyer** [comment]
> thinking from a JS perspective

If you're intending to execute Streamlink (actually python) from a JS runtime like NodeJS, you'll see that it won't differ much from running Streamlink in a shell script context, as the same stuff applies there as well. You could however build your desired event system around that by reacting to process signals or stdout/stderr output.

Closing...
