### ISSUE TITLE
TF1 plugin freezes

### ISSUE THREAD

**Issue by novazur972** [streamlink/streamlink#2270]
## Plugin Issue

- [X ] This is a plugin issue and I have read the contribution guidelines.

### Description

I'm trying the last update https://github.com/streamlink/streamlink/issues/2268
but, with vlc or mpv, I have freezes during a few sec each 8sec (about).
I tried 576p (best), 360p and even 234p (worst)
I don't have this on their website.

### Reproduction steps / Explicit stream URLs to test
streamlink https://www.tf1.fr/tf1/direct best

### Log output

https://paste.pound-python.org/show/JA0sSKhTZB660kQnVx0P/
```
[cli][debug] OS:         Linux-4.14.83-gentoo-x86_64-Intel-R-_Core-TM-_i5-8600K_CPU_@_3.60GHz-with-gentoo-2.6
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugin.tf1][debug] Found channel tf1
[plugin.tf1][debug] Got dash stream https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2000000.mpd?e=1548563911&st=FqrDxYS0sOGTL6RfhqmYfQ
[cli][info] Available streams: 234p (worst), 360p, 576p (best)
[cli][info] Opening stream: 576p (dash)
[stream.dash][debug] Opening DASH reader for: live_1828_H264 (video/mp4)
[stream.dash][debug] Opening DASH reader for: live_2328_AAC (audio/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-1423-90 -i /tmp/ffmpeg-1423-284 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-1423-90
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-1423-284
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_1828/init.m4v complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/init.m4a complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85010000.m4a complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85014000.m4a complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_1828/85010000.m4v complete
[cli][info] Starting player: /usr/bin/vlc
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[cli][debug] Writing stream to output
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85018000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85022000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_1828/85014000.m4v complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85026000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85030000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85034000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_1828/85018000.m4v complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85038000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85042000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85046000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85050000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85054000.m4a complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_1828/85022000.m4v complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85058000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85062000.m4a complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_1828_H264))
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=live_2328_AAC))
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2328/85066000.m4a complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_1828/85026000.m4v complete
[cli][info] Player closed
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
```

**Comment by gravyboat** [comment]
There's a PR that was merged for this already: https://github.com/streamlink/streamlink/pull/2269 so I'm going to close this one. To get the latest version you can either download the nightly build or wait for the next release.

**Comment by novazur972** [comment]
You didn't understand. My english is surely too bad, but I used tf1.py modified yesterday, I ALREADY use the lastest plugin version. Without it, you can't get stream. But with it, you get freezes.
That's not a duplicate, that's the result.

**Comment by beardypig** [comment]
@novazur972 which version of ffmpeg are you using?

**Comment by novazur972** [comment]
Gentoo stable media-video/ffmpeg-3.3.6

**Comment by novazur972** [comment]
I'm sorry but the problem is not solved for me.
I always have freezes playing tf1, with mpv or vlc.
With mpv, I can see it filling cache (10sec), then playing until cache is empty, then freezes, filling cache, etc...
I don't have this problem on the web site, nor with other streams like https://www.dailymotion.com/embed/video/x2lefik?autoplay=1 720p.

**Comment by back-to** [comment]
@novazur972 

> I'm sorry but the problem is not solved for me.

did you try https://github.com/streamlink/streamlink/pull/2297 or/and a newer version of ffmpeg?

**Comment by karlo2105** [comment]
I would like just to point out since @back-to fixed tf1 plugin everything works but dash streams stops after 10 seconds and such errors are displayed in output. 

``streamlink -l debug --https-proxy "195.154.36.74:80" "https://www.tf1.fr/tf1/direct" 576p_dash
[cli][debug] OS:         Windows 7
[cli][debug] Python:     2.7.16
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.46.0)
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugin.tf1][debug] Found channel tf1
[plugin.tf1][debug] Got dash stream https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/l
ive_2000000.mpd?e=1553341396&st=DeH3cmsBRIlhq-FDFoQKmg
[utils.l10n][debug] Language code: fr_BE
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/
a)
[plugin.tf1][debug] Got hls stream https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/mas
ter_2000000.m3u8?e=1553341398&st=2hnzF4aIupEwQRsNvxKYDw
[utils.l10n][debug] Language code: fr_BE
[cli][info] Available streams: 234p_dash, 360p_dash, 576p_dash, 234p (worst), 36
0p, 576p (best)
[cli][info] Opening stream: 576p_dash (dash)
[stream.dash][debug] Opening DASH reader for: live_1828_H264 (video/mp4)
[stream.dash][debug] Opening DASH reader for: live_2328_AAC (audio/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (
id=live_1828_H264))
[stream.mp4mux-ffmpeg][debug] ffmpeg command: C:\Program Files\Python27\Lib\site
-packages\ffmpeg\ffmpeg.exe -nostats -y -i \\.\pipe\ffmpeg-272-954 -i \\.\pipe\f
fmpeg-272-813 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (
id=live_2328_AAC))
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\ffmpeg-272-954
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\ffmpeg-272-813
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Reloading manifest (live_1828_H264:video/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_1828/init.m4v complete
[stream.dash][debug] Reloading manifest (live_2328_AAC:audio/mp4)
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_1828/24026000.m4v complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_1828/24030000.m4v complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_1828/24034000.m4v complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_2328/init.m4a complete
Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
  File "c:\program files\python27\lib\threading.py", line 801, in __bootstrap_in
ner
    self.run()
  File "c:\program files\python27\lib\site-packages\streamlink\stream\segmented.
py", line 59, in run
    for segment in self.iter_segments():
  File "c:\program files\python27\lib\site-packages\streamlink\stream\dash.py",
line 97, in iter_segments
    if not self.reload():
  File "c:\program files\python27\lib\site-packages\streamlink\stream\dash.py",
line 111, in reload
    res = self.session.http.get(self.mpd.url, exception=StreamError)
  File "c:\program files\python27\lib\site-packages\requests\sessions.py", line
546, in get
    return self.request('GET', url, **kwargs)
  File "c:\program files\python27\lib\site-packages\streamlink\plugin\api\http_s
ession.py", line 175, in request
    raise err
StreamError: Unable to open URL: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live
_2000000.mpd?e=1553341396&st=DeH3cmsBRIlhq-FDFoQKmg (403 Client Error: Forbidden
 for url: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2000000.mpd?e=15533413
96&st=DeH3cmsBRIlhq-FDFoQKmg)

Exception in thread Thread-DASHStreamWorker:
Traceback (most recent call last):
  File "c:\program files\python27\lib\threading.py", line 801, in __bootstrap_in
ner
    self.run()
  File "c:\program files\python27\lib\site-packages\streamlink\stream\segmented.
py", line 59, in run
    for segment in self.iter_segments():
  File "c:\program files\python27\lib\site-packages\streamlink\stream\dash.py",
line 97, in iter_segments
    if not self.reload():
  File "c:\program files\python27\lib\site-packages\streamlink\stream\dash.py",
line 111, in reload
    res = self.session.http.get(self.mpd.url, exception=StreamError)
  File "c:\program files\python27\lib\site-packages\requests\sessions.py", line
546, in get
    return self.request('GET', url, **kwargs)
  File "c:\program files\python27\lib\site-packages\streamlink\plugin\api\http_s
ession.py", line 175, in request
    raise err
StreamError: Unable to open URL: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live
_2000000.mpd?e=1553341396&st=DeH3cmsBRIlhq-FDFoQKmg (403 Client Error: Forbidden
 for url: https://tf1-das-live-ssl.tf1.fr/tf1/1/dash/live_2000000.mpd?e=15533413
96&st=DeH3cmsBRIlhq-FDFoQKmg)

[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_2328/24026000.m4a complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe"
--input-title-format 0 -
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_2328/24030000.m4a complete
[stream.dash][debug] Download of segment: https://tf1-das-live-ssl.tf1.fr/tf1/1/
dash/live_2328/24034000.m4a complete
[cli][debug] Writing stream to output
[stream.ffmpegmux][debug] Closing ffmpeg thread``

**Comment by back-to** [comment]
for the dash freezing issue see https://github.com/streamlink/streamlink/issues/2291
