### ISSUE TITLE
Streamlink no longer provides streamlink-script.py

### ISSUE THREAD

**Issue by AeolusDraco** [streamlink/streamlink#2287]
As of version 0.14.0 streamlink does not install the streamlink-script.py script,
because of this streamlink-twitch-gui does not work as it cannot load the script.
This may an issue in streamlink, as there is no mention of its removal in the changelog.

**Comment by back-to** [comment]
> streamlink-twitch-gui does not work as it cannot load the script.

there is a **streamlink.exe** file which can open the streams with streamlink-twitch-gui

you can find it in _(depends on your python location)_

`%LOCALAPPDATA%\Programs\Python\Python37-32\Scripts\streamlink.exe`

my tested `Streamlink Pythonscript` was

`C:\Users\win\AppData\Local\Programs\Python\Python37-32\Scripts\streamlink.exe`

---

the exe files works with a normal `python -m pip install -U streamlink`

don't use the exe file from `pip install --no-binary streamlink streamlink` this won't work

**Comment by back-to** [comment]
> A better way of solving this problem would be including both the wrapper executable and entry script in the pip package on Windows, just like Livestreamer did.

sure it could be done, but my point was that it already works **without any changes**

> > there is a **streamlink.exe** file which can open the streams with streamlink-twitch-gui
> 
> No, that doesn't work.

works for me

> The Twitch GUI's streamlink resolver expects a python executable and a streamlink entry script. Up until the point of this packaging change,

there is a `pythonw.exe` and `streamlink.exe`

---

I tested it with a fresh install

- new windows 10 virtual machine
- vlc install
- python 3.7.2 install with https://www.python.org/ftp/python/3.7.2/python-3.7.2-amd64.exe
- cmd: `python -m pip install streamlink` **(important use the .whl not .tar.gz)**
- streamlink-twitch-gui install with `streamlink-twitch-gui-v1.6.0-win64-installer.exe`
- config streamlink-twitch-gui

ALl user

```
Python
C:\Program Files (x86)\Python37-32\pythonw.exe

Streamlink
C:\Program Files (x86)\Python37-32\Scripts\streamlink.exe
```

or

current user

```
Python
C:\Users\new\AppData\Local\Programs\Python\Python37-32\pythonw.exe

Streamlink
C:\Users\new\AppData\Local\Programs\Python\Python37-32\Scripts\streamlink.exe
```
- open a random stream with vlc

Streamlink starts as expected

---

> because of this streamlink-twitch-gui does not work as it cannot load the script.

so this is invalid

**Comment by silentdragoon** [comment]
Just to confirm that setting the streamlink.exe file as the Streamlink python script appears to work so fine. It would be cool if it was set to this out of the box though!

![2019-02-05 15_42_35-streamlink twitch gui](https://user-images.githubusercontent.com/400279/52284619-ab595800-295c-11e9-8073-93cedc274bf6.png)

**Comment by bastimeyer** [comment]
> my point was that it already works **without any changes**

It only works if the user has set custom paths, which doesn't really mean *without any changes*. This is an **undocumented breaking packaging change** and we should fix this.

Sure, this can (and will be) fixed in the Twitch GUI's next release with an upgraded default resolver config, but other applications could be affected by this, too.

**Comment by bastimeyer** [comment]
Hm, so this seems to be a bit more difficult than I thought. Let me try to explain:

The packaging change was introduced by pynist on Nov 6th after the change in takluyver/pynsist#169. The regular [entry scripts were removed](https://github.com/takluyver/pynsist/pull/169/files#diff-082101e7ff364358b0b29162a1e4a4a9L41) during the switch from `win_cli_launchers` to `distlib` for building the wrapper executables, as that's what pip seems to be using nowadays. This removal is unfortunately breaking the Streamlink Twitch GUI, because of the way it has to resolve and varify the Streamlink entry script and python executable on Windows.

----

Here is how this works:

If a user has set custom paths in the Twitch GUI (as shown in the comments above), no entry-script and executable resolving has to be done, as it's up to the user to select the right files. In case the python executable is not set, it'll use the the `PATH` env var for looking it up and the user has to make sure that the correct python version is used.

If however no custom paths are set, the Twitch GUI has to find the right files on its own, and this unfortunately requires a workaround on Windows. The reason for that is that you can't simply execute the `streamlink.exe` wrapper executable from within the GUI, as it uses `python.exe` instead of `pythonw.exe`, and a terminal window will be opened, which is pretty annoying. Because of this, `pythonw.exe` has to be resolved from reading the shebang of the entry script (it actually reads the `dirname` of this path and looks up `pythonw.exe` in there, because the shebang also references the unwanted `python.exe`).
A quicker alternative to this could be looking up `streamlink-script.py`/`streamlink.exe` and `pythonw.exe` individually from the system's `PATH` env var, but that method is not good enough, as the user could have a global python environment installed and its path could be registered in the `PATH` env var before the one of Streamlink. That could lead to a python version mismatch. Reading the shebang of the entry script is therefore required.

But now, since there's no entry script included anymore in the installer, all you can do is try to read the shebang from the file embedded in the wrapper executable (a zip archive?!), and that's stupid. or you could guess a relative path from that file where `pythonw.exe` is located, but that's equally stupid.

----

The removal of the entry scripts from pynist is a breaking change, but they didn't bump their major version. We could fix this here (temporarily) by downgrading, or the removal could be reverted in pynsist if the dev(s) can be convinced.

Regarding pip, is there a way to make pip always ignore the binary, so one doesn't have to set the `--no-binary streamlink` parameter, like for example a certain packaging flag?
