### ISSUE TITLE
How can I catch the stream of myfreecams?

### ISSUE THREAD

**Issue by IRISlMaple** [streamlink/streamlink#229]
I failed if I key in the address of the chat room.
Please kindly advise.
Appreciate you can help~!!

**Comment by gravyboat** [comment]
I looked through the plugins and I couldn't fine one for myfreecams. I'm going to tag this as a plugin request.

**Comment by IRISlMaple** [comment]
@gravyboat Appreciate! 
Please kindly note me if there is any good news...

**Comment by Gameplayer9198** [comment]
"Sembiance commented on Jun 13, 2015
I figured out how to do this with code.

Here is a node.js script that will take a myfreecams URL or model name, and output the correct livestreamer hlsvariant url: https://gist.github.com/Sembiance/df151de0006a0bf8ae54
Note: You need to run npm install websocket before running the node.js script.

Essentially the steps are:

Connect to the myfreecams websocket chat server (with appropriate origin and cookie)
Send appropriate hello and guest login message
Wait for message type '005369' which contains a URL encoded 'fileno' field
Fetch a javascript file from web: "http://www.myfreecams.com/mfc2/php/mobj.php?f=" + fileno + "&s=xchat20"
Parse part of the JS file as JSON and then find the matching username (nm field) in the list of users and get the users 'uid' and 'camserv'
Format the url as: hlsvariant://http://video" + (modelData.u.camserv-500) + ".myfreecams.com:1935/NxServer/mfc_" + (100000000+modelData.uid) + ".f4v_aac/playlist.m3u8?nc=1423603882490"
Now you can execute livestreamer with the outputed hlsvariant URL and it will work.

Should be fairly straightforward for someone to convert my nodejs script into a python plugin."

This script still works so...  just going to drop this here :P

**Comment by IRISlMaple** [comment]
@gravyboat 
Hello gravyboat, if mfc can be added as a plugin?
Thank you very much.

**Comment by gravyboat** [comment]
@IRISlMaple If someone wants to take on the task of adding it they'll update the thread saying as much. If you want to put a bounty (https://www.bountysource.com/teams/streamlink) on adding it feel free to do so.

**Comment by back-to** [comment]
https://github.com/back-to/streamlink/commit/769aeb16218c8866fa55ad7deb7c76b3e83b334a

@IRISlMaple

Here is a working solution for streamlink.
But it requires a **websocket-client**

If you got `pip` you can install it with

```
pip install websocket-client
```
https://pypi.python.org/pypi/websocket-client

It's similar to the https://github.com/chrippa/livestreamer/issues/561 script, but a bit different and works with streamlink.

**Comment by reasonabledoubt** [comment]
@back-to thanks for that commit.  I tested your changes and they work a lot better then other solutions I've tried.

One sporadic issue I'm running into is that it sometimes hangs at

```[cli][info] Found matching plugin myfreecams for URL https://myfreecams.com/#NAME```

and never proceeds either to

```
[plugin.myfreecams][error] Stream is offline or username is incalid - NAME
error: No playable streams found on this URL: https://myfreecams.com/#NAME
```

or to the stream (if the stream is online).

If there's any testing I can do to help figure this out, I'd be more than happy to.

**Comment by back-to** [comment]
**very important** is that this only works with the same **case-sensitive** usernames as the url was,
mfc doesn't know the username if its not the same as it was in the url


For https://www.myfreecams.com/#UserNaME

**works**
`streamlink https://www.myfreecams.com/#UserNaME best`

**won't work**
`streamlink https://www.myfreecams.com/#username best`

---

the websocket server from **mfc** sometimes **doesn't answer everything** that I need even if i ask the websocket server the right things

so there is a **loop of 15**, if the script doesn't get the right data after 15 loops its cancels the script.

I doesn't want to spam there websocket with this,
because I got the right data most of the time after ~7 loops

But **if this doesn't work** for you,
you can try to **change the loop number** here.
 
https://github.com/back-to/streamlink/commit/769aeb16218c8866fa55ad7deb7c76b3e83b334a#diff-5b6158b3fc533916a37bfb391a5445c6R76

**Comment by reasonabledoubt** [comment]
@back-to ah, thanks for your reply.

Yeah, I'm careful about the case sensitivity, I figured that out.

That loop setting is interesting, but I'm not sure what to change the loop setting to.  As it is now, it'll just hang for perpetually if I don't do anything, so I think it's just waiting for a response and never getting it.  If it failed instead of waiting that might be better for my purposes.  The script I have I just tries again later, but right now it just hangs a lot of the time instead of failing.

So do I need more loops?  Less loops?  What's the best way to debug what's actually happening to me?

**Comment by back-to** [comment]
@reasonabledoubt 

ok I changed some stuff,
it will now use the websocket server only to get a session id for the http server.

with this change the case-sensitive is not important anymore it will work with everything 

---

and if it hangs, you can try to run it in debug mode and see if it does something in the backgroud

`streamlink https://www.myfreecams.com/#UserName best -l debug`

---

direct link to new file
https://raw.githubusercontent.com/back-to/streamlink/4cba50d40423df7dab200e25bfa8822baa896bac/src/streamlink/plugins/myfreecams.py

---

commit
https://github.com/back-to/streamlink/commit/4cba50d40423df7dab200e25bfa8822baa896bac

**Comment by reasonabledoubt** [comment]
@back-to thanks for that, it's working great now.

While debugging I found that with the previous websocket version it would hang at all points in the loop, with no pattern.  But it's very good now, no issues.

The other other suggestion I can make is maybe adding some way to specify `uid` directly instead of username?  I've seen fairly frequent username changes in the past and it might be easier for automation to have a `uid` option.

**Comment by back-to** [comment]
@reasonabledoubt 
yes its possible

USERNAME URL = https://www.myfreecams.com/#UserName
CUSTOM ID URL = https://www.myfreecams.com/id=01234567

this should work now,
it will always print the username and userid in the terminal.

---

file link
https://raw.githubusercontent.com/back-to/streamlink/8505aa001a76c828c79ea09bd92e522809d0f679/src/streamlink/plugins/myfreecams.py

---

commit
https://github.com/back-to/streamlink/commit/8505aa001a76c828c79ea09bd92e522809d0f679

**Comment by Gameplayer9198** [comment]
> C:\Windows\system32>pip install websocket-client
> Requirement already satisfied: websocket-client in c:\python27\lib\site-packages
> Requirement already satisfied: six in c:\python27\lib\site-packages (from websocket-client)
> Requirement already satisfied: backports.ssl_match_hostname in c:\python27\lib\site-packages (from websocket-client)
> 
> C:\Windows\system32>streamlink http://www.myfreecams.com/#Name best **(-l debug same error)**
> [cli][info] Found matching plugin myfreecams for URL http://www.myfreecams.com/#Name
> **[plugin.myfreecams][error] websocket-client is not installed**
> [plugin.myfreecams][info] You can install it with:
> [plugin.myfreecams][info] pip install websocket-client
> [plugin.myfreecams][info] https://pypi.python.org/pypi/websocket-client
> error: No playable streams found on this URL: http://www.myfreecams.com/#Name

file used: 

> file link
> https://raw.githubusercontent.com/back-to/streamlink/8505aa001a76c828c79ea09bd92e522809d0f679/src/streamlink/plugins/myfreecams.py
> 
> commit
> back-to@8505aa0
> 

Windows 10 pro 64bit 
streamlink 0.4.0
Firewall: yes, but off for test
installed myfreecams.py in C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins

As you can see websocket-client (0.40.0) is installed. i tried python 32bit 3.6.1 (same error) uninstalled it and now 2.7.13. is there recommended versions of both?

**Comment by back-to** [comment]
your **streamlink wants to use a different python path** than where the websocket is not installed

If streamlink was installed with pip
```
C:\Windows\system32>where streamlink
C:\Users\Desk\AppData\Local\Programs\Python\Python36-32\Scripts\streamlink.exe

C:\Windows\system32>where python
C:\Users\Desk\AppData\Local\Programs\Python\Python36-32\python.exe

C:\Windows\system32>where pip
C:\Users\Desk\AppData\Local\Programs\Python\Python36-32\Scripts\pip.exe
```

but since you installed streamlink with the exe file your streamlink wants to use

`C:\Program Files (x86)\Streamlink\Python\python.exe` and there is no pip install.

I can't realy say you how to install the websocket when you used the exe file because i get always an error if i try to install it in this path.

**Comment by Gameplayer9198** [comment]
Got it working thanks for the info, I just moved only the websocket-c and its Requirements
(six and backports.ssl if using 2.7).
`c:\python27\lib\site-packages ---> C:\Program Files (x86)\Streamlink\Python\`

**Comment by reasonabledoubt** [comment]
@back-to okay, I've testing using uid URLs and they work now as well.  Everything works very nicely for me now.

I'm not sure if you need to make a formal pull request or what, but I think it's ready.  @gravyboat would certainly know for sure.

**Comment by back-to** [comment]
I'm not so sure about a PR,
since it's maybe to weird for a user to install `websocket-client` for python

**Comment by Damianonymous** [comment]
Are there any chances of fixing the script after the last server update?

**Comment by back-to** [comment]
yes @Damianonymous 
it should work, if they don't change anything again.

https://github.com/back-to/streamlink/blob/195929557b214248c9cfda0d6929649b85b6cf73/src/streamlink/plugins/myfreecams.py

**Comment by Damianonymous** [comment]
Thank you, good job;)

**Comment by IRISlMaple** [comment]
@reasonabledoubt

**Comment by IRISlMaple** [comment]
@reasonabledoubt, @back-to
Really appreciate you two guys.
I'll try all you mentioned methods and thank you very much again...

**Comment by ForgotMyLogin** [comment]
@back-to No longer working for me. It was working this morning, but now it's not. Any fix to this? (Sorry if I should no longer comment here since this is closed)

`C:\Users\User>streamlink https://www.myfreecams.com/#Jenny_Jones best
[cli][info] Found matching plugin myfreecams for URL https://www.myfreecams.com/#Jenny_Jones
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1051, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 345, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 254, in streams
    ostreams = list(ostreams)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\myfreecams.py", line 69, in _get_streams
    data_ws = ws.recv()
  File "C:\Program Files (x86)\Streamlink\Python\lib\site-packages\websocket\_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "C:\Program Files (x86)\Streamlink\Python\lib\site-packages\websocket\_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "C:\Program Files (x86)\Streamlink\Python\lib\site-packages\websocket\_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "C:\Program Files (x86)\Streamlink\Python\lib\site-packages\websocket\_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "C:\Program Files (x86)\Streamlink\Python\lib\site-packages\websocket\_abnf.py", line 358, in recv_frame
    frame.validate(self.skip_utf8_validation)
  File "C:\Program Files (x86)\Streamlink\Python\lib\site-packages\websocket\_abnf.py", line 172, in validate
    raise WebSocketProtocolException("Invalid close opcode.")
websocket._exceptions.WebSocketProtocolException: Invalid close opcode.`

**Comment by throwaway582308** [comment]
Looks like the ping command string has changed.

On this plugin script:

https://github.com/back-to/streamlink/blob/195929557b214248c9cfda0d6929649b85b6cf73/src/streamlink/plugins/myfreecams.py

Change line 52 from

`send_msg_ping = "1 0 0 0 0\n\0"`

to

`send_msg_ping = "0 0 0 0 0\n\0"`

Why? Not sure, but... at

https://www.myfreecams.com/js/wsgw.js

function zgw_ping looks like this

```
function zgw_Ping()
{
  var now = new Date().getTime();
  if (t.g_fConnected && now >= wsNextPingStamp) {
    zgw_Post( { 'c':t.FCTYPE_NULL, 'f':0, 't':0, 'a1':0, 'a2':0 } );
    wsNextPingStamp = now + ((Math.floor(10 * Math.random()) + 10) * 1000);
  }
}
```

And at

https://www.myfreecams.com/js/FCS.js

`FCTYPE_NULL` is defined as `0`, not `1`.

The change worked for me anyway. Previously, I as getting the same error as @ForgotMyLogin above. After the change, I got the streams (well, the streams I was watching anyway; can't say they all work).

**Comment by ForgotMyLogin** [comment]
@throwaway582308 Sweet! Thanks, man! So far, so good...

**Comment by Ro-Den** [comment]
You'd better forget about this script. It uses a flawed scheme to get the required information. Sooner or later you'll start getting IP-bans for using it (see below).

I suspect that using such a scheme in other more popular applications with cool GUI was the cause of recent MFC black-outs. The authors of the apps were too dumb or lazy to study how MFC works. They've set models scan interval at 60 seconds by default. Their apps used by thousands overloaded and crashed the only one MFC server that sends the initial list of models. So, that MFC had to set IP-bans for downloading the initial list more frequently than one time in 20 minutes.

The proper scheme for the script is to get relevant information through dozens of websockets chat servers and avoid using php at all.

**Comment by Alexo88** [comment]
> [chrippa / livestreamer # 561](https://github.com/chrippa/livestreamer/issues/561)
> El script de Sembiance todavía funciona, así que ... solo voy a soltar esto aquí: P

works only for linkstreamer ?

**Comment by Alexo88** [comment]
> Parece que la cadena del comando ping ha cambiado.
> 
> En este script de complemento:
> 
> https://github.com/back-to/streamlink/blob/195929557b214248c9cfda0d6929649b85b6cf73/src/streamlink/plugins/myfreecams.py
> 
> Cambiar la línea 52 de
> 
> `send_msg_ping = "1 0 0 0 0\n\0"`
> 
> a
> 
> `send_msg_ping = "0 0 0 0 0\n\0"`
> 
> ¿Por qué? No estoy seguro, pero ... en
> 
> https://www.myfreecams.com/js/wsgw.js
> 
> La función zgw_ping se ve así
> 
> ```
> function zgw_Ping()
> {
>   var now = new Date().getTime();
>   if (t.g_fConnected && now >= wsNextPingStamp) {
>     zgw_Post( { 'c':t.FCTYPE_NULL, 'f':0, 't':0, 'a1':0, 'a2':0 } );
>     wsNextPingStamp = now + ((Math.floor(10 * Math.random()) + 10) * 1000);
>   }
> }
> ```
> 
> Y en
> 
> https://www.myfreecams.com/js/FCS.js
> 
> `FCTYPE_NULL`se define como `0`, no `1`.
> 
> El cambio funcionó para mí de todos modos. Anteriormente, recibía el mismo error que @ForgotMyLogin arriba. Después del cambio, obtuve las transmisiones (bueno, las transmisiones que estaba viendo de todos modos; no puedo decir que todas funcionen).

so sorry ill install this plugin but i think is not working.

**Comment by bastimeyer** [comment]
You are bumping an old thread of a NSFW plugin which got removed. No support.
