### ISSUE TITLE
`streamlink-script.py` is not found on windows installer installation.

### ISSUE THREAD

**Issue by Dinir** [streamlink/streamlink#2308]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I want to use Streamlink Twitch GUI and I get an error playing a stream there, but it says it didn't find `streamlink-scripts.py` that apparently should be provided by Streamlink so I am submitting this issue here in Streamlink repository.

I installed Streamlink and GUI on Windows 10 x64, and reinstalled them after installing Python 3.7 x64, because I wanted to ensure that it finds Python, although I am aware that Streamlink installer comes with a local python environment.

I also tried using the solution of setting the python script to the exe file (https://github.com/streamlink/streamlink/issues/2287#issuecomment-460010782) as follows:
- Python executable: `C:\Program Files\Python37\pythonw.exe`
- Streamlink python script: `C:\Program Files (x86)\Streamlink\bin\streamlink.exe`

### Expected / Actual behavior

When I was trying to play a stream without the setting for stream not filled up, I get this error:

> **Error: Streamlink misconfiguration**  
> Couldn't find python script  
> Executables were not found

and when I filled up the setting page as I written above, I get this one: 

> **Error: Couldn't launch the stream**  
> Unexpected version check output

### Reproduction steps / Explicit stream URLs to test

1. Install Streamlink with `streamlink-1.0.0.exe` in the release page, for all users.
2. Install Streamlink Twitch GUI with `streamlink-twitch-gui-v1.6.0-win64-installer.exe`, for all users.
3. With or without setting these values in `Settings - Streaming - Streamlink / Livestreamer` in Streamlink Twitch GUI, try watching a stream by clicking any stream that's live.

https://twitch.tv/TwitchDefrags always stream, so this should be a great explicit stream url to test.

### Log output

I can't provide the log output, I can use the CLI one without a problem, but the lack of the py file causes the problem on the GUI.

### Additional comments, screenshots, etc.

my Path as system variable contains
```
C:\Program Files\Python37\Scripts\
C:\Program Files\Python37\
C:\Program Files (x86)\Streamlink\bin
```

**Comment by bastimeyer** [comment]
> Unexpected version check output
> * Python executable: `C:\Program Files\Python37\pythonw.exe`
> * Streamlink python script: `C:\Program Files (x86)\Streamlink\bin\streamlink.exe`

You are mixing two different python environments on your system. You have to use the one bundled with the installer ([which is `3.6.6`](https://github.com/streamlink/streamlink/blob/1.0.0/script/makeinstaller.sh#L67)), in the `python` subdir, otherwise it'll output an error message and a call stack instead of the expected version string from the initial version check which the Twitch GUI has to perform.

> I can't provide the log output

It's fine. There's a detailed error log being output to `stderr` and also written to the logfile, as described in the GUI's wiki, but it's not relevant here.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel

> the lack of the py file causes the problem on the GUI

Yes, there has been an undocumented breaking packaging change here which should be fixed.

However, you can already fix this with the workaround from the other thread you've linked, if you configure it correctly. The GUI's default Streamlink resolver config still has to be updated in order to make it work out-of-the-box again without having to manually set the paths.

Let me close this thread as a duplicate.
