### ISSUE TITLE
How to define my proxy in Configuration file?

### ISSUE THREAD

**Issue by IRISlMaple** [streamlink/streamlink#233]
And I need an example with "Username" & "Password"
Please help~~!

And If there is a document defines all the example of Configuration file?
I want to learn it~!
Thank you very much~!

**Comment by IRISlMaple** [comment]
BTW, if potplayer support cache?

**Comment by Vangelis66** [comment]
@IRISlMaple asked: 

> How to define my proxy in Configuration file?

Is this about a (paid?) HTTP proxy with login credentials? On what OS?
First try to see if specifying it in the command line works: 

`--http-proxy "http://USERNAME:PASSWORD@proxyhost:proxyport"`

If it does, then experiment further by adding the following line in streamlinkrc

`http-proxy=http://USERNAME:PASSWORD@proxyhost:proxyport`

If unusual characters exist in **username** and/or **password**, 
these may need to be escaped; google is your friend here :wink: 
Someone from the devs may add additional input in this issue... 

General guidelines available at [Configuration File](https://streamlink.github.io/cli.html#configuration-file)

Regards.

**Comment by IRISlMaple** [comment]
@Vangelis66 WOW~~!
It really helps~~!
Thank you very much~~~
But the speed is not as well as I set it in an IE proxy...

**Comment by Vangelis66** [comment]
@IRISlMaple wrote: 

> But the speed is not as well as I set it in an IE proxy...

You are on Windows, then :wink:

Is the HTTP proxy your only way to the internet 
or is it being used to unblock specific geo-restricted sites? 

What method have you used for speed comparison 
between using a stream in IE and Streamlink? 
I am sure you know already that using a proxy 
entails an inherent reduction in download speeds; 
and streamlink's performance varies according 
to the type of stream that is being accessed 
(segmented, i.e HDS/HLS, or other type like 
progressive over HTTP, RTMP etc.) and the 
quality variant chosen. 
RTMP streams, when they work, do not use 
your HTTP proxy BTW!

I am not really an expert on this, but the 
performance of some HDS/HLS streams 
could be improved by tweaking some 
HDS/HLS related streamlink options - 
I am sure more experienced users can step in for further details... 
Choosing a lower quality (than the default "best") should also be of help... 

You appear to be stingy in the amount of info you disclose, 
so one can only speculate here :smile_cat:

**Comment by IRISlMaple** [comment]
@Vangelis66 
Really appreciate your patience~~!
I'm in China...As you know, due to the GFW, I only can catch the stream through the proxy~~
So......
I think the problem is streamlink does not support the proxy very well~~!
Whatever, much much much thanks all your help~~!

**Comment by Vangelis66** [comment]
@IRISlMaple wrote: 

> I'm in China... As you know, due to the GFW, 
> I only can catch the stream through the proxy

... I see... :wink: 

> I think the problem is streamlink does not support the proxy very well

All the `--http-proxy` switch does is instruct streamlink to 
forward ALL HTTP requests to the defined HTTP PROXY; 
streamlink is a Python script, so accessing the net is being 
realised through special python modules; I expect this mechanism  
to be quite different to a web browser, but again I am not an expert... 

> Whatever, much much much thanks all your help
 
If you feel my already provided help has covered 
most aspects of your original query, please CLOSE 
this issue; if you need to ask a dev something more 
specific, do so now or you can re-open it in the future... 

@gravyboat 
Don't you think it'd be a good idea to include my [answer](https://github.com/streamlink/streamlink/issues/233#issuecomment-264007551) 
in the help file as an example under "**HTTP options:**" ?
Because, while HTTP_PROXY refers to the environment variable, 
most newbies and Windows users don't know the syntax 
when proxy login credentials are required (a very common scenario)...

**Comment by gravyboat** [comment]
@Vangelis66  Yeah both https://streamlink.github.io/cli.html#cmdoption--http-proxy and https://streamlink.github.io/cli.html#cmdoption--https-proxy should probably have additional examples where a username and password is mentioned (as well as noting that if it is passed over http it's insecure).

**Comment by IRISlMaple** [comment]
@Vangelis66 Yep~! I should close the issue~~!
And again thanks all your help~~!
