### ISSUE TITLE
Youtube Issues

### ISSUE THREAD

**Issue by uknetfreak** [streamlink/streamlink#2330]
I love this plugin and have a host of streams setup on my satellite receiver and also use with VLC.

However, it would appear they have changed something again.

A short time ago, having changed nothing on my end

https://www.youtube.com/watch?v=21X5lGlDOfg
Works As Expected

https://www.youtube.com/user/Russia24TV
Doesn’t Work - 403 Error

https://www.youtube.com/channel/UCmw7DsSCQzRcRG6-SHE_ksg
Doesn’t Work - 403 Error

I'm sure this should be a simple fix and await a solution ASAP. Thanks.

**Comment by uknetfreak** [comment]
UPDATE: Very strange, it now seems to be working again. Did no one else experience this problem? Incidently, would it be possible to allow the plugin to handle multiple live streams per username e.g. RuptlyTV  sometimes has more than one stream at a time?

**Comment by gravyboat** [comment]
It's unlikely functionality would be added to support multiple streams on a single username at a time, you'll just have to get the direct stream URL. Handling that kind of logic within Streamlink isn't something we'd implement, though you could consider adding some sort of wrapper script to do so. I tried duplicating this but couldn't. I'm going to close this since I can't duplicate it.
