### ISSUE TITLE
ERROR 401 when doing "streamlink --loglevel debug --twitch-oauth-authenticate"

### ISSUE THREAD

**Issue by klabacher** [streamlink/streamlink#2339]
This is a bug report and I have read the contribution guidelines.
### Description
Using the --twitch-oauth-authenticate switch, the default browser opens but shows a 401 error generated by Twitch servers after this page
![image](https://user-images.githubusercontent.com/41272117/53887825-da1d2980-4001-11e9-9047-bc3475bb3a38.png)

### Expected / Actual behavior
Expected: Twitch page authorize the app
Actual: Error:
![image](https://user-images.githubusercontent.com/41272117/53887898-fd47d900-4001-11e9-9dd3-c4f146f5d234.png)

### Reproduction steps / Explicit stream URLs to test
Run streamlink --twitch-oauth-authenticate

it opens this

"https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=phiay4sq36lfv9zu7cbqwz2ndnesfd8&redirect_uri=http%3A%2F%2Flocalhost%3A65432%2Fredirect&scope=user_read+user_blocks_read+user_blocks_edit+user_follows_edit+user_subscriptions+chat_login&force_verify=true"

After i click authorize shows this error:
![image](https://user-images.githubusercontent.com/41272117/53887898-fd47d900-4001-11e9-9dd3-c4f146f5d234.png)

### streamlink --loglevel debug --twitch-oauth-authenticate
![image](https://user-images.githubusercontent.com/41272117/53888108-6e878c00-4002-11e9-95e3-cf51eb401f94.png)

**Comment by bastimeyer** [comment]
Why are you mixing up the Twitch authentication of `Streamlink` and `Streamlink Twitch GUI`? These are two different applications with two different Twitch OAuth client IDs.

The Twitch authentication in both Streamlink and Streamlink Twitch GUI is working fine. You must to be using the client ID of the [Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/config/twitch.json#L17) in [Streamlink](https://github.com/streamlink/streamlink/blob/1.0.0/src/streamlink/plugins/twitch.py#L35) itself, which is wrong and you will get a 401 error, because of the return-parameter mismatch.

- If you want to use Streamlink Twitch GUI, you don't have to do anything related to Streamlink and you just have to follow its own auth flow, nothing more. Make sure that your Streamlink config file is clean though...
- If you're using just Streamlink without the Twitch GUI, then don't set any additional parameters and just follow the [documentation](https://streamlink.github.io/cli.html#cmdoption-twitch-oauth-authenticate) and set the [`--twitch-oauth-token`](https://streamlink.github.io/cli.html#cmdoption-twitch-oauth-token) parameter manually afterwards, like you will be told on the return page.

**Comment by klabacher** [comment]
thanks
