### ISSUE TITLE
Feature Request : best-no60fps

### ISSUE THREAD

**Issue by Betsy25** [streamlink/streamlink#2384]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description
I'm streaming all kinds of sources with the "best" switch, however even though my mobile Radeon card (HD5000 series) is able to stream HQ content, it chokes my whole system with every stream that is a 60fps one.

Is there some option like "best-no60fps" ? That will look for and stream the highest quality stream that is NOT 60fps ?

### Expected / Actual behavior
best-no60fps should open the best available stream that is not 60fps.

**Comment by sfkpmr** [comment]
I seem to have a similar issue, so it'd be a nice feature. However, it only seems to happen when I play two 1080p60 streams simultaneously, so it'd be ideal if that was taken into consideration. In my case it'd probably make more sense in https://github.com/streamlink/streamlink-twitch-gui/

**Comment by bastimeyer** [comment]
The problem here is that Streamlink doesn't take "fps" into consideration when calculating the stream name and weight.
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugin/plugin.py#L54-L91
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugin/plugin.py#L280-L412
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/stream/hls.py#L387-L486

The reason for this is that an information like stream fps isn't always available, in case of HLS streams, it's an optional attribute, which means that it depends on the streaming service and also the plugin's implementation.

https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4

> FRAME-RATE
>
> The value is a decimal-floating-point describing the maximum frame
> rate for all the video in the Variant Stream, rounded to 3 decimal
> places.
>
> The FRAME-RATE attribute is OPTIONAL but is recommended if the
> Variant Stream includes video.  The FRAME-RATE attribute SHOULD be
> included if any video in a Variant Stream exceeds 30 frames per
> second.

Either the stream weights need to be changed, or a different filtering mechanism needs to get implemented, similar to `--stream-sorting-excludes`, but for specific attributes.
