### ISSUE TITLE
1.1.0: Windows specific wheels missing on PyPI (streamlinkw executable)

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#2392]
The PyPI deploy job of the 1.1.0 release has partially failed:
https://travis-ci.org/streamlink/streamlink/jobs/513828143#L3637
https://pypi.org/project/streamlink/#files

This means that there are no `win32` and `win-amd64` wheels on PyPI for the 1.1.0 release which include the `streamlinkw` executable (#2326).

The problem is the `cygwin` wheel, which was not accepted by PyPI. Fortunately, the `any` wheel (all platforms) was uploaded first, so the damage of the release failure is minimal. We should fix this in a `1.1.1` release soon, though.

The cygwin wheel can be removed from the next build, but now I'm not sure whether the other ones will be rejected on the next release as well, because there doesn't seem to be a list of platform names accepted by PyPI.

https://github.com/streamlink/streamlink/pull/2326#issuecomment-467825380

https://www.python.org/dev/peps/pep-0425/#platform-tag
https://www.python.org/dev/peps/pep-0425/#id1
https://www.python.org/dev/peps/pep-0427/#file-name-convention

----

The Windows specific wheels can be built and installed locally like this:
```bash
git clone https://github.com/streamlink/streamlink.git
cd streamlink
pip install -U setuptools wheel
pip install -U -r dev-requirements.txt
pip install pycountry
python setup.py bdist_wheel --plat-name=win32
pip install -U ./dist/streamlink-1.1.0-py2.py3-none-win32.whl
```

**Comment by gravyboat** [comment]
> because there doesn't seem to be a list of platform names accepted by PyPI.

PyPI having trash documentation, what a shock! This is rather annoying because even [PyCygwin](https://pypi.org/project/PyCygwin/) seems to be okay with cygwin as a platform but PyPI isn't? Makes no sense.

I went and dug through their [codebase and found the list](https://github.com/pypa/warehouse/blob/master/warehouse/forklift/legacy.py#L93), I didn't paste the mac ones in though:

```
_allowed_platforms = {
    "any",
    "win32",
    "win_amd64",
    "win_ia64",
    "manylinux1_x86_64",
    "manylinux1_i686",
    "manylinux2010_x86_64",
    "manylinux2010_i686",
    "linux_armv6l",
    "linux_armv7l",
}
```

So cygwin isn't supported at all, and we need to change the format from `win-amd64` to `win_amd64`.
