### ISSUE TITLE
plugins.twitch: Low Latency Test Plugin

### ISSUE THREAD

**Issue by Chibicon** [streamlink/streamlink#2402]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Stream doesn't start if the low latency plugin is sideloaded.

Twitch low latency test plugin:
https://github.com/streamlink/streamlink/issues/1676#issuecomment-430304591

### Reproduction steps / Explicit stream URLs to test

1. Launch any stream with the sideloaded [twitch.py](https://gist.githubusercontent.com/back-to/8e9ed3c60e5932d8c7a67ccd43b906d0/raw/e8b4466ace87d59aa43799f2ee14fd7523ee031f/twitch.py) in the plugins folder.

### Log output

```
[session][debug] Plugin twitch is being overridden by C:\Users\User\AppData\Roaming\streamlink\plugins\twitch.py
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/loltyler1
[plugin.twitch][warning] Test Plugin - Low Latency
[plugin.twitch][debug] Getting live HLS streams for loltyler1
[utils.l10n][debug] Language code: en_US
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1033, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 577, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 457, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Users\User\AppData\Roaming\streamlink\plugins\twitch.py", line 960, in _get_streams
    return self._get_hls_streams("live")
  File "C:\Users\User\AppData\Roaming\streamlink\plugins\twitch.py", line 923, in _get_hls_streams
    force_restart=not stream_type == "live")
  File "C:\Users\User\AppData\Roaming\streamlink\plugins\twitch.py", line 256, in parse_variant_playlist
    parser = hls_playlist_load(res.text, base_uri=res.url, parser=TwitchM3U8Parser)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls_playlist.py", line 316, in load
    return parser(base_uri, **kwargs).parse(data)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls_playlist.py", line 258, in parse
    parse_line(line)
  File "C:\Users\User\AppData\Roaming\streamlink\plugins\twitch.py", line 409, in parse_line
    attr = self.parse_tag(line, self.parse_attributes)
AttributeError: 'TwitchM3U8Parser' object has no attribute 'parse_tag'
```

### Additional comments, screenshots, etc.

I hope I did the debug log correctly I'm not that good with command prompt. I do understand that the plugin was just a test but it worked extremely well. So well in fact my player was ahead of the twitch site.

**Comment by bastimeyer** [comment]
Streamlink's Twitch plugin has been changed in `1.1.0` because of the embedded ads which you can now filter out. This required some refactorings of the `M3U8Parser` class (f10ec522a7cde47f7aa000c01e5003455d710e24), so that extending it with custom logic could be done much easier.

@back-to's low latency Twitch plugin also had to extend this class, but didn't refactor it and thus had to copy a bunch of other stuff from this class into the Twitch plugin. These two versions are now incompatible with each other, but it should be easier now for @back-to (or somebody) else to rebase and finally merge both plugin versions due to the refactorings.

**Comment by artemkobets** [comment]
Seems like plugin was extending `M3U8Parser` to handle the `#EXT-X-TWITCH-PREFETCH` tag. 

Here's a patched version that fixed the issue for me -  https://gist.github.com/artemkobets/80306d93b1a2c9dd9b5fa9bc6c34d58c

**Comment by bastimeyer** [comment]
I've pushed a branch for low latency streaming on Twitch to my Streamlink fork. See the diff here:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:plugins/twitch/low-latency
I don't want to submit a pull request though, because it's basically not my own work.

This branch merges the changes of @back-to's test plugin into the current version of the plugin. It also modifies the `HLSStream` and `HLSStreamWorker` classes, so that their methods don't have to be copied as a whole into the Twitch plugin, but this also means that you can't simply sideload it.

```bash
# clone streamlink
git clone https://github.com/streamlink/streamlink.git
cd streamlink
# add my fork to the list of remote repos
git remote add bastimeyer https://github.com/bastimeyer/streamlink.git
# get/update changes from my fork
git fetch bastimeyer
git checkout bastimeyer/plugins/twitch/low-latency
# install via setuptools or whatever method you prefer
python setup.py install
```

You can also apply the changes manually, if you prefer it that way. Here as a `.patch` file:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:plugins/twitch/low-latency.patch

**Comment by thinkpad4** [comment]
Thank you for this, I was gonna make a issue myself asking for a updated version of this plugin.  Thank you very much for the update

**Comment by back-to** [comment]
`stream=True` is missing for fetch (https://github.com/streamlink/streamlink/issues/2180)
without this the delay will be a bit longer

there should probably be an option to turn `EXT-X-TWITCH-PREFETCH` off

**Comment by bastimeyer** [comment]
I've added the streaming segments logic and a `--hls-segment-stream-data` parameter to my low latency branch.
Again, this is not meant for opening a PR, but rather for testing.

The version of my Twitch plugin now also limits the range of `--hls-live-edge` from 1 to 2, in case one is using the default value of 3. It also automatically sets the newly added `--hls-segment-stream-data` parameter.

While testing and using a `--hls-live-edge` value of 1 and MPV without additional cache (`--player-args '--cache=no {filename}'`), I was ahead of Twitch's web player by 2.5-3 seconds without any lags or interruptions. :tada: :tada: :tada:

> there should probably be an option to turn `EXT-X-TWITCH-PREFETCH` off

The official version of the plugins should indeed have such an option if this gets implemented.

**Comment by farzaa** [comment]
@bastimeyer Hello! Thanks so much for this branch :). I'm trying to use it like so

```
streamlink --stream-url --hls-live-edge 1 --twitch-disable-hosting twitch.tv/{self.streamer_user_name} best
```

And I use that link in a custom player, is this possible or must I use the Streamlink player?

**Comment by bastimeyer** [comment]
> I use that link in a custom player, is this possible or must I use the Streamlink player?

It doesn't matter which player you're using. MPV does have the best customization options, though, and its buffer/cache can be reduced to a bare minimum. Just make sure that you're not using the player-passthrough option by accident, because that would bypass Streamlink.

> `--stream-url`

You are not using this parameter correctly. It is meant for the input URL, but as a named parameter instead of the implicit positional parameter. This means that it requires a value, which you have not set.

> `--hls-segment-stream-data`

This parameter gets set implicitly by the plugin and you can leave it out. The parameter would not have been necessary for the sake of this test plugin, but I've added it anyway. As I've said in my post above, an official plugin version would also have the low latency stuff behind an additional plugin parameter, but this is not the case here. No additional parameters required at all.

----

Example using the low latency plugin while using MPV and setting its cache parameter to "no" and also reducing the HLS live edge value to "1" for having the lowest possible delay:

```bash
$ streamlink \
    --hls-live-edge 1 \
    --twitch-disable-hosting \
    --twitch-disable-ads \
    --player mpv \
    --player-args '--cache=no {filename}' \
    twitch.tv/CHANNEL \
    best
```

This may require pausing the stream by pressing <kbd>Spacebar</kbd> for a fraction of a second once it starts lagging/buffering. The delay added by pausing can be reset by pressing <kbd>Enter</kbd>. (assuming MPV's default input config)

**Comment by farzaa** [comment]
@bastimeyer  Got it, this is insanely helpful ty. I actually got things working with MPV which is a good sign =D. This may be a change that could be pushed to master after further testing. 

I'm actually using OpenCV to parse the stream (simply using `cv2.VideoCapture(twitch_streamlink_link_here)` and things are working perfectly for me. But, the problem arises when I start processing low-latency streams, it seems I always fall very behind, often 6-8 seconds. 

Is the OpenCV player the problem or am I getting the the `stream-url` from Streamlink incorrectly?

Using `streamlink --stream-url --hls-live-edge 1 --twitch-disable-hosting twitch.tv/loltyler1 best`.

**Comment by bastimeyer** [comment]
Forget what I wrote earlier... I confused the `--stream-url` parameter with `--url`, sorry about that.

You can't use this parameter. This will simply print out the HLS URL from Twitch. You won't be using Streamlink at all if you're using the returned URL as your player input. It's essentially the same as `--player-passthrough`.
https://streamlink.github.io/cli.html#cmdoption-stream-url
https://streamlink.github.io/cli.html#cmdoption-player-passthrough

You have to use the regular player method, standard output, named pipe or HTTP server output.

**Comment by bennyhillthebest** [comment]
@bastimeyer i tried to install via building myself or via pip, but urllib3 1.25.2 gives problems, because streamlink needs 1.24 iirc. Is editing this line in setup.py gonna solve the problem?

`urllib3[secure]>=1.23;python_version<"3.0"`

Sorry, i'm a noob.

**Comment by bastimeyer** [comment]
@bennyhillthebest See #2446 / #2448

**Comment by Chibicon** [comment]
@bastimeyer
Instructions were easy, thanks. Sideloading plugin method was breaking the disable twitch ads option in the gui program. My only question now is I just need the streamlink-script.py right? I can move it to a better location and delete everything else?

**Comment by bastimeyer** [comment]
> Sideloading plugin method was breaking the disable twitch ads option in the gui program

No, it does not break it. You must have done something wrong. Make sure that you've installed the right version(s).

Yeah, I should probably prepare a pull request for this.

**Comment by Chibicon** [comment]
The patch artemkobets posted above worked for me but if I checked off the "skip ads" option in the gui it wouldn't launch. It wasn't really an issue directly with streamlink itself so I didn't really want to bring it up here and it wasn't really an issue with the gui so I never really mentioned it over there either.

<img width="310" alt="Screenshot_1" src="https://user-images.githubusercontent.com/1420739/59729575-9fcc4680-9204-11e9-954d-fca32d785415.png">

**Comment by bastimeyer** [comment]
You have to install my low latency branch instead
https://github.com/streamlink/streamlink/issues/2402#issuecomment-480455258

What you are using is the old patch which is incompatible with the latest Streamlink release.

**Comment by bastimeyer** [comment]
In case somebody who's using my low latency branch intends to upgrade Streamlink, I have pushed some changes to the branch, as I'm using it for the pull request I've just opened.

This means that the parameters I've talked about earlier now need to be set manually, as no automatic parameter overrides will be done. You can however use the `--twitch-low-latency` parameter, which will set the required values instead. The delay can be further reduced by setting `--hls-live-edge` to 1 and reducing/removing any kind of player caching.

And in case somebody doesn't like these changes, the old commit id 27f75bf can be used instead of the branch name while installing it via pip.

**Comment by DeesseFortuna** [comment]
I've been searching the past few months for a solution that would drop my 7-8 second latency with mpv down to the 1-2s I see with the official web player - didn't find your branch until you mentioned `--twitch-low-latency` and DuckDuckGo picked it up. Now I'm a smidgen _faster_ than the web app. Outstanding. 

Just want to say thank you for your efforts, they forced me to relearn how git and python work together but it was well worth it. Cheers!

**Comment by Ericxgao** [comment]
@bastimeyer I've installed your branch, but am continuing to get 

`streamlink: error: unrecognized arguments: --twitch-low-latency`

With the command: 

`streamlink --twitch-low-latency twitch.tv/Starbeast best`

**Comment by bastimeyer** [comment]
Then you are not using the correct version.

If you're executing just `streamlink` in your command line shell, then it will try to resolve the first matching `streamlink` executable from the directories listed in the `PATH` system env var. You either need to fix the order of directories so that the pip directory comes before the directory where the regular streamlink executable is located, or you can simply use absolute paths when invoking streamlink.

But as I said, I've submitted a pull request for these changes. If there are no further blocking issues, then it will be merged into the master branch, which will probably be soon. See #2513.

There will also probably be a new release soon due to some plugins being broken in the current release.

**Comment by Ericxgao** [comment]
@bastimeyer I am trying using the absolute path, but I still run into the same issue. I am using /root/.local/streamlink.

**Comment by Corben78** [comment]
Thanks for your reply @bennyhillthebest, I tried it with various settings, but eventually those microstutters always occur. Also with mpv and above's recommended settings:
`.config/streamlink/config`:
```
twitch-oauth-token=<...>
player=mpv --cache=no {filename}
twitch-disable-hosting
twitch-disable-ads
hls-live-edge 1
twitch-low-latency
```
It seems depending on the stream I watch though, sometimes it happens earlier, sometimes later. But in the end, after 15 to 30 minutes I'm restarting the stream as the delay got too high. Though it's still way better (resources, simplicty, etc) than watching in the browser, but it would be nice to have solution for this microstutter and delay issue.

**Comment by bastimeyer** [comment]
My comment from above regarding the player parameters is wrong / out of date. Using the `--cache=no` MPV parameter can cause buffering issues, as you're saying yourself. See my comment in the pull request thread here for better caching values (still not 100% reliable though, but acceptable):
https://github.com/streamlink/streamlink/pull/2513#issuecomment-513413639

You also don't have to restart the stream if you fall behind. Just press enter (or the hotkey you've bound it to) to jump to the next entry in the playlist. Since it only contains one input stream, it should clear the (back-)buffer and start reading Streamlink's output again.

**Comment by Chibicon** [comment]
After updating the GUI and your fork of streamlink for 1.3.0 I'm getting this freeze at the beginning of each stream that ends up putting me behind the site now. I see that it is because of having skip ads checked because it says it isn't supported with low latency. This was working fine before what changed?

**Comment by Corben78** [comment]
Can the PR be updated? Looks like since today the twitch kraken API finally got shut down, and my current install of streamlink cannot connect anymore with twitch authentication. Trying to update streamlink and then checkout the PR doesn't work anymore due to conflicts.
