### ISSUE TITLE
Teamliquid's new domain tl.net usage broke the corresponding plugin

### ISSUE THREAD

**Issue by ptkovsky** [streamlink/streamlink#2416]
There's a major issue now where teamliquid's new domain tl.net usage has completely broken the corresponding plugin:
```
streamlink https://tl.net/video/streams/ioioiobb
error: No plugin can handle URL: https://tl.net/video/streams/ioioiobb
```

**Comment by bastimeyer** [comment]
> major issue

This is just a simple regex change, unless they've changed their site's layout.
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/teamliquid.py#L6

The plugin also still uses the deprecated logger calls and needs to get updated.

----

Btw, what is the policy on these kinds of wrapper/proxy/alias plugins? I can remember that we had a discussion about this a few months ago, but I can't find the thread. Doesn't this technically violate the third point here?
https://github.com/streamlink/streamlink/blob/1.1.1/CONTRIBUTING.md#plugin-requests

> 3. Sites which are primarily rehosting content that is available from a legitimate source

My personal opinion is that these plugins are rather pointless, but at the same time they've existed for a long time now and there are people who are using them.

**Comment by gravyboat** [comment]
@bastimeyer From what I remember the only reason we kept any of the teamliquid stuff was basically because it was grandfathered in. One of us (probably me since I hate the duplicate bloat) brought up getting rid of these specific types of plugins during some discussion and we came the the conclusion we would allow old plugins to stay, but wouldn't permit future restream plugins like this to exist.

If we ever want to bring down the hammer I'll be happy to put teamliquid and vaughnlive as number one on the chopping block.
