### ISSUE TITLE
Create streamlink IRC channel on freenode? 

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#242]
Edit: What I had in mind was an IRC channel for for this project where anyone can just 'pop' in and ask a question without having to have a github or gitter account etc. And anyone can also connect to it trough their web browser.

**Comment by bastimeyer** [comment]
I'd recommend using Gitter instead if you guys want a communication channel outside of the Github issue tracker. It is wonderful for any Github related stuff, has lots of integrations and also supports markdown. It's much easier for the average person to use instead of using an IRC client, since it is web based. There's also the Gitter IRC bridge that can be used by any IRC client (also forces secure connections).

Btw, I'm moving my Livestreamer Twitch GUI repo to Streamlink this weekend (streamlink/streamlink-twitch-gui), and I'm already using Gitter 😄 .

**Comment by DragonzMaster** [comment]
Can we have a more specific/general name that not related to another proj ?? @bastimeyer
It is just a suggestion.

**Comment by bastimeyer** [comment]
I misunderstood me... I was not talking about using a single channel for different projects. What I meant was that it'll be more convenient if both are on Gitter.
Btw, https://gitter.im/streamlink/streamlink has already been created back in september.

**Comment by DragonzMaster** [comment]
Sorry If that happened as English is not my native language. What I meant is that name "streamlink-twitch-gui"

**Comment by Hund** [comment]
Gitter is proprietary and it requires an account. I didn't even know what it was until I ducked it now. Just use IRC like everyone else.

**Comment by gravyboat** [comment]
If someone wants to make the IRC they are more than welcome to. Personally I'm not interested in providing that kind of real time support unpaid again. It eats up a lot of time.

**Comment by Robby-** [comment]
Yeah, you can use or direct people to the freenode webchat and embed the channel in the URL so they auto-join to it when logging on to the webchat. It is pretty easy for users and requires no registration at all. I have registered the channel in the meantime.

**Comment by gravyboat** [comment]
Going to close this out since @Robby- made the channel.
