### ISSUE TITLE
RTE Player

### ISSUE THREAD

**Issue by stephen147** [streamlink/streamlink#2426]
## Plugin Issue

[**x**] This is a plugin issue and I have read the contribution guidelines.

### Description
I'm trying an RTE Player URL. It has changed a lot since 2 years ago so getting a no plugin can handle URL error. There may be some territory restriction now since.

### Reproduction steps / Explicit stream URLs to test
1. Just do this in cmd line or similar
`streamlink https://www.rte.ie/player/movie/shortscreen-digs-for-pennies/94356520117`

### Log output
```
C:\Users\user>streamlink --loglevel debug https://www.rte.ie/player/movie/shortscreen-digs-for-pennies/94356520117
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
error: No plugin can handle URL: https://www.rte.ie/player/movie/shortscreen-digs-for-pennies/94356520117
```

**Comment by johnthecracker** [comment]
<a href='https://postimg.cc/LJx1MrXB' target='_blank'><img src='https://i.postimg.cc/LJx1MrXB/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>

**Comment by johnthecracker** [comment]
There is a problem, though.
This site doesn't run to their own admin himself as it looks like to me.
I don't get audio working on web page itself.
Stream playing in a player might be fixed with streamlink plugin, but this is my guess.

https://live.rte.ie/live/a/channel3/channel3.isml/.mpd?t=2019-04-14T07%3A00%3A00Z&available=1555225200&expiry=1555263000&ip=86.176.227.236&filter=systemBitrate%3C%3D100000000&token1=1d8ac60c4e447a69e63448539a012d67e7e60b0f885aec09525cfef0156afd88

<a href='https://postimg.cc/56QXrnQj' target='_blank'><img src='https://i.postimg.cc/56QXrnQj/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>

**Comment by stephen147** [comment]
> There is a problem, though.
> This site doesn't run to their own admin himself as it looks like to me.
> I don't get audio working on web page itself.
> Stream playing in a player might be fixed with streamlink plugin, but this is my guess.

The 404 page. Was that the URL I posted becuase it works my side.

Apparantly they're using a similar system to Netflix, Don't quote me on that (just something I read while on my quest)

**Comment by back-to** [comment]
I don't know if there are `.m3u8` URLs, but the `.mpd` URL is protected.

So this won't work with Streamlink.

**Comment by stephen147** [comment]
> I don't know if there are `.m3u8` URLs, but the `.mpd` URL is protected.
> 
> So this won't work with Streamlink.

Thanks, that's a shame.
