### ISSUE TITLE
[meta] Chocolatey package created for Streamlink

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink#244]
Hey Streamlink team,

I've created a Chocolatey package for Streamlink. ([what is Chocolatey?](https://chocolatey.org/about))
- Package url: https://chocolatey.org/packages/streamlink/0.1.0
- Package source: https://github.com/scowalt/chocolatey-streamlink

This post is mostly just informative, with the following action items:

1. Feel free to review the package and package source and provide feedback.
2. Consider pulling the chocolatey-streamlink package into the streamlink org
3. For future releases feel free to @ ping me on the pull request / commit. This gives me a notification to update the package manually. In the future, we can explore integrating the package into the Streamlink repository and deploying the package directly from Travis. However, there's not a good pre-baked solution that I know of at this time.

Cheers!

P.S. Thanks for making the Windows installer for this program! It made my job incredibly easy.

**Comment by gravyboat** [comment]
This is great @scowalt! I would be happy to get the repo moved over to the Streamlink org if you're interested in doing so. I'm not super familiar with chocolatey packaging, but were you planning on putting the nuspec file into that repo at some point so it is public? I just see the attributes and ignore file. Thanks again!

**Comment by scowalt** [comment]
The package source is in the development branch: https://github.com/scowalt/chocolatey-streamlink/tree/development/Streamlink. My typical development pattern is to PR the development branch into master only when the package is approved by Chocolatey's moderators (since they may have feedback that blocks the package from being published).

I would be happy to have the repo be in the Streamlink org! Makes sense to have it there as well. Feel free to just fork it and I can make PRs to the Streamlink org repo, or I can give up control of the original repository if GitHub has that functionality.

**Comment by gravyboat** [comment]
I totally overlooked there was a dev branch, thanks for pointing that out! I've created a repo for you here: https://github.com/streamlink/streamlink-chocolatey I didn't want to fork since I realized the format for your repo was different than our standard formatting for new repos (sorry about that). If you follow the instructions here: http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories/10548919#10548919 we can retain all your history and the appropriate branches with a PR or two. If you have time could you also add a license to the project? We've been slacking with that on a couple of the repos so I want to make sure we get it done.

Thanks again for taking the time to work on this! Let me know if you want to be added to the streamlink organization.

**Comment by bastimeyer** [comment]
> This package was approved by moderator flcdrg on 12/4/2016.

🎉 🎉 🎉

**Comment by scowalt** [comment]
Package was approved and is now live!

Looks like I'll need Collaborator permissions on the streamlink-chocolatey repo in order to create the `development` branch and merge my repo into yours.

**Comment by bastimeyer** [comment]
I have added you to the orga and given you rights for the repo

**Comment by scowalt** [comment]
Cheers! Working on performing the merge now

**Comment by scowalt** [comment]
Merge is done!

I'll delete scowalt/chocolatey-streamlink once we've confirmed that I performed the merge properly.

**Comment by gravyboat** [comment]
Repo looks good to me @scowalt! Thanks so much for getting that in there. I'll try to make some time to add the download link to the docs and releases page.

**Comment by scowalt** [comment]
Since the packaged is published and we have a maintenance plan in place, I'm going to go ahead and close this issue out.
