### ISSUE TITLE
Bloomberg plugin stopped working

### ISSUE THREAD

**Issue by MaximVol** [streamlink/streamlink#2476]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Bloomberg plugin stopped working May 22. Now it displays "Failed to parse playlist: Missing #EXTM3U header" error message.

### Reproduction steps / Explicit stream URLs to test

streamlink -l debug https://www.bloomberg.com/live/us

### Log output

[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin bloomberg for URL https://www.bloomberg.com/live/us
[utils.l10n][debug] Language code: en_US
error: Failed to parse playlist: Missing #EXTM3U header

**Comment by voltagex** [comment]
I can reproduce this. My browser is requesting https://d1g4mbj10o50ni.cloudfront.net/btv/desktop/us_live.m3u8 from https://www.bloomberg.com/live/us which still works. 

It would be useful to be able to get _more_ debugging information out of the plugin - what is it trying to download, what playlist does it think it's getting that doesn't have #EXTM3U

[working on this, will delete this line when I have an update]

**Comment by bastimeyer** [comment]
This can probably be fixed by adding a User-Agent HTTP header to the HTTP requests. I haven't tested it though...
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/bloomberg.py#L91-L98
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/bloomberg.py#L110-L117
Example here:
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/welt.py#L74-L75

You don't need to add more debug logging, especially log calls which include HTTP response data, as you can simply use python debug tools to see what exactly is going on in detail while fixing/developing a plugin. Including response data can lead to other issues or could potentially be abused.

**Comment by voltagex** [comment]
I understand the bit about not including response data, but I think including *some* debug logging is OK - I'm not using print(), it's only activated when -l debug is specified. The other thing is that the plugin finds multiple matching URLs but bails out after trying only one - perhaps a better behaviour would be to failover to another URL?

**Comment by voltagex** [comment]
`self.session.http.headers.update({"User-Agent": useragents.CHROME})` at the start of _get_live_streams seems to work, but I can't work out why I can't get an `__init__(self)` method to work.

**Comment by MaximVol** [comment]
I added manually definition of user agent in beginning of _get_live_streams and during two days Bloomberg plugin works well.
