### ISSUE TITLE
any plans to support squad streaming? the big new feature on twitch? (multiple streamers streams at once?)

### ISSUE THREAD

**Issue by left1000** [streamlink/streamlink#2480]
any plans to support squad streaming? the big new feature on twitch? (multiple streamers streams at once?)

**Comment by gravyboat** [comment]
I investigated this when squad streaming first came out and I don't see much of a reason to do so. The squad system is just X streams embedded into a single page. It doesn't combine the video or do anything fancy at all that would provided an improved viewing experience (I'm pretty disappointed in this feature if that isn't obvious). It's the same as opening a number of video players with Streamlink for the various people involved in the squad.

How would you see us implementing this? When I thought about it I didn't really come up with any good ways to do it that would improve the experience since we'd basically just open X number of video players with one Streamlink command that the user would then need to resize.

**Comment by beardypig** [comment]
This would probably be something that you'd want to support in an external tool/script - perhaps in streamlink-twitch-gui?
