### ISSUE TITLE
BBC Red Button?

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#2492]
## Issue

- [X] This is not a bug report, feature request, or plugin issue/request.
- [X] I have read the contribution guidelines.

Has anyone ever come across an online stream for the BBC Red Button service? The [Women's World Cup](https://www.bbc.com/sport/football/48064212) will have a number of games shown on the Red Button, I'm just wondering if there is a continuous stream for it somewhere, or if I'll have to navigate to the BBC Sport website each time. And if there is a continuous stream, does the iplayer plugin support it?

**Comment by DAL1189** [comment]
I thought I would bump this up rather than create a new thread. Whenever I use a bbc red button stream like the ones they have for Wimbledon I get an error
``streamlink --bbciplayer-username [username here]  --bbciplayer-password [password here] https://www.bbc.co.uk/iplayer/episode/p07f0z9p/wimbledon-red-button-evans-v-basilashvili

[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/episode/p07f0z9p/wimbledon-red-button-evans-v-basilashvili

[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence

[plugin.bbciplayer][error] Could not find VPID for episode p07f0z9p
error: No playable streams found on this URL: https://www.bbc.co.uk/iplayer/episode/p07f0z9p/wimbledon-red-button-evans-v-basilashvili

**Comment by back-to** [comment]
> The Women's World Cup will have a number of games shown on the Red Button,

closing, as it is over and there are not enough details in this plugin request
