### ISSUE TITLE
Ignore segments of different resolution than rest of stream

### ISSUE THREAD

**Issue by ischmidt20** [streamlink/streamlink#2497]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I would like streamlink to ignore segments of a different resolution than a main stream, particularly when recording/downloading with `-o`.

For some players, notably [FOX](https://www.fox.com/live/channel/FS1/) and [WatchESPN](http://www.espn.com/watch/) (login required for both), the segments during commercial breaks are often of a different resolution and codec than the segments for the actual content. This is not a problem if the stream is playing in a player, but when the goal is to save to a file with `-o`, the resulting .ts file with different resolutions is tricky to work with.

Note that I am using the "manual" method, with a command like so: `streamlink 'hlsvariant://https://content.uplynk.com/channel/d0695f6fa2f143eb95c7a41d96d581c4.m3u8?oid=d09b16c953aa40c98dd8c513526aca5a&ad=espnlive&ad.csid=watchespn:web:espn:live:en&ad.caid=8a474211-a0d0-45c3-a6f3-82d38a9dc9b4&ad.kv=_fw_ae,5525ff59adcaac313923ab89d0a618c5,_fw_euid,41D65629-4BD2-4779-A7E2-85FF9405478E&ct=c&tc=1&exp=1560293022&rn=646822596&ptid=ESPN_tvOS_VDMS&linearv=4&euid=SEC_VDMS&eid=espn_espn1&sig=1c6d9b0859f81575a92d9932b9cc18d9803a38bc84d4ae7ae1f28960775a1ae0' best -o espn.ts`

It appears such segments come up when there is an `#EXT-X-DISCONTINUITY` in the playlist file, in case that helps. There is also an `#UPLYNK-SEGMENT` tag, which will end with `,ad` in the case of an advertisement (see [here](https://github.com/ytdl-org/youtube-dl/issues/21363), you can tell I'm really after this problem), but this is not all-encompassing and ignoring segments with such a tag beforehand unfortunately does not completely solve the problem.

### Expected / Actual behavior

The end goal here is that when recording with streamlink, the .ts file should consistently have the same resolution throughout. Any segments of a different resolution should be ignored. `ffmpeg -i file.ts -c copy file.mp4` should result in an .mp4 file playable in dummy players such as QuickTime, which does not happen in the case of a multi-resolution file.

### Additional comments, screenshots, etc.

Another kind of side question—if this proves too difficult to do, is there any way I can rig streamlink to just save all the segments to a folder, as opposed to catting them on to the stream? This way I could always just manually remove the bad segments before putting them all together into one file.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> #EXT-X-DISCONTINUITY

This HLS tag alone just indicates that a *[content change](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.3)* has happened in the HLS stream and on its own it can't be used for detecting unwanted segments like ads. If the stream output starts with unwanted segments and switches to the "real"/desired content and this tag gets included and you'd filter out everything until the next discontinuity tag, then you'd filter out the wrong segments. There's usually some other metadata in the HLS playlist which can be used to filter out the unwanted segments, but without having access to it, I can't tell you much more. Also, stream inputs without a dedicated plugin are a bit problematic, because if you want to filter out HLS segments, you need to customize the HLS parser/worker/writer/reader.

We've just recently added an ad-segment blocker for Twitch.tv streams, and this works by filtering out segments in between `#EXT-X-SCTE35-{IN,OUT,OUT-CONT}` tags.
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/twitch.py#L142-L150
https://github.com/streamlink/streamlink/blob/1.1.1/tests/plugins/test_twitch.py#L37-L189

**Comment by ischmidt20** [comment]
Hmmm. Once I finally figured out all of the class dependencies, I actually tried my hand at editing the parser to stop segments once the `UPLYNK-SEGMENT` tag appeared. I got it to "work," but for the ads that still said "segment", streamlink understandably still recorded them. It also appears streamlink already takes note of the discontinuity, because it appears in the named tuple for a stream, but I can't find anywhere in the code where that information is used.

I'll edit this post in a bit once I get a couple examples of those "bad" m3u8 files.

**Comment by back-to** [comment]
might be releasable with `should_filter_sequence`

https://github.com/streamlink/streamlink/blob/2.0.0/src/streamlink/stream/hls.py#L129-L130

or with `MuxedStream`

https://github.com/streamlink/streamlink/blob/2.0.0/src/streamlink/plugins/pluto.py#L103-L104

---

but adding a feature for streams behind **paywalls** is just unnecessarily difficult.

closing
