### ISSUE TITLE
List VODs for a channel [enhancement]

### ISSUE THREAD

**Issue by crafty-geek** [streamlink/streamlink#2517]
(This is a separate idea to #134 I think)
(Inspired by a Twitch use case, apologies if there's a separate github specifically for the Twitch plugin that I should use if this isn't general enough, please advise if so)

Could we get a -v parameter or something like that which, when utilized with a channel URL (or the non-Twitch equivalent jargon), will list the last X VODs' names, datestamps, lengths, & other useful/applicable metadata, and allow selection of one of those VODs?  I use streamlink to not have to have a browser's ram overhead while viewing a stream, and having to open my browser to find what VOD link to supply to Streamlink or direct to VLC can get kinda annoying (especially if I'm switching to a new VOD while doing something RAM intensive),

Apparently, https://dev.twitch.tv/docs/api/reference#get-videos says that up to 100 (default 20) videos' details can be fetched through the API, including highlights and uploads by default.

Ideally, make this compatible with --player-passthrough (to allow seeking), quality specification, and other at-startup parameters; just design it as a flag for getting an additional parameter after some data's been fetched.

**Comment by bastimeyer** [comment]
This is not what Streamlink is built for. Streamlink is a tool for piping video streams of various types from an input URL into a player or another output method. It is not a stream/video browser. You will have to use a front end GUI/TUI or wrapper script for Streamlink.

Streamlink has an official [Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui) front end, but VODs are not supported, because as you've probably read in the linked issue thread, using Streamlink for watching VODs doesn't allow you to seek in the timeline of the video and you'll have to use the player-passthrough parameter. When this parameter gets used, Streamlink will be completely bypassed and the player itself will have to do all the stream data fetching on its own instead, which doesn't allow you to use Streamlink's buffering config, etc.

So if you want to browse Twitch VODs in a lightweight way while using Streamlink, you will have to find another front end which lets you do that or you will have to write yourself a simple wrapper script. The Twitch API should be quite easy to understand.
