### ISSUE TITLE
Twitch with --player-external-http playback in browser

### ISSUE THREAD

**Issue by TrevorDev** [streamlink/streamlink#2525]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I am trying to playback twitch through a browser video element but it does not seem to work as described by --player-external-http

### Expected / Actual behavior

Loading localhost:1337 in a video element in a browser would work. (It does work when using a youtube video but not with twitch for some reason)

### Additional comments, screenshots, etc.

1. Run:
streamlink with streamlink https://www.twitch.tv/loltyler1 best --player-external-http --player-external-http-port 1337
2. Observe it starts serving on localhost but trying to load localhost:1337 in a video element in a browser does not work
3. Try it here: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_video
4. Try it here: https://players.akamai.com/hls/ or here: https://videojs.github.io/videojs-contrib-hls/

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
I couldn't make YouTube work either (in latest Chrome), until I changed the `mime-type` output from the `http-server` to `video/mpegts` (it was `video/unknown`). I cannot get it to work with Twitch either - which is strange. The html5 player requests, and receives a part of the video stream, but does not play it. It is possible that the twitch stream is out of the standard and cannot be played. 
I will investigate a bit more, but there might not be much we can do about that. 

One possible workaround is to use VLC to create the stream (it can be done via the command line, but it's overly complex as I remember), then you should be able to access it via a browser - and multiple clients too. 

The original intention of the `--player-external-http` was to allow players that didn't support pipes to connect to the stream. Obviously, and html5 video player is a player that doesn't support pipes, so this _is_ a valid use - but it was not considered when the feature was added 😄 The HTTP server in Streamlink is very basic, so that could also cause some issues. 

I'll see if there is anything else that can be done.

**Comment by nsmith1024** [comment]
Maybe this is cause by a CORS error?

**Comment by nsmith1024** [comment]
can streamlink play LIVE HLS streams (twitch live streams) from a browser on a website?

**Comment by nsmith1024** [comment]
Has this problem been fixed?

**Comment by gravyboat** [comment]
@nsmith1024 The PR that fixes it would have been referenced in this issue if that was the case so no it has not.

**Comment by ryankashi** [comment]
Has there been any progress on this issue? I am currently trying to integrate an HTML5 video player into an Electron application with video supplied through streamlink CLI to essentially make my own user interface for Streamlink with an integrated video player. In this case, an HTML5-based webp layer works best, however as I have come to realize this does not seem to be possible with streamlink at the moment?

Thanks!

**Comment by gravyboat** [comment]
@ryankashi There has not been any progress on this.

**Comment by bastimeyer** [comment]
This completely goes against the idea of Streamlink - to extract streams from websites and view them in a video player. Why would you ever want to add an embedded video in a locally hosted website / locally run web environment with Streamlink as input. That doesn't make any sense, neither from a technical viewpoint, nor from a user experience standpoint. I think this thread should be closed, just like the others. If you really really want web based video players, implement some HLS/DASH js lib and use streamlink to get the stream's URL as input, because progressive output streams won't work well.

**Comment by ryankashi** [comment]
@bastimeyer I see what you're saying. I was able to manage playback inside of an html5 video player with a crunchyroll link but not with a twitch link. For the most part, I am able to get the desired, working use-case via the --stream-url CLI option.

It makes sense to me to close this issue now as you're right - this functionality does not make sense!

**Comment by mkbloke** [comment]
I know this is strictly out of scope, but as it's been asked before and because I have the relevant info to hand, I'm just going to put it here for future reference.  I am piping the stdout of streamlink into cvlc, which creates the necessary ```.m3u``` and ```.ts``` files for streaming.  With this set-up, you'll need a web server to access the content, configured to serve the target directory.  I'm using Apache.  In the example below, the host in the index URL is ```127.0.0.1```.  That would need to be changed to an appropriate IP or host name of the system for access by external clients.  For reasons I won't bore you with, I'm doing this on localhost and it makes sense for the my particular set-up.

Here's the basic command string in generic format to get people started:

```streamlink -O <URL> <STREAM> 2>> /tmp/streamlink.log | cvlc - --aout=adummy --no-xlib --no-dbus vlc://quit --sout="#std{access=livehttp{seglen=10,delsegs=true,numsegs=5,index=stream.m3u,index-url=http://127.0.0.1/stream-########.ts},mux=ts{use-key-frames},dst=stream-########.ts}" &>> /tmp/cvlc.log```

If you can't get this working, do not understand it or need further help, DO NOT ASK HERE!  You should seek help in another more appropriate forum.

**Comment by bastimeyer** [comment]
ffmpeg is more than enough for providing a HLS stream from any source
https://ffmpeg.org/ffmpeg-formats.html#hls-2

Closing this thread now for reasons stated above.
