### ISSUE TITLE
Documentation doesn't match stable version

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#254]
The documentation is build from master whenever there is a commit on master, which is nice for some things like errors or omissions in the docs, but not so good for new features. It is unclear which features the latest stable version supports. For example, the docs currently list bigo as a supported site, however it is only supported in the nightly/HEAD version rather than the latest tagged version (0.1.0). 

There are a couple of ways I can think of resolving this. 
1. We could have a separate repo for the docs and ask people to submit separate PRs to update the docs. This might lead to the docs going unloved as it's an extra bit of work.
2. We could build the docs only on tagged revisions. This would fix the new features only in nightlies, but we'd have to have a tag/release to fix errors and omissions in the docs. We can build multiple versions of the docs, for each tag and for the current HEAD revision (similar to the readthedocs site).
3. We could mark each feature with the version that it was added or if it is currently only supported in the nightly version. This would be more work to update the versions when we release a new version as we'd have to updated all the "this feature is only supported in the nightly version" type messages to "added in x.y.z". It's possible that some automation (sphinx magic) could be used to make the release managers life easier. 

All of these suggestions add extra work, but would ultimately would benefit the users. If anyone has any other suggestions to improve the quality of the docs they would be most welcome. 

I think the 3rd option is pretty good, but the 2nd option would be OK too. 

Thought? Suggestions?

**Comment by gravyboat** [comment]
Hmm, I like the idea of 3, but often times features don't get marked/updated correctly (this happened a lot in the main Salt repo). I definitely prefer this if we can keep it updated/accurate.

**Comment by thatlinuxfur** [comment]
I think 2 jumps out at me as being the most sensible option. In that case, release tags would need to be bumped only when a documentation edit is made that isn't a new addition. Taking a quick glance over the docs history:

https://github.com/streamlink/streamlink/commits/master/docs

I don't see too many of those.

Though this brings up a new question: what triggers a new release? I should think for a utility like this, patches that fix a broken site or ones that add a new site would be enough to push a new release. Youtube-dl seems to release quite often (approximately weekly), so maybe if releases happen sufficiently often this whole thing is just a non-issue. Thoughts?

**Comment by gravyboat** [comment]
@thatlinuxfur Right now nothing specific triggers a release, we've mostly just been doing them when it seems appropriate (bug fixes or big features are added). We added the nightly builds (thanks @beardypig) so people could more easily download very recent versions since this is a pretty small project. We could probably step up the release timeline now that the pipeline is a bit more solid, but I would still like to see more automation in place so it's easier on everyone.

**Comment by beardypig** [comment]
I was thinking that travis would build two versions of the docs, a stable and a nightly version. The stable version would be built when a release is tagged on master (as long as the version is the greatest) and a nightly version would be built on every commit to master.

**Comment by gravyboat** [comment]
@beardypig Yeah I agree with this, it's pretty much the only good way we can support it where we also won't go crazy with maintenance.

**Comment by back-to** [comment]
it can be done with `doctr` very easierly

https://github.com/drdoctr/doctr
https://drdoctr.github.io/doctr/commandline.html
https://drdoctr.github.io/doctr/recipes.html#deploy-docs-from-git-tags


it can push tags to **.**
and every master commit to **dev**

I tested it and it should work as expected,

_in my example dev won't update on a tag,
because I only run it for the main path not the dev path._

https://streamrepo.github.io/
https://streamrepo.github.io/dev/
https://github.com/streamrepo/streamlink/commit/9c832fc12f0edc175228c595978189437c29864d

tag
- https://github.com/streamrepo/streamrepo.github.io/commit/877f0c0c8b2bbc84b483e12ac0a38ab02ce4caf3

master
- https://github.com/streamrepo/streamrepo.github.io/commit/9d0a16913de3561ebbf6d6e4dcc8a7a46208403f

but the deploy key will be stored in the travis file now.

**Comment by beardypig** [comment]
Looks promising, we should investigate doing this some more!
