### ISSUE TITLE
[Plugin Request] Hidive Support

### ISSUE THREAD

**Issue by moyitpro** [streamlink/streamlink#2540]
## Plugin Request
- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Hidive is a streaming site for anime.

### Example stream URLs
https://www.hidive.com/stream/the-demon-girl-next-door/s01e001
https://www.hidive.com/manifest/master/1bf701e4122b0e605fafbeccadfc03e2fd059b99/MMZ_s01e001_tv_br_or_ja_xx_HLS_16x9_01_v.m3u8

### Additional comments, screenshots, etc.
Some titles/streams require a premium account or may have regional restrictions. The stream is not DRM protected (tested with Firefox with the Google DRM plugin disabled). Also, Youtubedl already supports this site, meaning there is no DRM protection.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
It doesn't seem like there are any live streams on this site, it's all just VODs. Am I just missing it somewhere on the site where they stream live content? A simulcast isn't a live stream.

**Comment by moyitpro** [comment]
I digged deeper and the player uses a M3U8 file extension. I don't see why it can't be supported since similar sites such as Crunchyroll and FunimationNow is supported.

**Comment by gravyboat** [comment]
@moyitpro We took the stance a while back that we weren't going to add new sites that are mostly VODs. Streamlink is for live streaming content. Stuff like Crunchyroll and FunimationNow were already part of Streamlink when we implemented this rule so we decided to keep them in. At one point we were getting inundated with VOD sites and as you noted Youtubedl already supports this so people are free to use that since they support a lot more VOD services than we do.

When you created the issue there was a note regarding reading our guidelines and plugin request requirements. You can find more details about them here: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by moyitpro** [comment]
If I develop a plugin for it, would this be okay?

**Comment by gravyboat** [comment]
@moyitpro You're welcome to [side load it](https://streamlink.github.io/cli.html#sideloading-plugins) but I don't think we would add it. Due to the large number of plugins Streamlink already has people who are running it on very weak hardware have noticed considerable delay in the past so we're trying to keep things as light as possible.
