### ISSUE TITLE
Streamlink doesn't give the exit code used to kill it

### ISSUE THREAD

**Issue by mlindner** [streamlink/streamlink#2548]
Normally when a process is killed the signal used to kill the process should be visible in the exit code. However streamlink doesn't do that which makes it hard to use as part of a script. If I hit ctrl+c when running it, it still returns 0, it should not do this.

**Comment by back-to** [comment]
some details would be nice

**Comment by beardypig** [comment]
The expected exit code will depend on the operating system. For this case POSIX just says that the exit code should be >128 I believe, no idea for Windows if there is a standard.

**Comment by mlindner** [comment]
Streamlink always returns 0, so it's not compliant either way.

Please remove the "does not meet requirements" label, it's incorrect. All the necessary details are available. This is common across all platforms.

**Comment by bastimeyer** [comment]
> ctrl+c inside mpv player

Terminating the spawned player child process, regardless the signal, is not treated as an error in Streamlink and therefore the exit code of itself is `0`. If you're instead sending a `SIGINT` (ctrl+c) or `SIGTERM` signal to Streamlink's python process, then it will be interpreted as an error and will exit with `128 + 2 = 130` (SIGINT=2).
For `SIGTERM`, we should change the exit code to `0` though.

> If I run the same test with just mpv I get return code of "4".

If you're using MPV on its own, then you are obviously not using streamlink and the exit codes can be different, because it depends on the individual program.

`CTRL+c` is a keybinding in MPV:
https://github.com/mpv-player/mpv/blob/v0.29.1/etc/input.conf#L162

Sending a `SIGTERM` signal to MPV on the other hand will result in the exit code `0`.

**Comment by mlindner** [comment]
This is incorrect behavior. If the subprocess is killed then streamlink __needs__ to take that as it’s error code or to exit with a similar non-zero error code. Exiting with zero is wrong.
