### ISSUE TITLE
Twitch is ending v3 API Sept 12th

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#2571]
I got this email from Twitch:  v3 API Shutdown

Starting on August 12, 2019, we will begin implementing scheduled outage windows of v3 endpoints over several weeks ending with a complete shutdown of v3 endpoints on September 12, 2019. If you do not take action to migrate your application to v5 of the API, your application will experience outages during this time and will completely break on September 12.

I don't know if Streamlink still uses API v3 but if so you have 2 months left

**Comment by bastimeyer** [comment]
> I don't know if Streamlink still uses API v3

The v3 API is the very old one and it's not being used by Streamlink since 2017-02-01 (#484):
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/twitch.py#L455

I'm not sure if they consider their old private API endpoints part of v3 though:
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/plugins/twitch.py#L305-L321

If that's true, then certain features like hosts redirection could fail. Possibly even the acquirement of the stream access token, but that's rather unlikely.

----

Regarding the Streamlink Twitch GUI, I've received an email from Twitch a few days ago as well which said that my registered app is still actively sending v3 requests, which I think is total nonsense. I have [migrated my app more than two years ago to v5](streamlink/streamlink-twitch-gui/d4e9885), but it's also still using many parts of the old private API, like following games or getting channel descriptions, which have been replaced by GQL on their site a while ago, and I'm unsure whether they are considered a part of v3 or not. The Twitch GUI also optionally passes its client-id to Streamlink, and therefore it is also possible that Streamlink itself is responsible for Twitch's claim by making certain API requests which the Twitch GUI is not making. Another possibilty is that people are still using (very) old versions or that someone "has stolen" the client-id and is using it in their own programs or scripts.

Either way, I don't think that this is an issue and neither Streamlink nor the Twitch GUI will be affected by the removal of the v3 API.

@gravyboat Since you have registered Streamlink's client-id on Twitch with your email address, did you receive a similar email?

**Comment by bastimeyer** [comment]
Before I forget it, regarding the shutdown of v5 (#1346), AFAIK the exact date is still unknown, but it will happen some time next year. This means that we will have to switch to the new "helix" API eventually.

Regarding the [rate limiting](https://dev.twitch.tv/docs/api/guide/#rate-limits), this is still a problem, because it's really low for requests without a [bearer token](https://dev.twitch.tv/docs/authentication/#types-of-tokens) (aka [auth token](https://dev.twitch.tv/docs/authentication/#sending-user-access-and-app-access-tokens), aka signed-in user). This means that Streamlink will have to require its users to sign into their Twitch accounts in the future, since 30 API requests per minute will not be enough.

Feature-wise, Streamlink should probably be okay, as it's using endpoints which (already) exist in both APIs. The private API calls however are again questionable.

**Comment by nsmith1024** [comment]
I was thinking of using streamlink for a twitch project, but now read that v3 will stop. Does streamlink have v5 capability already? anybody knows?
