### ISSUE TITLE
MPC-BE support

### ISSUE THREAD

**Issue by MannixMD** [streamlink/streamlink#2632]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Can we get support for MPC-BE because the MPC-HC has been discontinued ?

**Comment by Vangelis66** [comment]
> because the MPC-HC has been discontinued ?

This is only partially true; a coder related to the original dev team has taken over it, in essence maintaining the third party libs inside MPC-HC, with occasional bug fixing; see more at 

https://github.com/clsid2/mpc-hc/

https://github.com/clsid2/mpc-hc/releases

https://forum.doom9.org/showthread.php?p=1831201

FYI, a major project is under way, very close to completion actually, to give MPC-HC a dark look (in fact, even darker than MPC-BE); more [here](https://github.com/clsid2/mpc-hc/pull/90)! 

Regards 😄

**Comment by 10mins** [comment]
> Can we get support for MPC-BE

What version/build are you using? Streamlink is working just fine with MPC-BE.

**Comment by bastimeyer** [comment]
There is nothing for Streamlink to "support". The player has to support Streamlink's output, which is reading a stream from `stdin` in the default configuration and also demuxing/decoding the audio/video stream. That however is something every player should be capable of.

If you're asking for an entry to be added to Streamlink's config file (which only gets written by the Windows installer), then please send a pull request with the additional commented paths, similar to the MPC-HC ones:
https://github.com/streamlink/streamlink/blob/1.2.0/win32/streamlinkrc#L21-L23

If you're however asking for an addition to Streamlink Twitch GUI's player profiles, since you seem to be a user of it as you've already posted an issue on its tracker a few weeks ago, then you're on the wrong issue tracker here. Let me know and I'll move the thread to the right place.

**Comment by MannixMD** [comment]
> > Can we get support for MPC-BE
> 
> What version/build are you using? Streamlink is working just fine with MPC-BE.
> ![mpc png](https://user-images.githubusercontent.com/11040529/65490050-17b9a500-deb5-11e9-8ed3-f3aa25bad14c.jpg)

I use the latest version just like you on the screenshot but my is 32bit app and I'm getting Can't render file error under the controls.

**Comment by MannixMD** [comment]
> > because the MPC-HC has been discontinued ?
> 
> This is only partially true; a coder related to the original dev team has taken over it, in essence maintaining the third party libs inside MPC-HC, with occasional bug fixing; see more at
> 
> https://github.com/clsid2/mpc-hc/
> 
> https://github.com/clsid2/mpc-hc/releases
> 
> https://forum.doom9.org/showthread.php?p=1831201
> 
> FYI, a major project is under way, very close to completion actually, to give MPC-HC a dark look (in fact, even darker than MPC-BE); more [here](https://github.com/clsid2/mpc-hc/pull/90)!
> 
> Regards

Thank You for all this useful links ;)

**Comment by MannixMD** [comment]
Ok I have found what is wrong. The issue is with MPC-BE it can't handle the hls stream http works fine
