### ISSUE TITLE
freedesktop / x11 startup notifications

### ISSUE THREAD

**Issue by anlutro** [streamlink/streamlink#2668]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I use the i3 window manager, which has a concept of workspaces. by default, new windows are created in the active workspace, which is not always what I want. This happens a lot:

1. I run `streamlink twitch.tv/whatever` on workspace 1
2. I switch to workspace 2 to do other stuff while I wait for the stream to open
3. After 3-5 seconds, video player starts on workspace 2

Freedesktop/x11 has a concept of startup notifications which i3 uses to know which workspace to place windows in. http://standards.freedesktop.org/startup-notification-spec/startup-notification-latest.txt

If livestreamer were to send a startup notification, it would in theory start on workspace 1 instead. I say in theory because I have very little knowledge of how startup notifications work in practice, or if this is in any way doable. I also guess the fact that streamlink starts a media player subprocess complicates matters further.

### Expected / Actual behavior

Actual: In i3, the media player which streamlink spawns always shows up in the active workspace.

Expected: The media player spawns in the same workspace in which the `streamlink` command is invoked.

**Comment by gravyboat** [comment]
@anlutro Thanks for the clear explanation of the issue you're encountering. Does this happen no matter which video player you're using? Also are you running Streamlink via Python 2 or Python 3?

**Comment by bastimeyer** [comment]
That's not a Streamlink specific problem. This is the usual behavior when launching programs from the shell which will open X11 windows. If you're quickly switching to a different desktop before the process's window gets shown, it'll be opened on the current desktop where you've just switched to.

Is there a way to specify the initial desktop of X11 clients via an environment variable? Otherwise, Streamlink would need to implement X11 client messages.

> Expected: The media player spawns in the same workspace in which the `streamlink` command is invoked.

I know it's not an elegant solution, but as a dirty workaround for now, you could use this script which I've just written. It needs to be used as Streamlink's player and launches the actual player from the passed player parameters, then redirects stdin (unused if a different transport method gets chosen) and polls the X11 window ID tied to the player's process ID. Once the player window is shown and is found by the script, it'll get moved to the desktop specified by the `PLAYER_DESKTOP` env var, which you need to set before launching streamlink. The current desktop (when executing the script) can easily be set by a command substitution. Otherwise, set a static PLAYER_DESKTOP value from 0 to n-1.

Example:

```bash
env \
  PLAYER_DESKTOP=$(wmctrl -d | awk '$2 == "*" {print $1}') \
  streamlink \
  -p ./player.sh \
  -a "0.05 20 mpv --cache=no {filename}" \
  URL \
  QUALITY
```

**player.sh**
```bash
#!/usr/bin/env bash

SLEEP="$1"
MAX="$2"
PLAYER="$3"
shift 3

"$PLAYER" "$@" <&0 &
PLAYER_PID=$!

finish() {
	[ $PLAYER_PID -gt 0 ] && kill $PLAYER_PID
}
trap finish EXIT

PLAYER_WID=""
i=0
while : ; do
	i=$(( i + 1))
	PLAYER_WID=$(wmctrl -l -p | awk "\$3 == \"$PLAYER_PID\" {print \$1}")
	[ -n "$PLAYER_WID" -o "$i" -gt "$MAX" ] && break
	sleep "$SLEEP"
done

[ -z "$PLAYER_WID" ] && exit 1

wmctrl -i -r "$PLAYER_WID" -t "$PLAYER_DESKTOP"

wait $PLAYER_PID
```

This obviously requires `wmctrl` to be installed on your system. The player's window will get polled in the interval set by $1 for a maximum of $2 iterations. The player, $3, has to show a window during that time frame, otherwise the script will terminate.

That's why I used mpv's `--cache=no` parameter in my example, because mpv tries to cache for more than one second in its default config before its window gets shown.

**Comment by anlutro** [comment]
> Does this happen no matter which video player you're using?
yes.

> Also are you running Streamlink via Python 2 or Python 3?
Python 3.

@bastimeyer thanks for the input, I will read and try this out later! worth mentioning that I do already use `--no-cache` with `mpv` to make this issue less annoying, but the time `streamlink` spends before even opening the player command is also an issue:

```
$ time streamlink --player=/bin/false https://twitch.tv/rocketleague 720p
[cli][info] Found matching plugin twitch for URL https://twitch.tv/rocketleague
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /bin/false
error: Failed to start player: /bin/false (Process exited prematurely)
[cli][info] Closing currently open stream...

real	0m8.766s
user	0m0.741s
sys	0m0.218s
```

**Comment by anlutro** [comment]
@bastimeyer's bash script solution does work! though there is a brief flash of the video player on the active desktop.

**Comment by bastimeyer** [comment]
> brief flash of the video player on the active desktop

That's what I meant with not being an elegant solution. The script is polling the window ID from the player's PID. The lower the interval, the less time the newly shown window is visible on the active desktop.

> I do already use --no-cache with mpv to make this issue less annoying

I've mentioned the `--no-cache` MPV parameter in regards to the script, not streamlink itself. If the player takes too long to show its window before the script can find it, then it will terminate (don't poll forever). You can control this via the polling interval parameters (the first two) or by adding a static sleep command after the player launch statement in the script before the while loop starts running.

**Comment by back-to** [comment]
> That's not a Streamlink specific problem. This is the usual behavior when launching programs from the shell which will open X11 windows.

closing,
as there is a **workaround** for this and it is **not a Streamlink specific problem** as mentioned.

**Comment by bastimeyer** [comment]
MPV has just added the ability to specify the workspace the window will be visible on via its `--geometry` parameter:
https://github.com/mpv-player/mpv/commit/4a93b046e954892edf3356bcd5745c612232fe15
