### ISSUE TITLE
compatibility with HLS javascript players

### ISSUE THREAD

**Issue by sebseb7** [streamlink/streamlink#2669]
## Feature Request

compatibility with HLS javascript players like https://video-dev.github.io/hls.js/demo/

### Description

external http player needs to support https and CORS

**Comment by gravyboat** [comment]
I'll let others weigh in here but I'm pretty sure we've taken the stance of not implementing this in previous discussions so people don't use Streamlink to restream on their own site.

**Comment by sebseb7** [comment]
resteaming is easy anyway, using OBS

**Comment by gravyboat** [comment]
I'm well aware that restreaming is easy via OBS, but allowing streams to be piped to a JS player just opens us up to the project being seen as usable for that. Streamlink isn't intended for people to restream to JS players or to sites, it's intended use is so that individuals can watch streams on their system in a better player than what a website may provide.

**Comment by bastimeyer** [comment]
> HLS javascript players

Streamlink doesn't support HLS output streams. See #134.
You can achieve this by piping the stdout output into ffmpeg and making it an HLS stream, but that's none of Streamlink's business.

Also, as @gravyboat already said, web players are not Streamlink's intended target. In fact, Livestreamer/Streamlink was created to bypass web players, because video playback in web browsers is so poor.
