### ISSUE TITLE
streamlink as a zipapp?

### ISSUE THREAD

**Issue by M83tUt3** [streamlink/streamlink#2673]
## Issue
- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description
This is not as much as a feature request as it is a simple question.

Is it possible to create a self-contained zipapp of streamlink, including all of its dependencies? Youtube-dl for example offers this, so you just have a single neat binary to put in your PATH. 
If it's possible, I'd love to hear some pointers on how to accomplish this as I have very little knowledge of Python myself. Starting either from a git checkout or maybe a pip install would be fine.

**Comment by M83tUt3** [comment]
Nevermind, I think it's actually not possible to bundle all the deps as well. I figured out how to create one but it fails to run, saying it can't load some .so files in the crypto module. This seems to be a fundamental limitation with zipapps.
https://docs.python.org/3/library/zipapp.html#caveats

**Comment by mk-pmb** [comment]
Have you tried with [shiv](https://shiv.readthedocs.io/en/latest/)? It claims to bundle the dependencies as well.

**Comment by mk-pmb** [comment]
Update: I modified my shims to import pycryptodome only opportunistically. This way, I was able to [make streamlink run in a very minimal docker environment.](https://github.com/mk-pmb/streamlink-ubuntu-native/tree/master/bake-zipapp-in-docker)

However, I wasn't able to figure out how to use `shiv` to bundle the `streamlink_cli` because it seems to expect a pip application manifest or something. When you create a directory `docker.tmp` next to `bake.sh` and then run `./bake.sh`, the venv created by it will be persisted into the `docker.tmp` directory for you to inspect. Maybe you can figure out how to bundle from there.

I think this way we can create a zipapp that will be able to run at least on systems where pycryptodome is installed globally (like on my Ubuntu focal).
