### ISSUE TITLE
Low lantecy feature, is it even here?

### ISSUE THREAD

**Issue by dozzzz02** [streamlink/streamlink#2681]
Is the low latency feature here? How does it work? I've read about it but can't find any in the docs

**Comment by bastimeyer** [comment]
This hasn't been implemented yet. Please use the search function next time.
Feature request: #2402
Pull request: #2513

And to give an update on this:
No, I don't feel comfortable getting this merged (yet - or even ever), because it's more of a hack-job than a proper implementation and there are still some unsolved issues with it. It also requires the user to set player params with tight caching values, which can't be done in every player, and the experience is far from perfect, especially when you have a small network lag. You and everyone else can test it though. The instructions have been posted in the linked threads.
