### ISSUE TITLE
plugins.twitch: 401 Client Error Unauthorized for url

### ISSUE THREAD

**Issue by 161134050** [streamlink/streamlink#2697]
I can't open any twitch streams, I get 401 unauthorized with an oauth token, i've tried using my own oauth from F12, and even generating my own with all scopes enabled 

```
streamlink --loglevel debug twitch.tv/loltyler1 best --twitch-oauth-token=aimne78kx3ncx6begonmv6wki5h1ko
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.4
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/loltyler1
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-oauth-token=******** (oauth_token)
[plugin.twitch][debug] Getting live HLS streams for loltyler1
[plugin.twitch][info] Attempting to authenticate using OAuth token
error: Unable to open URL: https://api.twitch.tv/kraken/user.json (401 Client Error: Unauthorized for url: https://api.twitch.tv/kraken/user.json?as3=t&oauth_token=aimne78kx3ncx6begonmv6wki5h1ko)
```

**Comment by jshholland** [comment]
I see the same issue (also, I suspect you should remove that oauth_token from your report)

**Comment by bastimeyer** [comment]
You are trying to use Twitch's **client ID** as **OAuth token** (your post still includes the edit history).
These are two completely different things.

**Client ID** = An application ID (public), registered by a developer
**OAuth token** = An authorization key (secret), granted after a successful login of a user of the application where the user is logging in. The OAuth token is tied to the application's client-id.

> and even generating my own with all scopes enabled

You can't do this. Registering your own app and getting an OAuth token from there (with whatever scopes you're choosing) doesn't work, because the token is tied to the client-id, which is a third party ID and not Twitch's. You HAVE TO use Twitch's website.

Just follow this, which I've posted on the Twitch GUI issue tracker:
https://user-images.githubusercontent.com/467294/68801614-b7491780-065c-11ea-89cb-eece314fb541.png

**Comment by jshholland** [comment]
Hmm, odd. I tried logging in with --twitch-oauth-generate and got the same error. It seems to be working now I've dug the token out of my request headers, but is that option no longer functional?

**Comment by bastimeyer** [comment]
Once again, you CAN'T use 3rd party stuff during this reoccurring Twitch API issue.
https://github.com/streamlink/streamlink/issues/2680#issuecomment-552024753
