### ISSUE TITLE
410 Client Error: Gone for url:

### ISSUE THREAD

**Issue by Baerht** [streamlink/streamlink#2709]
## Issue
streamlink not able to connect to twitch stream

- x This is not a bug report, feature request, or plugin issue/request.
- x I have read the contribution guidelines.

### Description

After downloading the 1.3.0 exe file from the website . I ran the .exe file to install 

over the last build. I ran streamlink from the command promoted ( streamlink twitch.tv/pakratt0013 160p )and it got a error ( 
See text log.)  .I then uninstalled streamlink and cleared any file folders left ( from program files Directory and %%App directory). I then 

downloaded a fresh file from the website ( https://github.com/streamlink/streamlink/releases/tag/1.3.0 ) I then did a fresh install, running the exe 

file as the Adimin.After retrying to run stream link I got same error. I did also 

confirm that the streamer was streaming at the time . and tried with different 

streamers. 
   I do also use streamlink on a second computer ,in conjunction with Chatty. I 

mostly use this computer to check what quality option the interested streams have 

I have not updated streamlink on that computer yet as I was doing the first 

computer station first. both computers are are connected to the same router.
 I also confirmed the at the computer was Windows Vista  SP2 

### Logs

streamlink --loglevel debug twitch.tv/pakratt0013
[cli][info] Found matching plugin twitch for URL twitch.tv/pakratt0013
[plugin.twitch][debug] Getting live HLS streams for pakratt0013
error: Unable to open URL: https://api.twitch.tv/api/channels/pakratt0013/access
_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/
pakratt0013/access_token.json?as3=t)

**Comment by bastimeyer** [comment]
> streamlink --loglevel debug twitch.tv/pakratt0013
> [cli][info] Found matching plugin twitch for URL twitch.tv/pakratt0013

You are **not** using the latest version, otherwise version information would have been logged, as it was added one or two years ago I believe. Your used version is very old according to the output. `streamlink --version` will output the version string.

> exe
> running the exe file as the Admin

So you're a Windows user and have installed Streamlink via the Windows installer.

The Windows installer supports two different installation methods, a per-user and a system-wide method. Installers of the old versions (pre 0.14 I think) didn't have these options and their behavior was similar to the per-user method. The system-wide method requires admin permissions and by default chooses one of the `%PROGRAMFILES(X86)%` or `%PROGRAFILES%` directories (usually `C:\Program Files (x86)\Streamlink`), whereas the per-user method chooses the `%LOCALAPPDATA%` directory instead (usually `C:\Users\%USERNAME%\AppData\Local\Streamlink`).

So if you're upgrading to one of the "newer" Streamlink releases, you'll have to make sure that all old versions have been uninstalled from your system first or that you're using the same installation path as the old one, so that the old version can get replaced by the new one.

If you run `where streamlink` from the command prompt, you will see the directory that the command line shell will resolve when running the `streamlink` command (without absolute or relative paths). The shown path will be the directory of your old streamlink installation.

----

As you can see with a properly upgraded Streamlink, the Twitch plugin will work just fine:

```
streamlink --loglevel debug twitch.tv/pakratt0013
[cli][debug] OS:         Linux-5.4.0-rc7-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.3.0+4.gc1a146f
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/pakratt0013
[plugin.twitch][debug] Getting live HLS streams for pakratt0013
[plugin.twitch][info] pakratt0013 is hosting honneyplay
[plugin.twitch][info] switching to honneyplay
[plugin.twitch][debug] Getting live HLS streams for honneyplay
[utils.l10n][debug] Language code: en_US
Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
```
