### ISSUE TITLE
Question regarding installation

### ISSUE THREAD

**Issue by aschafmeister** [streamlink/streamlink#2758]
Not really a question concerning directly Streamlink and probably a quite stupid one, but some programs like e.g. Streamlink can be installed under Linux in different ways: 
1. Via a package manager, if a package is available
2. using pip, the Python package manager (obviously just for programs written in Python) 
3. Checking out the code with git and installing it via setuptools (Python) or 'make'

Assuming I installed Streamlink by one of the methods, let's say (1), and some time later I want to install a newer version, but can't remember the way it has been installed before and I do the upgrade using a different method, for example (2). 
Would this procedure be fine and there are no issues to worry about? Or would this cause problems e.g. regarding package management etc.? 
How is this dealt with in general under Linux, I for one don't take notes what program I installed in which way....

**Comment by bastimeyer** [comment]
Regardless of your operating system, if you're using a package manager to install a program - and that's how it works on Linux by default, then you are not supposed to interfere with any files of the installed packages afterwards without using the same package manager, or you'll be running into issues sooner or later because you're messing with the state of the installed packages.

This is a huge problem for Python on Linux especially, because your distro will most likely be using a couple of Python packages packaged for your current Python version. If you're going to use pip and you're also installing packages system-wide via sudo, then you're interfering with your disto's native package manager and its Python packages. Once a system upgrade includes an update or removal of the modified Python packages, you can run into problems and break your system. You could also accidentally remove system packages with pip or upgrade dependencies which are not supposed to be upgraded and break your system with that, too.

That's why you should not be using pip as root or install python packages via setuptools as root on Linux.

The alternative to that is setting the `--user` parameter when installing packages with pip or setuptools, so that packages get installed for the current user into `$HOME/.local` (`$XDG_DATA_HOME/..`) instead of `/usr` where your system packages are located. Using a virtual environment is another alternative.

See this section of the install docs here:
https://streamlink.github.io/install.html#source-code

**Comment by aschafmeister** [comment]
The problem I see with the package manager is, that the packages are often obsolete or poorly maintained. And the solution checking out the code with git doesn't consider any dependencies at all. 
So could one say that installing via pip and the `--user` parameter is the best solution for the typical user?

**Comment by bastimeyer** [comment]
> packages are often obsolete or poorly maintained

This entirely depends on the package maintainer, which is done by people from your distro or volunteers.

> pip and the `--user` parameter is the best solution

Yes, I would agree that pip with the `--user` parameter is the best choice, but it comes at the cost of having to check for updates yourself. You'll also have to reinstall any python packages via pip if your Python version changes.

> checking out the code with git

If you're cloning the repo, you still have to install via setuptools. You can't just run it from there, because you won't have an entry script and the dependencies will be missing.

You can also skip this manual cloning part and let pip do all of this by pointing pip to the git repo instead of the package name, so that it installs Streamlink from the latest version of the master branch instead of the latest version uploaded to PyPi, which will most likely be equal to your distro's version if your distro is up2date.

```bash
# latest release
pip install --user --upgrade streamlink
# latest commit on the master branch
pip install --user --upgrade git+https://github.com/streamlink/streamlink.git
```

**Comment by aschafmeister** [comment]
Thank you!
