### ISSUE TITLE
Version and Publisher in Windows Control Panel?

### ISSUE THREAD

**Issue by Vangelis66** [streamlink/streamlink#277]
Not an issue in itself, rather an enhancement suggestion...

When the stable or nightly NSIS installer is executed on Windows 
(Vista SP2 x86 in my case), the "version" and "Publisher" columns 
in Control Panel's "**Programs and Features**" (or its iteration in 
other Windows versions) are not being populated by the installer. 
You can observe that in this attachment: 

![prog feat](https://cloud.githubusercontent.com/assets/9669492/21027469/953f2b8e-bd99-11e6-88de-dcf8d29a3e0b.jpg)

As you can see, some other installed apps do follow the same route, 
but the acceptable standard is to include both, version at least...
E.g., current version is **0.1.0** and Publisher could be set to 
**Streamlink**/ **Streamlink Organisation** or whatever string 
the devs deem appropriate...
I hope you do consider it... :smile_cat:

**Comment by bastimeyer** [comment]
See https://github.com/streamlink/streamlink/issues/116#issuecomment-261114313 regarding the metadata.

This can't be done in the currently used pynsist version without overwriting the whole template with a custom one due to a missing template block. Overwriting would be bad, because when the original template gets updated in a new pynsist version, the custom one could potentially break stuff. Someone could open a PR for this or we use a custom fork.

**Comment by beardypig** [comment]
Sticking it at the end of the `install_files` block, while ugly, works:

```
WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\\${PRODUCT_NAME}" "DisplayVersion" "${STREAMLINK_VERSION}"
```

**Comment by bastimeyer** [comment]
Oh yes, you're right. Do you want me to add this and open a new PR, or do you want to do this yourself? 😃

**Comment by beardypig** [comment]
@bastimeyer I created a PR for `pynsist` but I have no idea how long it'll take to get in to the stable version. Feel free to create a PR for this, I'm going to call it a night now :)
