### ISSUE TITLE
Reuters.tv plugin stopped working

### ISSUE THREAD

**Issue by my-password-is-password** [streamlink/streamlink#2803]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Reuters must have changed something on their site that streamlink can't play the stream.

### Reproduction steps / Explicit stream URLs to test

1. Go to ```https://www.reuters.com/livevideo``` or ```https://www.reuters.tv/live?nonav=true```
2. Click any ```Live``` stream
3. Copy the url of the live stream, ex. ```https://www.reuters.tv/l/PUwh/2020/02/19/people-expected-to-leave-diamond-princess-as-quarantine-ends```
4. Try to play it in Streamlink

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin reuters for URL https://www.reuters.tv/l/PUwh/2020/02/19/people-expected-to-leave-diamond-princess-as-quarantine-ends
[plugin.reuters][error] Unsupported PageType.
error: No playable streams found on this URL: https://www.reuters.tv/l/PUwh/2020/02/19/people-expected-to-leave-diamond-princess-as-quarantine-ends
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
OK, so I have a fix for this (see below).  It appears to work with both URLs:

```https://www.reuters.com/livevideo```

and

```https://www.reuters.tv/live?nonav=true```

...when you have selected a video to watch from the list on either of those pages.

In the case of the former, as far as I can see, the easiest way to get the URL of the page is to right-click on the video and then in the context menu select: "This Frame"/"Show Only This Frame" (under Firefox at least), after having clicked on a video to view, as the URL does not change in the address bar on the ```https://www.reuters.com/livevideo``` site otherwise.

Fixing that has just involved searching for the IFRAME first and then assembling the correct URL to GET the source for the IFRAME.  In addition to that, I have added support to the URL match for ```reuters.com``` and the country specific ```subdomain.reuters.com``` URLs (e.g.: ```uk.reuters.com```).

The other URL you supplied: ```https://www.reuters.tv/l/PUwh/2020/02/19/people-expected-to-leave-diamond-princess-as-quarantine-ends``` when entered into a browser, redirects to: ```https://www.reuters.com/livevideo?id=PUwh``` - which in the browser results in no video shown and when passed to streamlink seems to find another video entirely.  What result do you get for that URL now?  Could it be that it has expired?

I have tried all the different URL types I can find for ```reuters.com```, ```reuters.tv``` and ```uk.reuters.com```.  All *seem* to work as expected, using the fall-back method in the code.

If you would like to test the code, you can get it from:

https://github.com/mkbloke/streamlink/blob/reuters-site-change-2020-02/src/streamlink/plugins/reuters.py

You can download the whole plugin by clicking on "Raw", then saving via your browser.

**Comment by my-password-is-password** [comment]
@mkbloke It works.  I just tried your code with the live stream "Steyer reacts to results of South Carolina primary" with both urls and they both played just fine:

 * https://www.reuters.tv/l/PUoZ/2020/02/28/steyer-reacts-to-results-of-south-carolina-primary
 * https://www.reuters.com/livevideo?id=PUoZ

So I think you're right about the "diamond princess" link being expired so it didn't play when you tried it.

Thank you
