### ISSUE TITLE
Is it possible to bring this to Android phones?

### ISSUE THREAD

**Issue by androiduser3** [streamlink/streamlink#283]
Hey all. This is not exactly an issue, but a suggestion. I'm a Livestreamer user, and mainly using Livestreamer just for Twitch. For some reason Twitch default player and official android Twitch app keep buffering all the streams while it is so smooth without buffering at highest quality with Livestreamer But there is no Livestreamer for android. Somebody asked chrippa few years ago for an android port but he declined.

I would appreciate (probably all android users too) so much if Streamlink devs can bring this to android. So I can enjoy twitch on my phone just like everybody else. 

Thanks in advance

**Comment by beardypig** [comment]
Related: chrippa/livestreamer/issues/574

I agree with the view that chrippa took on this issue for livestreamer, that it is out of the scope for this project. Of course anyone is free (within the terms of the license) to use the library to create their own Android app :-)

**Comment by gravyboat** [comment]
Yeah I definitely agree with @beardypig, it's way outside of the scope of this project (especially since none of us are getting paid to work on this) and would be a major investment in development time.

**Comment by Junior1544** [comment]
The ability to use a program like this on cell phones would be wonderful!  I've been working on an app for a long time that this would solve all my problems...  I understand that it's outside the scope of this here, but how long do you think it'd take to port to something cell phones could use and how much do you think would it cost???  

Just thinking out loud and wishing really...

**Comment by gravyboat** [comment]
I'm really not sure as I haven't done any research on it. There are a lot of gotchas and issues porting Python code to Android even through tools like Kivy (not to mention the video player hooks) so it would probably be a lot of work. As beardypig noted if someone wants to use the library within the terms of the license to create their own android app they're more than welcome to.

**Comment by L2501** [comment]
you can use kodi on android and write python plugins for it.

**Comment by gravyboat** [comment]
I'm going to close this, it's not something we have the bandwidth to even consider exploring at this time.

**Comment by beta-phenylethylamine** [comment]
Sorry to resurrect a long-closed issues but it's worth noting that you can run streamlink in Termux and just use the --player-external-http flag and open the link in a player of your choice.

I found I had to turn off software audio decoding in MX Player or I had awful audio glitchiness, but other than that it works perfectly as long as you remember to enable wakelock on the termux notification so it doesn't die

**Comment by beta-phenylethylamine** [comment]
Although that also proves there's a working model for an android application by running streamlink on an embedded busybox. I might try to see if I can make that work, especially since Termux is open source

**Comment by markosjal** [comment]
Streamlink does NOT install successfully to Termux using pip2 

Posting a separate thread here as a bug report

**Comment by nOLanSea** [comment]
> iam using succsessful using streamlink 0.14.2 on Android using termux and python 3.6.6 (requests 2.19.1, socks 1.6.7 and websocket 0.53.0)

Hi.
Could you please write a guide, how to use streamlink on android ? With links please.
I want to watch afreeca streams on my phone) Thanks

**Comment by Twilight0** [comment]
https://www.reddit.com/r/Streamlink/comments/cfno18/guide_streamlink_on_android_termux_vlc/

**Comment by pras92** [comment]
> I found I had to turn off hardware audio decoding in MX Player or I had awful audio glitchiness, but other than that it works perfectly.

I realize this is super old but, did you use any streamlink plugins to support mx links? I'm facing the "no plugin can handle url" for all mx links.

**Comment by bastimeyer** [comment]
> no plugin can handle url

This means that the input URL is not supported because no plugin exists which can translate it to an actual stream URL. If you can find the stream URL yourself, then you can always play it via the supported built-in streaming protocols:
https://streamlink.github.io/latest/cli/protocols.html

The latest versions of Streamlink are available as AppImages which can be run on all systems using the aarch64 architecture. Otherwise, use your own python environment and install Streamlink there. If your system is not aarch64 compatible, then you'll have to build/compile streamlink's dependencies yourself when installing it via python-pip, etc., and this will require additional development libraries like libxml2, libxslt, etc.
- https://streamlink.github.io/latest/install.html#appimages
- https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

How you pass data from Streamlink to your player on Android (or other related systems) depends on which kinds of inputs are supported by the player app and what the environment is where you're running Streamlink from. This means you might need to use `--player-external-http` and launch the player app manually. The linked thread on reddit is launching the player via Android's activity manager CLI utility `am` and it uses `--player-http` as stream transport method.
- https://streamlink.github.io/latest/cli.html#player-options
- https://android-doc.github.io/tools/help/shell.html

I'm going to lock this thread now. Questions can always be asked on the discussion forum, and if one feels like adding an extensive guide for the docs, they are welcome to submit a pull request.
