### ISSUE TITLE
low latency

### ISSUE THREAD

**Issue by deadkid14** [streamlink/streamlink#2847]
hi when i put my hls live edge all the way down to 1 I still see some latency between the stream on streamlink and the stream on twitch can someone please help?

**Comment by Joshfindit** [comment]
> hi when i put my hls live edge all the way down to 1 I still see some latency between the stream on streamlink and the stream on twitch can someone please help?

Can you quantify how many ms you mean when you mention some latency?

**Comment by bastimeyer** [comment]
@deadkid14 Your provided informations are very sparse...

You need to be running at least streamlink `1.3.1+51.geb72826`. Then set the `--twitch-low-latency` parameter and check the log output whether it is actually a low latency stream on Twitch. This is not always the case and the streamer has to enable this.

https://streamlink.github.io/latest/cli.html#cmdoption-twitch-low-latency


If you've set the twitch low latency parameter, it'll automatically reduce the [`hls-live-edge`](https://streamlink.github.io/latest/cli.html#cmdoption-hls-live-edge) parameter to a value of at most 2 and also sets [`--hls-segment-stream-data`](https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-stream-data) to true, so that HLS segments can be consumed by the player while they are being downloaded instead of having to wait for them to finish first. In addition to that, segments will be prefetched from Twitch and downloaded as soon as they become available.

Reducing `hls-live-edge` to 1 is the lowest latency you can have. However, the final output depends on your player and **its own caching/buffering**. As you can read in the parameter description, you'll have to set custom player parameters via `--player-args` or `--player` or configure your player manually.

If you're using MPV, which I definitely recommend, then you can play around with its [cache related parameters](https://mpv.io/manual/stable/#cache). You will have to read the documentation for this and understand what each of these MPV parameters does.

Once you've found the right balance between low latency and stable caching, you'll see a lower latency than Twitch's website by one or two seconds. However, as said in the pull request of the twitch-low-latency feature, this all is not very optimal and you'll run into issues sooner or later, especially if a stream is not a LL stream and you're still applying aggressive caching settings.

**Comment by deadkid14** [comment]
> @deadkid14 Your provided informations are very sparse...
> 
> You need to be running at least streamlink `1.3.1+51.geb72826`. Then set the `--twitch-low-latency` parameter and check the log output whether it is actually a low latency stream on Twitch. This is not always the case and the streamer has to enable this.
> 
> https://streamlink.github.io/latest/cli.html#cmdoption-twitch-low-latency
> 
> If you've set the twitch low latency parameter, it'll automatically reduce the [`hls-live-edge`](https://streamlink.github.io/latest/cli.html#cmdoption-hls-live-edge) parameter to a value of at most 2 and also sets [`--hls-segment-stream-data`](https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-stream-data) to true, so that HLS segments can be consumed by the player while they are being downloaded instead of having to wait for them to finish first. In addition to that, segments will be prefetched from Twitch and downloaded as soon as they become available.
> 
> Reducing `hls-live-edge` to 1 is the lowest latency you can have. However, the final output depends on your player and **its own caching/buffering**. As you can read in the parameter description, you'll have to set custom player parameters via `--player-args` or `--player` or configure your player manually.
> 
> If you're using MPV, which I definitely recommend, then you can play around with its [cache related parameters](https://mpv.io/manual/stable/#cache). You will have to read the documentation for this and understand what each of these MPV parameters does.
> 
> Once you've found the right balance between low latency and stable caching, you'll see a lower latency than Twitch's website by one or two seconds. However, as said in the pull request of the twitch-low-latency feature, this all is not very optimal and you'll run into issues sooner or later, especially if a stream is not a LL stream and you're still applying aggressive caching settings.

how do you enable that in the streamlink twitch gui?

**Comment by bastimeyer** [comment]
> how do you enable that in the streamlink twitch gui?

Not sure if deleting your comment and closing the thread means that you've figured it out, but in the Twitch GUI you can add custom streamlink parameters after you've enabled the advanced settings. Do that and add the `--twitch-low-latency` parameter. The live edge number field is down below. Then select the MPV player profile and add custom MPV parameters at the bottom if you need to, but make sure that you're using MPV's new parameter syntax, otherwise it'll fail.
