### ISSUE TITLE
Suggestion to replace custom sphinx theme with official sphinx rtd theme

### ISSUE THREAD

**Issue by amurzeau** [streamlink/streamlink#2851]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Currently, Streamlink documentation uses a custom sphinx read the docs theme originally made by chrippa.

As it ages, [stuff goes deprecated](https://github.com/readthedocs/sphinx_rtd_theme/pull/728/files) and the official sphinx read the docs theme is updated accordingly by their maintainers, but not the custom sphinx theme currently used.

So I'm suggesting to switch to the official sphinx_rtd_theme instead as an external theme.
This should mean:
- Remove the theme folder in Streamlink's git
- Add relevant configuration in docs/conf.py according to [readthedocs installation instructions](https://github.com/readthedocs/sphinx_rtd_theme#installation)

I've made a build of the Streamlink's documentation with the official readthedocs theme so you can see what it looks like, here: [streamlink-docs-with-sphinx_rtd_theme.zip](https://github.com/streamlink/streamlink/files/4396373/streamlink-docs-with-sphinx_rtd_theme.zip)

I'm making this suggestion primarily as the distribution packager to ease maintenance over Streamlink's documentation when other packages are updated (like sphinx).

Thanks for your consideration !

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Sounds reasonable, couple of questions though

1. Is the theme distributed as source and needs to get built while building the docs? If so, this would mean that we'd need to setup nodejs+npm on the CI side because it uses webpack for building.
2. According to the theme's docs, adding custom stylesheet properties is possible without having to fork it. This should help with a few custom changes/fixes we've applied in the past. However, we're building two separate versions, stable and latest, and deploy them into different subdirs which are then referenced by a custom template in the doc's main menu. Since this requires templates to be changed, I am not sure if it's possible without forking it. And forking puts us into the same situation we are in now, probably even worse.

https://github.com/streamlink/streamlink/commits/master/docs/_themes/sphinx_rtd_theme_violet

**Comment by amurzeau** [comment]
1. sphinx_rtd_theme does not need to be built to be used. Adding sphinx_rtd_theme in docs-requirements.txt is sufficient.
2. Indeed, I think for tables layout (commit e530e5b2d749a5491975aaa04e737d1920d19f42) can be handled fine in a custom css, but the version selection in the sidebar (commit 87a55fe4a026c5673f4135ddb6a9f03cd9a1c5b4) might be a too much invasive change.

This was just a suggestion, given the version selection I don't have an immediate idea to do the same with the official theme as is without major changes too (unless droping that change is ok).

I'm closing this until this come up again with better solutions if any :)
Thanks !

**Comment by bastimeyer** [comment]
Looks like individual templates can be overridden via the `templates_path` property:
https://www.sphinx-doc.org/en/1.5/theming.html#templating
If I'm not mistaken, this should enable us to customize main menu header with a version selection by extending specific blocks of the layout template without having to fork the whole theme.

**Comment by bastimeyer** [comment]
I've pushed the `docs/sphinx-rtd-theme` branch to my Streamlink fork:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:docs/sphinx-rtd-theme

This builds the docs with the latest version of the RTD theme and also uses the latest sphinx version, which is currently 2.4.4 (had to be upgraded to at least 1.8 due to an unavailable config property for extending the stylesheets).

The template overrides are annoying, but manageable, nothing too major. However, should the theme devs decide to change or rename the template block names, or should sphinx introduce breaking changes, then we'll have to fix it here. Or we'll have to set the deps to a specific version again.

Personally, I'm not a huge fan of this theme, as it's aligned to the left and it's very noisy in terms of its color scheme, but that's just my personal opinion. It's also pretty unoptimized, but that's nothing new and expected, I guess.

Not submitting a PR just yet...

**Comment by gravyboat** [comment]
@bastimeyer I assume it's this one yeah? https://sphinx-rtd-theme.readthedocs.io/en/stable/

That left alignment alone would be a deal breaker for me. 50%+ of my screen is empty white space, it looks awful.

**Comment by back-to** [comment]
> Personally, I'm not a huge fan of this theme

there are also other themes available, some are also maintained.

https://github.com/yoloseem/awesome-sphinxdoc#themes
https://sphinx-themes.org/
https://www.writethedocs.org/guide/tools/sphinx-themes/#sphinx-themes

**Comment by bastimeyer** [comment]
There's not a single one which fulfills these (simple) criteria:
1. center aligned with a proper width
2. menu on the left and always visible (part of the centered page)
3. neutral colors for texts, backgrounds and code-snippets
4. tasteful and elegant style (neither super artistic nor software-engineer-like)
5. actively maintained
6. support for overrides which are not too much effort

The only ones which came close were
- [`sphinx-press-theme`](https://sphinx-themes.org/html/sphinx-press-theme/press/index.html): failed to render the Streamlink CLI page
- [`sphinx-redactor-theme`](https://sphinx-themes.org/html/sphinx-redactor-theme/sphinx_redactor_theme/index.html): unmaintained and deleted source repo
- [`sphinx-readable-theme`](https://sphinx-readable-theme.readthedocs.io/en/latest/): weird current/next menu scheme, also requires rewriting lots of stylesheets, eg. fonts and spacings (the CLI page is NOT readable)

**Comment by bastimeyer** [comment]
Could this be an alternative maybe?
https://github.com/pradyunsg/furo

It's the Sphinx theme used by urllib3:
https://urllib3.readthedocs.io/en/latest/

Looks nice, is actively maintained, center-aligned (with menu), responsive design with multiple breakpoints for different screen sizes, neutral colors, light and dark variants, and it's extensible.

Haven't looked much into it yet though, so basically just a suggestion for now.

**Comment by beardypig** [comment]
I like it.

**Comment by gravyboat** [comment]
I'm fine with that theme as well.

**Comment by bastimeyer** [comment]
Ok, since everyone seems to like it, I've put something together in the past hour or so. This required some template overrides in the sidebar/menubar, some of the old custom CSS rules had to be modified and a couple of new CSS properties had to be tweaked via CSS variables, like spacings, etc.

![image](https://user-images.githubusercontent.com/467294/98940700-ac34fb80-24eb-11eb-9099-474015a07e01.png)

Ignoring all the small issues which are still left, I'm already pleased with the overall results, but what I don't like is how the CLI parameters and their descriptions are styled. It's too noisy and parameters are hard to find while scrolling through the page. The pygments style also has a very high contrast and I'm not sure if I like the increased font-size on the outer CSS media rule. The colors of the note-blocks will probably also require some tweaking.

**Comment by beardypig** [comment]
@bastimeyer open a draft/WIP PR if you like.

**Comment by bastimeyer** [comment]
@beardypig I'll open a PR later today (probably this evening) once I've spent some more time tweaking/correcting things. I haven't committed anything yet and want to have logical commits, which requires a bit of selective adding/committing and rebasing first.

There's also a "bug" in the furo theme regarding the stylesheet order when using custom stylesheets and I currently have to use a workaround for that. I've opened a bugreport on their tracker yesterday, but haven't seen a response yet.

In the PR I will also post a list of all the (opinionated) changes I've made and what I think should be done next.
