### ISSUE TITLE
Update ffmpeg included in Windows installer

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#2872]
The version of `ffmpeg` included with the Windows installer is pretty old (3.2.1). We should consider updating it to a newer version, like 4.2.2 from the Zeranoe builds. 

We could also take this as an opportunity to move the `ffmpeg` and `rtmpdump` executables out of this repo and in to the [streamlink/streamlink-assets](https://github.com/streamlink/streamlink-assets) repo.

**Comment by bastimeyer** [comment]
> Zeranoe builds

I have no clue about the Windows world :innocent:, but are these official builds? They are linked on the ffmpeg website and they're also used by the ffmpeg chocolatey package, but I couldn't find any proper information, not even build logs, etc.

Since self-compiling would introduce another maintenance burden and may not even be possible with current CI run limitations, I guess using the Zeranoe builds is probably the best idea.

> streamlink/streamlink-assets

Yes please, the files should be stored as release files though and not directly in the git repo. Otherwise, bumping versions could become difficult after a while.

A CI build script would be fairly simple: just read a list of assets with links and checksums, download them, compare checksums and rehost as GH release. The build scripts here can then get the release asset links via the GH API.

**Comment by beardypig** [comment]
How should we manage the different assets though? 

1. Create a release tag for each asset, eg. `ffmpeg-x.x.x` and `rtmpdump-x.x.x` and host the assets in their own release.
1. Create a release tag each time we update the assets, `v1.0.0`, `v1.1.0`, etc. and host all the different assets together. 
1. Create a `latest` tag and host only the latest versions of the assets there. 

Personally, I like the idea of 2, and updating the assets manually.

**Comment by bastimeyer** [comment]
@beardypig Definitely point 2.

I was bored a bit and set up a release script real quick:
https://github.com/bastimeyer-test/streamlink-assets-test
https://github.com/bastimeyer-test/streamlink-assets-test/runs/571802614
https://github.com/bastimeyer-test/streamlink-assets-test/releases

Apart from some final polishing (eg. log output) and a README.md, is there anything I've missed? Do we need to add license files or is it enough that the archives already include their respective licenses? Do we need to add a list of explicit file paths for extracting only what's needed when building the installer since the archives include a bit of unnecessary stuff?

**Comment by beardypig** [comment]
Looks good. I had imagined the installer builder would deal with extracting.

**Comment by bastimeyer** [comment]
> I had imagined the installer builder would deal with extracting.

Yes, what I meant was an additional file the installer script could read from with a list of files of each archive, so that unnecessary stuff could be skipped while extracting the archives. Or do you want to include everything? The current ffmpeg and rtmpdump files are just the licenses and executables, plus one dll in rtmpdump:
https://github.com/streamlink/streamlink/tree/master/win32

**Comment by beardypig** [comment]
yeah a list of files might be useful :) should include any license files though.

**Comment by bastimeyer** [comment]
I'll see if I can finish this with an updated installer build script this weekend. Not sure yet how to implement the files list. I was thinking about a JSON file that maps the files of the archives to their destination path so that there's enough flexibility in case the file structure changes in future ffmpeg archives.

After the installer stuff has been updated, we should publish a new release since we've got lots of changes since the last one.

**Comment by bastimeyer** [comment]
Not creating a PR just yet. @beardypig, could you please take a look at this?

streamlink-assets test repo:
https://github.com/bastimeyer-test/streamlink-assets-test
Had to update this a few times since my last post, so please re-check.

makeinstaller.sh changes:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:installer/external-assets
Split into 3 commits, one for rewriting or cleaning up the script, one for adding the external assets logic and one for removing the old binary files from the repo.

When testing this, don't forget to change the assets repo name in the makeinstaller.sh file to `bastimeyer-test/streamlink-assets-test`.

The installer builds just fine and is even a bit smaller in size than the old one. I've kept the same paths for the `ffmpeg/ffmpeg.exe` and `rtmpdump/rtmpdump.exe` files, as these paths are written to the user's config file by the installer, and changing that would break stuff. Both dependencies seem to be working fine, tested a muxed HLS stream from YT and an RTMP stream (earthcam plugin). Please verify though. The previously included `rtmpdump/librtmp.dll` is not needed, so I left it out. The licenses are only plain GPL license files, and licenses of each lib ffmpeg bundles are not included (because they are not in the Zeranoe archive).

**Comment by back-to** [comment]
> [makeinstaller.sh] jq is required to build the installer. Aborting.

not sure if this is installed within github actions,
at least my pc did not have it.

---

`STREAMLINK_PYTHON_VERSION=3.6.6` and `pypi_wheels=pycryptodome==3.6.4` should be updated

https://pypi.org/project/pycryptodome/#history

---

seems to work

**Comment by bastimeyer** [comment]
Thanks for the review, @back-to.

`jq` is installed, as it's pretty much the default JSON manipulation tool.
https://github.com/actions/virtual-environments/blame/master/images/linux/Ubuntu1804-README.md#L16

I didn't change the python version. Should be done separately.

Btw, I noticed some issues with my built installer yesterday when it was pre-compiling the python modules. It was failing on the websockets library, IIRC. Will check this again later. Could have been because of my venv.

**Comment by bastimeyer** [comment]
Updated the PR on the assets repo, so that it also tests the data.json on (future) PRs.
streamlink/streamlink-assets#1

I'd appreciate a review, so that I can continue with the makeinstaller PR, so that we can resolve the outdated ffmpeg issue.

**Comment by beardypig** [comment]
@bastimeyer wanna create a PR so we can comment/review? :)

**Comment by bastimeyer** [comment]
Absolutely. We need to tag a release in the assets repo first though. Is the semver-date/"CalVer" pattern okay, or do you prefer a different scheme, eg. just numbered or based on the ffmpeg number, etc?

**Comment by beardypig** [comment]
CalVer sounds like a good plan for this one.
