### ISSUE TITLE
Zattoo stopped working

### ISSUE THREAD

**Issue by Fernseher123** [streamlink/streamlink#2886]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...I am using 1.3.1 on my enigma box and on both boxes Zattoo-Streams stopped working.
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by misteranonymus** [comment]
The solution is:
In Line 158 from zattoo.py you must add this
res = self.session.http.get(self.base_url + '**/int**')

But somtime this doesn't work.
See this:
`[streamlinksrv][info] Found matching plugin zattoo for URL https://zattoo.com/watch/dmax
[streamlinksrv][error] Plugin error: Unable to open URL: https://zh2-10-hls-live.zahs.tv/CH_dmax-live.m3u8?
........... (HTTPSConnectionPool(host='zh2-10-hls-live.zahs.tv', port=443): Max retries exceeded with url: /CH_dmax-live.m3u8?z32=NVQXQ4TBORST2MJVGAYSM5LTMVZF62LEHU3DONBZGQ4TIJTDONUWIPJRGYYDKMKGGJBTMMSBHFBTEMZQFU2EMQJSGVBDSMCGIM2ECQZZGMZCMZLOMNZHS4DUNFXW4PJQEZQXKZDJN5PWG33EMVRXGPLBMFRSM2LONF2GSYLMOJQXIZJ5GATHG2LHHU4TQOLCHFQTQZTFMFSGEOLEGIZTSZJYGQZGGMZSGY3WGODCMQ3GEJTNNFXHEYLUMU6TMMBQ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),)))`

But with this:
res = self.session.http.get(self.base_url + '**/ch**')
it works for me.

**Comment by back-to** [comment]
@misteranonymus 

use the code from https://github.com/streamlink/streamlink/pull/2887/files
try it with `/int/` not `/int`

also use `--zattoo-purge-credentials` on the first run
