### ISSUE TITLE
--player-args "--fullscreen" with VLC breaks playback

### ISSUE THREAD

**Issue by emerysteele** [streamlink/streamlink#2947]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

VLC has a built in --fullscreen argument for auto opening in fullscreen mode. But when using `--player-args "--fullscreen"`, vlc will open, but it does not play the stream. Just goes to default playlist window.

### Expected / Actual behavior

VLC should open streams in fullscreen mode when '--fullscreen' is set as an argument.

Setting '--fullscreen' as an argument causes the stream to not open at all. Just VLC to the default window.

### Reproduction steps / Explicit stream URLs to test

1. run `streamlink --player-args "--fullscreen" <streamurl> best`

### Log output

```
>streamlink --player-args "--fullscreen" <streamurl> best
[cli][info] Found matching plugin okru for URL <streamurl>
[cli][info] Available streams: 240p (worst), 360p, 488p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
```
```

**Comment by gravyboat** [comment]
Can you look through the [fullscreen](https://trac.videolan.org/vlc/query?status=assigned&status=new&status=reopened&summary=~fullscreen&col=id&col=summary&col=status&col=owner&col=priority&col=milestone&col=component&col=version&order=priority) bug reports over on their tracker and see if anyone encountered your problem there? I don't know what we can do to solve this as we're just passing the option. If you call VLC to launch without dumping data in to it via Streamlink does the problem still occur? So maybe try either apps, or feeding it a video directly and passing those options. I'm not sure exactly what the command will look like for that as I don't use VLC.

**Comment by emerysteele** [comment]
Launching vlc directly with the --fullscreen argument is working normally. `C:\Program Files\VideoLAN\VLC\vlc.exe --fullscreen <streamurl>` Updated to latest VLC version, but still same issue when launched through streamlink.

Example Streamlink Command (Not Working/No Playback):
`streamlink --player-args "--fullscreen" hls://https://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl) best`
Note: removing '--player-args "--fullscreen"' from command will allow the stream to play, but obviously not in full screen.

Example VLC Command (Works/Fullscreen Playback):
`"C:\Program Files\VideoLAN\VLC\vlc.exe" --fullscreen https://b028.wpc.azureedge.net/80B028/Samples/a38e6323-95e9-4f1f-9b38-75eba91704e4/5f2ce531-d508-49fb-8152-647eba422aec.ism/Manifest(format=m3u8-aapl)`

**Comment by emerysteele** [comment]
Oddly, if I add --fullscreen to my streamlink config, then just leave out the player-args from command line, it works.
`player="C:\Program Files\VideoLAN\VLC\vlc.exe" --fullscreen`

I really only need to do playback in fullscreen, so this workaround will be fine.

**Comment by bastimeyer** [comment]
> Setting '--fullscreen' as an argument causes the stream to not open at all.

And this is intended behavior, because the correct usage of the `--player-args` parameter is `--fullscreen {filename}`, not just `--fullscreen`.
https://streamlink.github.io/cli.html#cmdoption-a

**The `{filename}` variable needs to be included**, so that Streamlink can generate a proper player parameter line that lets the player know where to read the output stream from, either from standard input (the dash `-` parameter), a named pipe if `--player-fifo` is set or a specific http(s) URL if `--player-http`, `--player-continuous-http` or `--player-passthrough` are set.

- https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink_cli/output.py#L173-L180
- https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink_cli/output.py#L205

**Comment by emerysteele** [comment]
Oop, my bad. Thought that was a placeholder for local files or something, makes sense now.

With {filename} added, it is now working. Thank you!!

**Comment by bastimeyer** [comment]
@gravyboat Maybe we should rename this to `playerinput` or so (with `filename` as fallback), which should make this much more clear.

**Comment by beardypig** [comment]
@bastimeyer sounds like a version 2 feature :D

**Comment by fireattack** [comment]
I think some clarification about this in https://streamlink.github.io/issues.html#enable-caching-in-your-player would be helpful, too. From the description there it's unclear (at least to me) you need to explicitly include "{filename}".

**Comment by bastimeyer** [comment]
This is already documented in the section of the `--player-args` parameter. This variable doesn't have to be set when setting player parameters via `--player`, so it doesn't make much sense adding a note to other places like the common player issues page where player parameters are shown.

What I'm in favor though is making the `{filename}` variable optional/implicit, so that if the user hasn't set it, it automatically gets appended to the parameter value. The only reason why it exists in the first place is to allow a customization of the player parameter order, but that is unnecessary or irrelevant in the vast majority of cases, and the variable becomes a nuisance because of it. And as said in my previous post, maybe we should rename it or add a second variable name, to make it more clear and easier to understand. I will submit a PR later once my u-strings removal PR has been merged, as it'd cause merge conflicts otherwise.

Thanks for reminding though, because I had already forgotten about this for the upcoming 2.0.0 release.

**Comment by fireattack** [comment]
Thanks!
