### ISSUE TITLE
is there any windows portable version ?

### ISSUE THREAD

**Issue by adrianmak** [streamlink/streamlink#295]
as title

**Comment by Brainzyy** [comment]
https://github.com/streamlink/streamlink-portable

**Comment by gravyboat** [comment]
Closing this since it was answered.

**Comment by Vangelis66** [comment]
@adrianmak 

There's a second Windows portable package created and _maintained_ 
(I think - initially it was only an experiment) by @beardypig at the following repo: 

https://github.com/beardypig/streamlink-portable

Download links for Windows users on the front page (**README.md**); 
**Windows 10 Universal C Runtime** (for WinOS < 10) has been 
integrated recently; no need for .NET Framework 4.5+ to be installed, either...

**Comment by gravyboat** [comment]
That's just for the nightly build as far as I'm aware @Vangelis66, the one from Rosadin is also maintained when we build new stable releases.

**Comment by Vangelis66** [comment]
@gravyboat 

> the one from Rosadin is also maintained 
> when we build new stable releases.

Be that as it may, in its current incarnation, 
@RosadinTV's "**Streamlink for Windows.exe**" 
compiles a portable Windows installation off 
of the master repo's latest commit (HEAD), 
so it, too, can be called _nightly_; I speak 
(...err write!) from experience, since that's the 
package I currently use :wink: 

I don't think there was any harm done by 
advertising the existence of @beardypig's 
[alternate portable solution](https://github.com/streamlink/streamlink/issues/296#issuecomment-267338175); a user can try both 
and choose accordingly...

**Comment by gravyboat** [comment]
@Vangelis66 Definitely no harm done! I just didn't want anything to think that release was the stable, thanks for suggesting it.

**Comment by beardypig** [comment]
Maybe I'll update it to build the tagged versions too :)
