### ISSUE TITLE
--retry-streams stop working after internet connection loss

### ISSUE THREAD

**Issue by EnterGin** [streamlink/streamlink#2956]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Are there any ways to fix issue #2751? Almost half a year without any answer on this issue.

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
There is no reason to create a new issue for asking about a different unsolved issue. If you have anything useful to contribute to that problem, like for example a proper debug log without any other side effects like channel hosting, then post that instead. This is an open source software project and people will work on issues whenever they feel like. Repeatedly asking (or begging) doesn't do anything. If there are no answers, then the issue is either not clear, or nobody has had interest in working on that (yet). You can also try and fix this problem yourself and share a solution in a pull request if you want to.
