### ISSUE TITLE
HLS plugin crashes on non-integer EXT-X-VERSION value

### ISSUE THREAD

**Issue by nattofriends** [streamlink/streamlink#2976]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

HLS plugin crashes on non-integer EXT-X-VERSION value

### Reproduction steps / Explicit stream URLs to test

Sorry, I don't have a stream URL to test because the stream where I saw this issue was for a internal corporate stream hosted on Lifesize Cloud which is not available to the public.

### Log output

```
$ streamlink --loglevel debug "<url>" best
[cli][debug] OS:         macOS 10.15.4
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin hls for URL https://live-us-west-2-prod-611.lifesizecloud.com/[...]/recordings/by-date/2020/05/14/[...]/[...]/2048.m3u8?token=[...]
[plugin.hls][debug] URL=https://live-us-west-2-prod-611.lifesizecloud.com/[...]/recordings/by-date/2020/05/14/[...]/[...]/2048.m3u8?token=[...]; params={}
[utils.l10n][debug] Language code: en_US
error: Failed to parse playlist: invalid literal for int() with base 10: '3.2'
```

### Additional comments, screenshots, etc.

This is probably because the playlist contains:
```
#EXT-X-VERSION:3.2
```

According to RFC 8216, this is supposed to be an integer only, so Lifesize should probably fix this, but it would be nice if Streamlink was able to support this as is.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Streamlink currently doesn't distinguish between different HLS protocol versions and accepts all tags it supports regardless the version number. The version itself gets parsed here:
https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/stream/hls_playlist.py#L222

Since the playlists are already not parsed "strictly" in regards to the version number, this strict parsing of the version tag could theoretically be changed.

However, if we start drifting off the spec and change the version to a float value, then it's still possible that next person will come and complain that some streams include a semver string or something else, and we'd have to change it to a string value instead. And as soon as Streamlink needs to start parsing more strictly in the future in regards to the playlist version, having an undefined version format becomes a problem. This is a slippery slope.

So where draw the line? Since a float value is compatible with the spec, I personally wouldn't mind a PR with a quick change. I'd like to see a response from another team member though.

**Comment by gravyboat** [comment]
@bastimeyer I don't support changing this to a float. the [RFC](https://tools.ietf.org/html/rfc8216#section-4.3.1.2) specifically notes this value should be an integer, not a float. The people who set up this stream aren't respecting the RFC, that's not our problem.

**Comment by bastimeyer** [comment]
True. The change is simple enough for the user to do on their own if they encounter a stream which doesn't behave nicely. And if there were more violations of the specification, we wouldn't merge custom code for this anyway.
