### ISSUE TITLE
Can't connect to proxy.

### ISSUE THREAD

**Issue by IRISlMaple** [streamlink/streamlink#298]
I always use proxy (Need authentication) to connect Internet.
And I have set the proxy in IE.
And this was worked very well.
But these several days, streamlink always tells me that failed to connect the proxy.
And I check the proxy in IE, it works well.
Please kindly help to advise if this is the problem with streamlink?
Can it be fixed?
Thank you very much~~~
![123](https://cloud.githubusercontent.com/assets/22773754/21222938/8500ffe8-c2ff-11e6-8300-225ec7685628.png)

**Comment by IRISlMaple** [comment]
Seems not the problem of streamlink.
Because youtube-dl has the same problem.
But I really don't know why the problem be happened.

**Comment by bastimeyer** [comment]
If the proxy server is not working while using Streamlink but is working while using a different client (your web browser), then you've either misconfigured the Streamlink proxy settings, or the server is blocking Streamlink (which is using the `requests` python library).

Are you sure that you are using the `--http-proxy` parameter correctly?
See this answer of your previous thread(s):
https://github.com/streamlink/streamlink/issues/233#issuecomment-264007551

The only way of distinguishing between proxy clients is the HTTP headers they are sending (`User-Agent`, etc.) and the IP address. But since you're using the same computer and the same connection, the address will be the same. Maybe you could try replacing the User-Agent header with the [`--http-header`](https://streamlink.github.io/cli.html#cmdoption-http-header) parameter.

By using the [`--json`](https://streamlink.github.io/cli.html#cmdoption-j) parameter, you should be able to see the headers being used. I can't tell you which headers IE is using, though...

**Comment by IRISlMaple** [comment]
@bastimeyer 
Thank you for your response.
I never set the proxy for streamlink, just set it in IE, because the speed was much better.
And this worked very very well before.
So I don't know what;s the problem.
If it is the Windows issue?
Because Win10 had a upgrade several days ago.

**Comment by xkbd** [comment]
When you set proxy settings in IE, you set **system** proxy settings.
To disable it in streamlink set `NO_PROXY` system variable with any value.
Or use `--http-proxy` option.

**Comment by gravyboat** [comment]
I think this is resolved based on some of the answers we've had here so I'm going to close it out for now.
