### ISSUE TITLE
Shell tab completion support

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#2993]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Streamlink should provide shell completions for all of its parameters. This could either be static and simple, or a bit more sophisticated and dynamic, depending on the allowed parameter values. Completion data for multiple shells, like fish for example, would also be nice.

I've checked a couple of solutions that work in conjunction with `argparse`, so that shell scripts don't have to be written manually and maintained next to the regular parameter definitions. This can be done with [`argcomplete`](https://github.com/kislyuk/argcomplete) for example, but it needs to run before streamlink-cli's own code gets executed and also needs to be added as a dependency (obviously), and I'm not sure if that's desired.

If there's a way to generate shell completion scripts from argparse, then this would be the best solution.

**Comment by gravyboat** [comment]
I've only ever used argcomplete for this. I don't think argparse has anything built in unless it has flown under the radar for quite some time. I'm against adding additional dependencies (such as the js parser as discussed before) since the value added is really low. This actually has some merit to improve functionality so if it doesn't add too much on to the start time of Streamlink or bloat unnecessarily I'd be okay with either argcomplete or something else.

**Comment by beardypig** [comment]
I wonder if it's possible to make it part of the build and include the generated files, without having to include the dependency in the distribution packages. 

Everyone hating on the js parser, even though it is pure python and has no transient dependencies, and is useful...

**Comment by gravyboat** [comment]
@beardypig My only hate comes from the fact it is unmaintained software. If it was actively being maintained I would have no issue.
