### ISSUE TITLE
Skip downloading ads?

### ISSUE THREAD

**Issue by bobby1973** [streamlink/streamlink#3035]
Is it possible to download a stream but ignore/skip the adverts?

I've downloaded a stream which had adverts which are at a different resolution and or frame rate to the content and every editing software I have tried to edit them out can't handle the different resolutions / frame rates in the same stream.

Looking at the m3u8 file there appears to be ad segments..

#UPLYNK-SEGMENT: 1b5d67c5f8b049a78676432c0b6de505,00000000,ad

or does it have something to do with..

#EXT-X-DISCONTINUITY

Is there some instruction to skip these segments? preferably starting a new stream/download after each advert so I can check easily check continuity when editing?

For ref. I'm new to streamlink and cmd..

Thanks in advance

**Comment by bastimeyer** [comment]
Filtering out ads from HLS streams requires writing a custom `M3U8Parser` and maybe also a `HLSStreamWriter`, depending on how the streaming service's ads are implemented. This also requires you to write a plugin for the stream input, so that those custom classes can be used instead of the regular ones.

See the Twitch.tv plugin for example:
- https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/plugins/twitch.py#L140-L145
- https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/plugins/twitch.py#L213-L216
- https://github.com/streamlink/streamlink/blob/1.4.1/tests/plugins/test_twitch.py#L96-L130

The problem you're seeing is indeed the stream discontinuity which gets annotated in the HLS playlist. This tag alone doesn't tell you though whether you're transitioning into an ad, out of an ad, or from one ad to another. It simply means that the next HLS segment will include data from a different stream. If there's more metadata included in the HLS playlist via extension tags or certain URL patterns in the segments for example and you're able to correctly figure out which segments are ads and which are not, you could filter them out properly.

However, if it's a live stream and the streaming provider is overlaying regular stream segments with ad segments, you will have no chance, because if you're filtering out ads, the regular live stream will continue and once the ad is over, you will have a discontinuity no matter what, even if it's the same stream with the same encoding.

So if Streamlink's output includes any kinds of stream discontinuities, the stream decoder of your player or whatever program you're opening the stream in will need to support discontinuities without any metadata, as Streamlink's output is just a MPEG-TS stream from the concatenated segments.

FFmpeg may be able to fix some parts of the invalid stream data though, but this depends on which data is missing.

**Comment by bobby1973** [comment]
Thanks for your detailed response,

Is there a way to download all the segments individually so I could weed out the ads and stitch the good content?

**Comment by bastimeyer** [comment]
Streamlink doesn't support "downloading" HLS segments independently (as in writing to the filesystem), as its purpose is to output a single stream from the given input.

> weed out the ads and stitch the good content

This is what I described with the custom implementations for the `M3U8Parser` and `HLSStreamWriter` classes. Since it depends on the streaming service on how ads are implemented, "ads filtering" isn't supported as a general purpose method and it has to be tied to a plugin.

If you want to do it by hand, use the `--stream-url` parameter and fetch the HLS playlist manually.
