### ISSUE TITLE
[Plugin Request] theta.tv

### ISSUE THREAD

**Issue by tegradyl** [streamlink/streamlink#3083]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Theta.tv is a live streaming platform similar to Twitch or Mixer. It does not support VOD yet but it is scheduled to be implemented in a few weeks. It is run by a team based in San Jose, CA and has a lot of partners such as Samsung or Sony (https://www.theta.tv/about).
It is based on the blockchain, so viewers can mine tfuel (the coin of the platform) with their additional bandwidth when they are watching a stream, and then use tfuel to subscribe, make donations to streamers, or buy items on the store (theta or streamers t-shirts or mugs, but also ledger wallet, gaming chairs, playstation 4 or nintendo switch).
The platform is improving day after day and there are always events (all information on their discord: https://discord.gg/fE2GhMm).

### Example stream URLs

1. https://www.theta.tv/marshalldracu
2. https://www.theta.tv/princemorii
3. https://www.theta.tv/davirus

### Additional comments, screenshots, etc.

The platform is made like a role-play game: viewers can earn xp watching streams of their favorite streamer to level up and have more visibility on the chat. There is also a system of badge that everyone can earn completing some tasks. Each streamer can use the giveaway system of the platform (using coins earned by watching streams) to reward their viewers.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/2743#issuecomment-565831704

**Comment by milanserfaty** [comment]
I saw this request but it has been 7 months and the platform has made a lot of improvements since then.

**Comment by gravyboat** [comment]
I'm going to say no to this and close it, the stance is the same as 6 months ago. Here are my additions on top of @bastimeyer's comment in #2743 in the event someone brings up this site in another 6 months.

* No one is using this website, there are less than 500 viewers across their entire "platform" on a Sunday mid-day PST.
* It's been 6 months since the original request in #2743 and they have experienced almost no growth in viewership.
* They've undergone a name change which is annoying maintenance for us if we were to implement this, will they change names again in 6 months?
* You note this blockchain functionality as though it is a feature, since we're not running in a browser this won't even work if we just pull the video stream, and even if login functionality was implemented I don't see how it would work without the miner running in the browser (which is extremely shady).

I don't see how this would add anything to Streamlink. We have a lot of obscure plugins already and we don't need more plugins that almost no one uses. If they ditch the buzzword blockchain gimmick and get some actual viewership I think we can reconsider at that time.
