### ISSUE TITLE
Report game being played

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink#3085]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I'd like streamlink to (optionally) report the game (or categorie) of the stream.
It makes scripting easier and it seems that is (for some) plugins already available, since you can pass the (game) categories name into the player, if you want.

### Expected / Actual behavior

It doesnt seem to be available, apart from the player options, which complicated parsing.

**Comment by bastimeyer** [comment]
> I'd like streamlink to (optionally) report the game (or categorie) of the stream.

That does only make sense in the context of certain streaming sites.

The Twitch plugin is the only plugin which implements the `get_category` method. There are overall 3 plugins which implement `get_author` and 13 plugins which implement `get_title` (some of them returning a static title).

If you're writing wrapper scripts around Streamlink, your scripts are most likely written for one specific platform. And since you're talking about games/categories, you must be talking about Twitch. In this case, you should make the API calls yourself. It's not Streamlink(-cli)'s job to be a retrieval tool for metadata from streaming platforms which you can then parse from its log output.

Also, all those methods are called lazily. Printing them in the log output would defeat this.
https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink_cli/main.py#L146-L158

**Comment by pquerner** [comment]
I thought streamlink could give that info since its already querying for it. Sure, I could query it myself.
