### ISSUE TITLE
Picarto: no streams found on this URL

### ISSUE THREAD

**Issue by mrskeltalride** [streamlink/streamlink#309]
Yo,
I'm trying to open any Picarto stream via streamlink and VLC but upon entering command for picarto:

**streamlink picarto.tv/name best**

results in

**[cli][info] Found matching plugin picarto for URL picarto.tv/name
error: No streams found on this URL: picarto.tv/name**

Basically checked almost every live channel on picarto. Am I doinng something wrong? Twitch and hitbox streams are running without problems but I'm only interested in Picarto.
OS is windows 10 and I installed streamlink via Python pip.

**Comment by bastimeyer** [comment]
Which streamlink version are you using?
The picarto plugin has been updated/fixed since the last published release (`0.1.0`) in #205...

You can try installing Streamlink [from the git repo](https://pip.pypa.io/en/stable/reference/pip_install/#git) to get the latest unreleased version:
`pip install git+https://github.com/streamlink/streamlink.git`

**Comment by mrskeltalride** [comment]
Works like charm, thanks and merry xmas.
