### ISSUE TITLE
Limiting access for Streamlink contributors

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#3113]
Recently RetroArch was compromised due to an old user with too much access and too little security maintenance. Their compromised password allowed for devastating and annoying action to be taken against the repository. To protect Streamlink as an org I am proposing the following changes, I understand that discussing this may open some members up to a potential attack vector but I don't see any other way around it that sticks to our commitments around openness:

* A secondary team called `Past Contributors` is added to allow us to move people from the `Members` team who are not actively working on Streamlink. This also allows us to ensure their contributions as part of the organization are recognized and they maintain the Streamlink badge on their profile in case anyone actually cares about that. This team will have read only access to the repository.
* All currently active members (those who have Github activity or contributions in the last 6 months) without 2FA enabled will temporarily be moved to `Past Contributors`, they will then be mentioned in this issue and told they must enable 2FA to remain part of the `members` team, however if they do not wish to do so for whatever reason they can stay on the `past contributors` team. Once that action has been completed they will be moved back to the members team. This is to both protect us from people who may potentially not be active while also ensuring those who wish to remain active members do so, and we don't introduce a risk factor where they are actively called out for not having 2FA while being part of the members team.
* We should have a discussion around the size of the members team, originally it made sense to have more people on the members team due to how quickly we were moving from livestreamer, but now does that make sense? Should we instead move some users to [`outside contributors`](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization)?

@beardypig @bastimeyer @back-to please review this when you have time, as well as the current list of members [here](https://github.com/orgs/streamlink/people) as it's relatively short and gives you an idea regarding what I'm talking about.

**Comment by bastimeyer** [comment]
> * Past Contributors

Sounds reasonable and I don't think there's anything wrong with that. To be honest, I didn't notice the members group had full write access to the repo here.

Some people of the members group are probably only in there because they had offered their help in the fork thread on the livestreamer repo, but then never actually contributed, if I'm not mistaken, and I don't think that they should be in either group.

> * outside contributors

I'd agree with an outside collaborators group for issue/PR management. If there are very active users, move them to the members group.

We should also create a packagers group, because some users of the members group are packagers for certain distros, even if they haven't actually contributed any code changes here.

**Comment by johnthecracker** [comment]
@gravyboat,

Don't you make backup of all project somewhere else?
If I get "compromised" in that way I laugh.

**Comment by gravyboat** [comment]
> To be honest, I didn't notice the members group had full write access to the repo here.

Yes I didn't notice this either until I looked yesterday prior to creating this issue. The team is so small it never crossed my mind to look.

I'm fine with just removing people entirely from the members group if they have never contributed. I just didn't feel like digging to figure out who has and who hasn't so the `Past Contributors` was an easy compromise.

> I'd agree with an outside collaborators group for issue/PR management. If there are very active users, move them to the members group.

Agreed.

> We should also create a packagers group

That's a good idea.

@johnthecracker Locally sure but not to other remote locations no. It's something worth consideration to set the bot up to push to another service such as gitlab.

> If I get "compromised" in that way I laugh.

We're not intending to laugh at anyone here, the situation for retro arch sucks but it's a possible issue on many open source projects that needs to be accounted for. The Streamlink install base is massive and we need to make sure we're taking steps to protect them with basic security checkups.

**Comment by bastimeyer** [comment]
@gravyboat I've created the "Past contributors" and "Packagers" teams.

First, I think we should rename the members team to something like maintainers or active contributors, because it's very confusing when the overall list of people in the orga is called team members. My previous comment wasn't exactly precise because of that confusion.

The only packager I can see who is currently in the members team is grazzolini (Arch Linux). The other package maintainers who are not in the members team but who have been active on the issue tracker in the past or have submitted PRs should be added to the packagers team as well, IMO. That would be conjuro + scowalt (chocolatey), amurzeau (Debian), melmorabity (Fedora), mmetak (Arch Linux - AUR) and ibara (OpenBSD). The separate chocolatey team needs to stay for rights management of those repos in the orga here. The other package maintainers listed in the docs either don't have a Github account, have never been active on the Streamlink repo or the package is outdated on the respective distro/OS/etc, which is another issue, but indicates inactivity and therefore doesn't justify the inclusion. Apologies if I missed someone. This also shows that this should have been done way sooner.

Regarding the past contributors, if you want to entirely remove certain users from the orga if there have been no contributions at all, that should be fine. If there is a problem with that, this can be discussed afterwards. This is not meant as an "orga kick", but rather a rational cleanup, in case somebody feels this way. The separation between the "Past contributors" and "Packagers" teams and who belongs into those teams should be clear then.

I've also checked individual write permissions and those were looking fine.

**Comment by gravyboat** [comment]
@bastimeyer Okay great.

> First, I think we should rename the members team to something like maintainers or active contributors

I think this is a good plan, I'm pretty sure that `members` is just the default name.

> The only packager I can see who is currently in the members team is grazzolini (Arch Linux)

Conjuro is also in the `members` team currently.

Regarding all other packagers I am in agreement and as far as I know that should be everyone unless someone has been packaging that we're unaware (totally possible).

> Regarding the past contributors, if you want to entirely remove certain users from the orga if there have been no contributions at all, that should be fine.

I don't really care too much here I just didn't want anyone to feel like they were being pushed out and figured this was an okay compromise. Of the current members the only people I'm unaware of recent activity/contributions are: lawli3t, SEQUOIIA, LEChaney, and SpootDev. I think they can reasonable be removed. For `Past Contributors`, fishscene, and sbstp should be added here as they have contributed in the past when we did the migration and afterwards.

**Comment by gravyboat** [comment]
@bastimeyer I've updated the name of the `members` team to be `Maintainers` so if you're in there please refresh. I've removed the users noted above from the `Maintainers` group or added them to `Past Contributors` as appropriate.

**Comment by gravyboat** [comment]
I think we can also remove grazzolini from the Maintainers list as they don't have any past direct contributions and should just be in the packagers group.

**Comment by bastimeyer** [comment]
Yes, that's what I've meant with the packagers. Grazzolini should be moved there and other packagers added, if you and everyone else agrees.

Btw, I didn't clean up anything (see the audit log). Conjuro wasn't in the members team and was only in the chocolatey team, which already existed for the permission management of the choco package repos. Same with scowalt.

**Comment by gravyboat** [comment]
@bastimeyer I was probably getting confused between the full team members list and the "members" team so hopefully that will be easier now, sorry about the confusion I see what you mean.

**Comment by SEQUOIIA** [comment]
Yup, can safely remove me @gravyboat ! 😄 Apologies for the inactivity.

**Comment by gravyboat** [comment]
@SEQUOIIA Thanks for letting us know and no need to apologize! We appreciate everyone's work no matter the context. I don't want anyone to think we don't appreciate them or are removing them as some sort of punishment, it's just about repo and org security.

**Comment by beardypig** [comment]
@gravyboat all sounds sensible to me.

**Comment by gravyboat** [comment]
@bastimeyer @beardypig I think this can be closed now unless anyone else has something to weigh in on, if so feel free to reopen.

**Comment by bastimeyer** [comment]
@gravyboat The packagers team and external contributors still haven't been addressed.

**Comment by gravyboat** [comment]
@bastimeyer Oh yep good point.

**Comment by bastimeyer** [comment]
After a short discussion with @gravyboat, I've just moved all inactive users from the streamlink orga's "members" list to "outside collaborators" and removed their write access to the repos which gets kept while doing so. No ill intentions, just a security measure, as states in the OP from 1.5 years ago. If anyone of those users wants to become active again and get moderation/administration rights back, they are very welcome, just like everyone else who's very much involved with the project.

Speaking of moderation rights, I added @mkbloke to the team members/maintainers list.

Streamlink packagers who were already added to the orga were also finally moved into the right "packagers" team, which I totally forgot about. Other packagers can get added there too, if they want. I'm not going to look for any Github accounts now though. Please just comment here in case you see this. Otherwise, anyone else with the necessary permissions can add those users.

Closing...
