### ISSUE TITLE
raiplay.it

### ISSUE THREAD

**Issue by writetome1** [streamlink/streamlink#3143]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

https://www.raiplay.it/dirette/rai2
2. ...
3. ...

### Logs

```
~$ streamlink   --loglevel debug https://www.raiplay.it/dirette/rai2   best --player  ffplay
[cli][debug] OS:         Linux-5.4.0-42-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai2
[plugin.raiplay][debug] Found channel: rai2
error: No playable streams found on this URL: https://www.raiplay.it/dirette/rai2
~$ 
```

### Additional comments, screenshots, etc.

```
:~$ streamlink   --version
streamlink 1.5.0
:~
```

same in windows 10

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
It's not a live stream, it's just VODs.

**Comment by writetome1** [comment]
I'm sorry You are wrong. Please enter in a browser "
https://www.raiplay.it/dirette/rai2" and You will see that you reach live
stream just clicking on play botton ( the URL field remain unchanged ! "
https://www.raiplay.it/dirette/rai2".
Just for example:
in web browser address:
"https://www.raiplay.it/dirette/rai2"
... stream playing
using video download helper ... copy address  ... insert user agent

then:

ffplay -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0)
Gecko/20100101 Firefox/80.0"  -i "
https://raidue1-live.akamaized.net/hls/live/598310/raidue1/raidue1/rai2_2400/exp=1599217615~acl=%2fhls%2flive%2f598310%2fraidue1%2f*!%2fhls%2flive%2f598310-b%2fraidue1%2f*!%2f*.key~data=hdntl~hmac=49b0cd0797a4ba799cfb290649c38f6a8fe88c4614224c41008a905217bc2549/chunklist.m3u8?aka_me_session_id=AAAAAAAAAADPH1JfAAAAAJw6HTo7gjvcyNGzLfZMeLFLSx9amXBd+hR0pzbTjDi0l8hGOdkbTy8RvHNoxvp1mhViuL6SMRPt"


play LIVE stream ....

bye for now

**Comment by gravyboat** [comment]
I can't access this because it's geo-restricted to Italy. When I visited the URL before, as well as now and did a translation on the title and description it's just a "live" stream of pre-recorded content, and in this case a movie from 2006. That's basically just a bunch of VODs pushed in to a live stream and I don't believe it counts. Please show me a link to live content that is occurring now.

**Comment by mkbloke** [comment]
@gravyboat, try: https://www.raiplay.it/dirette/rainews24 for an unrestricted channel.  It appears there are URL params on the playlist, but not the individual chunklists:
```
streamlink hls://https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/rainews_1200/chunklist.m3u8 live
[cli][info] Found matching plugin hls for URL hls://https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/rainews_1200/chunklist.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
Reopening, since there are a couple of live streams (news channels).

@writetome1 
Plugin requests should be as detailed as possible with enough information, so please don't wonder if your thread gets closed if it doesn't meet the requirements. Take a look here:
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

----

> try: [raiplay.it/dirette/rainews24](https://www.raiplay.it/dirette/rainews24) for an unrestricted channel

This one does indeed work with a non-italian IP, but everything else is geo-restricted. It looks like it doesn't make much of a difference though, as you can still make the necessary requests to get to the HLS playlist.

1. Find the DOM element with the `data-video-json` attribute and use it as the path segment of the input URL
   `https://www.raiplay.it/dirette/rai1` => `https://www.raiplay.it/dirette/rai1.json`
2. Request the video JSON URL, parse it as JSON and find the `video.content_url` value. Optionally replace the HTTP scheme with HTTPS.
3. That new URL will either redirect to the live stream's HLS playlist, or a mp4 file if it's geo-blocked.

**Comment by bastimeyer** [comment]
Didn't realize and didn't check that we already had a plugin for this site. Relabeling...

**Comment by gravyboat** [comment]
@bastimeyer I didn't either. I don't think I've seen anything referring to it for the entire time we've been managing the project.
