### ISSUE TITLE
XUMO Live Channels

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#3157]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

XUMO is a web service now owned by Comcast that is similar to Pluto.

They have many live streams like news channels and classic tv like Carol Burnett. They also have stand up comedy channels, food channels, and more.

They seem to use straight m3u8s with no DRM, so it shouldn’t be drama to add it.

It seems since Comcast bought it, more channels are popping up all the time and it would be nice to have streamlink play or record them.

XUMO has a decent library of VOD as well but it would be mainly nice to at least see the Live Streams better supported.

### Example stream URLs

1. ... https://www.xumo.tv/on-now/9999147/tyt
2. ... https://www.xumo.tv/on-now/9999105/the-best-of-the-carol-burnett-show
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
Is it actually worthwhile creating a plugin for this site?  The playlists seem to be static and can be accessed via the `hls://` prefix to the playlist URL...

**Comment by beardypig** [comment]
The HLS sources appear to be embedded in to the page source, should be a fairly simple plugin.

**Comment by gravyboat** [comment]
It doesn't seem as though this site meets the [plugin requirements](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests). Specifically points 3, then if you exclude those it falls under 6, and it also doesn't meet requirement 10.

**Comment by beardypig** [comment]
The TV stations would be the plugin. I believe this plugin would meet all the plugin requirements; the company behind the website provides those channels and is licensed to do so. I think point 10 is actually a bit ridiculous in general, but..

> Since January [2020], according to Xumo, its user base has soared 2.5 times to reach more than 24 million U.S. monthly active users.

**Comment by gravyboat** [comment]
@beardypig It's not so much that they are licensed to do so, it's that these same channels can be watched from the official source and it is just a TV rebroadcast. Are we going to start adding other sites that stream these same channels because they're licensed to do so instead of telling people to use the official sources? It just seems redundant.

> I think point 10 is actually a bit ridiculous in general

We had to add it a while back to combat all the cam, tiktok style, and random sites that would have made Streamlink really bloated and impact performance. If it's a live broadcast it should generally have some sort of viewer numbers available, but again this goes back to me not caring at all about TV stations and thinking they are ridiculous to include to begin with.
