### ISSUE TITLE
Stuttering or Ghosting in HLS Recorded TS files?

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#3168]
## Bug Report

- [ X] This is a bug report and I have read the contribution guidelines.

### Description

I am trying to figure out if this is some bug with the actual recording of HLS Streams with streamlink, something on the serverss end, or something on my end.

### Expected / Actual behavior

I just expect a basically flaw free TS file after I record.

### Reproduction steps / Explicit stream URLs to test

1. ... "streamlink -f --hls-segment-threads 10 --hls-segment-attempts 25 "https://content.uplynk.com/channel/87c82188ea944bcb961c34236b9648b0.m3u8?v=2&m.sound=normal&m.sound=normal&m.playback=autoplay" best -o out.ts"
2. ... OR "streamlink -f --hls-segment-threads 10 --hls-segment-attempts 25 "https://y5w8j4a9.ssl.hwcdn.net/zlivingusa_r_prod/index.m3u8" best -o out.ts"
3. ...

### Log output

```
streamlink --loglevel debug -f --hls-segment-threads 10 --hls-segment-attempts 25 "https://content.uplynk.com/channel/87c82188ea944bcb961c34236b9648b0.m3u8?v=2&m.sound=normal&m.sound=normal&m.playback=autoplay" best -o out.ts
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin hls for URL https://content.uplynk.com/channel/87c82188ea944bcb961c34236b9648b0.m3u8?v=2&m.sound=normal&m.sound=normal&m.playback=autoplay
[plugin.hls][debug] URL=https://content.uplynk.com/channel/87c82188ea944bcb961c34236b9648b0.m3u8?v=2&m.sound=normal&m.sound=normal&m.playback=autoplay; params={}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 234p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 0; Last Sequence: 8
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 6; End Sequence: None
[stream.hls][debug] Adding segment 6 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Download of segment 6 complete
[cli][debug] Checking file output
[stream.hls][debug] Download of segment 7 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 8 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Download of segment 9 complete
[download][out.ts] Written 3.4 MB (8s @ 404.0 KB/s)                            [stream.hls][debug] Download of segment 10 complete
[stream.hls][debug] Download of segment 11 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Download of segment 12 complete
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.
It normally records well, and I have tried it on two separate PCs now, as I wanted to verify it's not just one of my Win 10 Quad Core Laptops acting up.

I have tried a defrag, checked network, checked my Internet Connection speed, ping, etc to try and rule out my equipment causing the video errors.

Strangely, I sometimes get a weird effect like this in the recording of the first link:

https://www.dropbox.com/s/2uzl4x71ajd247z/stutter.ts?dl=1

It's like the video randomly pauses and the sound goes "errrrrrrrr" and then the video resumes like normal.

The second link will sometimes have a TS randomly freeze after playing great for many minutes and look like this:

https://www.dropbox.com/s/bxfchgw4d1i6fmr/broken-up.jpg?dl=0

I don't seem to get these types of effects when I record some other streams like YouTube Live. I record 1080P YouTube Live so I don't know why my PCs would not be good enough for 720P for these two streams.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Deep0d0** [comment]
i generally transcode mine to h.264 for playback. TS lags too much and has frame drops

**Comment by bastimeyer** [comment]
MPEG-TS is a stream container format. You don't have to re-encode / transcode the video stream data into a different codec.

HLS streams are chunks of (most of the time) MPEG-TS files which are concatenated in the final output. The MPEG-TS container mostly contains H.264 (AVC1 / MPEG4) video streams and AAC, AC-3 or MP3 audio streams. This is the case with the example stream URL posted above, albeit encrypted via AES-128 and decrypted by Streamlink before concatenating them.

There is no remuxing being done by Streamlink unless there are external alternative audio tracks available in the HLS master playlist. If you're having playback issues with the concatenated MPEG-TS segments, then it's because the MPEG-TS stream is lacking timing metadata. Tools like ffmpeg are most of the time able to reconstruct it properly and if you remux it, for example into an mp4 container with a proper "moov atom" (timing metadata) at the beginning of the file, then your player should be able to read it properly. You can try remuxing it on the fly via `--stdout` and piping the stream into ffmpeg, or after writing the entire MPEG-TS container to the filesystem and then remuxing it.

There have been enough answered questions on the issue tracker about remuxing.

**Comment by gravyboat** [comment]
Closing, question has been answered and there hasn't been a response in over a week.
