### ISSUE TITLE
Github discussions?

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3171]
Would it make sense applying for the "Github discussions" beta for the Streamlink repo? We always have tons of issue and pull request threads with support questions and comments which are unrelated to actual bugtracking.

Github discussions are basically another section/menu in addition to the issues where threads and comments can be posted, like a forum, as shown here:
- https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/
- https://github.community/t/can-one-apply-for-github-discussions-beta/121120

I don't know how this affects account notifications for those who are "watching" the repo, so this may be a concern here. I'm also not sure if this is something that should be included in the repository itself and people should instead ask for help elsewhere, eg. on Stackoverflow, etc. Another concern may also be that people will use it incorrectly and post on the wrong places anyway, adding a new maintenance burden. Thoughts?

**Comment by gravyboat** [comment]
I wouldn't be for it. I rarely even check the gitter.im channel and I wouldn't check in on this either as I'm unwilling to invest more of my free time in Streamlink maintenance and answering questions than I already do. I don't believe we have enough maintainers and moderators to handle the work that comes with a discussion forum of some kind. If it sends notifications that would be really terrible. As you mentioned it seems very likely people will use it incorrectly.

**Comment by mkbloke** [comment]
It's an interesting dilemma.  I've tried using the gitter.im channel for things that I didn't feel were appropriate to open an issue for, but unfortunately, that channel is basically useless for the help that it has been, to the point that it's reason for existence is pretty questionable.

I can understand the concerns regarding additional notifications.  Misuse of issue/PR threads seems commonplace on GitHub from what I've read recently, but I guess it's not helped by a lack of any other method of support as well.

The remaining option is to continue with the status quo and perhaps be a little more trigger happy with the thread locking to stem the flow, perhaps?

**Comment by gravyboat** [comment]
The gitter has always been problematic as providing help via chat like that is time consuming and with the portion of my day I'm willing to contribute to the project it's not going to be looking at the gitter. Most but not all of the questions that get asked are in relation to misuse of Streamlink, subpar players, incorporation in to some 3rd party tooling, or not reading the documentation.

We could update the issue templates again, but I don't think that would help much since people don't read the templates before submitting issues currently.

Maybe we do need to start locking issues more quickly or even immediately once an issue is created. Maybe part of it is that we also need to revamp the documentation in some way but I've been keeping a loose track of the issues with general questions and most of them are already addressed in the docs.

**Comment by mkbloke** [comment]
I have wondered if a permanently open and pinned issue (also locked), with general guidance on what should be in issues and what should not/where to seek help elsewhere might be useful, as it'll be somewhat prominent.  I very much doubt it'll cure the problems, but it might reduce the volume of noise a little bit, which could be of some relief for you.  You could try some different title names perhaps and see what might work best over time.

**Comment by bastimeyer** [comment]
With Gitter now being part of Element and being rewritten based on the matrix chat protocol, this will make Gitter way more accessible to people, and FOSS projects with a Gitter channel can be reached way more easily than before. Maybe we should just add links to Streamlink's Gitter channel to the readme and docs and forget about the discussions forum. How useful it is for solving issues, as it's a chat and not a forum, I don't know. It's not been used that much before except for the one time Twitch broke and I posted a link to the channel in the megathread. Not being able to find/browse older questions ordered by thread is also a problem with such a structure.

- https://blog.gitter.im/2020/09/30/gitter-element-acquisition/
- https://matrix.org/blog/2020/09/30/welcoming-gitter-to-matrix

----

Regarding a perma sticky thread with issue guidelines, this should in theory already be solved by the templates and the CONTRIBUTING.md file. But as it's usually the case, people are too lazy to read and/or ignore everything. Even such a simple task as replacing a space character with an x is a problem for most people. A good indicator though whether they've read the template. Maybe the markdown syntax is too overwhelming on a template that is rather large, especially with HTML comments. And maybe people get confused with the name "CONTRIBUTING.md", because they are reporting an issue and don't think they are contributing. A sticky thread could help to solve this problem at least.

**Comment by gravyboat** [comment]
I'd be in favor of this. After this recent bout of Twitch issues there's no way I'm going to ever review a discussion forum. The time investment is already high (and even higher for you as of late @bastimeyer).

In terms of the issues I think we should just start closing any issue that doesn't meet the guidelines. If people can't be bothered to read and fill out all the information I don't care whether they use Streamlink or not. They aren't paying us so who cares if they get pissed, it's their problem for not reading. I'd be fine with a sticky thread, but I'm not willing to accept any more excuses around poorly put together issues.

**Comment by mkbloke** [comment]
I don't know what the significance of the Element/matrix aspect is to Gitter, but if it makes things better, then great.

In some cases, people just don't read documentation or try to look for past issues and fixes, unfortunately.  I know in my case, even though I'd read the docs, I failed to put two and two together with regards to using the ```--player-no-close option``` for example.  I also know I've cocked up the tick box in an issue before now by leaving in a space after putting an x in it.  I blame the font on my system for that. ;-)

GH mark up isn't complicated, but some people still won't get it.  It did take a short while until I noticed that there is a slight difference in formatting when using the three back-ticks, depending on whether they are in-line or on their own lines.

I can understand your reluctance to add the GH discussion forum due to additional work, although it's not the case that you *have* to deal with it if it does exist, provided it's not going to flood you with notifications of course.  It could just be left for user-to-user support instead.  I'm not particularly trying to advocate for it though, just suggesting that it *could* help you by reducing the number of issues created.

Being stricter when it comes to plugin issues and requests seems reasonable to me.

**Comment by back-to** [comment]
>  We always have tons of issue and pull request threads with support questions and comments which are unrelated to actual bugtracking.

using Github discussions for **plugin requests** and some basic questions,
might improve the issue tracker here.

**Comment by bastimeyer** [comment]
Github discussions have just been made available for all repos (still labeled as beta). Do you guys want to enable it here? I have no idea how this works in regards to notifictions. I'd like to test it though and see if it's actually an improvement over having the issue tracker spammed with questions.

**Comment by gravyboat** [comment]
@bastimeyer Let's try it without any expectation that maintainers provide support. It's worth a shot.

**Comment by bastimeyer** [comment]
There's also a new config for the issue templates where you can add external links:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

Maybe worth adding a link to the discussions and maybe also linking to the docs...
