### ISSUE TITLE
--title switch with variable arguments prevents Twitch rerun vod from playing

### ISSUE THREAD

**Issue by azizLIGHT** [streamlink/streamlink#3206]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

 If you use the --title switch with arguments that contain variables like {author}, {category}, or {title}, streamlink cannot play certain twitch streams (reruns, I think)

### Expected / Actual behavior

I expect streamlink to open the twitch stream in my player of choice and start playing. Instead, I get errors, nothing plays, and streamlink quits.

### Reproduction steps / Explicit stream URLs to test

1. Find a twitch channel that is playing reruns, for example: reckful
2. Launch using a command like: streamlink --loglevel debug --verbose-player --player=mpv --title "{author}" twitch.tv/reckful best
3. See log output

### Log output

```
[azizLIGHT@fractal ~]$ /home/azizLIGHT/Documents/Scripts/streamlink-pip/bin/streamlink --loglevel debug --verbose-player --player=mpv --title "{author}" twitch.tv/reckful best
[cli][debug] OS:         Linux-5.4.52-1-MANJARO-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 1.5.0+31.g1913115
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/reckful
[plugin.twitch][debug] Getting live HLS streams for reckful
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60_alt, 720p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 3689; Last Sequence: 3702
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 3700; End Sequence: None
[stream.hls][debug] Adding segment 3700 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 3701 to queue
[stream.hls][debug] Adding segment 3702 to queue
[stream.hls][debug] Download of segment 3700 complete
[stream.hls][debug] Download of segment 3701 complete
[stream.hls][debug] Download of segment 3702 complete
[cli][info] Closing currently open stream...
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
Traceback (most recent call last):
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.5.0+31.g1913115', 'console_scripts', 'streamlink')()
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 1027, in main
    handle_url()
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 602, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 455, in handle_stream
    success = output_stream(plugin, stream)
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 316, in output_stream
    output = create_output(plugin)
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 114, in create_output
    title = create_title(plugin)
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 148, in create_title
    title = LazyFormatter.format(
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink/utils/lazy_formatter.py", line 22, in format
    return string.Formatter().vformat(fmt, (), cls(**lazy_props))
  File "/usr/lib/python3.8/string.py", line 167, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.8/string.py", line 207, in _vformat
    obj, arg_used = self.get_field(field_name, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 272, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 229, in get_value
    return kwargs[key]
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink/utils/lazy_formatter.py", line 11, in __getitem__
    return value()
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink_cli/main.py", line 151, in <lambda>
    author=lambda: plugin.get_author() or DEFAULT_STREAM_METADATA["author"],
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 422, in get_author
    self._get_metadata()
  File "/home/azizLIGHT/Documents/Scripts/streamlink-pip/lib/python3.8/site-packages/streamlink/plugins/twitch.py", line 410, in _get_metadata
    api_res = self.api.streams(self.channel_id)["stream"]["channel"]
TypeError: 'NoneType' object is not subscriptable
[azizLIGHT@fractal ~]$ 
```

### Additional comments, screenshots, etc.
Normally I use --title "{author} - {category} - {title} - (\${{video-bitrate}})" in my command, but any of those will cause streamlink to fail when trying to watch reckful stream. It does not seem to do it for regular live twitch channels, maybe it only does it to rerun channels. I am not sure. This was streamlink installed to a venv using [these instructions](https://streamlink.github.io/install.html#virtual-environment)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by azizLIGHT** [comment]
Stream launches fine without the --title switch: 
`streamlink --player="mpv --keep-open=yes --ontop --autofit=22%" --player-no-close --twitch-disable-ads --twitch-low-latency http://twitch.tv/reckful best`

and also launches fine with the --title switch, IF the arguments are NOT variables:
`streamlink --player="mpv --keep-open=yes --ontop --autofit=22%" --player-no-close --twitch-disable-ads --twitch-low-latency --title="test" http://twitch.tv/reckful best
`

**Comment by gravyboat** [comment]
This is because that data is not available from the API where we expect it to be. I'm not sure if this is something we'll consider fixing. @bastimeyer I feel like we discussed this in the past regarding rebroadcasts and that they work differently than a VOD or live stream and we said we wouldn't fix issues with them due to how rare they are, but I can't find the discussion now. Do you remember?

**Comment by bastimeyer** [comment]
This channel is not "live" (yes, I know why). The Twitch API doesn't return stream data in those cases. That might be a bug with kraken v5, I don't know, but I wouldn't be surprised either, because kraken v5 is really messy, and helix I believe still a shitshow, despite promises of improvements earlier this year.

Streamlink doesn't set the `stream_type` query parameter when requesting streams by channel ID, as documented here:
https://dev.twitch.tv/docs/v5/reference/streams#get-stream-by-user

It doesn't make a difference though, as you can see in the following example:

```bash
LOGIN=reckful
ID=$(curl -s \
      -H "Accept: application/vnd.twitchtv.v5+json" \
      -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
      "https://api.twitch.tv/kraken/users?login=${LOGIN}" \
      | jq -r '.users[0]._id'
)
```

**No `stream_type`**
```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
  "https://api.twitch.tv/kraken/streams/${ID}" \
  | jq
```
```json
{
  "stream": null
}
```

**With `stream_type=all`**
```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
  "https://api.twitch.tv/kraken/streams/${ID}?stream_type=all" \
  | jq
```
```json
{
  "stream": null
}
```

This is an issue on the Twitch API and we can't do anything about when they don't provide the correct data. It doesn't mean though that the plugin should raise a `TypeError`. The method for reading the stream's metadata currently doesn't check for missing data and also doesn't use a validation schema. This bug needs to be fixed.

The overall state of the Twitch plugin in regards to the API queries and stuff around that is very much outdated and hasn't been touched in several years. When the `--title` parameter was added two years ago, this should have been implemented way cleaner. When I get the time, I will look into refactoring the plugin's `TwitchAPI`, `UsherService` and overall plugin methods.
