### ISSUE TITLE
TS segment concatenation

### ISSUE THREAD

**Issue by markantonydev** [streamlink/streamlink#3229]
Hello!

Can you please point a place in the code where downloaded mpeg-ts files are getting continuously concatenated (spliced) during stream recording?
Unfortunately I'm failing figuring it out myself.
Thank you for your help!

Mark

**Comment by bastimeyer** [comment]
I won't link you explicit lines of the code, as you can figure it out on your own from my description, but this is how HLS streams work in Streamlink:

The `HLSStreamReader` first initializes a `RingBuffer` and spawns a `HLSStreamWorker` (`SegmentedStreamWorker`) thread and a `HLSStreamWriter` (`SegmentedStreamWriter`) thread. The worker thread is responsible for reloading and processing the HLS playlist and it puts sequences (numbered segments) into the `Queue` of the writer thread. The writer thread then fetches the segments via its `ThreadPoolExecutor` threads and writes them into Streamlink's `RingBuffer` in order. The `HLSStreamReader`'s `RingBuffer` then gets read/iterated by the main thread until no more data is available and the timeout (default is 60 seconds) has run out. This implicitly concatenates the segments in the final stream output.

**Comment by markantonydev** [comment]
@bastimeyer 
Thanks for your reply.
Following your detailed description I could track it down to
 https://github.com/streamlink/streamlink/blob/cb5cee6109b98e61f98b42967185a379a4748e0a/src/streamlink/stream/hls.py#L161

But what I can't still understand: is there any logic for processing segments while writing them to file? I mean any logic on MPEG transport stream level? Or they just written one after another bytewise?

**Comment by bastimeyer** [comment]
Assuming that the timestamps are correct in each of the MPEG-TS segments in a single HLS stream, segments don't need to be re-muxed. The HLS protocol is specifically designed for this, because the MPEG-2 transport stream allows for simple concatenation.

> Each Media Segment MUST carry the continuation of the encoded bitstream from the end of the segment with the previous Media Sequence Number, where values in a series such as timestamps and Continuity Counters MUST continue uninterrupted.

- https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-3
- https://en.wikipedia.org/wiki/MPEG_transport_stream

An exception to this are stream discontinuities, which are annotated in the HLS playlist. Streamlink doesn't support this though and the output will be corrupted on a discontinuity, and the player/demuxer needs to handle this exception when reading Streamlink's output. Some players do have problems with this though, like (old versions of) VLC for example.

----

Concatenating naively and via ffmpeg doesn't produce identical files, but it's no problem in the MPEG2 transport stream:

```bash
# Split up example video file
ffmpeg -i input-video-file -c copy -map 0 -segment_time 2 -f segment output%03d.ts

# simple/naive concat of the first two segments
cat output000.ts output001.ts > output-concat-simple.ts

# ffmpeg concat of the first two segments
ffmpeg -i 'concat:output000.ts|output001.ts' -c copy output-concat-ffmpeg.ts
# or like this
echo -e "file output000.ts\nfile output001.ts" | ffmpeg -f concat -safe 0 -protocol_whitelist pipe,file -auto_convert 0 -i pipe:0 -c copy output-concat-ffmpeg.ts

# compare
diff --side-by-side \
  <(ffprobe -v error -show_format -show_streams -print_format json output-concat-simple.ts | jq) \
  <(ffprobe -v error -show_format -show_streams -print_format json output-concat-ffmpeg.ts | jq)
```

----

Muxing only needs to be done when additional stream data should be included in the output stream, like for example from an external audio stream that's included in the HLS variant playlist. That's what the `MuxedHLSStream` is for and it (of course) spawns an FFmpeg child process for this.

**Comment by markantonydev** [comment]
Thank you!
