### ISSUE TITLE
itertags() case sensitivity and regex escaping

### ISSUE THREAD

**Issue by mkbloke** [streamlink/streamlink#3241]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

The ```itertags()``` function appears to be case sensitive.

### Expected / Actual behavior

That ```itertags()``` is not case sensitive.

Is there any reason why ```tag_re``` and ```attr_re``` do not both use the ```re.IGNORECASE``` flag?

Thanks.

**Comment by mkbloke** [comment]
> Is there any reason why tag_re and attr_re do not both use the re.IGNORECASE flag?

That's not the solution I think...  Maybe just:
```
if match.group("tag").lower() == tag.lower():
```

Is the answer.

**Comment by bastimeyer** [comment]
The method was added in a3c07b48e368e3e387c6b4f4baa6a6b88ac40e0a and I believe it was just a mistake, as [HTML5 tags are case-insensitive](https://w3c.github.io/html-reference/documents.html#case-insensitivity) (tags in a regular XML document however are not).

Parsing like this however isn't fail-proof, as regexes can't be used to correctly parse this kind of language. These regexes also don't support self-closing tags or deeply nested tags for example.

I'd like this to see this "hacky" solution being removed in favor of a real parser at some point in the future. I know that this was probably added for performance reasons and is good enough for most cases, but since a ton of plugins also use wonky regexes for extracting content from an HTML document, a real parser with Xpath queries or CSS selectors could fix both of these problems. I don't have any experience with the parsers of the standard library, but I've read that there are better 3rd party solutions which are also much faster, eg. [`lxml`](https://lxml.de/1.3/index.html).

**Comment by mkbloke** [comment]
Given that:
>  as HTML5 tags are case-insensitive (tags in a regular XML document however are not).

it might be better to close this as ```wontfix```.  There are lots of plugins using ```itertags()``` and although it's likely that almost all of them are using it with HTML rather than XML, without checking that's the case, perhaps changing ```itertags()``` now could break things.  I already have mitigation in place for my use-case anyway.

> eg. lxml

I was looking at lxml and Beautiful Soup a week or two back.  It would certainly be nice to have something like that at some point.

**Comment by bastimeyer** [comment]
Not sure how relevant and informative this is in 2020, but BeautifulSoup is allegedly rather slow:
http://blog.dispatched.ch/2010/08/16/beautifulsoup-vs-lxml-performance/

**Comment by mkbloke** [comment]
> BeautifulSoup is allegedly rather slow

Interesting.

Still, I guess the whole discussion about including/selecting an HTML parser is not top of your priorities right now,,,

**Comment by mkbloke** [comment]
Another issue I seem to have run into is that attributes don't seem to be regex escaped where they need to be.  For example:

```<form name="x" action="https://site.com/path?a=b&c=$something">```

```form.attributes.get("action")``` will return ```https://site.com/path?a=b&c=```

**Comment by back-to** [comment]
> @mkbloke
`form.attributes.get("action")` will return `https://site.com/path?a=b&c=`

it seems to work with your `$something` example

```py
from streamlink.plugin.api.utils import itertags
html = """<!DOCTYPE html>
<html>
<head>
<title>Hello World HTML</title>
</head>
<body>
<h1>Hello World</h1>
<form name="x" action="https://site.com/path?a=b&c=$something">
</body>
</html>"""
for form in itertags(html, 'form'):
    print(form.attributes.get('action'))
```

```py
>>> for form in itertags(html, 'form'):
...     print(form.attributes.get('action'))
... 
https://site.com/path?a=b&c=$something
```

**Comment by mkbloke** [comment]
@back-to, thanks for looking at this.  That's interesting, I wonder why I wasn't getting the full URL I was expecting.  I'll have to go back and look at it again.  Cheers.

**Comment by back-to** [comment]
doesn't seems to be important, if `itertags` checks for case sensitivity.
