### ISSUE TITLE
Twitch Soundtrack and handling audio tracks

### ISSUE THREAD

**Issue by arrowgent** [streamlink/streamlink#3260]
Twitch Soundtrack:
https://help.twitch.tv/s/article/soundtrack-audio-configuration
https://help.twitch.tv/s/article/soundtrack

are there any tests out there for this?

im curious how streamlink can handle this and if it is configured to handle seperate audio tracks or muxing

and which track is default, assuming track 1 is "soundtrack" and that track 6 is "streamer/game" audio
it would then have to be configured by the video player (mpc/vlc/mpv) ??

i did not see any issue for "soundtrack" so i started this to bring it attention

**Comment by bastimeyer** [comment]
I haven't heard about this yet, but it looks like the music is added as a separate audio track by the "soundtrack" OBS plugin and it can then be removed by Twitch by simply remuxing the VODs, so that they don't have to remove parts of the regular stream audio. For live streams, both audio tracks - the regular one and the music one - need to be played by the player. There also seem to be some annotations which tracks are being played.

I don't know how relevant this is for Streamlink. If this gets used by lots of streamers and certain players don't have the ability of playing multiple audio tracks at once, then what Streamlink could **optionally** do is mixing both audio streams and re-encoding them into one in the final output. That would require an FFmpeg version that was built with the necessary codec support, but that shouldn't be a problem on most systems. It would add an output delay though and increase the CPU usage due to the re-encoding.

**MPV**
https://mpv.io/manual/master/#options-lavfi-complex

**VLC**
https://superuser.com/questions/556182/how-to-play-multiple-audio-track-of-video-simultaneously-on-vlc/1372948#1372948

**MPC** (no CLI param)
https://superuser.com/questions/1184457/how-do-i-get-two-different-audio-streams-simutaneaously-in-my-computer/1185191#1185191

**Comment by back-to** [comment]
@arrowgent 

> are there any tests out there for this?

it is just a beta

> im curious how streamlink can handle this and if it is configured to handle seperate audio tracks or muxing

when it is out of beta, you might see what is possible or not possible.

---

@bastimeyer 

> I don't know how relevant this is for Streamlink.

in this beta state, it seems totally irrelevant for streamlink.

**Comment by arrowgent** [comment]
closed but wanted to post a test for this

https://www.twitch.tv/soundtrack

seems to be working fine

thanks guys
