### ISSUE TITLE
Feature Request. Ability to specify subprocess errorlog path

### ISSUE THREAD

**Issue by xkbd** [streamlink/streamlink#327]
Is it possible?

**Comment by beardypig** [comment]
Which subprocess? The player or stream subprocesses? I don't think either is possible at the moment, but it is possible to add an option.

**Comment by xkbd** [comment]
Stream subprocess. Option `--errorlog`.
I'd like to set the path but this parameter is a boolean.

**Comment by beardypig** [comment]
It is possible to add an option like `--errorlog-path` or similar. Would probably be worth while adding a path option for `--verbose-player`.

**Comment by xkbd** [comment]
By the way, it would be great to store logs in one place.

when i use `--errorlog` dest path for log file: %tmp%
In %appdata% i see `Streamlink.launch.pyw.log`
Also at `%appdata%` exists direcory `streamlink`
Why not store all the logs by default in the %appdata%\streamlink\logs?

**Comment by Vangelis66** [comment]
@xkbd wrote: 

> Why not store all the logs by default in 
> the %appdata%\streamlink\logs?

This is a sensible request, I am "+1"ing it for the installed versions 
of streamlink; however, I am mostly running portable installations 
myself, so I wouldn't want additional leftovers on the host machine; 
some prevision should be taken for the portable flavours (currently 
two exist, one from @beardypig and another from @RosadinTV), 
so that the logs folder is created inside the portable installation directory...
