### ISSUE TITLE
Consider moving away from github in light of recent youtube-dl DMCA takedown

### ISSUE THREAD

**Issue by sendc** [streamlink/streamlink#3284]
## Issue
Youtube-dl has been taken down due to a DMCA request: [https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md](https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md)
Streamlink features similar functionality so it can be assumed that it may be targeted in future DMCA takedown requests.

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description
Alternatives to github that I can think of off the top of my head:
https://codeberg.org
https://notabug.org
https://www.teknik.io

I should add that I don't know how safe they are against DMCA takedown requests.
Maybe someone else knows even better places to host git repositories.
Looking forward to your comments and suggestions.

**Comment by bastimeyer** [comment]
We have already received a DMCA takedown notice two and a half years ago (see #1493). This was a false claim and therefore an illegal abuse of the so well designed US copyright law, but Github as an American company has to obey these laws.

Opposed to yt-dl and its goal of being a stream/video downloader, the goal of Streamlink is to avoid slow and badly optimized websites in the user's web browser and pipe live streams into the user's hardware accelerated local video player instead. There is no intention of preventing any kind of DRM or content protection, or providing a tool for downloading and illegally re-distributing content. The focus is purely on watching live streams as they are happening. Unlike yt-dl, we also don't give instructions on how to steal content.

During the takedown request from two and a half years ago, what we had to do was remove the requested parts of the project within 24 hours or face the shutdown of the project by Github. Since Streamlink is based on a plugin system that covers individual websites, removing a single plugin in this case doesn't mean the end of the project. Fighting those abusive and false claims however is not possible for us, since we are only a small group of individual people working on a FOSS project as a hobby.

Moving the entire project to a different git-hoster because of a single plugin and crippling the overall reach and popularity of the project (and also having to replace the issue tracker, CI, website and release infrastructure) is something which doesn't make sense. If there's going to be another false and abusive DMCA takedown request, we'll unfortunately have to follow the request and remove the affected plugin. If you or anyone else doesn't like this, then please create a fork and go into legal battles with those companies. Switching the hoster also doesn't guarantee that you'll not be targeted over there, so the entire idea is rather pointless.

----

I'll leave this thread open for further discussion. If anyone of the other maintainers feels like closing it, please go ahead.

**Comment by beardypig** [comment]
If you read the DMCA takedown notice you'll see it's because they circumvent the protected video feature on YouTube.

**Comment by gravyboat** [comment]
I think the points have been covered pretty well here so I'm going to close this.
