### ISSUE TITLE
bitwave.tv Plugin Request

### ISSUE THREAD

**Issue by Frankthetankk** [streamlink/streamlink#3329]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

[https://bitwave.tv/](https://bitwave.tv/) is a new live streaming website. It allows streamers to broadcast live video to an audience. Viewers have a chat room and the website has features to support the live streamers. The website supports replays of past videos. The website is similar to [twitch.tv](https://twitch.tv) and [dlive.tv](https://dlive.tv). This site brings a lot of value because it is in direct competition with the previous websites.

### Example stream URLs

1. [https://bitwave.tv/doomtube](https://bitwave.tv/doomtube)
2. ...
3. ...

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
There are currently only 94 overall viewers on this site, and I don't think these numbers are accurate and most of them are just the broadcasters themselves or bots / fake viewers to artificially increase the numbers in a "subtle" way.

Sites like these have been requested a dozen times here, and the response has always been that it's not worth the time implementing it, especially since the site will probably be offline in a couple of months anyway, just like all competitors of Twitch in the recent years.

**Comment by back-to** [comment]
> Thank you for helping ALPHA test [bitwave.tv] and I look forward to bringing more exciting features in the future. 

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

`9. ..., are in beta or are undergoing heavy amounts of development and may change rapidly`
