### ISSUE TITLE
plugin for http://yoda.az/

### ISSUE THREAD

**Issue by mike8032** [streamlink/streamlink#3334]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

this is an official page for channels from azerbaijcan. there is no plugin yet for this country on streamlink.

### Example stream URLs

http://yoda.az/

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by worldmediaman** [comment]
I also wanted to express the wish to be able to play these channels via Streamlink. Have seen that a request has already been made on this.

Explained again in a little more detail.

Azerbaycan channels can be watched via this page http://yoda.az. These are original livestreams.
the live streams can be played via the windows 10 web browser without geoblocking.

Example:
http://yoda.az/idmanlive/index.php

Unfortunately, Streamlink does not support it:

streamlink -l debug http://yoda.az/idmanlive/index.php
[cli] [debug] OS: Windows 10
[cli] [debug] Python: 3.8.6
[cli] [debug] Streamlink: 2.0.0
[cli] [debug] Requests (2.25.1), Socks (1.7.1), Websocket (0.57.0)
error: No plugin can handle URL: http://yoda.az/idmanlive/index.php

would be really great if this would be playable via streamlink

**Comment by mkbloke** [comment]
This looks like it should be simple enough.  As far as I can see, it meets all the plugin request guidelines except for the dreaded number 10...

Devs, please assign an appropriate label to this; if approved, I'll make a start on it shortly.

**Comment by gravyboat** [comment]
@mkbloke It doesn't meet requirements 3 or 6 either. There's a full blown schedule of TV shows on the left hand side of the page. The provided link for `idmanlive` is streaming a sports match from 2019. None of this is live.

**Comment by mkbloke** [comment]
@gravyboat, thanks for checking it out.  I was a bit confused about the programme listing on the left hand side - it appears you can go back, but not forward beyond live time.  That suggested to me that the TS data is kept on the CDN to allow for that, but it's still live.  Clicking CANLI, I think, takes you to live and from there the +5:00 button doesn't advance beyond current time in AZ.  It appears to me that it's live, but the web player allows for playing content broadcast at least a few hours before.

I might well be wrong on the above, of course, but that's how it looked to me.  Cheers.

**Comment by gravyboat** [comment]
@mkbloke The problem is that the content being played isn't live. It's pre-recorded content which is then scheduled to run at a specific time. Being able to play a show that aired earlier in the day is just TIVO. Since there's no actual live streamed content that is being directly broadcast to the internet as it occurs it doesn't meet the requirements. I know it's confusing because there are a few sites like this that are grandfathered in, but there are way too many of these sites which are just TV shows in a web player.

**Comment by mkbloke** [comment]
@gravyboat, thanks for the clarification.  I think I understand what you are saying about live vs pre-scheduled VODs.  Just out of interest, what is your technique for determining that?  Looking at this particular site and selecting a previous programme shows TS sequence number starting from zero, which to me indicates pre-scheduled VODs.  Are you looking at the same, or something else to determine pre-scheduled VODs?  Thanks.

**Comment by gravyboat** [comment]
@mkbloke I spend a few minutes watching various channels on the site to see if it's actually "live" content or just TV shows pushed in to a stream. There's been a lot of people asking for these sorts of sites recently where the content is not being streamed live to the audience. The best way to think about it is something like a Twitch stream (live and occurring right now) versus something like this (pre-recorded content being pushed out via a stream).

**Comment by mkbloke** [comment]
@gravyboat, sorry to push the point, but as we've started discussing this here...

Hmm, so maybe I misunderstood your previous comment.  By the last comment you've made, does that mean that the likes of bbciplayer; filmon and tvplayer are all considered to be grandfathered-in?  I mean, given that TV is live, but the content is mostly still pre-recorded, but pushed out to a live stream?

If that's the case, I'm certainly very glad those plugins are grandfathered-in, as they're the only plugins I use on a regular basis!

**Comment by gravyboat** [comment]
> By the last comment you've made, does that mean that the likes of bbciplayer; filmon and tvplayer are all considered to be grandfathered-in?

Correct because they existed prior to the implementation of the rule. If a plugin request was opened for them now we would close it as out of scope since they're not actual live streams.

**Comment by mkbloke** [comment]
Thanks for the clarification on "live", that certainly clears things up, mostly, except for perhaps news channels, which often feature both pre-recorded and truly "live" content, but I won't open that can of worms now!

I must say, I'm not sure if the "live" rule is a good thing for Streamlink.  I know you can just tell me to "fork off!", or to create a repo with other plugins, but I fear the current policy will see Streamlink relegated to supporting niche sites compared to those offering quality content that the masses will tend to favour.  Streamlink will still meet its stated objectives of providing a lighter video viewing experience without the need of a browser; it just won't be doing it for sites that are actually consumed by the larger population.

**Comment by gravyboat** [comment]
@mkbloke News channels still qualify since they're actually live, that's been discussed in the past.

> I fear the current policy will see Streamlink relegated to supporting niche sites compared to those offering quality content that the masses will tend to favour

What do you consider niche sites? Livestreamer was originally only designed for Twitch and grew from there before we forked it in to Streamlink. At this point we support most of the big live streaming websites and I would argue that people using Streamlink for stuff like Crunchyroll, Filmon, etc. fall in to the actual niche category. Based on issues when something goes wrong, Twitch is far and away the largest portion of usage. I can only speak for myself but I'm not too concerned about whether Streamlink has a large user base or not. Whether we have 50k+ users like right now or 1k it doesn't matter much to me. What does matter is keeping Streamlink running well (not adding tons of niche plugins) and keeping maintenance work down.

**Comment by mkbloke** [comment]
I'm just thinking more about the future.  You're right, there's no need to grow the user base.  There's little incentive for that, but from a contribution point of view, I think the live rule will forbid useful future plugins for sites such as national TV stations.  Those are (in my opinion) likely to get more use than some of the obscure plugins that meet the current live rule.

I see this conversation has been vaguely referred to in #3609, relating essentially to rule number 10, but a quick look also suggests that it doesn't meet the live rule either.  It all just seems a bit of a shame that good content can't be accessed by Streamlink plugins due to some of these rules.

As I said, above, I know the options.  It's your project and you can make the rules.  I choose to contribute because I use the plugins listed previously on a daily basis and it's nice to give back.  I'm lucky those plugins are grandfathered-in, but people wanting plugins for sites like the one is this plugin request or the request that has generated the discussion in #3609 aren't so lucky.

**Comment by worldmediaman** [comment]
> 
> 
> @mkbloke Das Problem ist, dass der abgespielte Inhalt nicht live ist. Es handelt sich um aufgezeichnete Inhalte, deren Ausführung zu einem bestimmten Zeitpunkt geplant ist. Eine Show spielen zu können, die früher am Tag ausgestrahlt wurde, ist nur TIVO. Da es keinen tatsächlichen Live-Streaming-Inhalt gibt, der direkt ins Internet übertragen wird, entspricht er nicht den Anforderungen. Ich weiß, dass es verwirrend ist, weil es einige Websites wie diese gibt, auf denen Großvater ist, aber es gibt viel zu viele dieser Websites, die nur TV-Shows in einem Web-Player sind.

sorry i mean this site http://www.aztv.az/canli/aztv-canli.htm

**Comment by gravyboat** [comment]
@worldmediaman That isn't live content either.

**Comment by gravyboat** [comment]
@mkbloke Your points are valid and I don't have a good solution. In the past we've discussed creating another repo for "extra" plugins to keep streamlink from getting bloated, but who's going to maintain it? I'm definitely not going to spend time reviewing plugins and requests when people are asking why their 1500 population town's TV stations or webcam of the beach is broken. It also creates even more confusion about the creation of issues which is already a major problem.

We already let people side load plugins so #3609 isn't really a concern to me as the user can still side load their own plugin. I'm really not trying to be a pain here I just don't want to spend even more unpaid time dealing with incomplete issues and requests than we already do. I'm open to ideas for solutions, but just merging every plugin is not acceptable.

**Comment by mkbloke** [comment]
Yeah, I know it's difficult and I do not have the answers either.  I think plugins reported broken should just be removed if they haven't been fixed in a period of say, 1 or 2 years.  Some of the paid subscription based plugins that are currently grandfathered-in could get removed that way.  I'm thinking btsports; ine (reported recently); schoolism and wwenetwork as examples that are all a massive pain to support without a subscription.  I'm considering creating a free trial account to fix the ine plugin this time around, but it's going to be a headache doing that every time it's reported broken.  It's the same for the wwenetwork.  I don't know if free trials are even possible for btsports or schoolism.  In any event, depending on their systems, you could run out of payment methods to use across different trial accounts if they demand it as part of the sign-up process and check for duplicate usage.

It could be worthwhile looking at the language used in rule number 6.  Until this thread, I was not interpreting it in the way it seems to be meant, which probably means other people will also do the same.

Cheers.

**Comment by worldmediaman** [comment]
> 
> 
> @worldmediaman Das ist auch kein Live-Inhalt.

But that's the live stream from the television station's website, I don't understand. what is a livestream for you? this is the page http://www.aztv.az/az
if you press canli here you will be redirected to the other side. canli means live

**Comment by gravyboat** [comment]
> I don't understand. what is a livestream for you?

@worldmediaman It's live, here's the dictionary definition: `(of a broadcast) transmitted at the time of occurrence, not from a recording.`. I have looked at your link multiple times, it's not live, it's prerecorded content being played over the internet set up to run in a schedule. It's no different than a Youtube playlist or TV. You don't sit down and watch a TV show and think "boy this is some good live content!" because it's not. The show was prerecorded and then broadcast.

**Comment by mike8032** [comment]
because i opened this request, let me show you in short what "thiking errors" you guys are making.

1. live tv channels are channels wich are broadcasted by companies over the normal broadcasting technologies and now new over the internet (not realy new coz it is arround since there was the "realplayer").
2. anything which is not news, a live entertainment show or live sports is not live over normal broadcast technologies.
3. all not live and live content are mixed together labeled as a channel, for exmaple "cbs". and yes even the comercials are not live.
i undrestand it is a generational problem to understand live tv, but for sure live tv is not "netflix".
i recomend using this parameter for determining if a channel is live or not:
if the channel is listed in any satellit broadcasting, dvb-t broadcasting, isdb-t broadcasting or dvb-c broadcasting or any other common "old" tv technology than it is a live tv channel.
if it is not listed, than it is just a web tv channel which is based on pre-scheduled vod content.
