### ISSUE TITLE
Uncloseable Python Box

### ISSUE THREAD

**Issue by Cryptic-Soldier** [streamlink/streamlink#3339]
## Issue - Uncloseable Python Box

- [X] This is not a bug report, feature request, or plugin issue/request.
- [X] I have read the contribution guidelines.

### Description

I have done a clean install of Streamlink, Streamlink GUI, and VLC, due to getting a new harddrive. On my prior install everything was working as intended with no issues. Now, when I open a stream, I get an uncloseable python box. If I close the python box it closes the stream.

**Versions of software I'm using:**
-     Streamlink: 1.7.0 (latest at the time of posting)
-     Streamlink GUI: 1.10.0 (latest at the time of posting)
-     VLC: 3.0.11 (latest at the time of posting)

### Reproduction steps / Explicit stream URLs to test

I think it might be an issue on my end with a setting or config file, but I'm not sure where to look or how to fix it. Googling, it seems I'm the only one with this issue so far.

Here is an image of the Python box that opens when I open streams: https://i.imgur.com/ZMVM2Cy.png

**Comment by bastimeyer** [comment]
> python.exe

If you're a Windows user and you don't want to see a terminal window being opened while running Streamlink from a "non-terminal environment", then you're supposed to start Streamlink via `streamlinkw.exe` (notice the `w` suffix). This is a wrapper for `pythonw.exe`, something Windows specific for Python, which doesn't automatically open a terminal window. Streamlink on Windows comes with two separate executables specifically for that, `streamlink` and `streamlinkw`:
https://github.com/streamlink/streamlink/blob/d0b6598e073c755a2d38470a832e3622ac41f10f/setup.py#L58-L63

As a Twitch GUI user, you don't have to set any custom paths if you've installed Streamlink into its default install directory of if it can be found in your system's PATH environment variable, which is automatically managed by the Streamlink installer for Windows. Otherwise, the Twitch GUI will tell you in its placeholder text when choosing a custom Streamlink path that you'll have to select `streamlinkw.exe`.
