### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by ruben3443** [streamlink/streamlink#3343]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I have been getting this error since yesterday when I try to download a stream from Twitch, but I don´t find a solution. I'm using linux and I've created a simple bash script to check one channel every few minutes, and if this channel is on stream, it will start to download. It have worked for over a month now but it began to crash yesterday, and I'm having this issue just launching streamlink with the next command too.

### Reproduction steps / Explicit stream URLs to test

1. streamlink twitch.tv/<STREAM_CHANNEL> best -o "asdf.mp4" --twitch-oauth-token=<TOKEN_HERE>

### Log output

```
[cli][info] Found matching plugin twitch for URL twitch.tv/<STREAM_CHANNEL>
[plugin.twitch][info] Attempting to authenticate using OAuth token
error: Unable to open URL: https://api.twitch.tv/kraken/user.json (404 Client Error: Not Found for url: https://api.twitch.tv/kraken/user.json?as3=t&oauth_token=<TOKEN_HERE>)
```

**Comment by gravyboat** [comment]
Rerun your command as `streamlink -l debug twitch.tv/<STREAM_CHANNEL> best -o "asdf.mp4" --twitch-oauth-token=<TOKEN_HERE>`

We can't do anything without debug information. Are you on an old version of Streamlink? If so you need to upgrade.

**Comment by bastimeyer** [comment]
> OAuth token

You are not using the latest version. Authentication with Twitch is not supported anymore since several releases and by not using the latest version, the API calls which are made by Streamlink are not supported anymore by Twitch, hence your issues.

- https://github.com/streamlink/streamlink/blame/master/CHANGELOG.md#L464
- https://github.com/streamlink/streamlink/blame/master/CHANGELOG.md#L271

**Comment by bastimeyer** [comment]
Just to clarify, these API issues have nothing to do with the OAuth authentication. The OAuth stuff is just an indicator that you're using an older and unsupported Streamlink version, apart from the fact that 3rd party authentication doesn't work anymore on those old private API endpoints, which is the reason why we had to remove Twitch authentication from Streamlink last year.

What has been changed recently is how the Twitch API is being accessed. This was done in #3227 in a major Twitch plugin overhaul, which is part of the latest Streamlink release (currently 1.7.0). The reason why you're seeing those issues with older versions is that Twitch now seems to have removed support for the old API request methods, as they were already deprecated for several years.

This means you'll have to use Streamlink 1.7.0+.
https://streamlink.github.io/install.html

**Comment by ruben3443** [comment]
Thank you so much for your comments!

I was wondering why I had to use the token on Linux but not on Windows. I didn't realise I was using the 1.0.0 version, I thought it was the last version since I installed and upgraded the package with "apt", but I think this package is not actualiced on Linux.

I installed the new version (1.7.0) with pip3, like is said on the installation documentation, and now it is working.

**Comment by SharienRadaik** [comment]
Just a quick question related to this topic - is there any other authentication option available?
And if not, do you expect that one will become available at some point?
Im kind of expecting both of those to be no's, given twitches attitude towards 3rd party tools... but i would like to make sure im not missing something.

**Comment by bastimeyer** [comment]
No, it's not possible and especially not with the recent switch to their private GQL API.
- https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851
- https://github.com/streamlink/streamlink/pull/3344#issue-523498487

As I've explained plenty of times now in these posts and other ones in related threads, the only way is using an OAuth token which was generated by their website and not 3rd party applications. We don't however support this, because it doesn't make sense for an application linke Streamlink to ask the user to read the OAuth token from their web browser's dev tools, and we certainly won't write a browser extension/addon for this.

If you want to add your own OAuth token to the API requests, you are free to do so, just don't ask for support here.

**Comment by SharienRadaik** [comment]
Alright thanks - that was all i wanted to know. Thanks for all your work.

**Comment by Hebo** [comment]
@SharienRadaik If you're looking to use your Twitch OAuth token (generated by the website), you can use [this patch](https://github.com/Hebo/streamlink/commit/d89cb91a49a61f966ab72de3386a0354a8b48a1b).

Then call it with `streamlink --twitch-private-oauth-token=yourprivatetokenfromthewebsite`

It'd be nice if there was a more sanctioned way to do it, as users with Twitch Turbo or a channel sub would probably find it preferable to using the current `--twitch-disable-ads` behavior, which pauses content.

**Comment by SharienRadaik** [comment]
Also thanks for that Hebo - after some trial and error i already figured out the correct config file property and usage to just add the token as the Authorization header.
http-header Authorization=OAuth <your token>
or 
--http-header Authorization="OAuth <your token>"
if its a commandline option
Also tried it as Bearer rather than OAuth since the twitch API considers that deprecated(even though the website uses it), but the token i had only works as OAuth - i probably would need to extract a Bearer token elsewhere, but it should work the same way if you have one of those.

**Comment by Hebo** [comment]
Awesome! Much cleaner than my solution and no need to maintain a fork.
