### ISSUE TITLE
Change `author_email` in setup.py

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3392]
https://github.com/streamlink/streamlink/blob/08e582580f3411b2de2c368f8b0cc7108264f990/setup.py#L83

@gravyboat 
you've registered `streamlink@protonmail.com` a couple of years ago, right? Can this be used instead?

What's the email address of the `streamlink` account on pypi?
https://pypi.org/user/streamlink/

**Comment by gravyboat** [comment]
@bastimeyer Yes `streamlink@protonmail.com` is registered and can be used. I believe @beardypig also has access to this address. I thought I sent you the password as well but maybe not?

For the `streamlink` repo on pypi there is a `streamlink` user that has the same protonmail address, but that user doesn't have direct manage access to the pypi project since it's shared, they're just a maintainer. It was created by @beardypig. Cdrage and I both have owner access. We should get you added on there as well.

**Comment by bastimeyer** [comment]
> can be used

Open a PR then.

> I thought I sent you the password as well but maybe not?

No, I don't have access to any Streamlink accounts.

> We should get you added on there as well.

Not really important. I've created an acc today though, so if you want to add me, you can.

**Comment by gravyboat** [comment]
> No, I don't have access to any Streamlink accounts.

What's your preferred method to have the credentials shared?
