### ISSUE TITLE
Tango Live Come please, we are waiting for the plug-in

### ISSUE THREAD

**Issue by vivolivebook** [streamlink/streamlink#3447]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description
This title was opened once more during the day, but the person who opened it said it in a ridiculous way, people got it wrong, I was impatiently waiting for the issue to end. 

https://www.tango.me So Tango live here is a completely free program where broadcasters broadcast and people watch and chat, like bigo and mico live, which is exactly the same with bigo and mico live. If Bigo Live meets the requirements to  plugins here, Tango Live should also meet because the applications are almost the same.Pornographic content is banned in Tango Live, just like in Bigo and there is no membership fee.

### Example stream URLs

1. ...https://www.tango.me
2...https://www.tango.me/stream/A6a_CPlrwSBWQOElE71B6A
3. ...

### Additional comments, etc.
I am actively using the Bigo plug-in to get the broadcasts I made as images. Now I started broadcasting in tango live. I was looking for it. I saw the funny title here. I decided, I hope this will happen. You will make us happy. Do not break people who want it. If bigo came, tango should come live.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This request was already closed per the comment here: https://github.com/streamlink/streamlink/issues/3441#issuecomment-751290406

Just because it's like a plugin that already exists doesn't mean we'll add a new plugin. The rules are constantly updated to keep the code maintainable and reasonable. If you think bigo should be removed then open an issue and we'll discuss it. Otherwise you're free to write a plugin yourself and side load it.
