### ISSUE TITLE
Arch linux pacman version (1.7.0-2) is behind the main release (2.0.0-1)

### ISSUE THREAD

**Issue by casey-c** [streamlink/streamlink#3489]
Apologies if this isn't the best place for this, but I believe there might be an issue with the latest arch linux package. From the main package repository: 

https://archlinux.org/packages/community/any/streamlink/

It seems like it should be up to date to v2.0.0-1. Yet when inside a terminal, attempting to install streamlink

``` 
sudo pacman -S streamlink 
```

reports back that it actually installs an older version of the project. Searching for the streamlink package through a terminal:

``` 
sudo pacman -Ss streamlink 
```
shows the issue (similarly, installing streamlink and running --version on it reports back 1.7.0)

```
community/streamlink 1.7.0-2 [installed]
    CLI program that launches streams from various streaming services in a custom video player
    (livestreamer fork)
```

My (manjaro-i3) system is fully up to date and should have the latest database information (i.e. pacman -Syu reports back "there is nothing to do"). This lead me to the conclusion that there may be a small bug or human error in the latest arch linux package that results in installing an older version even though the website claims to be on 2.0.0.

**Comment by bastimeyer** [comment]
Packages are not maintained by the Streamlink devs. If your package is out of date, then contact the responsible package maintainer(s).

As you have already posted yourself, the Arch Linux package is on `2.0.0` (and it has been updated on the same day as Streamlink's `2.0.0` release). However, if your derivate distro is lagging behind, then that's neither a problem of Streamlink nor the original package maintainer and you need to contact your own disto's package maintainer(s).

Another possible reason on pacman-based distros is that your local mirrorlist could be outdated. Make sure that it's up2date, so that you receive the correct package database.

Other than that, you could try the `streamlink-git` PKGBUILD from the AUR, or install Streamlink via pip:
https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

**Comment by casey-c** [comment]
Thank you for the information! I will do a bit more research into those suggestions - I'm sorry I posted this here.
