### ISSUE TITLE
KeyError - Documentation - No "source" key in streams object "best" available

### ISSUE THREAD

**Issue by Kaszanas** [streamlink/streamlink#3550]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

It seems that the documentation mentions a "source" object as something that ought to be returned by using the following code:
```
streams = streamlink.streams(twitch_url)
stream_quality_source = streams["source"]
```

this returns a ```KeyError``` but it seems that the object is containing a key that is not ```source``` but ```best``` and this might be used to access the best possible quality of the stream.

**Comment by bastimeyer** [comment]
"source" is the name of the resolved stream in the returned `streams` dict, nothing more. The name depends on the input and what the matching plugin does with it.

Since you're referring to an input from Twitch, before 2017 or so, Twitch had named its stream qualities "low", "medium", "high" and "source". This is where this "source" example is coming from. It doesn't matter though, as it's just an example. The documentation simply hasn't been updated since then. And even if it was updated with a new example from Twitch, since Twitch is using dynamic quality names now, this wouldn't help with your question, as the example would more often than not be wrong.

- https://streamlink.github.io/api.html#streamlink.Streamlink.streams
- https://streamlink.github.io/api.html#streamlink.plugin.Plugin.streams
- https://streamlink.github.io/api_guide.html#extracting-streams

**Comment by Kaszanas** [comment]
@bastimeyer In case of multiple different Twitch and YouTube streams this never resulted in ```source``` but with the respective mentioned synonym ```best``` that is also in documentation but not mentioned in the example.

**Comment by bastimeyer** [comment]
> this never resulted in `source`

Yes, **because `source` is an example** of an old and explicit (non-synonym) stream quality name on Twitch. It is referring to the example streams dict mentioned in the section above. The docs simply haven't been updated after Twitch changed their stream name format. But as said, it's not important, because there is no uniform naming scheme and it depends on what is returned by the plugin / streaming platform.
- https://github.com/streamlink/streamlink/blame/da0bfe9353d95170762aebe52a7c15568caf2536/docs/api_guide.rst#L27-L33
- https://github.com/streamlink/streamlink/blame/176046d1e79fef315986668ebf57a936980028e9/docs/api_guide.rst#L27-L33

To help you with your confusion about the name `source`, nowadays a Twitch channel's input-stream (non-re-encoded-stream) is labeled as `1080p60` (actually `1080p60 (source)`, but it gets cut off by Streamlink) instead of just `source`, as this is what Twitch allows as the highest stream resolution. Like I've said, this was changed on Twitch in 2017 or so. **The Twitch plugin simply yields the stream names provided by Twitch**, which are part of the HLS master playlist.

> but with the respective mentioned synonym best

`best`, `worst`, `best-unfiltered` and `worst-unfiltered` are synonyms created by `Plugin.streams()`, so that the user doesn't have to explicitly specify the stream name. The example you're talking about simply doesn't use these synonyms.

- https://github.com/streamlink/streamlink/blob/da0bfe9353d95170762aebe52a7c15568caf2536/src/streamlink/plugin/plugin.py#L280-L410
- https://github.com/streamlink/streamlink/blob/da0bfe9353d95170762aebe52a7c15568caf2536/src/streamlink/stream/hls.py#L445-L578

**Comment by Kaszanas** [comment]
@bastimeyer I agree, but as the example is provided within the official streamlink documentation it should either be updated or include logic that would check for different synonyms if the key does not exist in a returned quality dict.

```
if "source" in quality_dict:
    # Use source
else:
    # Use different quality 
```

**Comment by bastimeyer** [comment]
> it should either be updated

Open a pull request if you think this should be updated.

> or include logic that would check for different synonyms if the key does not exist in a returned quality dict

Stream name synonyms are "best" and "worst", not "source" or any other explicit stream name. As I've said multiple times now, "source" is just an example of one of the streams in the example dict. The docs say this

> [Now that you have extracted some streams we might want to read some data **from one of them**](https://streamlink.github.io/api_guide.html#opening-streams-to-read-data)

which means it doesn't really matter which one is choosen here. The docs could choose one of the stream synonyms, but that would not be the point here. If the docs were showing a streams dict from a different site/plugin, then the stream names would all be different anyway, which means it is irrelevant if the example shows outdated data from Twitch.
