### ISSUE TITLE
Streamlink is not recognizing --https-proxy on M1 CPUs

### ISSUE THREAD

**Issue by StevensNJD4** [streamlink/streamlink#3622]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.
- [x ] I am using the latest development version from the master branch.

### Description

Users running my app on M1 CPUs are reporting the --https-proxy argument is not working. Streamlink is not tunneling requests through the specified proxy. It works fine on conventional CPUs.

### Expected / Actual behavior

I expect the requests to be tunneled through the specified proxy.

### Reproduction steps / Explicit stream URLs to test

0. Get a M1 Mac
1. Use something like MITMProxy
2. Open any stream with the --https-proxy pointing to the proxy 
3. Notice no requests are hitting the proxy 

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
All log output should go between two blocks of triple backticks (grave accents) for proper formatting.
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by StevensNJD4** [comment]
@betagan what did i do wrong?

**Comment by beardypig** [comment]
@StevensNJD4 can you provide a log output? It includes useful information that will help us debug the issue. It is pretty unlikely that any of the core contributors (who are most likely to help with this) have access to an M1 machine to test it and will rely on you to answer queries.

**Comment by bastimeyer** [comment]
> Users running my app on M1 CPUs are reporting

Post the **debug log** output **and** the **exact parameters** you were using, otherwise this kind of bug report is meaningless / uselss.

Either way, anything http related is handled by [python-requests](https://github.com/psf/requests) and not Streamlink itself, which means that if there's indeed an issue on a different CPU architecture for whatever reason, then it's an upstream issue.

This is all that Streamlink does to set up the proxy config for python-requests:

1. https://github.com/streamlink/streamlink/blob/10470c3586d28de83ac59aa2b97568778635376f/src/streamlink_cli/main.py#L702-L706
2. https://github.com/streamlink/streamlink/blob/10470c3586d28de83ac59aa2b97568778635376f/src/streamlink/session.py#L279-L285
3. https://github.com/streamlink/streamlink/blob/10470c3586d28de83ac59aa2b97568778635376f/src/streamlink/plugin/api/http_session.py#L126-L131

----

Python-requests docs:

- https://requests.readthedocs.io/en/v2.9.1/user/advanced/#proxies
- https://requests.readthedocs.io/en/v2.9.1/api/#requests.Session.proxies
