### ISSUE TITLE
plugins.[pixiv]: [create_cookie() missing 1 required positional argument: 'name']

### ISSUE THREAD

**Issue by willieh2x** [streamlink/streamlink#3652]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Can't streamlink from sketch.pixiv.net (both SFW and NSFW, with or without cookies for SFW)

### Reproduction steps / Explicit stream URLs to test

1. I use Python 3.9.2
2. Streamlink 2.1.1
3. Get sessionid and devicetoken from firefox

### Log output

```
C:\Users\Administrator>streamlink --loglevel debug https://sketch.pixiv.net/@*********/lives/ best --pixiv-purge-credentials --pixiv-sessionid ********* --pixiv-devicetoken *********
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\streamlink.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\streamlink_cli\main.py", line 1041, in main
    setup_config_args(parser)
  File "c:\python39\lib\site-packages\streamlink_cli\main.py", line 659, in setup_config_args
    plugin = streamlink.resolve_url(args.url)
  File "c:\python39\lib\site-packages\streamlink\session.py", line 397, in resolve_url
    return available_plugins[0](url)
  File "c:\python39\lib\site-packages\streamlink\plugins\pixiv.py", line 90, in __init__
    super().__init__(url)
  File "c:\python39\lib\site-packages\streamlink\plugin\plugin.py", line 217, in __init__
    self.load_cookies()
  File "c:\python39\lib\site-packages\streamlink\plugin\plugin.py", line 476, in load_cookies
    cookie = requests.cookies.create_cookie(**value)
TypeError: create_cookie() missing 1 required positional argument: 'name'
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
use `-l debug` and `--pixiv-purge-credentials`

**Comment by willieh2x** [comment]
wow Thanks a lot
streamlink working after deleting plugin-cache.json

**Comment by mythoRim** [comment]
@back-to I also had a similar problem and was looking for the plugin-cache.json that @willieh2x  found. The difference is that instead of firefox, I'm using Google Chrome for the sessionID and devicetoken and it ended with:

**File "C:\Program Files (x86)\Streamlink\pkgs\requests\cookies.py", line 466, in create_cookie
    raise TypeError(err % list(badargs))
TypeError: create_cookie() got unexpected keyword arguments: ['securere']**  

instead of: 
**TypeError: create_cookie() missing 1 required positional argument: 'name'**

I did try some stuff like removing my antivirus, adblock and cleared my browsing in 'all time' for site settings, cookies, history. This just happened last night and working the whole night trying to figure it out. I do use the same setting on my laptop but with a different session id and device token and it worked, just can't figure out why my desktop stopped right when it became midnight.

This is what I wrote (which should work on my desktop as it did work on my laptop): 
**streamlink https://sketch.pixiv.net/*******/lives best --output output/PixivStream-Streamlink-******.mkv --pixiv-sessionid ****** --pixiv-devicetoken ********* --force --pixiv-purge-credentials**

![image](https://user-images.githubusercontent.com/78310879/130326815-ab3e8a5c-8382-4465-9ae6-1d0778de33ef.png)

**Comment by back-to** [comment]
@mythoRim 
> was looking for the plugin-cache.json

the file is in `%APPDATA%\streamlink` or `C:\Users\USERNAME\AppData\Roaming\streamlink`

**Comment by mythoRim** [comment]
@back-to 

THANK YOU! You are a sleep saver! It's now working.
