### ISSUE TITLE
Tiktok live

### ISSUE THREAD

**Issue by l5503077** [streamlink/streamlink#3705]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Tiktok, live streams

### Example stream URLs

1. https://www.tiktok.com/@esmanurcelikel/live?lang=en
2. ...
3. ...

### Additional Info

https://github.com/Zipdox/tiktok-download-userscript

https://github.com/UnCrevard/tiktok-live

**Comment by ChristophKrause** [comment]
From my opinion Tiktok changed a lot since december 2020. I guess that all scripts and tools, Which have not been changed since then do not work.

In december 2020 it was relatively easy to get the livestream url to stream it with streamlink. 
At the moment it is easy to get the live page from a user, but I dont see a way to get the stream url; which makes me wonder.

**Comment by NeftaliYagua** [comment]
Tiktok is ready for staging, please check it.

https://raw.githubusercontent.com/NeftaliYagua/streamlink/tiktok-plugin/src/streamlink/plugins/tiktok.py
