### ISSUE TITLE
Curiositystream Plugin Request

### ISSUE THREAD

**Issue by deep0d0** [streamlink/streamlink#3716]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [X] I am using the latest development version from the master branch.

### Description

Curiositystream is a documentary platform with amazing content. I want to be able to download the documentaries for offline viewing, and it would benefit other users of this platform as well. Other sites, such as Crunchyroll have already been added, so this is really no different from that

### Additional comments, etc.
I have complimentary access through my ISP, which is no different than a paid subscription. I can provide my account for testing if needed.'

[YoutubeDL ](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/curiositystream.py )has this functionality, however, it would be nice to have that in Streamlink

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://raw.githubusercontent.com/streamlink/streamlink/master/.github/ISSUE_TEMPLATE/1_plugin_request.md

**Comment by gravyboat** [comment]
This isn't a live service and it violates rule 6: `Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted` so I'm going to close this now. Crunchyroll and several other sites are legacy exceptions due to being in place prior to implementing these rules. Feel free to create a plugin and [sideload](https://streamlink.github.io/cli.html?highlight=side%20load#sideloading-plugins) if you would like.
