### ISSUE TITLE
Feature: default quality setting

### ISSUE THREAD

**Issue by Decagon** [streamlink/streamlink#372]
When I do,

```
streamlink http://twitch.tv/day9tv
[cli][info] Found matching plugin twitch for URL twitch.tv/day9tv
Available streams: audio, high, low, medium, mobile (worst), source (best)
```

I was initially confused as to why it wasn't working (streamlink just exited.) I suggest to add a default quality (e.g. medium) so that you can just type the url without a quality setting and see the stream.

**Comment by Brainzyy** [comment]
@Decagon The thing is, not all Twitch streams have the quality "medium". Some twitch streams have qualities like "240p" and "480p" and so on.

**Comment by gravyboat** [comment]
As @Brainzyy we need to allow users to select this value because there are many different quality settings available that are dependent on the stream. There are several options in scenarios like this. The first is to modify the main configuration file as noted here in the docs: https://streamlink.github.io/cli.html#configuration-file to set values, or you can set values for a specific plugin here: https://streamlink.github.io/cli.html#plugin-specific-configuration-file. There are also open source projects such as https://github.com/streamlink/streamlink-twitch-gui and https://github.com/gravyboat/streamlink-powershell (and I'm sure other people have written their own wrappers) which allow you to set the default quality of a stream. I'm going to close this for now since we do offer this feature.
