### ISSUE TITLE
Move Twitch plugin to use Twitch API V5

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#377]
Moving discussion from https://github.com/streamlink/streamlink/issues/20 to here as there is a patch applied for V3, but we should stay ahead of the game by moving directly to V5.

**Comment by thinkpad4** [comment]
I would say this should be fast tracked, just incase Twitch pushes v5 early

**Comment by gravyboat** [comment]
It's already been updated to v3 so we should be okay for a bit.

**Comment by stevek123** [comment]
V3 is scheduled to be deprecated (2017) and removed altogether (Feb. 13, 2018)

**Comment by thinkpad4** [comment]
All the more reason to start testing V5 to be the default API streamlink uses for twitch and keep V3 as a fallback until it is removed

**Comment by beardypig** [comment]
Looks like v5 changes the `channels` api endpoints and all requests require the channel ID, instead of the channel shortname/username as in v3. It seems like the best way to do this is to use the channel search api and find the channel with the matching name. 

Most of the API calls made by the plugin are actually to the private `/api` prefix, which hasn't changed on the site. If they are upgraded their public API it's probably safe to assume that they will update their private API soon as well. But moving to use the v5 public API won't change that :)

**Comment by beardypig** [comment]
The move to v5 API was done as part of #484.

**Comment by stevek123** [comment]
On a side note @beardypig: Do you think it would be possible to echo the node that is being used to the command line? It's part of the m3u8 file, and the same as the stream server domain.

**Comment by beardypig** [comment]
The cluster ID? Like `lhr03`?

**Comment by stevek123** [comment]
Yeah, or the whole node part like `video-edge-835028.sfo01`. Sometimes it takes a while for a stream to populate to a closer node, and it would be nice to see which one is used when you start the stream

**Comment by beardypig** [comment]
Can add it as a debug message, printing it all the time is probably not useful to most people.

**Comment by stevek123** [comment]
Yeah, it can be hidden, but it would be nice to have. Would it be possible to turn it on with a command line parameter instead of turning on the whole debugging? Debugging level generates a lot of log, but something like `--twitch-server` could only output this info as a plus if it's added to the command

**Comment by stevek123** [comment]
Should I open a new issue if I want this to get implemented?

**Comment by beardypig** [comment]
@stevek123, yeah. I don't really want to add an extra command line argument for something like that though. Maybe an info level message is suitable, not sure...
