### ISSUE TITLE
Streams kept buffering and ending on VLC for no reason

### ISSUE THREAD

**Issue by S54656** [streamlink/streamlink#3834]
## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Most of the streams I'm trying to watch through VLC kept lagging and closing for no reason, and this isn't just with the plugin, but also in the Twitch GUI.

### Expected / Actual behavior

I expect the streams to play normally in VLC. But they've been lagging a lot and then they stopped playing and ended, and it's very annoying to no end.

### Reproduction steps / Explicit stream URLs to test

1. It happens with every stream.
2. It happens with every stream.
3. It happens with every stream.

### Log output

```
It happens with every stream.
```

### Additional comments, etc.

It is the software itself, or internet connection issues? I want to know.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
You've already opened #3833 and instead of amending your previous post, you're still ignoring the issue templates while not providing any useful informations AT ALL. This is a waste of time for everyone reading this and nobody will be able to help you. Just saying "my streams lag" is not sufficient.

This is not a Streamlink "bug" and instead an issue with your system and its configuration which could have thousands of different reasons. We don't even know which operating system you're using, which Streamlink version you have installed and whether this is a network issue or a rendering issue in your VLC player.

**Read the issue template and provide ALL the required informations**. Since you're saying that this is happening with every stream, then you surely won't have any issues posting a proper debug log.

**Comment by S54656** [comment]
> 
> 
> You've already opened #3833 and instead of amending your previous post, you're still ignoring the issue templates while not providing any useful informations AT ALL. This is a waste of time for everyone reading this and nobody will be able to help you. Just saying "my streams lag" is not sufficient.
> 
> This is not a Streamlink "bug" and instead an issue with your system and its configuration which could have thousands of different reasons. We don't even know which operating system you're using, which Streamlink version you have installed and whether this is a network issue or a rendering issue in your VLC player.
> 
> **Read the issue template and provide ALL the required informations**. Since you're saying that this is happening with every stream, then you surely won't have any issues posting a proper debug log.

Seriously, THIS HAS BEEN GOING ON SINCE DECEMBER, and IT'S GETTING ON MY NERVES. I can't TAKE it anymore, and you HAVE to help me, for God's sakes.
