### ISSUE TITLE
YouTube live stream not detected from channel page

### ISSUE THREAD

**Issue by viannaricardo** [streamlink/streamlink#3846]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Streamlink doesn't detect a YouTube live stream when you put in channel home page as parameter. Tested with several YT channels. If I input direct video link works, but detecting that video from the channel page shows a no plugin error

### Expected / Actual behavior

Streamlink should find an ID of the live stream and start downloading/streaming it. Instead, no plugin error is shown.

### Reproduction steps / Explicit stream URLs to test

Find a YouTube channel that has a live stream
Input: streamlink https://www.youtube.com/c/xxxxxx
Output: error: No plugin can handle URL

### Log output

```
streamlink --loglevel debug https://www.youtube.com/c/xxxxxxx
[cli][debug] OS:         Linux-5.4.0-72-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.2.0
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/c/xxxxxxx
[cli][debug]  --loglevel=debug
error: No plugin can handle URL: https://www.youtube.com/c/xxxxxxx
```

**Comment by bastimeyer** [comment]
See https://github.com/streamlink/streamlink/pull/3797#issuecomment-864443385

Finding a live stream from a channel page is not possible anymore with the removal of the old private API in #3797, even with the fallback API quests added in #3809.

You have to add the `/live` suffix to the URL, otherwise the URL won't match the Youtube plugin, which was an intentional change due to that.

However, as I mentioned in #3797, a URL translation could be added which redirects to `/live` automatically. That is all that can be done. Let me prepare a PR...
