### ISSUE TITLE
Simple but very useful command needed when fail/error happens

### ISSUE THREAD

**Issue by Jeffade1** [streamlink/streamlink#3861]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hi. I'm one of those who're using Streamlink with batch to record 24/24 7/7 live streams and not lost any second.
Streamlink doing overall a great job but there is one problem, when an error/fail happens.
In those moments of 403, 404, 492, etc errors, it can take some times and/or multiples retries before the stream ends/closes. At that moment the batch files can finally reinitialize the stream but it took too long and there is some moments lost. In the worst cases, when the error is infinite, if afk then the stream will not be restarted...
I did some tests and tried to play with commands that Streamlink already offer like the reload/attempts/timeout variants but it doesn't do the job properly or there will always be an exception that will make the thing not work.
A simple command could fix all this, something like "--close-on-error" to indicate to Streamlink to stop when error/fail happens.

"--close-on-error 1" Close on first error.
"--close-on-error 2" Close on two consecutive errors.

After various searches I've seen people were interested by things in that spirit but it was mostly to indicate to streamlink to do the whole job and reload the playlist. @back-to worked on something a bit similar some years ago but in the end it seems that it has not been integrated.
Since Streamlink is used with batch that are doing the whole operations and parameters, it doesn't need to do anything more than just close when the error happens. If that command can be integrated it would be greatly appreciated because it became a real need lately with some streams. 👍👍

**Comment by bastimeyer** [comment]
Streamlink will always retry failed segment downloads in segmented HTTP streams (eg. HLS or DASH) when a 4xx/5xx error occurs, unless the retry value is set to 0. The delay between retries can't be changed via the CLI and it increases exponentially (`0.3 * 2^n`) with a maximum of 10 seconds. In addition to that, there's also a timeout value for segment requests when the server takes too long to respond.

So if you don't want Streamlink to re-attempt downloading segments and instead exit immediately, then you'll have to disable segment retry attempts and optionally also reduce the segment timeout value.

The generic CLI argument for segment retries is [`--stream-segment-attempts`](https://streamlink.github.io/cli.html#cmdoption-stream-segment-attempts), but this gets overridden by [`--hls-segment-attempts`](https://streamlink.github.io/cli.html#cmdoption-hls-segment-attempts) for HLS streams (not sure why this was implemented). Both argument values default to `3`, which means in order to disable the retry-behavior as a whole, you'll have to set both to `0`, as the value of the generic argument gets used if the HLS one is set to `0` due to a simple `if not value` statement.

Same thing for the timeout value. See the docs.

----

- `HTTPSession.request()`:  
  https://github.com/streamlink/streamlink/blob/5b0687224fe9d44cd7c433c06e58d142bea8e8fa/src/streamlink/plugin/api/http_session.py#L128-L178
- `HLSStreamWriter.fetch()`:  
  https://github.com/streamlink/streamlink/blob/d04767fa5b812a4e971e454226cecb25b4d975ae/src/streamlink/stream/hls.py#L150-L157
- `HLSStreamWriter.__init__()`:  
  https://github.com/streamlink/streamlink/blob/d04767fa5b812a4e971e454226cecb25b4d975ae/src/streamlink/stream/hls.py#L35-L39
- `SegmentedStreamWriter.__init__()`:  
  https://github.com/streamlink/streamlink/blob/d04767fa5b812a4e971e454226cecb25b4d975ae/src/streamlink/stream/segmented.py#L107-L117
- `Session.options`:  
  https://github.com/streamlink/streamlink/blob/d04767fa5b812a4e971e454226cecb25b4d975ae/src/streamlink/session.py#L37-L77
