### ISSUE TITLE
pandalive.co.kr (not to be confused with panda.tv)

### ISSUE THREAD

**Issue by chorong761** [streamlink/streamlink#3866]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Pandalive is a Korean live streaming site similar to afreecatv. Previous tickets were closed with "more info required" but was never explained why ticket was rejected. 

It has the same name as the panda.tv which is a closed down china site, which in the old ticket others have confused with.

If this ticket gets closed, I hope there would at least be a reason/explanation on why it might be it (like in the previous closed ticket, what exactly is "does not meet requirements"? Seeing that thee list has many possible reasons the plugin might not be added but was never mentioned in the closed ticket.

Thanks

### Input URLs

https://www.pandalive.co.kr/

**Comment by Trung0246** [comment]
Hi, I managed to grab the stream url from the site (apparently the site uses WebSocket to get the stream url)

Demo: https://replit.com/@Trung0246/BowedImperfectZettabyte#main.py
Gist: https://gist.github.com/Trung0246/1cd4a385498c462f4e8c5607aa916151

Any idea?

**Comment by mkbloke** [comment]
The reason past requests for this plugin have been closed is because they have not sufficiently met the requirements as set out in the first paragraph of the plugin request advice detailed at: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

Also, plugin requests will only be considered if the sites meet the 11 requirements also set out there.

I'm unsure what the viewership numbers are for the live streams on the site.  There's a person icon with a number next to it in the range of ~10 to ~40, which could be the current number of viewers?  There's also a bit on the stream page itself which translates to `cumulative` in English with a number next to it in the hundreds of thousands.  I'm not sure what that is, it's probably not a great translation (total number of views for the channel?).

I can't tell you what viewership figures might justify a plugin addition to Streamlink, as it's up to the maintainers and there seems to be no quotable magic figure that I'm aware of.

> Apparently there's password protected stream

When you say `password protected`, do you mean that would require an account and to be signed in to the website?  Do these streams require any form of monetary subscription to view?  If so, they are unlikely to be supported because they are difficult to maintain.

**Comment by Trung0246** [comment]
> When you say `password protected`, do you mean that would require an account and to be signed in to the website? Do these streams require any form of monetary subscription to view? If so, they are unlikely to be supported because they are difficult to maintain.

I'm not really which type of password protected stream but by looking at the js code it's seems like you don't even needs to login and only needs the password that are associated with the stream. Needs more investigation of course.
