### ISSUE TITLE
plugins.twitch: Use "thunderdome" player to replace ads segments

### ISSUE THREAD

**Issue by kasper93** [streamlink/streamlink#3881]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Currently there is an option to skip ads segments with `twitch-disable-ads` and wait real content. There could be another mode to use `thunderdome` player type to get real content segments during ad on main stream. `thunderdome` stream is used for pip on mobile when there is an ad playing. It is 480p only, but allows for uninterrupted, continuous stream playback by replacing ad segments with the real lower quality stream and restoring to main one when possible.

**Comment by gravyboat** [comment]
I don't understand what you're saying. Is `thunderdome` a stream type? Or an actual video player? Either way I don't see why we would do something like that. It's unlikely it's something that will stick around if it's something Twitch is now providing, and we're definitely not embedding an actual video player of any kind inside of Streamlink.

**Comment by kasper93** [comment]
> I don't understand what you're saying. Is `thunderdome` a stream type?

It is player type name as provided for twitch API. Streamlink currently sets `embed` :https://github.com/streamlink/streamlink/blob/a1fd4edee6c1f07f2ac7f4f1b010e16604abb0fd/src/streamlink/plugins/twitch.py#L277
You can replace this with `thunderdome` to get 480p stream without ads, the idea is to create hybrid mode. There is all code to detect ads segments, so half of works is there, the other is to replace them with `thunderdome` instead of waiting.

**Comment by bastimeyer** [comment]
> hybrid mode

This is not possible as Streamlink can only output a single progressive stream which the player need to demux and decode, and replacing ad segments with segments of a different stream would cause a stream discontinuity as it's two separate streams, which needs to be avoided. Not to mention that re-encoded streams will have a certain delay on Twitch, so this would cause another issue, even if it was supported by Streamlink's HLS implementation to switch between different streams while running.

The only thing that would make sense here is giving the user an option to choose one of the player types, but since the "thunderdome" player type is limited to a very low resolution, I don't think this is worth adding. If you really want to watch a delayed 480p stream, then please fork and change it yourself.

**Comment by bastimeyer** [comment]
> Ad segments in itself is a discontinuity

Which is the reason why filtering out ads is important when using certain players, even if the user doesn't mind watching ads or the "purple screen". **The main goal when filtering out ads is avoiding the stream discontinuity** to avoid player/demuxer/decoder issues/crashes, nothing else. The content, whether it's advertisements or not, is completely irrelevant. Stitching together multiple streams, even if it was supported by Streamlink, means actively looking for stream discontinuities, which doesn't make sense.

Players which implement HLS on their own (eg. web- or mobile players) are not affected by this problem, because they can reset the state of their demuxer/decoder/renderer when the HLS implementation detects a discontinuity in the HLS media playlist tags. Streamlink has no way of telling the player to reset, as it only outputs a progressive stream of concatenated segments which the player reads, just like a single file from your filesystem but instead from stdin, a named pipe, or a local http server. Recorded streams would also suffer from stream discontinuities.

> This is non-problem

It is a problem and not as simple as you think. Twitch's HLS segments are annotated with timestamps and of course duration metadata, and there is no guarantee that two separate streams with different qualities, where one stream is delayed by a bit, match up with the available stream segments and their metadata. This also depends on the user's desired live-edge value of the running live stream, and in order for Streamlink to find matching segment metadata, it would need to cache and compare segments individually, which it doesn't do. And of course there is no implementation for switching streams during runtime because it doesn't make sense for Streamlink.

> you sound passive aggressive

There is nothing passive aggressive about telling users of a FOSS project to make their desired changes themselves if it's out of scope. This PIP-stream workaround is nothing new and has already been brought up several times, and it is out of scope of this project.

If you're still under the impression that I've been passive aggressive with my answer then it's maybe because I've been dealing with Twitch ads questions, suggestions and back-and-forth code changes (plus a ton more unrelated to ads) for several years now, with Streamlink and Streamlink Twitch GUI, and I've been answering this stuff on several platforms all the time, so I don't always feel the need to explain everything in detail and in a "super-friendly" way every time.

In regards to the `playerType` access token request parameter, its value has been changed at least four times in the past when there were ways to circumvent Twitch serving ads, but this always only lasted a couple of days until Twitch fixed this "loophole" again. We've already said multiple times in the past that it doesn't make sense for Streamlink to add a parameter for making the `playerType` value customizable because it's too volatile and it would cause too much confusion when stuff breaks again. This has to work for every kind of user in a reliable way, and since an access token with the "thunderdome" playerType value does only yield streams with a low quality, there is no reason for Streamlink to make any changes here.
