### ISSUE TITLE
Output video file much shorter than expected

### ISSUE THREAD

**Issue by archiif** [streamlink/streamlink#3900]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I recently recorded a stream from Piczel, but the output length was much shorter than expected.
The streamlink output suggests that it has been recording 10 hours worth of stream.
```
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[download][2021-08-05_001.mp4] Written 2.04 GB (10h35m48s @ 56.6 KB/s)
```
But the actual video file was much shorter than expected:
```
Input #0, mpegts, from '2021-08-05_001.mp4':
  Duration: 03:19:32.46, start: 0.700000, bitrate: 1464 kb/s
  Program 1
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 4 kb/s
```

This has never happened to me before, what is the cause of this issue?
Is there a way to recover the original length of the stream and prevent this from happening again in the future?

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.4
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```

**Comment by bastimeyer** [comment]
> the output length was much shorter than expected.
> `[download][2021-08-05_001.mp4] Written 2.04 GB (10h35m48s @ 56.6 KB/s)`
> `Duration: 03:19:32.46`

Streamlink logs the time which has elapsed since it started recording. This is not the video/stream length. The logger has no information about the stream length, as it's not always possible to tell, depending on the kind of stream.

https://github.com/streamlink/streamlink/blob/db73cb2b00efaf54a13d6a6c642f49ea4777c6b2/src/streamlink_cli/utils/progress.py#L111-L153

> what is the cause of this issue?

Probably slow and/or non-parallel HLS segment downloads. Speed also depends on the server or your connection to the server. Streamlink allows you to download multiple segments in parallel (when it's a segmented stream, like HLS), which can improve download speeds for VODs. See the docs:
https://streamlink.github.io/latest/cli.html#stream-transport-options

> Is there a way to recover the original length of the stream

When recording an HLS stream, Streamlink will download every segment from the beginning until the end of the stream, unless it runs into error responses from the server or unless the connection times out. This will result in the process returning an error code. If there was no error code, then the download has been successful.

Start offset and duration of HLS streams can be set via CLI arguments. See the documentation.
https://streamlink.github.io/latest/cli.html#hls-options

**Comment by archiif** [comment]
> Probably slow and/or non-parallel HLS segment downloads. Speed also depends on the server or your connection to the server. Streamlink allows you to download multiple segments in parallel (when it's a segmented stream, like HLS), which can improve download speeds for VODs. 

I was downloading a non-VOD livestream, so I guess multiple segments are not possible. I think this issue actually happened to me before a while ago, where the download would basically stop (the speed status froze) but no errors were returned and the duration counter continued to elapse. I was able to manually monitor the download at that time, so I just restarted streamlink, but this wasn't the case this time as I was recording overnight.

Do you have any suggestions or theories on how to prevent this (I'm using the no configuration, so everything is set to the default option)? There's up to 7 hours worth of loss, so I don't think it's a timeout/connection issue as streamlink would probably give up very early on.

I'll try to record with the debug flag from now on in order to provide more information the next time this happens.

**Comment by bastimeyer** [comment]
> non-VOD livestream

Maybe related to #3628
