### ISSUE TITLE
Tests are failing on test_cookie_clear_unbound

### ISSUE THREAD

**Issue by grazzolini** [streamlink/streamlink#3919]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I'm trying to build the package for 2.3.0 on Arch and the tests are failing on test_cookie_clear_unbound. This does look to be an issue with the test itself. I have attached the build log.

[streamlink-2.3.0-1-x86_64-check.log](https://github.com/streamlink/streamlink/files/7001827/streamlink-2.3.0-1-x86_64-check.log)

### Debug log

```text
This issue is on the build process.
```

**Comment by bastimeyer** [comment]
The plugin cookie stuff hasn't been touched in three years since it was implemented in #1724:
- https://github.com/streamlink/streamlink/blame/2.3.0/tests/test_plugin.py#L133-L143
- https://github.com/streamlink/streamlink/blame/2.3.0/src/streamlink/plugin/plugin.py#L437-L520

The test checks whether a RuntimeError is being raised when the test plugin is "unbound" and no session object exists on it. Since the test fails, this means that the session object was set somewhere as a class attribute. There are lots of tests which don't have proper setups and pollute the state of certain objects, which means the execution depends on the order of tests being run, which is really bad.

Without having looked at the issue yet, I'm pretty sure that it's caused by some other test calling `Plugin.bind()` instead of calling `SomePluginImplementation.bind()`. Let me see...

**Comment by bastimeyer** [comment]
@grazzolini Does this patch fix the issue?
https://github.com/streamlink/streamlink/commit/5f2c051635fc2a0a1426f1d5a3af91e438f66148.patch

**Comment by grazzolini** [comment]
Yep, it does @bastimeyer. I'm going to apply this patch to the package and remove it on the next release, if it gets merged.

**Comment by bastimeyer** [comment]
> if it gets merged

#3920
