### ISSUE TITLE
Add this fix for Twitch Oauth

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#4]
https://github.com/javiercantero/livestreamer/commit/2d1325a9b44757b1c54de5d4778e6fc40a05d3a0

**Comment by fishscene** [comment]
I believe we'll also need to create our own oauth redirect url. Here's an example from javiercantero in the link above:
+    redirect_uri = "http://docs.livestreamer.io/twitch_oauth.html"

Further information about this process can be found here:
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.usmkehncb

**Comment by gravyboat** [comment]
This is definitely an annoying addition from Twitch as it basically requires that you have an acocunt, or we provide a publicly available client ID. I'm not sure what the best way to go about this is going to be as I don't want to log in if I don't have to.

**Comment by cbirchinger** [comment]
As far as i understand it. Twitch wants the author of the software that accesses their API to register a Client-ID. They don't demand that every user registers their own Client-ID, they just want a uniq one
per Application.

Livestreamer already has one registered client_id = "ewvlchtxgqq88ru9gmfp1gmyt6h2b93".
The patch by LoneFox78 in the https://github.com/chrippa/livestreamer/issues/1478 comments
already fix the whole issue by sending the already present client_id when requesting the API.

Of course this concept is totally based around commercial software or at least software that's
based around one single developer.

I fully understand if the author of this fork does not want a Twitch account. A possible solution
would be to register a new Twitch account (maybe called streamlink) with as little personal information
as possible. No solution is really perfect as it requires a single responsible person having that account
though.

If none of the authors want to register a Client-ID for this fork, it would probably the best to just
keep using the Client-ID from livestreamer which is already present in the code. As previously
mentioned, the patch fixes the Client-ID issue.

**Comment by bastimeyer** [comment]
> Livestreamer already has one registered client_id

It would be better to register a new application on Twitch, since the old one was registered by chrippa and we don't know if he will keep his twitch account and the registered application.

> I believe we'll also need to create our own oauth redirect url

A better solution would also be starting a local webserver whenever the user is requesting a new oauth token. This eliminates the dependency of having a website for this.

> as it basically requires that you have an acocunt

It requires either the basic *application client-id* or a generated *user oauth token*. The new application client-id could be set statically as a default value in the config which will then be used in a `Client-ID=${client-id}` HTTP header that needs to be included in all API requests. It could then easily be changed by the user if a different one is perferred. Right now this is done via the `--http-header` parameter.

**Comment by javiercantero** [comment]
You shouldn't merge my squashed branch but the original #1359

**Comment by cdrage** [comment]
@bastimeyer i'm on the fence on this, since twitch *requires* now that every user uses an API token and there's no more anonymized streams, it's better to alert the user to provide an oauth token / etc to streamlink / livestreamer. 

at the same time, if we hardcode an official "streamlink" key into it, it can be revoked at any time with abuse and screw up any releases we've done previously with the hardcoded key in it.

**Comment by bastimeyer** [comment]
OAuth tokens are linked to the application client-id. So even if the client-id in not used globally and users are required to authenticate, Twitch still knows which application they are using. Revoking a client-id will also invalidate all oauth tokens associated with it.
There is no choice here. You can either make it simple for everyone or make it difficult by requiring annoying setup steps.
That's why I think it's important to add a config option for the client-id (`--twitch-client-id`), so that it can easily be switched if the user decides to or in case it was revoked, without the need of using the `--http-header` option.

I don't know how I feel about alerting the users that are using the default client-id. It's not a terrible idea, as it would reduce the number of people using the default one, but I'm not sure if people will actually care. They would need to register their own application on Twitch or use an oauth token registered by a different app with the sufficient API access permissions.

**Comment by sbstp** [comment]
Using a public and shared client ID is a nice way of providing anonymity to the users. Keeping the application turnkey would be pretty cool, but providing the option to use a different client ID should definitely exist.

**Comment by fishscene** [comment]
Agreed. I think we should have our own Application-ID, but allow it to be overwritten with (--twitch-client-id). 
Also, if it's possible to have a local URL redirect for oauth, that would keep dependency (and costs) on infrastructure down to a minimum.

**Comment by cdrage** [comment]
This will be fixed in #9 with an application-id.

I do agree with @fishscene by default let's have a streamlink-specific application id and have the option to override it with --twitch-client-id.

**Comment by beardypig** [comment]
There already appears to be a usable redirect URL as part of the docs: https://streamlink.github.io/twitch_oauth.html Creating a new twitch client Id would be required to use this new URL, as the redirect url is tied to the application. 

The `--twitch-oauth-authenticate` option is still broken, and it doesn't look like it can be fixed just by changing the redirect URI to http://docs.livestreamer.io/twitch_oauth.html because that does not match the redirect URI for the livestreamer clientID. A straightforward approach would be to mirror what livestreamer did, and create a new clientID for streamlink and just update the clientID and the redirect URI - it would fix the issue for now with scope to improve it later.

**Comment by gravyboat** [comment]
I'm closing this since 9 fixed it up.

**Comment by beardypig** [comment]
Probably need a new issue for fixing `--twitch-oauth-authenticate`, that shouldn't get lost :-)
