### ISSUE TITLE
streamlink command not recognized despite adding path variable

### ISSUE THREAD

**Issue by Woolton** [streamlink/streamlink#4014]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

 I've installed via choco on windows 10. I tried to use the streamlink command and I got the "command not recognized error." I went to check my environment variables and noticed streamlink was already in the global variables so I added it to my user variables as well. No difference. The command only works when navigating to the installed folder.

This bug is consistently reproducible.

![image](https://user-images.githubusercontent.com/36093760/133183350-69cae8c6-3278-41cc-a95f-511bef0ef8c5.png)
en

### Debug log

```text
C:\Program Files (x86)\Streamlink\bin>streamlink --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
usage: streamlink [OPTIONS] <URL> [STREAM]
```

**Comment by bastimeyer** [comment]
> The command only works when navigating to the installed folder.

because on Windows `.` (the current directory) is the first entry in `PATH`.

> command not recognized error

Your shell might still be using old values of the `PATH` env var.
**Post the output of `echo %PATH%` to see its contents.**
If it's not using the correct values, log out and log back in, or restart your system.

Streamlink's Windows installer will automatically append its install path + `\bin` to the `PATH` env var, so that your system can find the `streamlink.exe` and `streamlinkw.exe` entry point executables without relative or absolute paths. And Windows' `PATHEXT` adds optional `.exe` suffixes by default for the `PATH` lookups.

The install path gets appended to `PATH` by a bundles python script from the [`pynsist`](https://github.com/takluyver/pynsist) project used to build the installer, and it's run after you've successfully run the installer. So if there is a bug (which there is most likely not), then it's an upstream issue and not a Streamlink issue.

Again, check the value of your `PATH` env var from the shell.
