### ISSUE TITLE
Create new directory upon no such directory found. 

### ISSUE THREAD

**Issue by ShiroUwUs7** [streamlink/streamlink#4081]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

add new directory to stop the error for streamlink. if no directory is made create one. 
![1Nhxhvq 1](https://user-images.githubusercontent.com/53096166/136674160-c21f68fc-ba55-461b-b3ce-3da7f50cc0b9.png)

**Comment by bastimeyer** [comment]
This is a limitation with the current implementation of the FileOutput. This has already been brought up I believe in one of the PRs that lead to the implementation of the new metadata formatter (#3962).

Without further heavy modification, subdirectories with metadata can't be created, because with the way the formatted path is passed to the FileOutput right now (where the file handle gets initialized), substituted metadata variables could alter the path in such a way that it points to somewhere else (parent directories), which is surely not what you want.

- https://github.com/streamlink/streamlink/blob/5b01621fd1226e4804e7af05590bead1f5a5ad07/src/streamlink_cli/main.py#L106
- https://github.com/streamlink/streamlink/blob/5b01621fd1226e4804e7af05590bead1f5a5ad07/src/streamlink_cli/output.py#L56-L58

I'd say that it's not worth spending the time rewriting everything again and deal with all the pitfalls that come with that when the user can simply write the file into a single target directory instead. Just use a dash as a separator between author and title.

**Comment by Lawrence575** [comment]
Because im doing it through powershell I can probably just use your method of adding author # title (a unique char that wont be used in a stream title for example #)  then having powershell create directory from the file name itself before # and moving it to that directory after proccessing. as a workaround. 

`cd C:\Users\PC\Videos\Test\test1
  $files = Get-ChildItem -file;
  ForEach ($file in $files)
  {
    $folder = New-Item -type directory -name ($file.BaseName -replace "#.*");
    Move-Item $file.FullName $folder.FullName;
    Move-Item $folder.FullName C:\Users\PC\Videos\Test\recorded;
  }

`

**Comment by bastimeyer** [comment]
An update could be simpler than I thought. Just had another quick look at it. We're already subclassing the Formatter for the streamlink_cli specific interface, which has the public `filename` method. Instead of formatting an input string, a Path object could be formatted component-wise and FileOutput be updated so that it accepts Path objects instead of strings. Then creating directories before initializing the file handle becomes trivial. I'll take a proper look at it tomorrow. Doesn't sound too complicated.
