### ISSUE TITLE
plugins.schoolism: new schoolism site (still considered beta) not working

### ISSUE THREAD

**Issue by Knauj** [streamlink/streamlink#4182]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

new user are at schoolism are redirected to https://beta.schoolism.com/login
all schoolism video urls are changed accordingly.

"error: No plugin can handle URL: https://beta.schoolism.com/s/course/library/lessons/50"

### Debug log

```text
error: No plugin can handle URL: https://beta.schoolism.com/s/course/library/lessons/50
```

**Comment by gravyboat** [comment]
We don't do plugin updates for website betas since the beta can be constantly changing, once it's no longer in a beta state someone can take a look if they feel like it.

**Comment by mkbloke** [comment]
I was going to say more or less the same as above, but also that due to Schoolism being a subscriber site, it's even more unlikely that this will get fixed, unfortunately.

**Comment by CasualRascal** [comment]
I would like to add that while it carries "beta" in the name, it is not an actual beta but the production website. There is no way to access the older website and the URLs do not contain the `beta.` subdomain. 

This makes the plugin completely broken, not just partly broken.

**Comment by gravyboat** [comment]
> I would like to add that while it carries "beta" in the name, it is not an actual beta but the production website.

As long as it carries the beta name whether it's on the primary domain or not it's still subject to changes. If someone feels like updating the plugin they're welcome to do so and it can be side loaded.

**Comment by AntoineC4Ci** [comment]
The schoolism URL does not incudes "beta" anymore. (but the ébeta" tag is still present on the website header).

Even if I am not sure about what i was trying to do, I tried to change the following command : 

_C:\Users[OMITTED]> streamlink https://schoolism.com/s/course/library/lessons/25 best -o "location and file name.mp4" --schoolism-email EMAIL --schoolism-password PASSWORD
error: No plugin can handle URL: https://schoolism.com/s/course/library/lessons/25_


Then i used a webbrowser extention that detects the following HLS URLs from the schoolism webpage : 
https://ts.schoolism.com/ts/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8
https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1_sd.m3u8
https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8

When I replace the command whith these urls, I get :

_C:\Users[OMITTED]> streamlink https://ts.schoolism.com/ts/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8 best -o "location and file name.mp4" --schoolism-email EMAIL --schoolism-password PASSWORD
[cli][info] Found matching plugin hls for URL https://ts.schoolism.com/ts/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8
[stream.hls_playlist][warning] Malformed HLS Playlist. Expected #EXTM3U, but got <!DOCTYPE html>
error: Failed to parse playlist: Missing #EXTM3U header_

_C:\Users[OMITTED]> streamlink https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1_sd.m3u8 best -o "location and file name.mp4" --schoolism-email EMAIL--schoolism-password PASSWORD
[cli][info] Found matching plugin hls for URL https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1_sd.m3u8
error: Unable to open URL: https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1_sd.m3u8 (403 Client Error: Forbidden for url: https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1_sd.m3u8)_

_C:\Users[OMITTED]> streamlink https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8 best -o "location and file name.mp4" --schoolism-email EMAIL --schoolism-password PASSWORD
[cli][info] Found matching plugin hls for URL https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8
error: Unable to open URL: https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8 (403 Client Error: Forbidden for url: https://cdn.schoolism.com/courses/lesson-videos/25/6b9a09a0-78c7-4bfd-92ea-ce23ddcf0ee1.m3u8)_


Hope this can help updating/fixing the plugin ^^

**Comment by bastimeyer** [comment]
I've been refactoring a lot of plugins the past couple of days and I also had a look at the schoolism plugin. I wasn't aware that this issue thread existed.

The site's entire content is behind a paywall, and the free stuff is just a bunch of youtube videos embedded on their site. Fixing this plugin requires having access to an account with a paid subscription.

However, since the plugin is currently broken and there don't appear to be any live streams, this makes it a candidate for removal.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

----

> Hope this can help updating/fixing the plugin ^^

No, because all you did was check your web browser's HTTP requests made to HLS playlists. Passing an HLS URL to streamlink makes it select the HLS plugin, not the schoolism plugin, so the parameters related to the schoolism plugin won't affect any HTTP requests made by streamlink. If you're seeing authentication errors on custom HLS URLs, then you have to set the missing HTTP headers yourself via the [`--http-header`](https://streamlink.github.io/cli.html#cmdoption-http-header) CLI argument. Fixing the plugin requires being able to take a look at the site's HTML content and JS code.

**Comment by mkbloke** [comment]
I looked at the Schoolism website quite a while ago and found, as you have, @bastimeyer, that it's all pay-walled.

I can't recall now if it's possible to get a free trial period for this site, but that's not really a good answer - the plugin could be fixed in the short term, but longer term it's just not viable.

This plugin suffers the same issue as the WWE plugin did - a necessary subscription and nobody with a subscription who is able or bothered to fix it.  Therefore, it seems likely this plugin will face the same fate - eventual removal when it completely stops working, as IMHO, is the only reasonable way forward for plugins of this ilk.  If somebody with a subscription and the ability/motivation to support a plugin for this site comes along in the future, it can always be reintroduced.  Given that this issue has been open for the better part of a year, I'm not that hopeful though.
