### ISSUE TITLE
AttributeError: module 'chardet' has no attribute 'detect'

### ISSUE THREAD

**Issue by vijay6672** [streamlink/streamlink#4183]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Streamlink 3.0.1 always starts with an 
AttributeError: module 'chardet' has no attribute 'detect' error.

### Debug log

```text
streamlink https://www.twitch.tv/hiko best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.8
[cli][debug] Streamlink: 3.0.1
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/hiko
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/hiko
[plugins.twitch][debug] Getting live HLS streams for hiko
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1051, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 564, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 335, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", line 642, in _get_streams
    return self._get_hls_streams_live()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", line 594, in _get_hls_streams_live
    return self._get_hls_streams(url, restricted_bitrates)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\twitch.py", line 613, in _get_hls_streams
    streams = TwitchHLSStream.parse_variant_playlist(self.session, url, start_offset=time_offset, **extra_params)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 501, in parse_variant_playlist
    parser = cls._get_variant_playlist(res)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 476, in _get_variant_playlist
    return load_hls_playlist(res.text, base_uri=res.url)
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 865, in text
    encoding = self.apparent_encoding
  File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 735, in apparent_encoding
    return chardet.detect(self.content)['encoding']
AttributeError: module 'chardet' has no attribute 'detect'
```

**Comment by bastimeyer** [comment]
> chardet

`chardet` is not a dependency of `requests` 2.26 anymore.
https://github.com/psf/requests/blob/v2.26.0/setup.py#L44

This was changed when Streamlink 2.3.0 upgraded from requests 2.25.1 to 2.26 in 35cb8d9f9ae454b1edb01751d64e5910bce222df
https://github.com/psf/requests/blob/v2.25.1/setup.py#L45

The reason why you're seeing this issue is that `requests` seems to try to load the old chardet version as it still requires it for its python2 compatibility code, but it's of course not working in a python3 environment.

That looks like an issue of the Windows installer's upgrade, as it doesn't remove old files first. You have to completely uninstall Streamlink and then re-install it manually.

**Comment by vijay6672** [comment]
Uninstall and reinstall doesn't solved the issue.
Changed below lines in "Streamlink\pkgs\requests\compact.py" to make it work.

try:
    import charset_normalizer as chardet
    #import chardet
except ImportError:    
    import chardet
    #import charset_normalizer as chardet

**Comment by bastimeyer** [comment]
> Uninstall and reinstall doesn't solved the issue.

No, you'll have to clean the entire install directory.

This is the `compat.py` module of `requests` 2.26.0:
https://github.com/psf/requests/blob/v2.26.0/requests/compat.py#L11-L14

As you can see, it first tries to import `chardet`, and if it raises an `ImportError`, it imports `charset_normalizer` instead, which it then uses as the same import name for usage in various methods.

I have already shown in my previous post that `requests` 2.26.0 doesn't depend on `chardet` on python3 anymore. The Streamlink installer which bundles Streamlink and all of its dependencies does not include `chardet` since 2.3.0 for that reason.

This means that you will only see the error if you have `chardet` installed in the python environment of Streamlink's Windows installer. This can happen if you didn't completely uninstall and remove Streamlink from your system, because the installer doesn't clean up old installs when it extracts new content. This is a known issue and limitation of the installer built via pynsist, and it requires a custom workaround which no one has implemented yet.

So once again, **completely uninstall and remove any previous files from your Streamlink install and then re-install the latest version**.
