### ISSUE TITLE
Can't install 2.3.0 on mac and thus getting "410 Client Error: Gone for url" error

### ISSUE THREAD

**Issue by VityaSchel** [streamlink/streamlink#4189]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Running `brew install streamlink` installing streamlink with version 2.0.0
```
VITA@MacBook-Air ~ % streamlink --version
streamlink 2.0.0
```
So I can't use it to download streams (known issue with older version)
```
streamlink --loglevel debug --http-cookie 'VISITOR_INFO1_LIVE=[11 chars]' 'https://youtu.be/LszOq7dMgYE' best
```
(see response from streamlink below)

How to install latest version? Do I need to update OS?

### Debug log

```text
[cli][debug] OS:         macOS 11.4
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://youtu.be/LszOq7dMgYE
[plugins.youtube][debug] Video ID from URL
[plugins.youtube][debug] Using video ID: LszOq7dMgYE
error: Unable to open URL: https://youtube.com/get_video_info (410 Client Error: Gone for url: https://www.youtube.com/get_video_info?video_id=LszOq7dMgYE&el=detailpage)
```

**Comment by VityaSchel** [comment]
visitor token is correct, I tried different channels and livestreams, --retry-stream, different accounts, but I'm sure it's because of old version (see comment from @bastimeyer in #3990)

**Comment by VityaSchel** [comment]
Right now I'm trying to make it work on my ubuntu machine to see if it's bug specific to homebrew or I stable version number has not been updated by maintainers yet

**Comment by VityaSchel** [comment]
`sudo apt install streamlink` on Ubuntu 20.04 LTS installs streamlink 1.7.0 with the same error

**Comment by gravyboat** [comment]
We don't maintain the homebrew release or the linux packages directly so if no one is updating those then you'll have to follow the alternate instructions: https://streamlink.github.io/install.html#pypi-package-and-source-code

**Comment by VityaSchel** [comment]
Just wanted to say that looks like those packages are abandoned 
![image](https://user-images.githubusercontent.com/59040542/142573744-34015752-99a8-4a82-aeae-f9d5172c360a.png)

**Comment by bastimeyer** [comment]
We don't maintain any packages of Streamlink.

> Running `brew install streamlink` installing streamlink with version 2.0.0

The homebrew-core `streamlink` package is currently at 2.4.0, as you can see here:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/streamlink.rb
You need to update your package index. Wait until someone submits a pull request for 3.0.0 or update the formula yourself.

> Ubuntu

Ubuntu is not a rolling release distro and certain package versions are only available for your point release.
Focal Fossa, alias 20.04 LTS, does not receive any updates anymore on the webudp8 PPA.
http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/s/streamlink/
If you don't like how the maintainers of the PPA handle the package updates, please contact them.

Otherwise, read the install page of Streamlink's documentation and install the appimage, which is available for all glibc-based distros ([`manylinux2014`](https://www.python.org/dev/peps/pep-0600/) platform tag), or install streamlink via python-pip.
https://streamlink.github.io/install.html#linux-and-bsd
