### ISSUE TITLE
unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe

### ISSUE THREAD

**Issue by zydjohnHotmail** [streamlink/streamlink#4211]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hello:
I found streamlink has a new version (3.0.2), so I wanted to do a simple test, like this, but I got errors:
streamlink --stream-segment-threads 10 https://xyz/playlist_gtom.m3u8 --hls-duration 00:00:100 -o test_20threds.mp4
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe https://xyz/playlist_gtom.m3u8
I knew that in version 3.0.1, I had this issue, so I had to go back to use streamlink version 2.0.4, then the above command works.
But for the new version 3.0.2, I still have the same issue.
Let me know if in the next version, can we get rid of those issues. I think if new version drop the support of rtmp, then it is better not showing the error and quit the command.  Simply ignore the error and continue.
By the way, I am using Windows 10 (version 21H2) with Python 3.9.
Thanks,

### Debug log

```text
streamlink --stream-segment-threads 10 https://xyz/playlist_gtom.m3u8 --hls-duration 00:00:100 -o test_20threds.mp4
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe https://xyz/playlist_gtom.m3u8
```

**Comment by bastimeyer** [comment]
**You have not read the changelog of the Streamlink 3.0.0 release**, which has introduced breaking changes, hence the major version bump from 2.4.0 to 3.0.0.

https://streamlink.github.io/changelog.html#streamlink-3-0-2-2021-11-25

> Please see the changelog of 3.0.0, **as it contains breaking changes that may require user interaction.**

https://streamlink.github.io/changelog.html#streamlink-3-0-0-2021-11-17

> - BREAKING: removed the following CLI arguments (and respective session options):
>   - `--rtmp-rtmpdump`, `--rtmpdump`, `--rtmp-proxy`, `--rtmp-timeout`  
>    Users of Streamlink's Windows installer will need to update their [config file](https://streamlink.github.io/cli.html#configuration-file).

**If you have `rtmp-rtmpdump` in your default streamlink config file, which is the case for all users on Windows who have previously installed a version of Streamlink lower than 3.0.0 via the Windows installer, then you have to remove the `rtmp-rtmpdump` line from the config file.**

Streamlink's Windows installer has to create a config file because of the custom ffmpeg (and rtmpdump) dependency paths and the lack of proper PATH env var resolution for third-party binaries on Windows (unlike Linux or macOS). If a config file already exists, eg. when upgrading Streamlink, then the installer won't touch the config file, because that would mess with the user's config, which it's not supposed to and needs to be avoided. So if a parameter gets removed from Streamlink in a major version change and becomes unsupported, then you have to fix your old config file yourself. You can also remove the config file and reinstall Streamlink, if you prefer this method.

As you can read in [Streamlink's documentation](https://streamlink.github.io/cli.html#configuration-file), the config file path on Windows is
`%APPDATA%\streamlink\config` (the default path)
or
`%APPDATA%\streamlink\streamlinkrc` (an old and deprecated path)
if you've been using an even older version of Streamlink and you haven't renamed the file to its proper name yet.

The `%APPDATA%` environment variable usually points to the `AppData\Roaming` directory in your home directory in `C:\Users\%USERNAME%`.

So once again, either update or remove your Streamlink config file which still includes the now unsupported `rtmp-rtmpdump` parameter.

**Comment by zydjohnHotmail** [comment]
Thanks,
I know how to fix it now!

**Comment by ChristophKrause** [comment]
Streamlink: Now working
Me: very ashamed.

Thank you
