### ISSUE TITLE
output with --json flag is not parseable if handled error occurs

### ISSUE THREAD

**Issue by spedrickson** [streamlink/streamlink#4235]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Steps to reproduce
1. Run streamlink against a YouTube channel that is not live, e.g. `streamlink youtube.com/c/LudwigAhgren -j`
2. Output is unparseable as JSON:

### Expected Behavior
All output on stdout should be parseable when the  `--json` is enabled (barring an unrecoverable error)
```json
{
  "error": "No playable streams found on this URL: youtube.com/c/LudwigAhgren"
}
```
### Actual Behavior
Plugin errors are printed to stdout along with the parseable JSON output
```json
[plugins.youtube][error] Could not find videoId on channel page
{
  "error": "No playable streams found on this URL: youtube.com/c/LudwigAhgren"
}
```

### Possible Solutions
* Write error messages to stderr instead of stdout when `--json` flag is enabled (or always)
* Suppress error messages when `--json` flag is enabled, since the content is duplicated in the JSON output

### Debug log

```text
[plugins.youtube][error] Could not find videoId on channel page
{
  "error": "No playable streams found on this URL: youtube.com/c/LudwigAhgren"
}
```

*Note*:   
the debug log is with the proper `--loglevel debug` param, it seems `--json` suppresses debug messages already. System info is as follows:
```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.8
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
```

**Comment by bastimeyer** [comment]
The problem here is how the logger and console output stream is set up when `--json` is set. It uses the same stream output, which is usually fine, but `console.exit` has special logic when `--json` is set, so any regular console/log message prior to the `console.exit` call gets printed to the same output stream. The logger and console output should not share the same stream output when `--json` is set, and the logger should print to `stderr` while `console` should print to `stdout`.

- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink_cli/main.py#L1009
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink_cli/main.py#L967-L987
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink_cli/console.py#L85-L87
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink_cli/main.py#L571-L572
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink/plugins/youtube.py#L321

**Comment by bastimeyer** [comment]
Had a quick look at this again. The way `--json` is implemented is not particularly great. And neither is the entire streamlink_cli, but that's not the point of this thread.

The JSON output is either done via `console.msg_json(data)` or `console.exit(data)` (if `ConsoleOutput` was initialized with `json=True`). As I said earlier, both the logger and the console instances share the same output stream. The output stream however varies depending on whether streamlink_cli outputs stream data to `stdout` when `--stdout` is set (or related arguments like `--output=-`, etc). This means that outputting the console's JSON data to `stdout` and the logger's log messages to `stderr` for example when `--json` is set is not always possible, so fixing this issue is not that simple.

`console.msg_json(data)` and `console.exit()` are meant as the last output method call for printing messages, because there can only be one JSON output. In order to respect the `--json` argument, all logger calls would either need to be suppressed when it is set (which is bad), or they need to be buffered and then included in the final JSON output, so that it can be parsed. That however does not guarantee that there will be a `console.msg_json(data)` or `console.exit()` call at the end, so the `ConsoleOutput` would need to be made aware of a `SystemExit`.

**Comment by bastimeyer** [comment]
Ignore what I have said earlier. `--json` is already defined in the `SILENT_OPTIONS` tuple, which means that the loglevel gets set to `none` in that case, and log messages should get suppressed.

- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink_cli/main.py#L41
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink_cli/main.py#L1006-L1007

The issue is something else. Going to submit a PR now.
