### ISSUE TITLE
Streamlink is starting download before user's response for file overwrite

### ISSUE THREAD

**Issue by kikuyan** [streamlink/streamlink#4248]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When file output option `-o` is used to an existing file, Streamlink prints confirmation message for file overwrite and asks for user's response.
However, before the response, Streamlink has already started downloading and continues. If the user responds with "n", this will result in a waste of bandwidth. It can also be confusing when used with `-l debug`, as the debug messages are printed as if confirmation is ignored.

It would be better to check the output file before opening the stream.

In the debug log below, I responded with "n" after `[stream.segmented][debug] Closing writer thread` message.

### Debug log

```text
[cli][debug] OS:         macOS 10.12.6
[cli][debug] Python:     3.9.9
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.dailymotion.com/video/x853fvr
[cli][debug]  stream=['480p']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=video.ts
[cli][debug]  --hls-duration=20
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x853fvr
[plugins.dailymotion][debug] Found media ID: x853fvr
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 112p_alt (worst), 112p, 184p_alt, 184p, 288p_alt, 288p, 480p_alt, 480p, 720p_alt, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 480p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 0; Last Sequence: 53
[stream.hls][debug] Start offset: 0; Duration: 20; Start Sequence: 0; End Sequence: 53
[stream.hls][debug] Adding segment 0 to queue
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][info] Stopping stream early after 20
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Segment 0 complete
[cli][debug] Checking file output
File video.ts already exists! Overwrite it? [y/N] [stream.hls][debug] Segment 1 complete
[stream.hls][debug] Segment 2 complete
[stream.hls][debug] Segment 3 complete
[stream.hls][debug] Segment 4 complete
[stream.hls][debug] Segment 5 complete
[stream.hls][debug] Segment 6 complete
[stream.segmented][debug] Closing writer thread
n
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
The reason why streamlink_cli first tries to open the stream is that it needs to know whether it was successful. If it was not, then it'll exit, which is done before preparing the output.

The problem here is that the output can either be a `FileOutput` or a `PlayerOutput` instance, returned by the `create_output(formatter)` call. If the output would get created before opening the stream and the path of the `FileOutput` already exists, then a file descriptor would get created before opening the stream and if the stream then fails, then the file would be overwritten with zero data for no reason, which is bad. In order to fix that, the `FileOutput` class would need to get changed so that it only creates a file descriptor on demand, on the first write call.

https://github.com/streamlink/streamlink/blob/820d13c1b391ab78b25897f3408fe92af462550e/src/streamlink_cli/main.py#L306-L320

**Comment by scottbernstein** [comment]
I don't think it's much of an issue that a few segments get downloaded before exiting.
________________________________

**Comment by kikuyan** [comment]
Thank you for a fix.
