### ISSUE TITLE
Huya.com plugin/support

### ISSUE THREAD

**Issue by prech** [streamlink/streamlink#425]
Many thanks to the developers for making Streamlink such a wonderful tool.

Would appreciate any tips for supporting Huya.com streams, or for adding a plugin for it. Very popular Chinese streaming platform, similar to Douyu, Pandatv and Longzhu. 

I attempted to play around with editing douyutv.py and tga.py, but didn't have any luck. They appear to have a very similar interface. No log-in is necessary for viewing on either the mobile app or website.

Huya's mobile app streams in HD resolutions, but the stream through Huya.com is hit and miss, often with poor latency.

Some examples:
[http://www.huya.com/g/lol](http://www.huya.com/g/lol)

Thanks!

**Comment by fozzysec** [comment]
You can get hls stream address easily by specifying UA to mobile device like iPhone, but to get the http stream it is a bit more work to do because there are no public API to use. From Huya's swf file you can find two functions `getCdnTokenInfo` and `getFlvTokenInfo` in scripts/taf/TafManager.as, by analysis these two functions, you may able to find out the method to get the tokens and API.

**Comment by beardypig** [comment]
Since #465 was merged this should be fixed.

**Comment by yeahjack** [comment]
Hello, There should probably be updates for HuyaTV since we cannot use streamlink to visit Huya
