### ISSUE TITLE
Getting session_key

### ISSUE THREAD

**Issue by Jason-Needham** [streamlink/streamlink#4334]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I've tried for months to figure out how to get the session_key, live headers, curl and more and all to no avail. Could you help me in how it's done??
Thanks,
Jason

**Comment by mkbloke** [comment]
You should have started this as discussion.

The session key for what?  You'll need to provide much more information than you have so far if you want any help.

**Comment by Jason-Needham** [comment]
I'm sorry... my first post ever without a 300 baud modem. I'm referring to
the token referenced in
https://github.com/streamlink/streamlink/issues/4332*mkbloke
<https://github.com/mkbloke> *wrote "but that requires a session key for
the API" referencing url
http://www.filmon.com/tv/api/channel/815?protocol=hls
It is that key I can't figure out for the life of me how to get.

Thanks,
Jason

**Comment by mkbloke** [comment]
You won't find it, the session key is generated when developers apply for access to the full API with FilmOn.  That comment was merely an observation.

I have a fixed FilmOn plugin now (#4335), which will hopefully be accepted into Streamlink master in the next few days.  You can either wait for that or look at side-loading the updated plugin (see: https://github.com/streamlink/streamlink/issues/4332#issuecomment-1030487509 and following messages).

**Comment by Jason-Needham** [comment]
Thank you for getting back so fast. I do have it working w/side load, just wanted to see if I could do it myself through shell curl. I use your package with a lot of my own scrapers. I run Kodi, url?with=args to local host, php shell_exec( shell scrapers script ), change Tor proxy if needed, feed streamlink hls m3u urls, php redirect to streamlink port and watch tv.
So how are you overcoming the Hmm, 404 for:[http://www.filmon.com/api-v2/channel/{0}?protocol=hls] as described in #4332?
I'm an old man and cripple, it keeps me busy.
Thanks again,
Jason

**Comment by mkbloke** [comment]
I'm just using different data sources - those that are currently used when you visit the website with a browser.

**Comment by Jason-Needham** [comment]
I'm not asking you for the secret sauce, but could you point me or even hint where to find the json referenced in post  #4332 or where to find the .m3u url? I can recite the html from memory I've scoured it so many times, same with the /api/ files I've found so far.
On another unrelated matter, prior to side-loading filmon I used http and streamlink was fine with that. The side-load disregards http and upgrades to https. Assuming my pc isn't unique I had to modify openssl.cfg to obtain functionality, this may be a problem for others... just an observation. 
Quoting your original response "You should have started this as a discussion." couldn't have been more right.
Thanks,
Jason

**Comment by mkbloke** [comment]
There's no secret sauce, the answers are in the source!  For the live channels and VODs respectively:
https://github.com/streamlink/streamlink/blob/854d3ddeea08762599963a2ab1d9f8fc8db25fb7/src/streamlink/plugins/filmon.py#L126-L127
Search for one of those URLs in the network tab of the developer console depending on what kind of video page you're looking at.  Click on the entry and you can then view headers/request/response tabs in the other window that appears.  You can see the JSON in the response tab which will contain the video source URLs for high and low streams in the `streams` section near the bottom of the JSON.

The live channel data comes from a POST request as described in: https://github.com/streamlink/streamlink/issues/4332#issuecomment-1030333161
The VOD channel data comes from a GET request where the `id` is the slug of VOD video page you're looking at.  The slug is the bit after the last `/`, e.g. in `https://www.filmon.com/vod/view/8762-john-lennon-the-ultimate-collection` the slug is `8762-john-lennon-the-ultimate-collection`, replace `id={0}` in the VOD URL with `id=8762-john-lennon-the-ultimate-collection`, for example.

The upgrade to HTTPS should have been happening for a while if you were using scheme-less URLs on the command line such as `filmon.com/tv/itv1`.  See the [release notes](https://github.com/streamlink/streamlink/releases/tag/3.0.0) for version 3.0.0.

I also have to start Streamlink with a local .openssl.conf file for FilmOn.  I just use `OPENSSL_CONF=~/.openssl.cnf streamlink ...` if it's required.  This is because recent distributions have upgraded their minimum TLS requirement in OpenSSL to version 1.3, but some sites are still using version 1.2.
