### ISSUE TITLE
Best quality subplaylist isn't considered as best for certain m3u8

### ISSUE THREAD

**Issue by fireattack** [streamlink/streamlink#4350]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

URL: https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8

Content:
```m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="Source",NAME="Source",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-STREAM-INF:BANDWIDTH=5000000,CODECS="avc1.64002a,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=60.0,VIDEO="Source"
chunklist_source/chunklist.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="540p30",NAME="540p",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-STREAM-INF:BANDWIDTH=1086000,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=30.0,VIDEO="540p30"
chunklist_medium/chunklist.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p30",NAME="360p",DEFAULT=YES,AUTOSELECT=YES
#EXT-X-STREAM-INF:BANDWIDTH=757000,CODECS="avc1.42c01e,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=30.0,VIDEO="360p30"
chunklist_low/chunklist.m3u8
```

As you can see, the first subplaylist has higher nominal bitrate, resolution and frame-rate. But for some reason streamlink considers the second 540p one "best".

### Debug log

```text
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 3.1.1+9.g0580917
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8
[cli][debug]  --loglevel=debug
[cli][debug]  --player=D:\Program Files\SMPlayer\mpv\mpv.exe
[cli][debug]  --ffmpeg-ffmpeg=D:\Program Files\!cli\ffmpeg.exe
[cli][info] Found matching plugin hls for URL https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8
[plugins.hls][debug] URL=https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8; params={}
[utils.l10n][debug] Language code: zh_CN
Available streams: source, 360p (worst), 540p (best)
```

**Comment by bastimeyer** [comment]
Streamlink needs to rank the streams in order to be able to find the "best" stream. This is done by each stream's "name" attribute by default.

The names of the streams of the master playlist you've posted are this
- `Source`
- `540p30`
- `360p30`

Streams that are named in the `${res}p${fps}` format can be ranked automatically. But streams which have arbitrary names can't be ranked like this and need another parameter for selecting the attribute which they are ranked by.

The HLS-protocol-plugin allows you to choose this attribute via the `name_key` parameter. Unfortunately, only the format of how you can set the parameter is described in the documentation. This needs to be improved.
https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly

The available parameters are the ones supported by the `HLSStream.parse_variant_playlist` classmethod, which you can see here:
https://github.com/streamlink/streamlink/blob/3.1.1/src/streamlink/plugins/hls.py#L22-L25
https://github.com/streamlink/streamlink/blob/3.1.1/src/streamlink/stream/hls.py#L523-L528

Ranked by `name` (default):
```
$ streamlink 'hls://https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8 name_key=name'
[cli][info] Found matching plugin hls for URL hls://https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8 name_key=name
Available streams: source, 360p (worst), 540p (best)
```

Ranked by `pixels`:
```
$ streamlink 'hls://https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8 name_key=pixels'
[cli][info] Found matching plugin hls for URL hls://https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8 name_key=pixels
Available streams: 360p (worst), 540p, 1080p (best)
```

Ranked by `bitrate`:
```
$ streamlink 'hls://https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8 name_key=bitrate'
[cli][info] Found matching plugin hls for URL hls://https://d3cfw2mckicdfw.cloudfront.net/adbb731d8cfcef790d1f3b343a655f6d89a12d8c/playlist.m3u8 name_key=bitrate
Available streams: 760k (worst), 1100k, 5000k (best)
```

**Comment by fireattack** [comment]
Thanks. 

I would think having default of `(pixels, framerate, bitrate)` as key makes more sense than using name.

Is there a reason it doesn't work this way?

**Comment by bastimeyer** [comment]
I don't know why `name` was chosen as the default. This was done back in 2013 during the livestreamer days, way before the streamlink fork:
7b5501b6479462e7581ec0bdf5e259d4c9a09a8b

Plugins can choose the name format themselves when returning/yielding HLS streams, but for custom HLS stream inputs like here, this is indeed a bit awkward.

The reason why ranking fails for arbitrary names is this, which, as you can see, also hasn't been changed in a very long time:
https://github.com/streamlink/streamlink/blame/3.1.1/src/streamlink/plugin/plugin.py#L60

I've commented several times here that the whole stream selection needs a major refactoring, because it is purely based on stream names, and those names are taken from the ordered dictionary's keys, which is pretty bad. A smart implementation would rank the streams in a list of streams via their attributes. That would be a major breaking change though and requires a lot of refactoring.
