### ISSUE TITLE
Brew version doesn't work while pip version works fine

### ISSUE THREAD

**Issue by imloualvaro** [streamlink/streamlink#4352]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

using same arguments it works fine using pip version, while cant do the same with homebrew

### Debug log

```text
streamlink http://www.twitch.tv/aceu best --twitch-disable-ads --twitch-disable-hosting --twitch-disable-reruns --twitch-low-latency --ringbuffer-size 256 --loglevel trace
[05:57:18.066586][cli][debug] OS:         macOS 11.6.2
[05:57:18.066844][cli][debug] Python:     3.10.2
[05:57:18.066956][cli][debug] Streamlink: 3.1.1
[05:57:18.067104][cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[05:57:18.067382][cli][debug] Arguments:
[05:57:18.067459][cli][debug]  url=http://www.twitch.tv/aceu
[05:57:18.067538][cli][debug]  stream=['best']
[05:57:18.067621][cli][debug]  --loglevel=trace
[05:57:18.067715][cli][debug]  --ringbuffer-size=256
[05:57:18.067835][cli][debug]  --twitch-disable-hosting=True
[05:57:18.067895][cli][debug]  --twitch-disable-ads=True
[05:57:18.067957][cli][debug]  --twitch-disable-reruns=True
[05:57:18.068012][cli][debug]  --twitch-low-latency=True
[05:57:18.068449][cli][info] Found matching plugin twitch for URL http://www.twitch.tv/aceu
[05:57:18.095170][plugins.twitch][debug] Getting live HLS streams for aceu
error: No playable streams found on this URL: http://www.twitch.tv/aceu
```

**Comment by bastimeyer** [comment]
Any kind of packaging except the official wheel on PyPi is done by third parties, and not by the Streamlink maintainers. If there are issues with a certain package that don't come up when installing Streamlink via pip, then you'll have to ask the package maintainers, unless you can show that it's indeed caused by the code here.

You are forcing an initial `http` request instead of `https` by explicitly setting the input URL to `http://www.twitch.tv/aceu` instead of `https://www.twitch.tv/aceu` or just `www.twitch.tv/aceu` / `twitch.tv/aceu`, so maybe try changing that.

Otherwise, take a look at the plugin code and see which of the API requests fail that are required for getting the stream URL:
https://github.com/streamlink/streamlink/blob/3.1.1/src/streamlink/plugins/twitch.py#L644

This is however not a Streamlink issue or plugin issue.

The stream is working perfectly fine in my macOS Catalina VM with streamlink installed via homebrew:
```
$ streamlink -l debug --stdout --twitch-disable-hosting --twitch-disable-ads --twitch-disable-reruns --twitch-low-latency --ringbuffer-size 256 http://www.twitch.tv/aceu best >/dev/null
[cli][debug] OS:         macOS 10.15.2
[cli][debug] Python:     3.10.2
[cli][debug] Streamlink: 3.1.1
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=http://www.twitch.tv/aceu
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --stdout=True
[cli][debug]  --ringbuffer-size=256
[cli][debug]  --twitch-disable-hosting=True
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-disable-reruns=True
[cli][debug]  --twitch-low-latency=True
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/aceu
[plugins.twitch][debug] Getting live HLS streams for aceu
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
```
