### ISSUE TITLE
plugin: session memory leak

### ISSUE THREAD

**Issue by justpaul** [streamlink/streamlink#4358]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Reproduce:
```python
import streamlink
import gc

s = streamlink.Streamlink()
del s
gc.collect()

len([obj for obj in gc.get_objects() if isinstance(obj, streamlink.Streamlink)]) == 1
```

@lru_cache used on a class method causes a memory leak:
```python
@lru_cache(maxsize=128)
    def resolve_url(self, url: str, follow_redirect: bool = True) -> Tuple[Type[Plugin], str]:
```
created sessions are not released from the memory.

### Debug log

```text
-
```

**Comment by bastimeyer** [comment]
Btw, I have no idea why the `Plugin.bind` classmethod was implemented (via 2e27f21a3eee8bfbc86135993c642853d6a37264 back in the Livestreamer days in 2013). It's not a particularly nice solution for storing the session on a plugin. It could very easily be done in each plugin's constructor method, especially now since we're returning plugin classes in the `resolve_url` method instead of plugin instances.

Changing that however would be a major breaking change. But since there are also plans for the plugin resolver to switch to a resolver that only operates on pre-built lists of URL regexes instead of loading all builtin plugins at once in order to access their URL regexes, it doesn't make much sense change the `Plugin.bind` method now.
