### ISSUE TITLE
plugins.twitch: The metadata is null for a few seconds after the stream starts.

### ISSUE THREAD

**Issue by B4TT3RY** [streamlink/streamlink#4411]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When I start the stream and run `streamlink --json https://twitch.tv/{STREAMER_ID}`, I get the result below.
```json
{
  "plugin": "twitch",
  "metadata": {
    "id": null,
    "author": null,
    "category": null,
    "title": null
  },
...
```

After a few seconds, it prints normally.
```json
{
  "plugin": "twitch",
  "metadata": {
    "id": "{ID}",
    "author": "{STREAMER_ID}",
    "category": "Just Chatting",
    "title": "Test"
  },
...
```

I tried to record a stream using the `--retry-streams` option, but when I set the file title using the metadata variable, it outputs a space in the file name because the metadata is null.

### Debug log

```text
`--json` option did not output Debug.
```

![image](https://user-images.githubusercontent.com/12368101/160631647-911a9a33-e3f8-4c92-84f0-4f86f5766ab2.png)
![image](https://user-images.githubusercontent.com/12368101/160631673-be8943f4-302d-47f6-8b23-91e3bc1be50f.png)

**Comment by bastimeyer** [comment]
That's not a Streamlink issue. Twitch simply doesn't provide the necessary data on their API. This might be caused by how they cache and propagate data in their network.

The same issue also occurs partially on Twitch's public "helix" API (eg. when querying followed streams, it often yields empty stream titles for newly started streams). Streamlink is however not using the helix API but Twitch's "GraphQL" API (GQL) instead, which is built for their website and which is needed for aquiring streaming access tokens.

But as said, this is an issue on Twitch's end, so there's nothing that can be done here.

If you need metadata for writing the stream output to the file system from streams which have just started, then wait until metadata is available.

This can easily be achieved with a wrapper script like this, where the first argument is the stream URL:

```bash
#!/usr/bin/env bash
set -eo pipefail

wait=3
max=3
n=1
while streamlink --json "$1" | jq -e '.metadata.id == null' 2>&1 >/dev/null; do
  [[ $n > $max ]] && exit 1
  echo "Metadata missing, waiting for $wait seconds ($n / $max)"
  n=$((n + 1))
  sleep $wait
done

streamlink "$@"
```

Something like this should however not be implemented into the plugin itself, because it doesn't care whether metadata is available (yet) or not. Its job is it to yield stream data as quickly as possible, without stalling and waiting for metadata which *might* be read by the user. Metadata availability is optional, and in this case an unfortunate issue on Twitch's end.

**Comment by B4TT3RY** [comment]
Thank you

**Comment by hanacchi** [comment]
I ran into the same issue a while ago. I think it'd be nice if at least the `author` and `id` fields could be set every time.
I'm not too familiar with streamlink's architecture but it I think it's possible to implement without waiting for the API to update.
author could be extracted from the URL and the broadcast id can be found in the `EXT-X-TWITCH-INFO` tag of the variant playlist.

**Comment by bastimeyer** [comment]
The plugin does not have access to the HLS playlist contents without re-implementing the entire `HLSStream.parse_variant_playlist` method, because its implementation is non-modular, unfortunately. And the author metadata is read from the user's "display name" data, not its "user name", which can differ, so input URLs don't provide any useful data. The reason for this is that the metadata is actually intended for player window titles, and not for file output paths, which is just an afterthought.

Since this is a rare edge case, I don't see fixing this or adding a workaround being important. Streamlink's focus is not on recording anyway.

**Comment by hanacchi** [comment]
Ah, that's fair enough then.

> HLSStream.parse_variant_playlist 

Thanks for the pointer! I'll see if I can figure something out for my personal use.

**Comment by nixxquality** [comment]
I just ran into this issue as well.

My feature request would be a `--require-metadata` option that would exit Streamlink if, when using the --output argument a substitution string was empty.

This would be a simple solution for me at least, since I'm already calling it in a sleep loop.

**Comment by bastimeyer** [comment]
No, the empty formatter variable stuff is intentional. That would be a pretty bad idea if users have set a generic `--title` or `--output` value in their config files and Streamlink would exit on every other input URL because other sites don't support metadata or only some.

A much better solution would be adding support for optional "conversion" flags via Streamlink's string formatter:
- https://docs.python.org/3/library/string.html#format-string-syntax
- https://github.com/streamlink/streamlink/blob/f0202598322692a757e9660c9d952ce689f7d606/src/streamlink/utils/formatter.py
- https://github.com/streamlink/streamlink/blob/f0202598322692a757e9660c9d952ce689f7d606/src/streamlink_cli/utils/formatter.py

Python's string formatting syntax allows variables in formatted strings to have a conversion flag, eg. `!r` for turning the value into its representation format via `repr()`. Since Streamlink's formatter simply ignores the conversion flag, custom logic could be added that accepts something like `!required` (or even `!r` as a shorthand flag) and which then raises an exception if the value is missing/empty, and streamlink_cli could catch that exception and exit (or the fetch loop could be extended).

**Comment by bastimeyer** [comment]
> we could skip the whole string formatting thing and only check if metadata exists at all

That does not work, because some plugins do only support a subset of the available metadata. If we check that something's not set, then this approach fails. If we check whether metadata is not set at all, then that's also a problem, because some plugins don't support any metadata, but the user could still have set the `{time}` variable and expects this to work.

As said, the formatter can be extended with conversion flags. In order to mark all variables that are set in the formatted string as required, so that adding a conversion flag to every variable is not needed, special syntax could even be added with an empty variable name at the beginning of the string that includes the conversion flag, like this:
`{!r}/tmp/recordings/{author}/{title}.ts`
Not 100% sure though if that's supported by the string formatter's parser.

**Comment by nixxquality** [comment]
In my opinion, if a user would run into that problem they should simply not use the argument, but your method sounds more reliable.
