### ISSUE TITLE
plugins.nicolive: Niconico login broken (404)

### ISSUE THREAD

**Issue by cddb222** [streamlink/streamlink#4539]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [ ] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

The niconico function using login is broken. This error is shown:
404 Client Error: Not Found for url: https://account.nicovideo.jp/

The plugin seems to be pointing to https://account.nicovideo.jp/login/redirector which does not work anymore.
Pointing to https://account.nicovideo.jp/login instead should solve the issue.

### Debug log

```text
Used syntax:
streamlink -o "output.ts" https://live.nicovideo.jp/watch/[video-ID] best --niconico-email [mailaddress] --niconico-password [PW]
```

**Comment by bastimeyer** [comment]
**Post the entire output when setting the `--loglevel=debug` parameter.**

The nicolive email logins were fixed recently in #4380. This looks like you're not using the latest version.

**Comment by cddb222** [comment]
> **Post the entire output when setting the `--loglevel=debug` parameter.**
> 
> The nicolive email logins were fixed recently in #4380. This looks like you're not using the latest version.

Full log:

`[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 4.0.1
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://live.nicovideo.jp/watch/lv336832924
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=output.ts
[cli][debug]  --ffmpeg-ffmpeg=C:\Users\xxx\AppData\Local\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --niconico-email=********
[cli][debug]  --niconico-password=********
[cli][info] Found matching plugin nicolive for URL https://live.nicovideo.jp/watch/lv336832924
[plugins.nicolive][info] Logging in via provided email and password
[plugins.nicolive][debug] unknown input: None
[plugins.nicolive][debug] unknown input: None
error: Unable to open URL: https://account.nicovideo.jp (404 Client Error: Not Found for url: https://account.nicovideo.jp/)`

**Comment by bastimeyer** [comment]
I can't reproduce this.

Invalid logins get caught, valid logins via email that require a confirmation code are working fine, and so are cached session cookies after a successful login.

Apart from that, the stream URL doesn't seem to require a login.

> [plugins.nicolive][info] Logging in via provided email and password
> [plugins.nicolive][debug] unknown input: None
> [plugins.nicolive][debug] unknown input: None
> error: Unable to open URL: https://account.nicovideo.jp/ (404 Client Error: Not Found for url: https://account.nicovideo.jp/)

This looks like you're seeing a different page after trying to logging in which the plugin can't handle. This might be caused by regional differences.

**Comment by cddb222** [comment]
> I can't reproduce this.
> 
> Invalid logins get caught, valid logins via email that require a confirmation code are working fine, and so are cached session cookies after a successful login.
> 
> Apart from that, the stream URL doesn't seem to require a login.
> 
> > [plugins.nicolive][info] Logging in via provided email and password
> > [plugins.nicolive][debug] unknown input: None
> > [plugins.nicolive][debug] unknown input: None
> > error: Unable to open URL: https://account.nicovideo.jp/ (404 Client Error: Not Found for url: https://account.nicovideo.jp/)
> 
> This looks like you're seeing a different page after trying to logging in which the plugin can't handle. This might be caused by regional differences.

The video has a "members-only" part in the second half that is not shown if you are a guest/non-member user. This is a "timeshift" archive video of a live-stream.
Regional should not be an issue, since I am accessing from Japan.

Please see line 161 in this file:
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/nicolive.py
The link "https://account.nicovideo.jp/login/redirector" when accessed from browser is giving the error straight away. Like mentioned in OP, changing this to https://account.nicovideo.jp/login might solve the issue. (I cannot do commits, sorry)

**Comment by bastimeyer** [comment]
https://account.nicovideo.jp/login/redirector is the target of the login form of https://account.nicovideo.jp/login, and it requires a POST request with the `mail_tel` and `password` parameters. The plugin is doing this correctly, as you can see here:
https://github.com/streamlink/streamlink/blob/473fda0a452745ea207dbcfec72bc83f7356bf99/src/streamlink/plugins/nicolive.py#L259-L263

As said, the issue is caused by the response of this request, which looks to be different in certain cases.

**Comment by back-to** [comment]
works with an IP from Europe,
does not work with an IP from Japan.

Plugin needs some changes.

**Comment by cddb222** [comment]
@bastimeyer 
Is this already part of the nightly build? Still getting the same issue with nightly #69 from here: https://github.com/streamlink/windows-installer/actions?query=event%3Aschedule+is%3Asuccess+branch%3Amaster

**Comment by bastimeyer** [comment]
@cddb222 
Post the entire **debug log output** ([`--loglevel=debug`](https://streamlink.github.io/latest/cli.html#cmdoption-loglevel)) and set [`--niconico-purge-credentials`](https://streamlink.github.io/latest/cli.html#cmdoption-niconico-purge-credentials).

**Comment by cddb222** [comment]
@bastimeyer 

Used syntax:
`streamlink -o "output.ts" https://live.nicovideo.jp/watch/lv337000198 best --niconico-purge-credentials --niconico-email a@b.com --niconico-password abc --loglevel=debug`

Debug output:
`[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 4.0.1
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://live.nicovideo.jp/watch/lv337000198
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=output.ts
[cli][debug]  --ffmpeg-ffmpeg=C:\Users\xxx\AppData\Local\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --niconico-email=********
[cli][debug]  --niconico-password=********
[cli][debug]  --niconico-purge-credentials=True
[plugins.nicolive][debug] Restored cookies: mfa_session, nicosid, user_session, user_session_secure, mfa_trusted_device_token
[cli][info] Found matching plugin nicolive for URL https://live.nicovideo.jp/watch/lv337000198
[plugins.nicolive][info] All credentials were successfully removed
[plugins.nicolive][info] Logging in via provided email and password
[plugins.nicolive][debug] unknown input: None
[plugins.nicolive][debug] unknown input: None
error: Unable to open URL: https://account.nicovideo.jp (404 Client Error: Not Found for url: https://account.nicovideo.jp/)`

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 4.0.1

You are not using the latest version.

**Comment by cddb222** [comment]
@bastimeyer 

It's the latest nightly build 69 from this link:
https://github.com/streamlink/windows-installer/actions?query=event%3Aschedule+is%3Asuccess+branch%3Amaster

![grafik](https://user-images.githubusercontent.com/106001814/170998891-44a152db-2834-468b-9210-a953822e46e4.png)

**Comment by cddb222** [comment]
@bastimeyer 
It's not a parallel install, this is the default installation on Windows:
![grafik](https://user-images.githubusercontent.com/106001814/171008485-cf167620-9a10-46e8-b15d-5633fc0e79bf.png)

And this is the actual nightly version, for some reason the debug output does not show the latest build number on Windows, just uninstalled, rebooted and re-installed and tested again, it still says [cli][debug] Streamlink: 4.0.1

**Comment by bastimeyer** [comment]
Whenever you execute a program name without an absolute or relative path, like `streamlink` instead of `C:\path\to\streamlink.exe` for exampe, your shell first needs to resolve the full path before it can execute it. This is done via the `PATH` environment variable. Depending on the contents of the `PATH` env var, a different `streamlink.exe` can get resolved first. Check your `PATH` env var by executing `echo %PATH%` or `echo $env:PATH` (depending on whether you're using cmd or powershell) to see which paths are defined. `where streamlink` or `(get-command streamlink).Path` will also show you the resolved path.
https://github.com/streamlink/windows-installer#notes

If the debug log is showing version `4.0.1` and not `4.0.1+N.gXXXXXXX`, then you are **not** using a nightly build and a stable release instead. Simple as that. This is deterministic and not "for some reason" an unknown issue. You must have installed the stable release. As I already told you, you should uninstall **everything** (both versions) if you're having trouble running the right version.

Since your streamlink install path is in your home directory, this suggests that there may be a system-wide streamlink install in parallel on your system (`C:\Program Files\` or `C:\Program Files (x86)\`) which gets resolved first, because its path is registered first in the `PATH` env var.

The latest nightly build shows the following debug output, which I have just checked in my Windows VM:
```
$ streamlink -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.3
[cli][debug] Streamlink: 4.0.1+55.g42f1112
```

In the pull request where I pinged you and asked if you could verify the plugin changes, I also suggested **sideloading** the updated plugin, so you don't need to install a separate nightly build. This is another option you have for running the latest version of the plugin.

This is all I can do for you to help you resolve your setup issues and I have given you enough hints on how to solve them. I don't want to spend more time on some user's setup issues. Good luck.

**Comment by cddb222** [comment]
@bastimeyer 
Thank you for the extensive reply, and my apologies for causing confusion.

Thanks to your advice I found an additional version of Streamlink within the Python folder, which also was part of the system path and took priority over the nightly regular install.
I wiped all Python and Streamlink files and made a completely fresh installation.

I can confirm the bug is fixed with the latest nightly, login is working as expected. Verified with a video that has a members-only part in the second half and was able to get the full video via Streamlink.

Again, my apologies for making you provide additional support, much appreciated.
