### ISSUE TITLE
Add generic m3u8 finder

### ISSUE THREAD

**Issue by BountyChocolate123456** [streamlink/streamlink#4560]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Some websites just have a expiring m3u. It would be nice to have one generic plugin that tries to extract it.

### Input URLs

e.g.

curl -s https://www.alsumaria.tv/live/video | grep -Eo 'https://[^ >]+playlist.m3u8'
curl -s 'https://www.mtv.com.lb/OneTV/Live' | grep -Eo 'https://[^ >]+playlist.m3u8'
curl -s 'https://www.otv.com.lb/new-live.php' | grep -Eo 'https://[^ >]+playlist.m3u8'

and it should be smart enough to extract m3u8 from json as well

curl -s https://aloula.faulio.com/api/v1/channels/1 

create a generic plugin that loads the url and then tries to extract a url that matches 'https://[^ >]+.m3u8' . This can be the streamlink fallback if no plugin is found

this translate to 
streamlink https://www.alsumaria.tv/live/video best
streamlink https://www.mtv.com.lb/OneTV/Live best
streamlink https://www.otv.com.lb/new-live.php best
streamlink https://aloula.faulio.com/api/v1/channels/1  best

**Comment by mkbloke** [comment]
I think this would have to be considered out of scope for Streamlink.  As Streamlink would only be parsing HTML without any JS active, it is better left to a browser extension that can search the page for streaming URLs.  Even those URLs found via such extensions may not be playable via Streamlink on their own due to a lack of cookies or certain HTTP headers that the server might expect.

**Comment by BountyChocolate123456** [comment]
OK, thank you
