### ISSUE TITLE
plugins.huya: recorded streams error "error: No plugin can handle URL"

### ISSUE THREAD

**Issue by Firwanaa** [streamlink/streamlink#4609]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Older "recorded" streams give the following error:

`error: No plugin can handle URL: https://v.huya.com/play/716796317.html
`

However, it works fine with the current **"live"** stream.
Example URL of live stream: 
`https://www.huya.com/20641`

### Debug log

```text
❯ streamlink https://v.huya.com/play/716796317.html best --loglevel debug
[cli][debug] OS:         Linux-5.18.5-arch1-1-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://v.huya.com/play/716796317.html
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv --cache=yes --demuxer-max-bytes=2048KiB
[cli][debug]  --player-no-close=True
[cli][debug]  --title={author} + {title}
error: No plugin can handle URL: https://v.huya.com/play/716796317.html
```

**Comment by bastimeyer** [comment]
v.huya.com uses a completely different backend from what it looks like

> However, it works fine with the current **"live"** stream.

The current plugin implementation uses progressive HTTP streams, which is kinda bad. Their website does so as well, but according to the parsed JSON data, HLS streams are available. I couldn't manage to get it to work though. The stream URLs are construction from four parts: the host, the stream name/ID, the stream file ending and additional query data. Both http and hls stream data attributes are provided in the same manner, but apparently the HLS streams require additional stuff. Without the website using HLS, it's hard to figure out, especially when their player's JS code is obfuscated and implemented in a rather messy way on top of that. There also seems to be some kind of URL refreshing logic.

> v.huya.com

HLS streams can be accessed via an API endpoint. In order to access it, some base64 encoded data needs to be passed as query data. And this data contains binary as well as text data. The API response then includes binary and text data as well, including HLS URLs which can be used by streamlink. So the challenge here is figuring out how to make the API calls and parsing the result.

**Comment by Firwanaa** [comment]
Currently, I'm able to extract links by using the Chrome extension [Open in VLC™ media player](https://chrome.google.com/webstore/detail/open-in-vlc-media-player/ihpiinojhnfhpdmmacgmpoonphhimkaj?hl=en) ([Github link](https://github.com/andy-portmen/open-in-vlc/)). It gives me a few links to open in VLC according to what video quality I choose, usually, the first link works and the rest are just 1-second random clips.

Using the extension for the same exact link I posted above gave me this:

![play-with-vlc](https://user-images.githubusercontent.com/65984781/174494066-fe8a94c7-f4a8-4488-8214-af5395ba6abe.png)

I was able to run the first [link](https://v-replay-tx.cdn.huya.com/record/huyalive/1199512718563-1199512718563-5226300799172214784-2399025560582-10057-A-0-1-imgplus_4000/2022-05-23-19:00:38_2022-05-24-00:04:16.m3u8?hyvid=716796317&hyauid=1199512718563&hyroomid=1199512718563&hyratio=4000&hyscence=vod&appid=66&domainid=17&srckey=NjZfMTdfNzE2Nzk2MzE3&bitrate=3906&client=81&definition=yuanhua&pid=1199512718563&scene=vodreplay&vid=716796317&&u=336642149&t=100&sv=2206161936) in both MPV and VLC.

Without changing quality settings:
![play-with-vlc2](https://user-images.githubusercontent.com/65984781/174494813-ed1d0a41-b5d8-4b43-98ec-dd9fd8bd84d4.png)

**Comment by bastimeyer** [comment]
Browser extensions can intercept network requests made by the browser, after its has run the site's JS code. Streamlink can't do that and it needs to parse HTML/JSON data and use regexes to extract data, and it needs to re-implement player logic in Python.

**Comment by back-to** [comment]
> No plugin can handle URL

VODs were never supported, adding them is not really important

closing
