### ISSUE TITLE
cli: option for running --player-external-http in "non-continuous" mode

### ISSUE THREAD

**Issue by nbgibson** [streamlink/streamlink#4738]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I frequently run streamlink with the `player-external-http` flags within a tmux session to have the ability to swap between devices. This works quite well, but I'll occasionally encounter errors where streamlink is still running idle off in a session somewhere long after the target stream has wrapped up. It would be nice if we could be able to customize behavior of the app when a target stream ends (or is down for X amount of time to allow for unintended disconnects on the source stream's end). 

The current behavior is largely fine for desktop use, but the ability to get more granular control would be appreciated for headless use cases.

**Comment by bastimeyer** [comment]
See #4739 for a proposed solution. Feedback welcome.

**Comment by WolfganP** [comment]
I also run streamlink in a headless mode with http serving, but didn't see cases where streamlink stays in the background if the origin stream ended, unless there's no consumption from the http client side (then streamlink is in idle state waiting but with no connection to the origin stream till an http client request comes thru).

Is https://github.com/streamlink/streamlink/pull/4739 targeting that use case?

**Comment by bastimeyer** [comment]
> didn't see cases where streamlink stays in the background if the origin stream ended

When Streamlink gets launched with the `--player-external-http` CLI argument, only the HTTP server gets started and it waits for HTTP requests to arrive in an infinite loop. HTTP requests then trigger the stream fetching+reading of the input URL and stream quality selection (only one request/client is handled at a time). If there's no HTTP request, then the server keeps running, and it also does so when a stream ends, where it waits for the next request, which then re-fetches the stream and starts outputting data anew. See the CLI argument help texts.

#4739 breaks the infinite HTTP request loop of the HTTP server once the stream ends if `--player-external-continuous-http=false` is set, which means it won't wait for additional requests and the streamlink process can terminate, which is the desired effect, only serve one stream attempt via HTTP and then stop, so that no idle streamlink processes remain.

**Comment by WolfganP** [comment]
> > didn't see cases where streamlink stays in the background if the origin stream ended
> 
> When Streamlink gets launched with the `--player-external-http` CLI argument, only the HTTP server gets started and it waits for HTTP requests to arrive in an infinite loop. HTTP requests then trigger the stream fetching+reading of the input URL and stream quality selection (only one request/client is handled at a time). If there's no HTTP request, then the server keeps running, and it also does so when a stream ends, where it waits for the next request, which then re-fetches the stream and starts outputting data anew. See the CLI argument help texts.
> 

Thx for the explanation, it matches my experience for the infinite loop for the http client request.

> #4739 breaks the infinite HTTP request loop of the HTTP server once the stream ends if `--player-external-continuous-http=false` is set, which means it won't wait for additional requests and the streamlink process can terminate, which is the desired effect, only serve one stream attempt via HTTP and then stop, so that no idle streamlink processes remain.

Thx again. So that means that the non-continuous functionality will break keeping the session open and switch devices (as the OP user case) and streamlink will need to be relaunched every time. Right?

**Comment by nbgibson** [comment]
Ok, I didn't have enough coffee this morning and misread/misunderstood things. @bastimeyer while #4739 will certainly prevent clashes from happening, it's not quite what I'm after. 

In a nutshell I'd like the existing functionality to remain as is, but with the tweak that once
```[cli][info] Stream ended``` is passed by SL we can optionally choose to have Streamlink kill the server and exit the process. I can likely script something to watch for this and kill the process as a result, but it would be preferrable to have it as a config option.

**Comment by bastimeyer** [comment]
I don't understand your confusion. If you're not sure what #4739 does, then install from the branch of the PR and test it yourself.
https://streamlink.github.io/install.html#pypi-package-and-source-code

> Keeping things running regardless of a connected client would be desirable in this use case.

It already does, because it doesn't check/download any streams if no client request was made. As I explained, when Streamlink is launched with `--player-external-http`, it'll **only** start the HTTP server and then wait. HTTP requests of any client **then** initiate the stream fetching/downloading and the data is written to the client response. If there's no HTTP request, then the server will stay alive. That also means that even if the run-mode is set to non-continuous via `--player-external-http-continuous=false` as added in #4739, Streamlink will keep running if no HTTP request was made. However, if a request was made and the stream has ended, the server will shut down and Streamlink's process will terminate, unlike in the default continuous mode, where it keeps running and waiting for the next client request, where it re-fetches the stream.

> I'll occasionally encounter errors where streamlink is still running idle off in a session somewhere long after the target stream has wrapped up. It would be nice if we could be able to customize behavior of the app when a target stream ends

This is exactly what #4739 does.

Continuous mode (default), with multiple requests, then terminated manually
```
$ streamlink --player-external-http --player-external-http-continuous=true --player-external-http-port=12345 youtube.com/hospitalrecords best
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:12345/
[cli][info] Got HTTP request from libmpv
[cli][info] Opening stream: 1080p (hls)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Got HTTP request from libmpv
[cli][info] Opening stream: 1080p (hls)
[cli][info] HTTP connection closed
[cli][info] Stream ended
^CInterrupted! Exiting...
[cli][info] Closing currently open stream...
```

Non-contionuous mode, only one request, which stops the server once the player closes its HTTP connection.
```
$ streamlink --player-external-http --player-external-http-continuous=false --player-external-http-port=12345 youtube.com/hospitalrecords best
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:12345/
[cli][info] Got HTTP request from libmpv
[cli][info] Opening stream: 1080p (hls)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Don't get confused by the `Closing currently open stream...` line, this is coming from somewhere else because the `Stream` instance does not get set to `None` in the HTTP stream transport logic (which it should, but I didn't change it in my PR).
