### ISSUE TITLE
plugins.tf1: add support for "stream" VODs

### ISSUE THREAD

**Issue by schumijo** [streamlink/streamlink#4793]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hi Team,

French channel provider TF1 launched a new AVOD service called "stream"
Maybe should be possible to upddate current plugin to support them.

### Input URLs

https://www.tf1.fr/stream/chante-69061019
https://www.tf1.fr/stream/thriller-fiction-89242722
https://www.tf1.fr/stream/classique-fiction-83644275
and a lot more....

**Comment by LaneSh4d0w** [comment]
URL presents itself like this : 

https://stream.tf1.fr/v1/v2l/prd-v2l-*showname*-*programID*/dash-hd.mpd?Expires=*time in epoch*&Signature=*most certainly a mixture of server data + account*&Key-Pair-Id=*linked to signature*

**Comment by BZHDeveloper** [comment]
dash url is invalid (only works on TF1 website)
hls url is valid

no account needed (don't understand this label)

in progress https://github.com/streamlink/streamlink/pull/4889

**Comment by mkbloke** [comment]
> no account needed (don't understand this label)

Are you using a French IP address?  When I added the label it was because I'd visited the site and it reported: `Pour regarder l’ensemble des replay et le direct sur MYTF1, il vous suffit de vous connecter !` (`To watch all replays and live on MYTF1, all you have to do is log in!`), but that was from a UK IP address.

Checking your updated plugin from a UK IP address:
```
$ streamlink -l debug 'https://www.tf1.fr/stream/chante-69061019'
[session][debug] Plugin tf1 is being overridden by /home/user/.local/share/streamlink/plugins/tf1.py
[cli][debug] OS:         Linux-5.4.0-125-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.0.1+17.gbfcd3725
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug]  importlib-metadata: 4.11.4
[cli][debug] Arguments:
[cli][debug]  url=https://www.tf1.fr/stream/chante-69061019
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/stream/chante-69061019
[plugins.tf1][debug] Found channel chante-69061019
error: No playable streams found on this URL: https://www.tf1.fr/stream/chante-69061019
```
So I guess it's due to an IP geo-restriction, which may or may not still  be enforced even when logged into an account, but I won't check that as I don't really want to create an account just for that purpose.

I'll remove the label.
