### ISSUE TITLE
A config setting or env var to use system python

### ISSUE THREAD

**Issue by brian6932** [streamlink/streamlink#4831]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Not sure if possible, but it would be nice to be able to use system python instead of the bundled python, like the `ffmpeg-ffmpeg` config setting, or maybe there is some env var that that could be set (or maybe one even exists and I just am ignorant).

For reference I'm talking about Windows 10, Idk if this is different by default on other platforms.

**Comment by gravyboat** [comment]
What purpose would this serve?

**Comment by brian6932** [comment]
Just for a lighter installation, if you already have python, why not just use that, you can delete the bundled python from your package if you don't want it.

**Comment by bastimeyer** [comment]
The whole idea behind the Windows builds is to bundle a Python install, same with the AppImages on Linux.

If you want to install Streamlink using your already existing system Python install, regardless which OS you're using, then install Streamlink via pip, preferrably in a virtual environment, so that it has a clean dependency tree.

https://streamlink.github.io/install.html#pypi-package-and-source-code
https://streamlink.github.io/install.html#virtual-environment

**Comment by brian6932** [comment]
I found a workaround anyway, symlinking Python works

**Comment by bastimeyer** [comment]
> symlinking Python works

No, that's a very stupid idea. This won't work because the dependencies which are bundled with the Windows installers or Windows portable builds **are built specifically for the bundled Python version**. If the bundled Python version gets changed and different wheels get pulled from PyPI for these dependencies (some include C extensions, like `lxml` and `pycyptodome`), then your system's Python environment you've symlinked won't be compatible unless you're using the exact same version.

As said, **if you're using your global system Python environenment, then use the appropriate package management of this environment, aka. `pip`, ideally in a clean virtual environment (`virtualenv`)**.

Read the links I've posted above.

**Comment by brian6932** [comment]
It does work

**Comment by bastimeyer** [comment]
> If I wanted to use pip, I already would've
> Just for a lighter installation, if you already have python, why not just use that, you can delete the bundled python from your package if you don't want it.

Doesn't make any sense. Good luck with your setup, but don't post any issues or bug reports with custom wonky setups like this. Those will be closed immediately.

Btw, if this is about the bundled FFmpeg binaries, they can be downloaded from [here](https://github.com/streamlink/FFmpeg-Builds), which means that when using a different Python environment, the Windows builds are completely pointless.
