### ISSUE TITLE
plugins.showroom: Once stream terminated, the m3u8 link rule will change and then Streamlink cannot catch it

### ISSUE THREAD

**Issue by DCxDESIGN** [streamlink/streamlink#4847]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

It might be caused by the rule change of SHOWROOM - when the stream is once terminated (usually a miss by the broadcaster or network issue of the broadcaster) and restarted again, Streamlink can't catch the stream.

Usually, the m3u8 link of a SHOWROOM room is like:

`https://hls-origin[***].showroom-cdn.com/liveedge/ngrp:[*key*]_all/chunklist_[*ID*].m3u8`

But when terminated and restarted again, the m3u8 link will (or might, I'm not sure it 100% will) be changed to:

`https://hls-origin[***].showroom-cdn.com/liveedge/[*key*]/chunklist.m3u8`

And then Streamlink can't catch it.

Here's the screenshot:
![SShot-20220923-163227-cmd](https://user-images.githubusercontent.com/48208459/191924065-69221652-e82a-4ecd-8a82-c2ad0619bce4.png)

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.showroom-live.com/r/46_kuboshiori
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --locale=ja_JP
[cli][debug]  --player=C:\Program Files (x86)\Pure Codec\x64\PotPlayerMini64.exe
[cli][debug]  --player-no-close=True
[cli][debug]  --retry-streams=3.0
[cli][debug]  --stream-segment-attempts=5
[cli][debug]  --stream-segment-threads=10
[cli][debug]  --stream-segment-timeout=1.5
[cli][debug]  --stream-timeout=600.0
[cli][debug]  --hls-live-restart=True
[cli][debug]  --http-proxy=http://127.0.0.1:7890
[cli][debug]  --http-header=[('referer', '')]
[cli][debug]  --twitch-disable-ads=True
[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/r/46_kuboshiori
[utils.l10n][debug] Language code: ja_JP
[cli][info] Waiting for streams, retrying every 3.0 second(s)
[utils.l10n][debug] Language code: ja_JP
[utils.l10n][debug] Language code: ja_JP
```

**Comment by bastimeyer** [comment]
The plugin correctly resolves the HLS stream URL with adaptive bitrates ("automatic" qualities), aka `hls_all`, as you can see here:
https://github.com/streamlink/streamlink/blob/5.0.1/src/streamlink/plugins/showroom.py#L76

If there's an issue with streams which have just come online, then this is probably the reason why, because the site is returning junk data. But that's not the problem of the plugin or Streamlink.

Example API response:
`https://www.showroom-live.com/api/live/streaming_url?room_id=ROOMID&abr_available=1`

```json
{
  "streaming_url_list": [
    {
      "url": "https://hls-origin249.showroom-cdn.com/liveedge/ngrp:SOMEHASH_all/playlist.m3u8",
      "id": 100,
      "type": "hls_all",
      "label": "Automatic"
    },
    {
      "url": "https://hls-origin249.showroom-cdn.com/liveedge/SOMEHASH_source/chunklist.m3u8",
      "type": "hls",
      "id": 2,
      "label": "original quality",
      "quality": 1000
    },
    {
      "url": "https://hls-ull.showroom-cdn.com/SOMEHASH/source/chunklist.m3u8",
      "type": "lhls",
      "id": 1,
      "label": "original quality",
      "quality": 1000
    },
    {
      "url": "https://hls-origin249.showroom-cdn.com/liveedge/SOMEHASH_low/chunklist.m3u8",
      "type": "hls",
      "id": 4,
      "label": "low quality",
      "quality": 100
    },
    {
      "url": "https://hls-ull.showroom-cdn.com/SOMEHASH/low/chunklist.m3u8",
      "type": "lhls",
      "id": 3,
      "label": "low quality",
      "quality": 100
    }
  ]
}
```

If the `abr_available=1` query string parameter doesn't get set, then the API response won't contain the "automatic" quality, which is a multivariant HLS playlist and the most ideal one to choose, as it contains all the streams with their quality labels and bitrates, and it also involves checking for geo restrictions.

If the plugin would not use the multivariant playlist, then each individual HLS media playlist would need to be returned by the plugin with a fitting quality name and stream weight.

Those issues are such rare edge cases that it's usually not worth spending the time on that and figuring out a workaround implementation. Same with Twitch for example which doesn't return any metadata for a few seconds after a stream has come live and which then causes problem for people trying to record stuff as soon as it comes lives, just like you.

You can fiddle around with these changes, but IMO, this makes the plugin worse, even if it returns more stream qualities to choose from:
https://github.com/bastimeyer/streamlink/commit/8def5476d68fbc0b174548f14998aa727924632a

**Comment by bastimeyer** [comment]
> But I still look forward to it.

JFYI, I won't be testing this myself at all. I've posted some changes which might help you, but it's up to you to test this. If this works, then we could merge the changes, but as said, IMO this is not an improvement.

**Comment by DCxDESIGN** [comment]
> > But I still look forward to it.
> 
> JFYI, I won't be testing this myself at all. I've posted some changes which might help you, but it's up to you to test this. If this works, then we could merge the changes, but as said, IMO this is not an improvement.

I fully understand what you mean and what my position should be. So I'm just expressing my naive wish, not making an order. 

I'm just a user with little common sense on developing and no more than that. That's why I submitted this issue instead of submitting a pull request.

**Comment by back-to** [comment]
impossible to reproduce,
all the livestreams got `hls_all` even the new ones

**Comment by wlerin** [comment]
In my opinion, the "automatic best" stream returned is not actually the best stream. Either of the "original quality" ones are preferred, hls if you're recording, lhls if you want to watch in as close to real time as possible.
