### ISSUE TITLE
Python v3.8 already installed

### ISSUE THREAD

**Issue by hellishvictor** [streamlink/streamlink#4856]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hi, 
I have already installed Python v3.8, and I wonder if there's a way to make StreamLink point to that location instead of the one used on its package, and if not, that would be a good implementation to add.
Cheers.

**Comment by bastimeyer** [comment]
Not sure what you are talking about.

> point to that location
> its package

The PyPI package? If you install streamlink via `pip` in your python environment, then it'll be installed in that python environment, as well as the `streamlink` entry point. If your `PATH` env var does not have the environment's `bin` directory (or `Scripts` if you're on Windows) added to its list, then invoking `streamlink` on the command line shell will of course not work unless you set a relative or absolute path (avoiding the `PATH` env var resolution).

If you're talking about any other package on any other operating system (you haven't mentioned anything in your post), then by design of these packages, the `streamlink` entry point will be made available. Those packages are completely unrelated to your local python environment when installing streamlink there.
