### ISSUE TITLE
CLI: Respond To Some POSIX Signal By Re-Evaluating Arguments For --output, --record, --title and --record-and-pipe

### ISSUE THREAD

**Issue by roryyamm** [streamlink/streamlink#4881]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

This is somewhat in the vein of #3214 and #1245, but is more general in its scope. Its primary goal is to allow for better segmented recordings, but has other potential uses, as well. 

Currently, splitting a stream based on duration requires killing and restarting Streamlink every interval via a wrapper. This technically gets the job done, but also requires Streamlink to re-acquire the stream for each segment - which results in downtime, no matter how fast re-acquisition can be done. This downtime leads to gaps in the recording - which is understandably undesirable if one is using -o to begin with. 

Rather than having a flag for splitting recordings, a more flexible alternative would be to have Streamlink respond to some POSIX signal (perhaps SIGUSR1 or SIGUSR2) in a way that would have it re-read and re-evaluate the arguments for `--title`, `--record`, `--output` and `--record-and-pipe` (especially any metadata tags like `{category}` and `{time}`) and apply them as soon as possible - without having to re-acquire the stream or kill the process completely. For recording, this would likely mean writing subsequent HLS or DASH segments to the new file specified. 

This may result in an unusable file for recording outside of raw MPEG-TS, but would allow for wrappers or other command-line programs to split recordings or update titles without interruption. This would allow for more than seamless recording - anything where metadata can change would be improved by the ability to update on an interrupt. 

A script using it for recording might look like this:
```
#!/bin/bash
streamlink -o {author}_{time:%Y-%m-%d-%H-%M-%S}.ts &
while true; do
   sleep 3600
   if [ ! ps -p $! >&- ]; then
       kill -SIGUSR1 $!
   else
       break
   fi
done
echo "Do what you want now"
exit 0
```

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/1245#issuecomment-331932004

Nothing has changed since this comment was posted. Recording is not the main focus of Streamlink and every time something new gets implemented in regards to recording, the next feature request is already on its way. This is a slippery slope and it's streching the goal of the project every single time. We have already discussed this multiple times.

Your feature request is on the same questionable level as #4786.

Going to close this. Send a pull request if you want this implemented.

What makes this even worse is that the state of `streamlink_cli` is a total mess, and adding more and more new edge-case features like this on top of this mess makes a rewrite/modernization of the module more and more difficult.
