### ISSUE TITLE
Stop creating "__pycache__" subfolders.

### ISSUE THREAD

**Issue by hellishvictor** [streamlink/streamlink#4897]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hi, 
Streamlink creates "__pycache__" subfolders on the pkgs folder; it seems that there's must be added "PYTHONDONTWRITEBYTECODE=1", but don't know where.
Cheers.

**Comment by bastimeyer** [comment]
1. Wrong repo. Packaging is not done here, and this issue does not belong here. You didn't even mention anything about your platform and which Streamlink distribution you're using.
2. Python bytecode gets written to `__pycache__` directories automatically by the Python interpreter unless the `PYTHONDONTWRITEBYTECODE` evironment variable is set.
3. In case you're talking about Windows portable archive (which is the only thing that makes sense from the context of your post), [writing bytecode upon first execution is done by design](https://github.com/streamlink/windows-builds#notes), and if you don't like this or if this is an issue for third-party packagers who base their streamlink package on the portable archives, then simply set the environment variable when launching streamlink. Optionally create a wrapper script.

**Comment by hellishvictor** [comment]
> then simply set the environment variable when launching streamlink. Optionally create a wrapper script.

Yes, and how can I do that?

**Comment by bastimeyer** [comment]
Depends on your used command line shell. Consult its manual or google it.

Any posix compliant shell:
```sh
export ENVVAR1=value1
ENVVAR2=value2 command parameters
```

FISH:
```fish
set -gx ENVVAR1=value1
ENVVAR2=value2 command parameters
```

Powershell:
```pwsh
$Env:ENVVAR1 = "value1"
$Env:ENVVAR2 = "value2"; command parameters; Remove-Item Env:\ENVVAR2
```

Windows CMD / batch script:
```batch
set "ENVVAR1=value1"
set "ENVVAR2=value2" & command parameters & set ENVVAR2=
```

**Comment by hellishvictor** [comment]
> Windows CMD / batch script:
> 
> ```batchfile
> set "ENVVAR1=value1"
> set "ENVVAR2=value2" & command parameters & set ENVVAR2=
> ```

Thank you, it worked with **set "PYTHONDONTWRITEBYTECODE=1"**. Hope that is permanent after reboot.
Cheers.

**Comment by bastimeyer** [comment]
> Hope that is permanent after reboot.

It is not. I believe setting env vars permanently can be done via `setx`, but I'm not sure, as I don't use Windows. Otherwise, use the Windows settings menus where you can set env vars. As said, google it.

**Comment by hellishvictor** [comment]
> It is not. I believe setting env vars permanently can be done via `setx`,

**"setx PYTHONDONTWRITEBYTECODE 1"** did it. Wish that can be done with just add that to a config.ini or something like that for the portable, but is better than nothing. You rule, man!
