### ISSUE TITLE
Twitch: Discarding midroll segments causes player freezes

### ISSUE THREAD

**Issue by brian6932** [streamlink/streamlink#4960]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

<details>
  <summary>I'm on MPC-HC 1.9.24 (ffe50c0c7)</summary>

```
MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.24 (ffe50c0c7)
    Compiler:           MSVC v19.29.30145
    Build date:         Nov 12 2022

LAV Filters:
    LAV Splitter:       0.77.0.1
    LAV Video:          0.77.0.1
    LAV Audio:          0.77.0.1
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0
```
    
</details>

~~Now this may or may not be a player issue, I'm not sure~~
~~I'll do some testing with other players, I have the latest mpvnet installed as well.~~

**EDIT**: Can confirm, the issue happens with mpvnet as well, however it doesn't drop frames, probably cause I config MPC-HC with no buffer.
With MPC-HC: Once the discarding stops, and the player unfreezes, it starts to constantly drop frames.
~~I'll try messing with config, maybe stuff like low latency is the culprit.~~
`twitch-low-latency` has no effect on this.

`-l all` logs: https://i.alienpls.org/ipD.txt

### Debug log

```text
The logs are pretty long, as I used `-l all`, so I'll sent them as their own file
```

**Comment by bastimeyer** [comment]
> Discarding midroll segments causes player freezes

What do you think will happen if the output pauses when advertisements get **filtered out** and there's no content for a short while?

Read the description of the `--twitch-disable-ads` parameter.

https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads

> Skip embedded advertisement segments at the beginning or during a stream. **Will cause these segments to be missing from the output.**

And read this
https://github.com/streamlink/streamlink/issues/4949

And most importantly, **READ THIS**
https://streamlink.github.io/latest/cli/plugins/twitch.html#embedded-ads

----

> Once the discarding stops, and the player unfreezes, it starts to constantly drop frames.

Yes, this is because of the stream discontinuity and broken bitstream with timestamp offsets. If your player can't recover from this, then use a different player. There is literally nothing which can be done here. Both ads and ads filtering causes a stream discontinuity, and filtering out ad stuff is less of an issue, because it's still the same stream, just with a gap of data and timestamps.

**Comment by bastimeyer** [comment]
This is the same as a stream discontinuity, and doesn't make any sense. Locking this thread, as it's not meant as a discussion thread. This was a duplicate/spam thread and the answers already existed in the sticky thread.
