### ISSUE TITLE
plugins.twitch: --twitch-disable-ads still/again not working correctly, purple screen showing

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4969]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Just had a purple screen again. This didn't happen the whole time the past few days while being on #4942 or on the master branch after the fixes were merged. This means that either something was missed, or something has changed just today on the side of Twitch. Really unfortunate timing, considering that we've just published 5.1.0.

I will be checking for logs now. If anyone wants to help, please upload compressed log files with the `--loglevel=all`, `--logfile=log.txt` and `--twitch-disable-ads` parameters set. Make sure to remove the existing log file when running streamlink multiple times. Logs should not be truncated at all, but it's important that it includes the important parts and not too much uninteresting data without any ad breaks.

### Debug log

```text
-
```

**Comment by KaMyKaSii** [comment]
@bastimeyer it wasn't a false alarm but it happens not so often. At least for me I saw it once when using the streamlink from your testing branch and it also happened twice today already using the last stable streamlink, but because it's not frequent it's hard to capture logs.
Returning to the issue of preventing ads instead of filtering them, what do you think about setting the api parameters to request the m3u8 link as closely as possible to the way Twitch's mobile app does? I have an Amazon prime account but besides that I'm not a subscriber of basically any channel I watch and even then I notice that in the app I get much less fullscreen ads (just to say none) than in the streamlink (even providing my token), maybe through the api that the app uses Twitch just doesn't provide embedded ads? I captured the app's traffic for a specific stream and the m3u8 link used is [here](https://pastebin.com/MGthQpxh). Opening this link on the computer directly in the mpv simultaneously with through the streamlink the difference is visible, even after an hour I did not receive any purple screen using the m3u8 link of the app and in the stream through the streamlink every 5 minutes the transmission pauses for around one or two minutes because of the ads. If you need more traffic data from the app then maybe I should email you as it contains my account tokens. Thanks!

**Comment by bastimeyer** [comment]
> it wasn't a false alarm

I have explained this pretty clearly why I was seeing a failure when filtering, and that was that I was accidentally running not up-to-date code in one of my dev environments. Simple as that.

> it happens not so often

I haven't seen any unfiltered segments since I've merged the fix, and I've had 100s of ad breaks of dozens of channels by now, all filtered out correctly. Post the log with the HLS playlist contents if you think that there's an actual issue. Every HLS playlist content I've observed during an ad transition had the same pattern, and the Twitch plugin's HLS subclass properly handles this, all with added tests according to the HLS playlist contents.

> Twitch's mobile app

I don't use the mobile app and I don't know which API it uses (very likely just the GQL API) and which API parameters or HTTP headers it sets when requesting an access token. The HLS playlist URL you've posted is the result of the GQL API response, so it's useless if you want to know how it was requested. Streamlink allows you to set and override any access token API request parameters it sets, which is basically just `playerType=embed` and the necessary `isLive`+`login` or `isVod`+`vodID` parameters. See the plugin docs and `--twitch-api-header`/`--twitch-access-token-param`.

If there is an **actual benefit** of changing the plugin defaults **which you can prove**, then this can be discussed in another thread.

Going to lock this now, as I don't want to turn this closed (and invalid) issue into a (different) discussion.

**Comment by bastimeyer** [comment]
missed that part:

> I have an Amazon prime account

So if you're logged into your Twitch account on the mobile app, then it'll most likely set the `Authorization` header on the access token API requests, which results in an access token where you don't see much ads, just as explained in the docs.
https://streamlink.github.io/cli/plugins/twitch.html
