### ISSUE TITLE
Feature: Option to skip Twitch pre-roll ads but keep the mid-rolls

### ISSUE THREAD

**Issue by mk-pmb** [streamlink/streamlink#4980]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

#4949 claims "all possible solutions and workarounds are mentioned above", but I couldn't find this one. I hope that starting the stream with the streamer's audio codec rather than the ad audio codec, will improve the audio experience in our default media player.
(In my case, a stream that starts with visible pre-roll has high-pitched, gap-ridden audio as soon as the streamer takes over. I assume this is due to a change in audio encoding. Tested with 0bda6e1f = 5.1.0, run on Ubuntu from a venv that was created by a dockerized pip.)
I know the other thread recommends using a better one, but I think we should try to accomodate our default as far as is easily possible.

Update: I managed to test standard HLS mode with a stream where there was no pre-roll. It started with a few seconds of real stream content, which had good audio. Then a "commercial break in progress", then again real stream, and again with good audio. I'm very optimistic now.

**Comment by bastimeyer** [comment]
The intention for `--twitch-disable-ads` is to prevent stream discontinuities between different streams, aka. the regular stream and ads. You never want to have stream discontinuities, and there is no reason whatsoever for having two separate filtering plugin parameters, one for pre-roll and one for mid-roll. Filtering the pre-rolls comes for free, because HLS streams can start at any segment due to the design of the MPEG-TS transport stream (or fragmented MPEG-4 stream with an initialization segment). Filtering mid-rolls however is necessary to avoid a broken stream output when the stream suddenly switches to a completely different format. When filtering out mid-roll ads, the only bad thing that happens during that particular discontinuity is a gap in the regular stream data with broken timestamp references, but this can be recovered from. That's why you need to use a player which can handle this.

Please stop requesting features in regards to Twitch ads. The situation has been explained several dozens of times, and not just over the past couple of days. It is enough now. I've even already linked you the explanation of Streamlink's limitation of outputting multiple streams that prevents handling discontinuities in HLS streams. Internally, this could be implemented with lots and lots of refactoring work, so that new output buffers get created every time a discontinuity happens, and the `Stream.open()` method could be turned into an interator for yielding more than one instance of `StreamIO`, but the issue would still be the player output and related stuff on the CLI side. The CLI's file output could theoretically be rewritten, but this would mean rewriting the entire CLI just for file outputs, which is not the purpose of Streamlink, so the motivation is even lower.
