### ISSUE TITLE
Locating win64 binaries requires clicking through entire internet first

### ISSUE THREAD

**Issue by sleepyspider1** [streamlink/streamlink#4987]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

If a user goes here: [https://github.com/streamlink](https://github.com/streamlink) looking for the streamlink binaries, they expect to be met with the same situation like every other project on github.
They expect to go to "releases" on the right hand side and get the binaries from there under each release per version.
But instead, they're met with a whopping 5 more sites/pages/clicks to navigate through before they can actually download the win64 binaries to install.

Solution: Reorganize the project so it's "normal" like very other project on github.

**Comment by bastimeyer** [comment]
> looking for the streamlink binaries

What are THE Streamlink binaries? This entirely depends on the user's operating system, their CPU architecture and their overall environment and needs. Streamlink provides only these three official binaries:

1. Python wheels, which are hosted on PyPI (and are meant for Python users and developers)
2. Windows installers and portable archives (for x86/x86_64 with a bundled py37 or py310 environment and FFmpeg), which are built in a separate repository
3. GNU/Linux AppImages (for x86_64, i686 and aarch64), which are also built in a separate repository

And in addition to that there are lots of other unofficial binaries built and distributed by third party package repositories, like various Linux distros, macOS, etc.

> If a user goes here: https://github.com/streamlink

This is not the place where users will go, because it's where all development repositories of the Streamlink organization are listed, which also includes other projects like Streamlink Twitch GUI for example. Not even search engines like Google lead the users to the GitHub organization URL.

**Users are supposed to go to Streamlink's documentation, which is linked pretty much everywhere important:**
https://streamlink.github.io/

From the start page of the docs it's (less than) four clicks to access every available official binary distribution.

This requires reading though, and most people don't like reading. Reading however is a requirement if you want to use Streamlink, as it's a CLI tool with a Python API. So if one doesn't want to read, then this is not the right tool for them.

Overloading every repository with tons of links doesn't solve what you're requesting, and we certainly won't make Windows users a priority here by including only Windows relevant stuff in readmes or repository descriptions, etc.

The Windows builds have been moved out of this repository intentionally, for reasons you can read here:
https://github.com/streamlink/streamlink/issues/4390
