### ISSUE TITLE
plugins.svtplay: No streams found on svt1+svt2

### ISSUE THREAD

**Issue by pfassberg** [streamlink/streamlink#4992]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

svt1 and svt2 don't work.  Kunskapskanalen still works.

```
[plugins.svtplay][debug] Path=/kanaler/svt1
[plugins.svtplay][debug] Live ID=ch-svt1
error: No playable streams found on this URL: https://www.svtplay.se/kanaler/svt1
```

One month ago it worked so something have changed since then.

### Debug log

```text
streamlink -l debug https://www.svtplay.se/kanaler/svt1
[cli][debug] OS:         Linux-5.15.56-v7l+-armv7l-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  PySocks: 1.7.1
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.6.3
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodomex: 3.9.7
[cli][debug]  requests: 2.25.1
[cli][debug]  websocket-client: 0.57.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.svtplay.se/kanaler/svt1
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin svtplay for URL https://www.svtplay.se/kanaler/svt1
[plugins.svtplay][debug] Path=/kanaler/svt1
[plugins.svtplay][debug] Live ID=ch-svt1
error: No playable streams found on this URL: https://www.svtplay.se/kanaler/svt1

Kunskapskanalen still works:
streamlink -l debug https://www.svtplay.se/kanaler/kunskapskanalen
[cli][debug] OS:         Linux-5.15.56-v7l+-armv7l-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  PySocks: 1.7.1
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.6.3
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodomex: 3.9.7
[cli][debug]  requests: 2.25.1
[cli][debug]  websocket-client: 0.57.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.svtplay.se/kanaler/kunskapskanalen
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin svtplay for URL https://www.svtplay.se/kanaler/kunskapskanalen
[plugins.svtplay][debug] Path=/kanaler/kunskapskanalen
[plugins.svtplay][debug] Live ID=ch-kunskapskanalen
[utils.l10n][debug] Language code: en_GB
[stream.dash][debug] Available languages for DASH audio streams: sv-x-tal, sv (using: sv)
Available streams: 234p (worst), 360p, 540p, 720p_alt, 720p (best)
```

**Comment by bastimeyer** [comment]
The plugin currently expects DASH streams for live content. The site's API however only returns HLS streams, with optional subtitles. This means that the plugin needs an update, and ideally a complete rewrite, because it's very much outdated.

The content however is geo-restricted, which is why nobody has updated the plugin yet. I'm surprised I was able to access the API and see the JSON response. I can't access the HLS playlists though, so even if someone with a VPN takes a look at rewriting the plugin, a confirmation will be needed before merging.

Btw, as a side note, you are not using the latest stable version, and the dependency versions of your currently used Streamlink version do not match Streamlink's requirements. For the SVT plugin though, this is not a problem. For others however and for other code part of Streamlink, it is. Not sure if you're using a system package of your distro's package manager, but if that's the case, then the packager should fix this.

**Comment by pfassberg** [comment]
Thanks bastimer,

I'm using the backports repo of Debian 11, I will contact the packager.

I can provide a VPN and/or proxy.
