### ISSUE TITLE
plugins.twitch: Show error message when the provided OAuth token is not valid

### ISSUE THREAD

**Issue by MrBrax** [streamlink/streamlink#5009]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I'd imagine the playlist server returning some kind of 403 error or similar when the authorization fails, and if this is the case, could there be an error message related to tokens instead of "No playable streams found"?
Would help with scripting a lot. Thanks.

**Comment by bastimeyer** [comment]
Twitch authentication is not an officially supported feature, otherwise we'd add back the dedicated `--twitch-oauth-token` CLI parameter for that. This is because of how the GQL OAuth token is obtained by the user and how there's no proper integrated authentication flow, like there was on kraken or how there is on helix.

Twitch's GQL API returns status code 200 if the `Authorization` header contains random garbage data when requesting a `PlaybackAccessToken`. If the header value however is in the format `OAuth token` and `token` is invalid, only then the response will be 401 with an appropriate JSON payload.

The Twitch plugin would need to handle this separately and therefore implement partial authentication support, which I don't think is a good idea.

If you want to automate unofficial authentication, then interact with Twitch's GQL API yourself and find a query where you can validate the OAuth token.

```sh
$ curl \
  -D - \
  -H 'Client-ID: kimne78kx3ncx6brgo4mv6wki5h1ko' \
  -H 'Authorization: invalid-data' \
  -d '{"operationName": "PlaybackAccessToken", "extensions": {"persistedQuery": {"version": 1, "sha256Hash": "0828119ded1c13477966434e15800ff57ddacf13ba1911c129dc2200705b0712"}}, "variables": {"isLive": true, "login": "...", "isVod": false, "vodID": "", "playerType": "embed"}}' \
  'https://gql.twitch.tv/gql'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 952
Content-Type: application/json
Access-Control-Allow-Origin: *
Date: Sat, 03 Dec 2022 13:07:38 GMT

{"data":{"streamPlaybackAccessToken":{"value":"...","signature":"...","__typename":"PlaybackAccessToken"}},"extensions":{"durationMilliseconds":57,"operationName":"PlaybackAccessToken","requestID":"..."}}
```

```sh
$ curl \
  -D - \
  -H 'Client-ID: kimne78kx3ncx6brgo4mv6wki5h1ko' \
  -H 'Authorization: OAuth invalid-token' \
  -d '{"operationName": "PlaybackAccessToken", "extensions": {"persistedQuery": {"version": 1, "sha256Hash": "0828119ded1c13477966434e15800ff57ddacf13ba1911c129dc2200705b0712"}}, "variables": {"isLive": true, "login": "...", "isVod": false, "vodID": "", "playerType": "embed"}}' \
  'https://gql.twitch.tv/gql'
HTTP/1.1 401 Unauthorized
Connection: keep-alive
Content-Length: 89
Content-Type: application/json
Access-Control-Allow-Origin: *
Date: Sat, 03 Dec 2022 13:07:53 GMT

{"error":"Unauthorized","status":401,"message":"The \"Authorization\" token is invalid."}
```

**Comment by MrBrax** [comment]
That is a good idea, thank you.

**Comment by bastimeyer** [comment]
Btw, we can add generic access token failure handling. I'll submit a PR later. I have already implemented it with some added tests.
