### ISSUE TITLE
Emoji support in stream title sent to VLC

### ISSUE THREAD

**Issue by TrantaLocked** [streamlink/streamlink#5029]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I asked on the VLC forum but they told me this is a Streamlink or Streamlink Twitch GUI problem but honestly I don't know which of the three projects would need to implement this. 

Emojis show as square boxes when the Twitch stream title is sent to VLC. I am requesting that emoji support be added (if this is something Streamlink can do).

**Comment by gravyboat** [comment]
This is either a problem with your machine because you don't have a font that supports the correct emoji or the player, not Streamlink. All we do is pass the title through to the player. If they aren't handling emoji interpretation correctly that is on them. As an example MPV is perfectly fine based on some random stream I found with a bunch of Emoji in the title:

Twitch:
![emoji_in_title](https://user-images.githubusercontent.com/1396878/207735369-4553c56c-d804-4329-8975-d0f9d3277af1.PNG)
MPV:
![emoji_in_title_mpv](https://user-images.githubusercontent.com/1396878/207735451-500eef5e-ab39-4316-84bd-6779bc110785.PNG)

As you can see the colors aren't there but the emoji itself is.

**Comment by TrantaLocked** [comment]
It's a VLC skin darkvoodoo that breaks emojis. That sucks as the way I set things up the skin is important.
