### ISSUE TITLE
Odysee

### ISSUE THREAD

**Issue by GUUser91** [streamlink/streamlink#5043]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Odysee is a video streaming website run by LBRY, Inc. It features livestreaming. It provides a variety of channels and videos that cover video games, finance, tech, sports, etc. Livestreaming videos aren't region locked and don't require an account to view it.

### Input URLs

The top section of this link below are livestreams. Their thumbnails have a red icon featuring a live viewer count.
https://odysee.com/$/rabbithole

**Comment by gravyboat** [comment]
I don't know about this one @bastimeyer, there's barely 500 people watching ALL of the live streams combined, doesn't seem worth the time to implement. This is the Wikipedia page for the company: https://en.wikipedia.org/wiki/LBRY. I would almost consider this a violation of rules 1, 2, 6 (to an extent), 7 based on a number of the streams, and 10 since these numbers are hilariously low.
