### ISSUE TITLE
Live Dash Multi Period Support

### ISSUE THREAD

**Issue by m0hamedessam** [streamlink/streamlink#5058]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Live Dash Multi Period Not Supported any plan to support it in the future.

**Comment by bastimeyer** [comment]
Streamlink will probably never support this, similar to #4535. Closing as a "duplicate", as it's the same issue, even though the linked thread is about HLS and not DASH.

**Comment by titus-au** [comment]
Hi bastimeyer, I've published a [dash streamlink plugin](https://github.com/titus-au/streamlink-plugin-dashdrm) which amongst other things implements multi period support. Eg, add an option that allows playing the last period instead of default first, which even without support for moving to the next period will allow playing some content that contains pre-rolls in the first few periods, then then actual content as the last period. Most of the comments you made in [#4535](https://github.com/streamlink/streamlink/issues/4535) of course still applies, but this at least allows to play some of the content. 

My question to you is would you want me to do a PR to add this to the mainline streamlink code, or you don't really want to go down this path given there'll obviously always be issues given the technical problems you raised.

**Comment by titus-au** [comment]
> Streamlink will probably never support this, similar to [#4535](https://github.com/streamlink/streamlink/issues/4535). Closing as a "duplicate", as it's the same issue, even though the linked thread is about HLS and not DASH.

Hi @bastimeyer, I've published a [dash streamlink plugin](https://github.com/titus-au/streamlink-plugin-dashdrm) which amongst other things implements multi period support. Eg, add an option that allows playing the last period instead of default first, which even without support for moving to the next period will allow playing some content that contains pre-rolls in the first few periods, then then actual content as the last period. Most of the comments you made in https://github.com/streamlink/streamlink/issues/4535 of course still applies, but this at least allows to play some of the content.

My question to you is would you want me to do a PR to add this to the mainline streamlink code, or you don't really want to go down this path given you said streamlink will probably never support this, there'll obviously always be issues given the technical problems you raised.

**Comment by bastimeyer** [comment]
Streamlink's `dash` plugin already supports the `period` parameter, which is passed to `DASHStream.parse_manifest()`, where the respective DASH period will be selected for playback:
- https://streamlink.github.io/cli/protocols.html#protocol-parameters
- https://github.com/streamlink/streamlink/blame/7.3.0/src/streamlink/plugins/dash.py#L13-L23
- https://github.com/streamlink/streamlink/blame/7.3.0/src/streamlink/plugins/dash.py#L40-L43

The question of this thread was "Multi Period", aka. outputting multiple periods one after another, hence my previous response with the HLS discontinuity issue thread.

```
streamlink -l debug "dash://URL period=123" best
```

**Comment by titus-au** [comment]
> Streamlink's `dash` plugin already supports the `period` parameter, which is passed to `DASHStream.parse_manifest()`, where the respective DASH period will be selected for playback:
> 
> * https://streamlink.github.io/cli/protocols.html#protocol-parameters
> * https://github.com/streamlink/streamlink/blame/7.3.0/src/streamlink/plugins/dash.py#L13-L23
> * https://github.com/streamlink/streamlink/blame/7.3.0/src/streamlink/plugins/dash.py#L40-L43
> 
> The question of this thread was "Multi Period", aka. outputting multiple periods one after another, hence my previous response with the HLS discontinuity issue thread.
> 
> ```
> streamlink -l debug "dash://URL period=123" best
> ```
> 
> `dash` plugin parameters were added in 4.0.0 via [9790ebc](https://github.com/streamlink/streamlink/commit/9790ebc479e9653df68969e9d64fb6b6bd7089a5)

Ah I didn't see the addition for period choice, excellent. What about code to move through the periods? Do you want a PR for it?

**Comment by bastimeyer** [comment]
No, thanks, because of #6346 and because this would introduce the same issue as HLS discontinuities, which are not supported by Streamlink, as it can only output a single stream. Non-continuous bitstream outputs should not actively be encouraged. Your implementation is also not ideal, which means that this wouldn't be merged in this state anyway, sorry.

**Comment by titus-au** [comment]
> No, thanks, because of [#6346](https://github.com/streamlink/streamlink/issues/6346) and because this would introduce the same issue as HLS discontinuities, which are not supported by Streamlink, as it can only output a single stream. Non-continuous bitstream outputs should not actively be encouraged. Your implementation is also not ideal, which means that this wouldn't be merged in this state anyway, sorry.

No worries mate. I know this is really a stop-gap and it's not ideal which is why I wanted to check whether you wanted a PR.
