### ISSUE TITLE
Add plugin: yupptv

### ISSUE THREAD

**Issue by digitalcelery** [streamlink/streamlink#506]
I am suspecting that cookies/token expires and I am no longer able to play the stream, not even a restart as it returns **`403 Client Error: Forbidden`**

Example of the links I am getting:

`http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/master.m3u8?hdnea=st%3d1485750135%7eexp%3d1485750495%7eacl%3d%2fi%2fams54_russiatoday%40349571%2f*%7edata%3d1814225%7ehmac%3da3a3c4227a1c121aca77c38e9c21252bd881a5a9d5c96d7851ac8f53bb56c2a7&dw=160`

Streaming url: 

`http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/master.m3u8`
Token?:

`hdnea=st%3d1485750135%7eexp%3d1485750495%7eacl%3d%2fi%2fams54_russiatoday%40349571%2f*%7edata%3d1814225%7ehmac%3da3a3c4227a1c121aca77c38e9c21252bd881a5a9d5c96d7851ac8f53bb56c2a7&dw=160`

Seems like there is linux epoch time that sets the expiry of the stream. So each time i need to login to the website and request new token.

I also know the following:
SWF: `http://d3hprka3kr08q2.cloudfront.net/staticstorage/jwplayer/jw_7_8_2/jwplayer.loader.swf`

Content of M3U8 file: 

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=87000,RESOLUTION=256x144,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_64_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=226000,RESOLUTION=384x216,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_200_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=403000,RESOLUTION=480x270,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_400_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=647000,RESOLUTION=512x288,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_800_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1233000,RESOLUTION=704x396,CODECS="avc1.66.30, mp4a.40.2"
http://hlsbanglanews-lh.akamaihd.net/i/ams54_russiatoday@349571/index_1100_av-p.m3u8?sd=10&dw=160&rebase=on&hdntl=exp=1485836971~acl=%2fi%2fams54_russiatoday%40349571%2f*~data=hdntl~hmac=a18a639e66837c960067f07eae81b129b3d20804fd69aaec598f138ab9321128
```

Also, few attributes such as "Referer" for the m3u8 stream.

Is it possible to somehow automate via streamlink the token request process? The website does require a log on in order to get the stream link.

**Comment by beardypig** [comment]
You will almost certainly need a plugin to do this. What is the website? 

Normally the Akamai HLS streams set a long token cookie, but there have been some streams where the long token doesn't work for the playlist. Not much you can do expect create a plugin to support the site.

**Comment by digitalcelery** [comment]
yupptv.com
How would I go about seeking help for the plugin? Not even sure where to look and who to ask...?

Thank you,

**Comment by beardypig** [comment]
You can request one here :-)

**Comment by digitalcelery** [comment]
Would it need to be as a new ticket?

**Comment by beardypig** [comment]
Just update the title of this one :)

**Comment by digitalcelery** [comment]
Done :)

**Comment by raulsifra** [comment]
Is there plugin for it to download:)

**Comment by raulsifra** [comment]
Can some help how to make plugin for it

**Comment by maanich** [comment]
anyluck with  yupptv.com plugin

**Comment by beardypig** [comment]
@digitalcelery @raulsifra @maanich sorry for the delay - I have created a plugin for yupptv. Maybe you can help test it? It’s on this PR #1805

**Comment by maanich** [comment]
what i need to do is to reinstall streamlink to try

Raja Imran Aslam

**Comment by maanich** [comment]
streamlink --YuppTv-email=xxx@gmail.com --YuppTv-password=xxxx --http-no-ssl-verify https://www.yupptv.com/channels/etv-telugu/live best

cant work whats the right format to do that


ido upgrade streamlink but looks like u hvnt implement it yet  please let me know how to upgrade streamlink with the plugin.

**Comment by beardypig** [comment]
The arguments should be lowercase, `--yupptv-email` and `--yupptv-password`. 

But, you'll have to manually install [yupptv.py](https://raw.githubusercontent.com/beardypig/streamlink/7bbfb2a79ffd3a9c692333d8242faf257139e3a5/src/streamlink/plugins/yupptv.py) to use the plugin, you will also need to "sideload" it. Please refer to the documentation on [sideloading plugins](https://streamlink.github.io/cli.html#sideloading-plugins).

**Comment by maanich** [comment]
git clone git://github.com/streamlink/streamlink.git


i added yupptv.py in streamlink/plugins manual to
/root/streamlink/src/streamlink/plugins/

then run this..

cd streamlink
python setup.py install


is it the right path or do i need some other way  thanks

Raja Imran Aslam

**Comment by beardypig** [comment]
@maanich that should work too :) If you do `streamlink --help` are the `yupptv` options listed?

**Comment by maanich** [comment]
streamlink --yupptv-email xxxx@gmail.com --yupptv-password xxxx4
--http-no-ssl-verify https://www.yupptv.com/channels/etv-telugu/live
--player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec
copy -acodec copy -flags -global_header -hls_flags delete_segments
-hls_time 10 -hls_list_size 6 /mnt/hls/ind.m3u8
ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c)
2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static
--disable-debug --disable-ffplay --disable-indev=sndio
--disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig
--enable-frei0r --enable-gnutls --enable-gray --enable-libaom
--enable-libfribidi --enable-libass --enable-libfreetype
--enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopenjpeg --enable-librubberband --enable-libsoxr
--enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora
--enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx
--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2
--enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --yupptv-email --yupptv-password
xxxx4 https://www.yupptv.com/channels/etv-telugu/live
pipe:0: Invalid data found when processing input


errro for yupptv-email here no username shown but pyupptv-passwird shows
password

can u please check wether i got yupttv plugn installed or any command to
check instaaled plugins specially sideloaded

Raja Imran Aslam

**Comment by maanich** [comment]
yupptv option not shown with help

Raja Imran Aslam

**Comment by beardypig** [comment]
[--plugins](https://streamlink.github.io/cli.html#cmdoption-plugins) - the docs are your friend.

**Comment by maanich** [comment]
while compiling


byte-compiling build/bdist.linux-x86_64/egg/streamlink/plugins/vaughnlive.py
to vaughnlive.pyc
byte-compiling build/bdist.linux-x86_64/egg/streamlink/plugins/yupptv.py to
yupptv.pyc
byte-compiling build/bdist.linux-x86_64/egg/streamlink/plugins/__init__.py
to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/streamlink/plugins/camsoda.py
to camsoda.pyc

copying build/lib.linux-x86_64-2.7/streamlink/plugins/vaughnlive.py ->
build/bdist.linux-x86_64/egg/streamlink/plugins
copying build/lib.linux-x86_64-2.7/streamlink/plugins/yupptv.py ->
build/bdist.linux-x86_64/egg/streamlink/plugins
copying build/lib.linux-x86_64-2.7/streamlink/plugins/__init__.py ->
build/bdist.linux-x86_64/egg/streamlink/plugins
copying build/lib.linux-x86_64-2.7/streamlink/plugins/camsoda.py ->
build/bdist.linux-x86_64/egg/streamlink/plugins


but help option not  showing yupp option.

yuuptv-email option not showing in yupptv.py  is that the probelm as that
option can be seen in other plugins


Raja Imran Aslam

**Comment by beardypig** [comment]
Can you provide a debug log? (include the `-l debug` option.)

**Comment by maanich** [comment]
streamlink -l debug --yupptv-email xxxx@gmail.com --yupptv-passwordrrrrrr
--http-no-ssl-verify https://www.yupptv.com/channels/bbo/live best
--player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec
copy -acodec copy -flags -global_header -hls_flags delete_segments
-hls_time 10 -hls_list_size 6 /mnt/hls/ind.m3u8
ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c)
2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static
--disable-debug --disable-ffplay --disable-indev=sndio
--disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig
--enable-frei0r --enable-gnutls --enable-gray --enable-libaom
--enable-libfribidi --enable-libass --enable-libfreetype
--enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
--enable-libopenjpeg --enable-librubberband --enable-libsoxr
--enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora
--enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx
--enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2
--enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:
 Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 0.13.0+35.g933126d
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin yupptv for URL
https://www.yupptv.com/channels/bbo/live
[cli][debug] Plugin specific arguments:
[cli][debug]  --yupptv-email=xxxx@gmail.com (email)
[cli][debug]  --yupptv-password=******** (password)
[plugin.yupptv][info] Logging out on other device: cc5ffee6e93142e6
[plugin.yupptv][info] Logged in as xxxx@gmail.com
[plugin.yupptv][error] This stream requires a subscription
error: No playable streams found on this URL:
https://www.yupptv.com/channels/bbo/live
pipe:0: Invalid data found when processing input


Raja Imran Aslam

**Comment by maanich** [comment]
as i told that in local pc is fine i logged in with same account but same account in vps it says need subscription.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 16/06/2018  02:22  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [streamlink/streamlink] Add plugin: yupptv (#506) 
@maanich that stream requires a subscription, do you have a subscription?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/506#issuecomment-397776735","url":"https://github.com/streamlink/streamlink/issues/506#issuecomment-397776735","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #506: @maanich that stream requires a subscription, do you have a subscription? "}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/506#issuecomment-397776735"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] Add plugin: yupptv (#506)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 506,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 506\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/506#issuecomment-397776735"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 197404641\n}"
}
],
"themeColor": "26292E"
}

**Comment by beardypig** [comment]
I don’t have a subscription, so it’s hard to debug. Make sure you are logged out on the other devices first. It might be because you were logged in on a different IP address shortly before. Try logging out of on your local pc, leaving it 5 minutes, then try on the vps.

**Comment by maanich** [comment]
do u think ip block can be the issue but i tried on three different vps all
start with 62.210 .xxxxx   will it be the case. or if i  send u the account
privately to debug.

Raja Imran Aslam

**Comment by beardypig** [comment]
@maanich, you can send it - but I won't be able to help until next week now. My email address is on my GitHub profile page.

**Comment by beardypig** [comment]
@maanich If you still want to send me the account you can do so, my email address if on my public github profile.

**Comment by maanich** [comment]
ok i will s3nd u in 30 min


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: beardypig <notifications@github.com> Date: 19/06/2018  11:34  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [streamlink/streamlink] Add plugin: yupptv (#506) 
@maanich If you still want to send me the account you can do so, my email address if on my public github profile.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/506#issuecomment-398353485","url":"https://github.com/streamlink/streamlink/issues/506#issuecomment-398353485","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beardypig in #506: @maanich If you still want to send me the account you can do so, my email address if on my public github profile. "}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/506#issuecomment-398353485"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] Add plugin: yupptv (#506)",
"sections": [
{
"text": "",
"activityTitle": "**beardypig**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beardypig",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 506,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 506\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/506#issuecomment-398353485"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 197404641\n}"
}
],
"themeColor": "26292E"
}
