### ISSUE TITLE
[Features Request] Two minor twitch ad related features

### ISSUE THREAD

**Issue by gyvess** [streamlink/streamlink#5272]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I'd like to see two separate features added for Streamlink. I use mpv as my player by the way.

* **Immediate Player Opening**
    Currently opening a Twitch stream almost always incurs pre-roll ads. In my experience this delays the player from opening by about ~15 seconds. I would like to player to be launched immediately, even if shows a black screen or the pre-roll placeholder. That way the player won't open while I'm doing something else or there is no extended wait to adjust/place the window.

* **OSD Ad Warning Message**
    While you have a stream opened and playing, if an ad is triggered the video is simply frozen. It'd be nice if Streamlink could send persistent OSD message telling you the stream has been interrupted by an ad. This way you can know for sure an ad is playing, and isn't instead some sort of network error or accidental pause of the player.

**Comment by bastimeyer** [comment]
> Immediate Player Opening

Opening the stream first is very much intentional, for several reasons:

1. Attempting to open the stream can result in an error, so opening the player first can lead to issues and a bad user experience, for example if `--player-no-close` was set. Streamlink therefore must open and read data first before launching the player process.
   https://github.com/streamlink/streamlink/blob/a5a12c63e58fb701f363c0871fdd7a5e5eff67ab/src/streamlink_cli/main.py#L318-L319
2. File outputs need to be able to prompt for user confirmation if the chosen path already exists. Otherwise, the stream gets opened unnecessarily and can fill the ring-buffer until the confirmation was made, which can lead to buffer congestion issues depending on the download speed and size of the buffer.
   https://github.com/streamlink/streamlink/blob/a5a12c63e58fb701f363c0871fdd7a5e5eff67ab/src/streamlink_cli/main.py#L338

When opening the stream and reading, the ads filtering blocks those read calls until data is available. I am aware that this is an issue when filtering out pre-roll ads, but as I've just shown you, this issue is insignificant compared to the other ones mentioned.

If you don't want to wait for the player to open until data is available, then launch the player process yourself and let Streamlink pipe into that:

```sh
streamlink --stdout ... | "$PLAYER" -
```

> OSD Ad Warning Message

Streamlink is a CLI application. Something like desktop notifications won't be implemented for not just this reason. Also not to mention that this varies drastically between each OS and its configuration.

Filtering ads and resuming the output already gets logged to the `info` log channel by the HLS filtering implementation, as you can see here:

- https://github.com/streamlink/streamlink/blob/a5a12c63e58fb701f363c0871fdd7a5e5eff67ab/src/streamlink/stream/hls.py#L236-L239
- https://github.com/streamlink/streamlink/blob/a5a12c63e58fb701f363c0871fdd7a5e5eff67ab/src/streamlink/stream/hls.py#L224-L227

**Comment by gyvess** [comment]
Fair enough, but I should have been more clear so I wanted the clarify a little bit. When opening a live twitch stream with `yt-dlp` the player opens within a few seconds to display the multicolored stock twitch "Commercial break in progress" message. I was hoping for an argument more in line with doing that. However, `yt-dlp` is not as latency sensitive as `streamlink` is of course so I can see how that would not be possible.

Also, I shouldn't have used an acronym here. OSD means On-Screen Display. I didn't mean desktop notifications as that would be unnecessarily complicated, but the messaging system within the player itself or maybe even subtitles. I know `syncplay` is able to display/send messages within both `mpv`  and `vlc`, so I thought something similar would be possible here. Oh well.

**Comment by bastimeyer** [comment]
> the player opens within a few seconds to display the multicolored stock twitch "Commercial break in progress" message

Then don't set `--twitch-disable-ads` if you want to see that screen. Simple as that.
https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads
https://streamlink.github.io/cli/plugins/twitch.html#embedded-ads

> but the messaging system within the player itself

Streamlink allows users to set arbitrary players, so this would be specific to only a subset of players.

> maybe even subtitles

There is no muxing being done when watching Twitch streams. And dynamic embedding of subtitle data would be rather difficult and also not useful considering that the entire output stops when ads are encountered.

**Comment by nicktelford** [comment]
@bastimeyer 

I just wanted to elaborate a bit on this issue. Although I actually think it's two distinct (albeit related) issues, so I will address them separately.

### Immedate Player Launch

Now that streamlink _always_ filters Twitch ads, and pre-rolls occur when opening most streams, it's quite jarring to have to wait ~15 seconds for the player window to open, because:

1. It can affect window placement, especially with multi-monitor or tiling window manager setups.
2. It can steal focus from the user, who may have moved on to another task while waiting.

So I think it would be highly desirable to at least offer the user the _option_ of opening the player before the pre-roll ads have been completed.

> Attempting to open the stream can result in an error, so opening the player first can lead to issues and a bad user experience, for example if --player-no-close was set. Streamlink therefore must open and read data first before launching the player process.

By the point that streamlink is filtering ads, we know that the stream has connected and is free of errors, so it would be reasonable to open the player at this point imo.

It's notable that, depending on the player, launching the player when the video stream contains no output may not actually open a window. For example, with `mpv` you need to include the `--force-window=immediate` option to have it display a window before output is available from Streamlink.

> If you don't want to wait for the player to open until data is available, then launch the player process yourself and let Streamlink pipe into that

You can, and it works well. However, this precludes integration with streamlink-twitch-gui, which uses `--player` to launch the player.

### On-screen Notification of Ads

This is a cool idea, but it might not be possible without muxing into the stream data, which obviously streamlink doesn't want to do.

One thing that _is_ possible, if using `mpv` as your player, is to make use of its ability to show _images_ in its playlist. A quirk of MPV is that, when it moves onto the next track in the playlist, it will continue to display the current frame until it receives stream data.

So, you can _at least_ display a notification during pre-roll ads by doing something like this:
```
streamlink --stdout twitch.tv/<channel> | mpv --image-display-duration=1 stream-load-notification.png -
```

Where `stream-load-notification.png` is an image displaying a message about pre-roll ads or "stream loading" etc. This message will display for a minimum of 1 second (configured by `--image-display-duarion=1`), and will remain on-screen until `streamlink` starts sending through stream data.

Note: this doesn't work if launching via `--player`, because streamlink won't even launch MPV until the pre-roll ads have ended (see above).

Unfortunately, I don't think this approach can be used to have MPV display a message for AD rolls _mid-stream_. If MPV had a way to automatically advance the playlist whenever no video data is received for N milliseconds, you could just loop the playlist and it would switch back to the "stream loading" image until more data was received. But alas, I have not found a way to configure MPV to do that.

I realise I've talked a lot about MPV here. It might be possible to do something similar with VLC and/or other media players, but I haven't looked into it. There are already several streamlink options that are specific to certain players, so it wouldn't be a huge problem to have an option that, for example, automatically adds a stream load notification image to the MPV playlist (as above).

**Comment by bastimeyer** [comment]
> Immedate Player Launch

The issue is that Streamlink's CLI always attempts to read / "pre-buffer" 8 KiB of stream data before opening the output. Streamlink's ad filtering, or rather the ability to pause the stream output, was added in its first iteration years later (6b22aca) on top of the old pre-buffering implementation, which still stems from the livestreamer era:

- https://github.com/streamlink/streamlink/blame/7.5.0/src/streamlink_cli/main.py#L338-L366
- https://github.com/streamlink/streamlink/blame/7.5.0/src/streamlink_cli/main.py#L396-L412
- https://github.com/streamlink/streamlink/blame/7.5.0/src/streamlink_cli/main.py#L280-L292

Pre-buffering is still the right thing to do, to prevent opening the output (which doesn't necessarily have to be a player process btw) if the stream doesn't return any data. Since there's no communication method between the pre-buffering `stream_fd.read()` call and the actual stream implementation (HLS, DASH, etc), as data is read from the `RingBuffer` object that's shared between those threads, the only way to ensure that data is or will be available is reading those initial 8 KiB of stream data. The individual stream implementations, and thus also the ad filtering mechanism, are unknown the to consumer thread, which is the CLI's main thread.

What would need to be done is adding a `threading.Event` to the `RingBuffer`'s base class `Buffer` which signals that data is or will be available, in addition to its `written_once` boolean attribute which is used to suppress a warning message in certain cases during stream discontinuities in segmented streams like HLS. The producer thread which writes to the ring-buffer (the filtering `Stream` instance) could then set the event ahead of time when filtering pre-roll ads, even though no data has been written to the ring-buffer yet. Then the consumer thread (the CLI) doesn't have to rely on the initial `read()` call and the 8 KiB of stream data, and it can simply await this event instead.

I'm not sure about adding a CLI argument for letting the user choose, as it'd bloat up the list of CLI arguments. However, opening the player process without data might be problematic for two reasons. First, this may confuse users who won't see Streamlink's log output with the filtering of pre-roll ads, and second, this may cause problems with certain players which require data to be read from their stdin pipe (in a certain amount of time) when launching the player process with the stdin argument. And related to the second issue is what you've mentioned with mpv and the required launch argument for making the window show up without stream data.

As you can see, this isn't trivial and requires some deeper changes and certain decisions to be made.

> On-screen Notification of Ads

I've already added explicit log messages to the Twitch plugin several versions back which also log the expected duration of the advertisement segment.

In regards to the Twitch GUI, since you've opened an issue there today first, I had started work on parsing these log messages and showing a countdown in the stream's popup/dialog, but I never finished it, because adding new features to this terribly old code is annoying. I've already said multiple times that this project is not actively maintained by me anymore and just kept alive with minimal effort.

**Comment by nicktelford** [comment]
@bastimeyer 

> The issue is that Streamlink's CLI always attempts to read / "pre-buffer" 8 KiB of stream data before opening the output.

I had a feeling this was the case 😄 

> I've already said multiple times that this project is not actively maintained by me anymore and just kept alive with minimal effort.

My apologies, I didn't realise!

After I sent my comment earlier, I realised that streamlink-twitch-gui allows you to provide an explicit path to the `streamlink` executable... which can be (ab)used to provide a wrapper that does some tricks to get 90% of the way towards the requests in this ticket: https://gist.github.com/nicktelford/f2c6b76e4a3f00cf25abec795ce78665

It's not quite perfect, and being a BASH script might not be the most portable solution, but it's a reasonable proof-of-concept, and others may find it useful. 😄 

The main thing that's missing is some way to get mpv to automatically advance the playlist whenever the stream is interrupted (i.e. during ads), which would enable it to automatically switch back to the "loading" screen.
