### ISSUE TITLE
Any way to auto archive a twitch channel for when it does start a stream?

### ISSUE THREAD

**Issue by gameinn1** [streamlink/streamlink#5383]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Some way of being able to put a streamlink cli command that will routinely check to see if a channel is live (say every 5 minutes) and then will begin automatically archiving that stream once the streamer goes live. I have this command currently:

streamlink -o D:\TwitchLive\{author}-{title}({id}).mp4 --twitch-disable-ads --twitch-disable-hosting https://www.twitch.tv/streamer 720p,720p60,best

But obviously this only works if I am actually there to input the command when the streamer is live. If you're wondering why, some streamers don't have vods and unless I'm at the PC I will miss it completely. So ideally you would put a command like:

streamlink -o D:\TwitchLive\{author}-{title}({id}).mp4 --twitch-disable-ads --twitch-disable-hosting --twitch-streamcheckinterval-5 https://www.twitch.tv/streamer 720p,720p60,best

Yes I just made --twitch-streamcheckinterval-5 up but you get the idea. It's also a good idea having something like this because if a streamer has a disconnection early on in the stream then the streamlink will stop recording. This way even if a streamer did end broadcast for say a minute and restarted back up, you could easily archive what you would have missed.

**Comment by bastimeyer** [comment]
- https://streamlink.github.io/cli.html#cmdoption-retry-streams
- https://streamlink.github.io/cli.html#cmdoption-retry-max

Twitch does have a metadata issue though, so you'll have to write a shell wrapper script.
https://github.com/streamlink/streamlink/issues/4411#issuecomment-1081965952

**Comment by gameinn1** [comment]
> * https://streamlink.github.io/cli.html#cmdoption-retry-streams
> * https://streamlink.github.io/cli.html#cmdoption-retry-max
> 
> Twitch does have a metadata issue though, so you'll have to write a shell wrapper script. [#4411 (comment)](https://github.com/streamlink/streamlink/issues/4411#issuecomment-1081965952)

What happens if I don't have this script? Will it still record video locally just with a weird filename or something instead?

**Comment by bastimeyer** [comment]
This is already explained in the linked threads and all the other threads which reference this one (see the thread's timeline).

Let me repeat this again:
The value of the `{id}`, `{author}`, `{category}` and `{title}` variables will be empty sometimes, because Twitch doesn't publish the values on their API in time when the channel goes live, hence the shell script workaround which checks the metadata values from streamlink's JSON output and loops until they are available. If you don't use those metadata variables, then you don't have to worry. Just use the `{time}` variable for having unique file names or let your shell generate unique file names.
https://streamlink.github.io/cli/metadata.html
