### ISSUE TITLE
plugins.filmon: Not working SSL: WRONG_SIGNATURE_TYPE

### ISSUE THREAD

**Issue by UltraHDR** [streamlink/streamlink#5425]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Plugin doesn't work

```
streamlink https://www.filmon.tv/tv/bbc-world-news best
streamlink https://www.filmon.tv/tv/bbc-one best
```

### Debug log

```text
pi@raspberrypi:~ $ streamlink https://www.filmon.tv/tv/bbc-world-news best --loglevel=debug
[cli][debug] OS:         Linux-6.1.21-v8+-aarch64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 5.5.1+52.g272a846e
[cli][debug] Dependencies:
[cli][debug]  certifi: 2020.6.20
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.2
[cli][debug]  urllib3: 1.26.5
[cli][debug]  websocket-client: 1.5.1
[cli][debug]  importlib-metadata: 6.6.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.filmon.tv/tv/bbc-world-news
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin filmon for URL https://www.filmon.tv/tv/bbc-world-news
error: Unable to open URL: https://www.filmon.tv/tv/bbc-world-news (HTTPSConnectionPool(host='www.filmon.tv', port=443): Max retries exceeded with url: /tv/bbc-world-news (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1123)'))))
pi@raspberrypi:~ $
```

**Comment by bastimeyer** [comment]
This is a TLS misconfiguration on their end.

You can see the same issue when using `curl`:
```
curl 'https://www.filmon.tv/tv/bbc-world-news'
curl: (35) OpenSSL/3.1.1: error:0A000172:SSL routines::wrong signature type
```

Or when checking the TLS connection using OpenSSL directly:
```
$ openssl s_client -connect www.filmon.tv:443 -verify_return_error
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = *.filmon.tv
verify return:1
40D7B48E9D7F0000:error:0A000172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1573:
---
Certificate chain
 0 s:CN = *.filmon.tv
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 17 16:35:50 2023 GMT; NotAfter: Sep 15 16:35:49 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
 3 s:CN = *.filmon.com
   i:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 28 00:00:00 2022 GMT; NotAfter: Sep 28 23:59:59 2023 GMT
 4 s:C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
   i:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA384
   v:NotBefore: Nov  2 00:00:00 2018 GMT; NotAfter: Dec 31 23:59:59 2030 GMT
 5 s:C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA384
   v:NotBefore: Mar 12 00:00:00 2019 GMT; NotAfter: Dec 31 23:59:59 2028 GMT
 6 s:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
   i:C = GB, ST = Greater Manchester, L = Salford, O = Comodo CA Limited, CN = AAA Certificate Services
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA1
   v:NotBefore: Jan  1 00:00:00 2004 GMT; NotAfter: Dec 31 23:59:59 2028 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIE7zCCA9egAwIBAgISBKulaKDfPYF1cyIbhUIH2uJ9MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzA2MTcxNjM1NTBaFw0yMzA5MTUxNjM1NDlaMBYxFDASBgNVBAMM
CyouZmlsbW9uLnR2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0nIw
jZupXatQwe7zMFWdEcuSBZSD/B5lzJ+bMQFx8L6UHMOzcmGqJ/wkOjARxBhPgrzm
9c8ix7vxT0EpgKtfRzj6vppJeQAFoosk6m/I++URNM8QCcarnXkbZFv7tNplOz04
LQiNRVsbVhOC8jqUnaTQp6MNZvoAs9B7Q6HU1R0EUX/O3gHnTnQCwgSL4zc+x4yY
tgna7vsnsuDuddCkpc4UmA1vJlmcwkM0/AL6rT0fbt666eZkBXmd8q4U88L9Hflr
I7WymDtY4sHdTnOm8qTRppQZ8xnpyyiW4xRsgStKf6ex/eUJX7yYQ/Qef5sEKhK0
mlWscd+yERk36sWnmQIDAQABo4ICGTCCAhUwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
BBQL4A1DlSpjTFyipxgm7haL2IY2VTAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDm
H6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5v
LmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAh
BgNVHREEGjAYggsqLmZpbG1vbi50doIJZmlsbW9uLnR2MBMGA1UdIAQMMAowCAYG
Z4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYAtz77JN+cTbp18jnFulj0
bF38Qs96nzXEnh0JgSXttJkAAAGIym1zMQAABAMARzBFAiAbK5wIpndp12IaQn8C
mWBY1tv62HVmbIfEm5VWFEvLkwIhALk637ecMT5T8u5OAgewaDyMb9BbnQ5o03j4
foyrioBYAHcArfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvcgooAAAGIym1z
aQAABAMASDBGAiEA+7stky/1dMYCIgRSRqElYxbMrseYV/D5JZ9CX/JhpiICIQCO
Vi8rAhsr/nT8NcEyLkZhLF/hruCDRmMPngReRXw3HjANBgkqhkiG9w0BAQsFAAOC
AQEAeA2B4ZLgAJjS8uYMHMZD6nTyXQwcXVodrEhsSEIxp9BlIB+UVmexuEzPo1gF
RNjDiCgGuDe59q1EYcSa6U1IlAQRx242ZCn1asUcGD3Tm4s5wJZp4B9+1tYvwOFg
MxT48ntCDglQvnWB3IluWXLFJGHoULTPLcq4dTLR+zsx0aTEvG21vdAICQ3k8DBP
L9F5xoeEXJCC5dH0kURSdEsKfXg6dkQBVNuOfYs8/Wl65dlCiYMPqIFgRE3HMioN
8hEbVV6zpPRp9RKtMUpbCwU/kwxT13auMYoJFeywy3jbRtTYsq6xPijRvwWBsZMs
XxLTSuJQrVvWshxhI+VYpGlnIg==
-----END CERTIFICATE-----
subject=CN = *.filmon.tv
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 10313 bytes and written 322 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 299F90B394E66ABFFC433544BAAB2F4815B863E3D20C65F12BA4ECCC758FA450
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1688827959
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

This is caused by their servers returning `sigalg: RSA-SHA1` despite the TLS client having negotiated something much more secure according to the TLS version 1.2 in use, which itself is already old and deprecated.

Chromium for example simply ignores it:
![image](https://github.com/streamlink/streamlink/assets/467294/adb220e3-0868-402a-aa2f-ba18e423b98d)

According to the OpenSSL docs, the client's signature algorithm can be overridden, but I don't know if this can be done using Python's ssl module.
https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set1_sigalgs.html

----

Streamlink already had to lower the OpenSSL seclevel to 1 in the FIlmOn plugin, as you can see here, but this new issue is caused by the sent signatures and not their weak encryption ciphers:

- https://github.com/streamlink/streamlink/blob/5.5.1/src/streamlink/plugins/filmon.py#L183-L186
- https://github.com/streamlink/streamlink/blob/5.5.1/src/streamlink/plugin/api/http_session.py#L207-L213
- https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_security_level.html

----

https://updown.uservoice.com/knowledgebase/articles/1989757-what-does-the-wrong-signature-type-ssl-error-mea

**Comment by bastimeyer** [comment]
This looks like a candidate for a plugin removal. I don't think you can make OpenSSL accept the invalid certificate signature type.

**Comment by UltraHDR** [comment]
Many thanks for looking into this. Can you force it to use http?

**Comment by bastimeyer** [comment]
No, because the HTTP requests get upgraded to HTTPS

```
$ curl -I http://www.filmon.tv
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Sun, 09 Jul 2023 16:21:27 GMT
Content-Type: text/html
Content-Length: 154
Connection: keep-alive
Keep-Alive: timeout=20
Location: https://www.filmon.tv/
```

**Comment by mkbloke** [comment]
The filmon plugin is still working on one of my ageing (out of support systems).  I don't know if that might mean it's possible to work around this within the plugin implementation.

I'm pretty busy with other stuff in life right now though.  Can we keep this open and I'll try to take a look whenever I can find time.

**Comment by bastimeyer** [comment]
That Python version is very likely built against OpenSSL 1.1.1 then.

**Comment by johnthecracker** [comment]
This plugin works in Windows and doesn't work in Linux. It is beyond me the reason why.
Maybe this information can help developers interested in fixing this plugin.

**Comment by bastimeyer** [comment]
I have already explained it. This is neither a Python nor an OS issue. It's caused by OpenSSL rejecting their invalid server configuration. Depending on how your Python runtime was built, you are using different OpenSSL versions.

Older versions of OpenSSL accept Filmon's misconfiguration, while newer ones don't (even on the 1.1.1 branch), and I believe there's no option to configure it either, at least from within Python. If anyone knows how to configure it, then we can add a workaround, but otherwise this plugin will have to go unless they fix their mess. It's only a matter of time until web browsers like Chromium will stop supporting these misconfigurations too. This should make them fix their servers though.

> works in Windows and doesn't work in Linux

On Linux, you're most likely using the dynamically linked OpenSSL from your system's package management, whereas on Windows, it's statically linked and comes bundled. But as said, the important part is how old your OpenSSL version is.

----

- `3.1.1` (2023-05-30): doesn't work
- `1.1.1u` (2023-05-30): doesn't work
- `1.1.1m` (2022-03-15): doesn't work
- `1.1.1d` (2019-09-10): works

----

Arch Linux's latest default Python env:

```sh
$ python -c "import sys;print(sys.path)"
['', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']

$ ldd /usr/lib/python3.11/lib-dynload/_ssl.cpython-311-x86_64-linux-gnu.so | grep libssl
        libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f36c1c7e000)

$ python -c "import ssl;print(ssl.OPENSSL_VERSION)"
OpenSSL 3.1.1 30 May 2023
```

----

Python env included in Streamlink's latest AppImage (extracted AppImage contents):

```sh
$ ./squashfs-root/usr/bin/python -c 'import sys;print(sys.path)'
['', '/home/basti/repos/streamlink-appimage/dist/squashfs-root/opt/python3.11/lib/python311.zip', '/home/basti/repos/streamlink-appimage/dist/squashfs-root/opt/python3.11/lib/python3.11', '/home/basti/repos/streamlink-appimage/dist/squashfs-root/opt/python3.11/lib/python3.11/lib-dynload', '/home/basti/repos/streamlink-appimage/dist/squashfs-root/opt/python3.11/lib/python3.11/site-packages']

$ ldd ./squashfs-root/opt/python3.11/lib/python3.11/lib-dynload/_ssl.cpython-311-x86_64-linux-gnu.so | grep libssl

$ ./squashfs-root/usr/bin/python -c 'import ssl;print(ssl.OPENSSL_VERSION)'
OpenSSL 1.1.1u  30 May 2023
```

----

Python bundled with Streamlink's latest Windows builds:

```
$ pwsh -c "(Get-Item ./Python/DLLs/libssl-1_1.dll).VersionInfo"
ProductVersion   FileVersion      FileName
--------------   -----------      --------
1.1.1u           1.1.1u           C:\Program Files\Streamlink\Python\DLLs\libssl-1_1.dll

$ ./Python/python.exe -c "import ssl;print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1u  30 May 2023
```

----

Official Windows Python 3.8.0 build (oldest supported Python version):

```
$ pwsh -c "(Get-Item .\DLLs\libssl-1_1.dll).VersionInfo"
ProductVersion   FileVersion      FileName
--------------   -----------      --------
1.1.1d           1.1.1d           C:\Python38\DLLs\libssl-1_1.dll

$ .\python.exe -c "import ssl;print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1d  10 Sep 2019

$ ./python.exe -m streamlink -l debug filmon.tv/tv/bbc-world-news
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 6.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=filmon.tv/tv/bbc-world-news
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin filmon for URL filmon.tv/tv/bbc-world-news
[plugins.filmon][debug] Found channel ID: 3268
[plugins.filmon][debug] Received invalid or non-JSON data, attempt 1/5
Available streams: low (worst), high (best)
```

**Comment by devmarxx** [comment]
I have found a solution for this on Debian 12. 

The problem is NOT the filmon plugin. The developers of the plugin did a great job and it is definitively not a candidate for plugin removal! 

The problem on Debian 12 is Python 3.11

On Debian 12 libssl.3 is used, which does not support TLS1 (used by Filmon) anymore. The Python 3.11 ssl wrapper points to libssl.3 and therefor the filmon plugin can't set the adapter to use TLS1.

What I did was getting the libssl-1.1.1 libraries from Debian 11 (libssl1.1_1.1.1n-0+deb11u5_amd64.deb) and installed them. That does not interfere with the normal ssl3 behavior of the system at all. Then I got the Python ssl wrapper library from Python 3.9 out of Debian 11 (_ssl.cpython-39-x86_64-linux-gnu.so) and renamed that to _ssl.cpython-311-x86_64-linux-gnu.so. I replaced the original file at /usr/lib/python3.11/lib-dynload with my renamed one and voila no more ssl error and filmon up and running with streamlink on Debian 12 :-)

This of course sets the whole Python 3.11 environment to ssl 1.1.1 (not ideal), but for me it is worth it solving the filmon plugin ssl error.

Regards

Chris

**Comment by bastimeyer** [comment]
> The problem on Debian 12 is Python 3.11

The exact problem has already been described in detail in my previous posts. Read them.

FilmOn uses TLS 1.2 with an invalid server configuration which OpenSSL doesn't accept since version 3.x or somewhere between 1.1.1d and 1.1.1m (not exactly sure which one). It is however not advised to downgrade to versions with unpatched security vulnerabilities.
https://www.openssl.org/news/cl111.txt

OpenSSL 1.1.1 will see its EOL in less than two weeks, on 2023-09-11:
https://endoflife.date/openssl

Older versions aren't even supported by Python anymore, and 1.1.1 will probably soon follow once most Linux distros have switched to 3.x. Python's Windows builds have just switched over to 3.0.9 in the latest release.
https://peps.python.org/pep-0644/

> renamed that to

**Never ever rename or symlink shared object files, and especially never make such advices.**

Shared objects have a specific `SONAME` property which indicates ABI compatibility (`objdump -p path/to/shared-object.so | grep SONAME`). Whenever the `SONAME` gets bumped, those shared objects are explicitly incompatible with older versions, which means the application which links them is likely to crash if you mindlessly/unknowingly rename the files.

Replacing such crucial libs for the system's main Python environment is especially bad, because you will break lots of different other things on your system. **Don't do that.**

**Comment by bastimeyer** [comment]
If you want to make the FilmOn plugin work, then run a Python environment which links against an old enough OpenSSL build.

The best idea for that is running it inside a container. The official manylinux2014 docker images should work fine. Example which runs a manylinux2014 container from 2021-08-26 using CPython 3.9 with OpenSSL 1.1.1l:

```sh
docker run --rm -it quay.io/pypa/manylinux2014_x86_64:2021-08-26-12e5da0 bash -e <<EOL
/opt/python/cp39-cp39/bin/python -m pip install git+https://github.com/streamlink/streamlink.git
/opt/python/cp39-cp39/bin/python -m streamlink --loglevel=debug --hls-duration=60 --output=/dev/null filmon.com/tv/bbc-world-news best
EOL
```
```
...
[cli][debug] OS:         Linux-6.5.0-1-git-x86_64-with-glibc2.17
[cli][debug] Python:     3.9.6
[cli][debug] OpenSSL:    OpenSSL 1.1.1l  24 Aug 2021
[cli][debug] Streamlink: 6.1.0+14.g561f7ef8
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.2
[cli][debug] Arguments:
[cli][debug]  url=filmon.com/tv/bbc-world-news
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=/dev/null
[cli][debug]  --hls-duration=60.0
[cli][info] Found matching plugin filmon for URL filmon.com/tv/bbc-world-news
[plugins.filmon][debug] Found channel ID: 3268
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Writing output to
/dev/null
[cli][debug] Checking file output
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[plugins.filmon][debug] Reloading FilmOn channel playlist: 3268
[stream.hls][debug] First Sequence: 5875711; Last Sequence: 5875716
[stream.hls][debug] Start offset: 0; Duration: 60; Start Sequence: 5875714; End Sequence: None
[stream.hls][debug] Adding segment 5875714 to queue
[stream.hls][debug] Adding segment 5875715 to queue
[stream.hls][debug] Adding segment 5875716 to queue
[stream.hls][debug] Writing segment 5875714 to output
[stream.hls][debug] Segment 5875714 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Writing segment 5875715 to output
[stream.hls][debug] Segment 5875715 complete
[stream.hls][debug] Writing segment 5875716 to output
[stream.hls][debug] Segment 5875716 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5875717 to queue
[stream.hls][debug] Writing segment 5875717 to output
[stream.hls][debug] Segment 5875717 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5875718 to queue
[stream.hls][info] Stopping stream early after 60
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Writing segment 5875718 to output
[stream.hls][debug] Segment 5875718 complete
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by johnthecracker** [comment]
This plugin works now on my side:

`[cli][debug] OS:         Linux-6.5.0-10-generic-x86_64-with-glibc2.38
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.0.10 1 Aug 2023
[cli][debug] Streamlink: 6.3.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.11.17
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.1
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.6.4
[cli][debug] Arguments:
[cli][debug]  url=https://www.filmon.com/tv/bbc-world-news
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin filmon for URL https://www.filmon.com/tv/bbc-world-news
[plugins.filmon][debug] Found cached channel ID: 3268
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: mpv
[stream.hls][debug] Reloading playlist
[plugins.filmon][debug] Reloading FilmOn channel playlist: 3268
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 6463263; Last Sequence: 6463268
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 6463266; End Sequence: None
[stream.hls][debug] Adding segment 6463266 to queue
[stream.hls][debug] Adding segment 6463267 to queue
[stream.hls][debug] Adding segment 6463268 to queue
[stream.hls][debug] Writing segment 6463266 to output
[stream.hls][debug] Segment 6463266 complete
[cli.output][debug] Opening subprocess: ['/usr/bin/mpv', '--force-media-title=https://www.filmon.com/tv/bbc-world-news', '-']
[cli][debug] Writing stream to output
[stream.hls][debug] Writing segment 6463267 to output
[stream.hls][debug] Segment 6463267 complete
[stream.hls][debug] Writing segment 6463268 to output
[stream.hls][debug] Segment 6463268 complete`
