### ISSUE TITLE
Twitch - output the used node to log

### ISSUE THREAD

**Issue by stevek123** [streamlink/streamlink#546]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

As discussed in https://github.com/streamlink/streamlink/issues/377, I would like to ask for a feature for the Twitch plugin. I want to be able to see and echo the node that is being used to the command line output. It's part of the main m3u8 file, and the same as the stream's server domain. I think it would be fine to implement it either as a command line argument (to turn on the message), or as an info level message. Other plugins output info level messages as well that are not necessarily the most important, and the debug level would output way to many things constantly (but it would be fine as a debug level message as well, I can easily change it for myself after it's implemented to be an info message).

**Comment by bastimeyer** [comment]
You can already see the server address by using the `--stream-url` parameter. Twitch should assign the same server to you when running streamlink twice...
Please keep in mind that anything server infrastructure related (in terms of manipulation) is against Twitch's TOS.

**Comment by stevek123** [comment]
I don't want to manipulate it, but sometimes it takes time for streams to "move" to closer nodes, and I just want to know wheter it might worth to restart the stream when I'm having issues or I'm already using the closest one, and maybe the issue is something else,

**Comment by bastimeyer** [comment]
A log message when launching a stream isn't necessary in this use case, though. In fact, it wouldn't even be useful, since you'd need to restart the stream or need to launch the stream twice in order to see the currently used server.

A much better solution would be writing a simple shell script that periodically launches streamlink with the `--stream-url` parameter and then informs you when the stream is available on one of your desired servers that have a better connection/routing.

**Comment by gravyboat** [comment]
Yeah I really don't want to get into the identification/viewing of nodes past what we already have if we can because it's a huge ToS issue and I don't want any excuses to try and shut us down.
