### ISSUE TITLE
ipv4 setting in config file doesn't work

### ISSUE THREAD

**Issue by trunc88** [streamlink/streamlink#5481]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

With `ipv4` in the config file, streamlink --loglevel=debug $URL produces:
```
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: ambiguous option: --ipv=4 could match --ipv4, --ipv6
```
With just `4`, it works

### Debug log

```text
streamlink --loglevel=debug <url>
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: ambiguous option: --ipv=4 could match --ipv4, --ipv6
```

**Comment by bastimeyer** [comment]
Thanks. Looks like it's caused by this poor regex:
- https://github.com/streamlink/streamlink/blame/6.0.1/src/streamlink_cli/argparser.py#L19-L26
- https://github.com/streamlink/streamlink/blame/6.0.1/src/streamlink_cli/argparser.py#L59-L62

Tests were never added to this `argparse.ArgumentParser` override:
https://app.codecov.io/gh/streamlink/streamlink/commit/4a234ff76a73ad238eea8470267366592963ad50/blob/src/streamlink_cli/argparser.py#L51

Going to fix this later today...

**Comment by bastimeyer** [comment]
See #5484

**Comment by trunc88** [comment]
Nice, thank you!
