### ISSUE TITLE
Python 3.11 Included Installer - SSL Module Missing

### ISSUE THREAD

**Issue by wagwan-piffting-blud** [streamlink/streamlink#5518]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.1.0

### Description

When attempting to run the following command:

streamlink --twitch-disable-ads https://www.twitch.tv/noctaq best -o file.ts

This error is output:

`[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/noctaq`
`error: Unable to open URL: https://gql.twitch.tv/gql (Can't connect to HTTPS URL because the SSL module is not available.)`

The installer I used is the one provided here, which is supposed to include Python and all dependencies: https://github.com/streamlink/windows-builds/releases/tag/6.1.0-1 (file streamlink-6.1.0-1-py311-x86_64.exe)

### Debug log

```text
D:\Programs\Streamlink\bin> streamlink --twitch-disable-ads https://www.twitch.tv/noctaq best -o file.ts --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.4
[cli][debug] Streamlink: 6.1.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/noctaq
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=file.ts
[cli][debug]  --ffmpeg-ffmpeg=D:\Programs\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth OAUTH_TOKEN')]
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/noctaq
[plugins.twitch][debug] Getting live HLS streams for noctaq
error: Unable to open URL: https://gql.twitch.tv/gql (Can't connect to HTTPS URL because the SSL module is not available.)
```

**Comment by wagwan-piffting-blud** [comment]
Conjecture: I believe this is the result of Python not being complied correctly, as I compiled Python 3.11 by hand, and replaced the binaries in the Streamlink/Python directory, and it worked just fine with the newly compiled binary. Unsure if this is the true cause of the error or not but thought it would be helpful to add.

**Comment by bastimeyer** [comment]
This issue doesn't belong here, as you can clearly read in the bug template. Issues regarding the Windows builds belong on the windows-builds issue tracker. Let me answer this here anyway...

----

> Conjecture: I believe this is the result of Python not being complied correctly

Before making random guesses and claims, why don't you have a look at the build files and build logs first? This is all FOSS and freely accessible. Your "conjecture" is 100% wrong. I wouldn't even have to show you why, because if it was the case, then everyone else would have the same issue as you, and this is clearly not the case. Software is deterministic.

> Can't connect to HTTPS URL because the SSL module is not available

Here's what's actually happened on your system: either you (by accident), or a different program removed the needed files from your Streamlink install, or you are doing other weird things which are unrelated to the Streamlink installer for Windows.

----

Both the installer and portable builds of Streamlink's Windows builds `6.1.0-1` are based on Python `3.11.4`, which is built here, where you can see the build config, build logs and build artifacts, including the release files:

- https://github.com/streamlink/python-windows-embed
- https://github.com/streamlink/python-windows-embed/blob/20230607-1/.github/workflows/main.yml
- https://github.com/streamlink/python-windows-embed/actions/runs/5200998962
- https://github.com/streamlink/python-windows-embed/releases/tag/20230607-1

Python 3.11.4 bundles OpenSSL 1.1.1u, which is pre-built by the python devs:
- https://github.com/python/cpython/blob/v3.11.4/PCbuild/get_externals.bat#L56
- https://github.com/python/cpython-bin-deps/tree/openssl-bin-1.1.1u

The respective files from the stdlib (bundled as `python311.zip`) are built and included correctly.

```
$ curl -sSL https://github.com/streamlink/python-windows-embed/releases/download/20230607-1/python-v3.11.4-0-gd2340ef2-windows-x64-embed.zip \
  | bsdtar -ztf -
python.exe
pythonw.exe
python311.dll
vcruntime140.dll
vcruntime140_1.dll
LICENSE.txt
DLLs/pyexpat.pyd
DLLs/select.pyd
DLLs/unicodedata.pyd
DLLs/winsound.pyd
DLLs/_asyncio.pyd
DLLs/_bz2.pyd
DLLs/_ctypes.pyd
DLLs/_decimal.pyd
DLLs/_elementtree.pyd
DLLs/_hashlib.pyd
DLLs/_lzma.pyd
DLLs/_msi.pyd
DLLs/_multiprocessing.pyd
DLLs/_overlapped.pyd
DLLs/_queue.pyd
DLLs/_socket.pyd
DLLs/_sqlite3.pyd
DLLs/_ssl.pyd
DLLs/_uuid.pyd
DLLs/_zoneinfo.pyd
DLLs/libcrypto-1_1.dll
DLLs/libffi-8.dll
DLLs/libssl-1_1.dll
DLLs/sqlite3.dll
python311.zip
```

```
$ curl -sSL https://github.com/streamlink/python-windows-embed/releases/download/20230607-1/python-v3.11.4-0-gd2340ef2-windows-x64-embed.zip \
  | bsdtar -xOzf - python311.zip \
  | bsdtar -ztf - \
  | grep ssl
ssl.pyc
asyncio/sslproto.pyc
```

----

The config of Streamlink's Windows builds simply bundles the embedded Python builds and doesn't touch its contents. Neither does the `pynsist` build-dependency which manages the `NSIS` config template and the `NSIS` execution for building the installer:

- https://github.com/streamlink/windows-builds/blob/6.1.0-1/config.json#L190-L195
- https://github.com/streamlink/windows-builds/blob/6.1.0-1/build-installer.sh#L115-L123
- https://github.com/streamlink/windows-builds/blob/6.1.0-1/build-installer.sh#L203-L208
- https://github.com/streamlink/windows-builds/blob/6.1.0-1/installer.cfg#L8-L11
- https://github.com/takluyver/pynsist/blob/2.8/nsist/__init__.py#L207-L211
- https://github.com/streamlink/windows-builds/actions/runs/5881561626/job/15950293232#step:5:232

----

You can even see which files are being unpacked by the installer in its log output after it's finished writing the files.

![image](https://github.com/streamlink/streamlink/assets/467294/3e99718b-e2d4-491d-a6a9-6abe4eb5849d)

The portable build includes the same files.

```
$ curl -sSL https://github.com/streamlink/windows-builds/releases/download/6.1.0-1/streamlink-6.1.0-1-py311-x86_64.zip | bsdtar -ztf - | grep /Python
streamlink-6.1.0-1-py311-x86_64/Python/
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_asyncio.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_bz2.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_ctypes.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_decimal.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_elementtree.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_hashlib.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_lzma.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_msi.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_multiprocessing.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_overlapped.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_queue.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_socket.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_sqlite3.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_ssl.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_uuid.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/_zoneinfo.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/libcrypto-1_1.dll
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/libffi-8.dll
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/libssl-1_1.dll
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/pyexpat.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/select.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/sqlite3.dll
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/unicodedata.pyd
streamlink-6.1.0-1-py311-x86_64/Python/DLLs/winsound.pyd
streamlink-6.1.0-1-py311-x86_64/Python/LICENSE.txt
streamlink-6.1.0-1-py311-x86_64/Python/python.exe
streamlink-6.1.0-1-py311-x86_64/Python/python311.dll
streamlink-6.1.0-1-py311-x86_64/Python/python311.zip
streamlink-6.1.0-1-py311-x86_64/Python/pythonw.exe
streamlink-6.1.0-1-py311-x86_64/Python/vcruntime140.dll
streamlink-6.1.0-1-py311-x86_64/Python/vcruntime140_1.dll
```

----

Here are the contents of the installer, run on an empty install directory:

```
$ ls -R 'C:\Program Files\Streamlink\Python\'

    Directory: C:\Program Files\Streamlink\Python

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          26/08/2023    13:40                DLLs
-a---          16/08/2023    18:49          32768 LICENSE.txt
-a---          16/08/2023    18:49          91136 python.exe
-a---          16/08/2023    18:49        6180864 python311.dll
-a---          16/08/2023    18:49        4268237 python311.zip
-a---          16/08/2023    18:49          89600 pythonw.exe
-a---          16/08/2023    18:49          49520 vcruntime140_1.dll
-a---          16/08/2023    18:49         109392 vcruntime140.dll

    Directory: C:\Program Files\Streamlink\Python\DLLs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          16/08/2023    18:49          55296 _asyncio.pyd
-a---          16/08/2023    18:49          79360 _bz2.pyd
-a---          16/08/2023    18:49         121344 _ctypes.pyd
-a---          16/08/2023    18:49         295936 _decimal.pyd
-a---          16/08/2023    18:49         126464 _elementtree.pyd
-a---          16/08/2023    18:49          48128 _hashlib.pyd
-a---          16/08/2023    18:49         156672 _lzma.pyd
-a---          16/08/2023    18:49          32768 _msi.pyd
-a---          16/08/2023    18:49          22528 _multiprocessing.pyd
-a---          16/08/2023    18:49          43008 _overlapped.pyd
-a---          16/08/2023    18:49          19968 _queue.pyd
-a---          16/08/2023    18:49          69120 _socket.pyd
-a---          16/08/2023    18:49          98304 _sqlite3.pyd
-a---          16/08/2023    18:49         156160 _ssl.pyd
-a---          16/08/2023    18:49          13312 _uuid.pyd
-a---          16/08/2023    18:49          32768 _zoneinfo.pyd
-a---          16/08/2023    18:49        3445016 libcrypto-1_1.dll
-a---          16/08/2023    18:49          39696 libffi-8.dll
-a---          16/08/2023    18:49         704792 libssl-1_1.dll
-a---          16/08/2023    18:49         192512 pyexpat.pyd
-a---          16/08/2023    18:49          18944 select.pyd
-a---          16/08/2023    18:49        1491968 sqlite3.dll
-a---          16/08/2023    18:49        1127424 unicodedata.pyd
-a---          16/08/2023    18:49          18944 winsound.pyd
```

----

```
$ & "C:\Program Files\Streamlink\bin\streamlink" -l debug twitch.tv/bobross
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.4
[cli][debug] Streamlink: 6.1.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/bobross
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin twitch for URL twitch.tv/bobross
[plugins.twitch][debug] Getting live HLS streams for bobross
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
```

**Comment by wagwan-piffting-blud** [comment]
Alright, sure, I get I put this in the wrong repo, I absolutely get that and that is 100% my fault.

However.

> Before making random guesses and claims, why don't you have a look at the build files and build logs first? This is all FOSS and freely accessible. Your "conjecture" is 100% wrong. I wouldn't even have to show you why, because if it was the case, then everyone else would have the same issue as you, and this is clearly not the case. Software is deterministic.

Was it _really_ necessary to be this rude? I usually try to have an open mind when it comes to open source projects, hell, I have quite a few I have contributed to over the years both on and off GitHub. But your response comes off as just the kind of thing that makes me dislike contributing toward open source projects. I urge you to pelase have more of an open mind when it comes to wanting to help people and be less rude when faced with an issue that is considered "user error". Thank you for the response either way, I appreciate it and will look more into it privately.

**Comment by bastimeyer** [comment]
Apologies if I came off rude, but what you have to understand is that writing such a detailed response is a massive waste of time, just to show that there is no issue here. If I want to back up my statements, then I have to dig through all these sources and link them accordingly, for no real gain other than trying to be correct and showing some insights. This waste of time is especially annoying when the person who has opened the issue didn't even bother spending a bit of time reading the issue template and also makes wild claims about apparently broken stuff that's not backed up by any facts. At least I hope I could give you some hints on how to resolve your local issue.

**Comment by bastimeyer** [comment]
I did some further debugging because Python `3.11.5` just got released 3 days ago (after a delay of more than two weeks) and it bumped its OpenSSL version on Windows from `1.1.1u` to `3.0.9`, so it got me curious about your issue.

The Python build used by Streamlink doesn't include the `python311._pth` file. Apparently, if it's missing, the python executable from the embedded builds for some reason can attempt to load DLLs from a globally installed system Python environment, which means it's possible that Streamlink's Python build `3.11.4` has collided with `3.11.5` and thus OpenSSL `3.0.9` on your system, if you indeed have that one installed. That would explain the error message on your system and why I didn't see it.

The missing `_pth` file can be included by adding `--include-underpth` (or the `--preset-embed` preset) argument when packaging it via the `PC/layout` package.

- https://github.com/python/cpython/blob/v3.11.5/.azure-pipelines/windows-release/stage-layout-embed.yml#L48
- https://github.com/python/cpython/blob/v3.11.5/.azure-pipelines/windows-release/layout-command.yml
- https://github.com/python/cpython/blob/v3.11.5/PC/layout/support/options.py#L29
- https://github.com/python/cpython/blob/v3.11.5/PC/layout/support/options.py#L86-L89
- https://github.com/python/cpython/blob/v3.11.5/PC/layout/main.py#L345-L361

----

If you add the following file to the Streamlink install
`./Python/python311._pth`
with the following contents
```
python311.zip
./DLLs
```
it should work.

I'm preparing a new build right now.

**Comment by bastimeyer** [comment]
Fixed:
https://github.com/streamlink/windows-builds/releases/tag/6.1.0-2

----

Looks like I was 100% wrong. Apologies.

This was only noticable after triggering a build of `3.11.5` and validating the files in my Windows VM where `3.11.4` was installed globally.

This resulted in `python -c 'import ssl;print(ssl.OPENSSL_VERSION)'` showing up as `1.1.1u` despite `3.0.9` being bundled. After upgrading the global install to `3.11.5`, the output changed to `3.0.9` and the same error when running the `6.1.0-1` Streamlink build occurred.

Using `WinDbg`, I could see that the wrong `_ssl` module of the stdlib and thus the wrong `libssl` DLL got loaded.

I checked the build config of the cpython repo and noticed the missing pth file due to the missing packaging flag.

**Comment by wagwan-piffting-blud** [comment]
Thank you for looking into it further and going above and beyond to fix it and issue a correction. I appreciate your help greatly and am glad to see that it was not only me who would have experienced it in the long run. Issuing a correction and retraction like that takes courage to do. Thanks again!

**Comment by madhatr** [comment]
Thanks for looking at this further.  I was having issues with this problem but it looked like I had SSL.  I upgraded to latest build of streamlink and things are working again now.
