### ISSUE TITLE
plugins.Twitch: no_cdm_specified for Prime Video TNF Twitch channel

### ISSUE THREAD

**Issue by adamef93** [streamlink/streamlink#5592]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

[cli][info] Your Streamlink version (6.2.1) is up to date!

### Description

I'm attempting to get a link for the free and publicly available stream of Thursday Night Football on Amazon's Twitch channel (twitch.tv/primevideo) to add to my Channels DVR so I can watch as if it was a traditional broadcast. I'm not trying to circumvent any geo-blocking the Twitch channel may have in place; the stream works fine for me in a browser from my location. My original issue (#5590) regarding the app crashing has been resolved and I'm now receiving the error below with the updated `twitch.py` file in my plugins directory. I've also updated from 6.2.0 from winget to 6.2.1 downloaded directly from github.

### Debug log

```text
PS C:\Users\*user*> streamlink twitch.tv/primevideo best --loglevel=debug
[session][debug] Plugin twitch is being overridden by C:\Users\*user*\AppData\Roaming\streamlink\plugins\twitch.py
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.0.9 30 May 2023
[cli][debug] Streamlink: 6.2.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.0.6
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/primevideo
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin twitch for URL twitch.tv/primevideo
[plugins.twitch][debug] Getting live HLS streams for primevideo
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[plugins.twitch][error] no_cdm_specified
error: No playable streams found on this URL: twitch.tv/primevideo
```

**Comment by 0xW1sKy** [comment]
I'm working on the primevideo channel playback in another project but wanted to add some color here since it looks like you'll be facing some of the same issues.

For the `no_cdm_specified` error, you can add `&cdm=wv` to the usher url request parameters.

however, the issue with the primevideo channel is it appears that it is using WideVine DRM to encrypt the video feed. 

you can use the following twitch GQL query to identify if a stream is encrypted:

```json
{
    "operationName":"VideoPlayerStreamMetadata",
    "variables":{
        "channel":"primevideo"
    },
    "extensions":{
        "persistedQuery":{
            "version":1,
            "sha256Hash":"248fee6868e983c4e7b69074e888960f77735bd21a1d4a1d882b55f45d30a420"
        }
    }
}
```
example response:
```json
{
        "data": {
            "user": {
                "id": "168843586",
                "stream": {
                    "id": "42901718939",
                    "isEncrypted": true,
                    "__typename": "Stream"
                },
                "__typename": "User"
            }
        },
        "extensions": {
            "durationMilliseconds": 40,
            "operationName": "VideoPlayerStreamMetadata",
            "requestID": "REDACTED"
        }
    }
```

i'm still working on getting all the info needed to decrypt the streams. so far this is what i've found:

There is a widevine appdata token available at the following url:
```
https://usher.ttvnw.net/api/authxml/primevideo?token=<Encoded PlaybackAccessToken>&sig=<PlaybackAccessTokenSignature>
```
This token is a base64 encoded xml doc with the widevine DRM access info

Next i've found requests being made to the following license server with the base64 encoded xml token from above being sent.
`https://wv-keyos-twitch.licensekeyserver.com/`

This is as far as i've got so far, but have yet to figure out how to successfully leverage the information to implement it in my project. I'm hoping by leaving some of this here the smarter-than-me team behind streamlink might be able to figure it out :D

notes: I have a suspicion the cdm value being `wv` might be in reference to "west virginia" (i.e. AWS US-West-2 region) and that the licensekeyserver url has to have a matching value in the beginning of the url. My current guess is that west virginia is the only location they've imiplemented the keyserver as it wouldnt make a lot of sense to geolock it, nor do I think aws has made the IVS key systems available in all regions yet.

**Comment by bastimeyer** [comment]
Going to close this, due to alleged DRM protection schemes.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by adamef93** [comment]
> I'm working on the primevideo channel playback in another project but wanted to add some color here since it looks like you'll be facing some of the same issues.
> 
> For the `no_cdm_specified` error, you can add `&cdm=wv` to the usher url request parameters.
> 
> however, the issue with the primevideo channel is it appears that it is using WideVine DRM to encrypt the video feed.
> 
> you can use the following twitch GQL query to identify if a stream is encrypted:
> 
> {
>     "operationName":"VideoPlayerStreamMetadata",
>     "variables":{
>         "channel":"primevideo"
>     },
>     "extensions":{
>         "persistedQuery":{
>             "version":1,
>             "sha256Hash":"248fee6868e983c4e7b69074e888960f77735bd21a1d4a1d882b55f45d30a420"
>         }
>     }
> }
> 
> example response:
> 
> {
>         "data": {
>             "user": {
>                 "id": "168843586",
>                 "stream": {
>                     "id": "42901718939",
>                     "isEncrypted": true,
>                     "__typename": "Stream"
>                 },
>                 "__typename": "User"
>             }
>         },
>         "extensions": {
>             "durationMilliseconds": 40,
>             "operationName": "VideoPlayerStreamMetadata",
>             "requestID": "REDACTED"
>         }
>     }
> 
> i'm still working on getting all the info needed to decrypt the streams. so far this is what i've found:
> 
> There is a widevine appdata token available at the following url:
> 
> ```
> https://usher.ttvnw.net/api/authxml/primevideo?token=<Encoded PlaybackAccessToken>&sig=<PlaybackAccessTokenSignature>
> ```
> 
> This token is a base64 encoded xml doc with the widevine DRM access info
> 
> Next i've found requests being made to the following license server with the base64 encoded xml token from above being sent. `https://wv-keyos-twitch.licensekeyserver.com/`
> 
> This is as far as i've got so far, but have yet to figure out how to successfully leverage the information to implement it in my project. I'm hoping by leaving some of this here the smarter-than-me team behind streamlink might be able to figure it out :D
> 
> edit: cdm=wv is for widevine.

Anything ever come of this?
