### ISSUE TITLE
plugins.twitch: latest update started flooding console with confusing messages

### ISSUE THREAD

**Issue by username-not-taken** [streamlink/streamlink#5656]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.3.1

### Description

did someone enable a new debug setting or something and how to turn that off if so? the plugin appears to work but it has started flooding the console with messages. its not the end of the world but i would like the console clean like it used to be

### Debug log

```text
[plugins.twitch][error] twirp error not_found: transcode does not exist
[plugins.twitch][error] Could not access HLS playlist
```

**Comment by DannyDarth** [comment]
Whenever i try to load a stream it just comes up with this:

https://i.imgur.com/X1WNJWB.png

**Comment by bastimeyer** [comment]
I don't see any issues with the plugin. Twitch live streams are working fine, including ad filtering and low latency streaming, as well as VODs. I've checked various channels and qualities.

What you have posted is not a debug log. You completely ignored the issue form/template, so this issue doesn't have any useful information at all apart from the error message Twitch is spitting out. I don't even know which channel you're attempting to watch.

As you can see from the error message, Twitch doesn't let you access the HLS playlist because this specific quality hasn't been encoded (yet?).

Streamlink `6.3.0` fixed the error handling of the Twitch plugin when resolving HLS playlists, which you can read in the changelog:
https://streamlink.github.io/changelog.html#streamlink-6-3-0-2023-10-25

This was fixed because of geo-restricted streams on Twitch with Amazon Prime-Video stuff, exclusive to the US area.

> started flooding

Nothing is flooding unless you've set `--retry-streams`. Streamlink's CLI will keep resolving the streams on error when set.
https://streamlink.github.io/cli.html#cmdoption-retry-streams

----

> Whenever i try to load a stream it just comes up with this:

Please stop posting Twitch GUI stuff here on this issue tracker. It doesn't belong here. This image also doesn't say anything, as well as your post. My guess however is that your player closes on its own immediately when it receives its input. Otherwise you'd see a Streamlink error message. This is a regular exit of the playback, at least from the perspective from Streamlink. The Twitch GUI is just a launcher and isn't involved at all here.

**Comment by username-not-taken** [comment]
> > started flooding
> 
> Nothing is flooding unless you've set `--retry-streams`. Streamlink's CLI will keep resolving the streams on error when set. https://streamlink.github.io/cli.html#cmdoption-retry-streams
> 
yeah and that is new behavior. since its setup to poll the channel for streams to record there will be a lot of those messages. in the past it would retry silently
