### ISSUE TITLE
Cannot output files to special directories in home directory on Windows

### ISSUE THREAD

**Issue by lumynou5** [streamlink/streamlink#5727]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.5.0

### Description

Attempt to output files to special directories such as `Videos`, `Pictures`, etc. in home directory on Windows failed with `[Errno 2] No such file or directory`.

### Debug log

```text
PS C:\Users\***\Pictures> python -m streamlink --hls-start-offset 02:11:38 --hls-duration 00:45:58 --output stream.ts "https://www.twitch.tv/videos/2000427166" best --loglevel=debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.6
[cli][debug] OpenSSL:    OpenSSL 1.1.1k  25 Mar 2021
[cli][debug] Streamlink: 6.5.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.0.7
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/videos/2000427166
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=stream.ts
[cli][debug]  --hls-start-offset=7898.0
[cli][debug]  --hls-duration=2758.0
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/2000427166
[plugins.twitch][debug] Getting HLS streams for video ID 2000427166
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Writing output to
stream.ts
[cli][debug] Checking file output
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 0; Last Sequence: 1711
[stream.hls][debug] Start offset: 7898; Duration: 2758; Start Sequence: 790; End Sequence: 1711
[stream.hls][debug] Adding segment 790 to queue
[stream.hls][debug] Adding segment 791 to queue
[stream.hls][debug] Adding segment 792 to queue
[stream.hls][debug] Adding segment 793 to queue
[stream.hls][debug] Adding segment 794 to queue
[stream.hls][debug] Adding segment 795 to queue
[stream.hls][debug] Adding segment 796 to queue
[stream.hls][debug] Adding segment 797 to queue
[stream.hls][debug] Adding segment 798 to queue
[stream.hls][debug] Adding segment 799 to queue
[stream.hls][debug] Adding segment 800 to queue
[stream.hls][debug] Adding segment 801 to queue
[stream.hls][debug] Adding segment 802 to queue
[stream.hls][debug] Adding segment 803 to queue
[stream.hls][debug] Adding segment 804 to queue
[stream.hls][debug] Adding segment 805 to queue
[stream.hls][debug] Adding segment 806 to queue
[stream.hls][debug] Adding segment 807 to queue
[stream.hls][debug] Adding segment 808 to queue
[stream.hls][debug] Adding segment 809 to queue
[stream.hls][debug] Adding segment 810 to queue
[stream.hls][debug] Adding segment 811 to queue
[stream.hls][debug] Writing segment 790 to output
[stream.hls][debug] Segment 790 complete
[stream.hls][debug] Adding segment 812 to queue
error: Failed to open output: stream.ts ([Errno 2] No such file or directory: 'stream.ts')
[cli][info] Closing currently open stream...
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
```

**Comment by bastimeyer** [comment]
I can't reproduce this, and I don't think this is a Streamlink issue either.

Example from my W10 VM using the latest Streamlink build for py38 (in case this is a `pathlib` issue):

```
PS C:\Users\basti\Pictures> C:\Users\basti\Desktop\streamlink-6.5.0-2-py38-x86_64\bin\streamlink.exe -l debug -o foo.ts twitch.tv/shroud best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.18+
[cli][debug] OpenSSL:    OpenSSL 1.1.1u  30 May 2023
[cli][debug] Streamlink: 6.5.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.11.17
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/shroud
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=foo.ts
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin twitch for URL twitch.tv/shroud
[plugins.twitch][debug] Getting live HLS streams for shroud
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Writing output to
foo.ts
[cli][debug] Checking file output
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 0; Last Sequence: 2
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: None
[stream.hls][debug] Adding segment 0 to queue
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Writing segment 0 to output
[stream.hls][debug] Segment 0 complete
[stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.
[cli][debug] Writing stream to output
[stream.hls][debug] Writing segment 1 to output
[stream.hls][debug] Segment 1 complete
[stream.hls][debug] Writing segment 2 to output
[stream.hls][debug] Segment 2 complete
[download] Written 3.27 MiB to foo.ts (4s @ 736.60 KiB/s)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Writing segment 3 to output
[stream.hls][debug] Segment 3 complete
[stream.hls][debug] Writing segment 4 to output
[stream.hls][debug] Segment 4 complete
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Writing segment 5 to output
[stream.hls][debug] Segment 5 complete
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...

PS C:\Users\basti\Pictures> ls .\foo.ts

    Directory: C:\Users\basti\Pictures

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          17/12/2023    05:30        4883676 foo.ts
```

----

As you can see here, when writing the stream output to the file system, Streamlink CLI will first attempt to create the parent directories (recursively) and it then creates the file descriptor in `wb` mode.
https://github.com/streamlink/streamlink/blob/6.5.0/src/streamlink_cli/output/file.py#L26-L29

> [Errno 2] No such file or directory

This error does only get raised in `wb` mode, if the parent directory does not exist.

> [cli][info] Writing output to
> stream.ts

This is strange however, because Streamlink CLI should log the fully **resolved** path. It also didn't do this in my test.
https://github.com/streamlink/streamlink/blob/6.5.0/src/streamlink_cli/main.py#L70

So this is either an issue with Python's `pathlib`, or with your Windows config.

Remember that Windows treats folders in your home directory special. What this means is that the actual layout on the file system might be different compared to what you're seeing on your desktop. This depends on the system's locale settings and can also be overridden by some registry settings from what I could find according to my Google search results. I don't use Windows, so I don't fully know. There's more info required here.

**Comment by michaelarnauts** [comment]
Could it be that your username has special characters? I didn't try to reproduce, but I see similar issues in other applications when my userdir is named "Michaël" for example.

I can't tell here since you censored your username in your log.

**Comment by bastimeyer** [comment]
> This is strange however, because Streamlink CLI should log the fully resolved path. It also didn't do this in my test.

Apparently, there's a bug in `pathlib.WindowsPath.resolve()` on `<=py39` where it doesn't actually resolve the full/absolute path:
https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve

- https://github.com/python/cpython/blame/v3.9.18/Lib/pathlib.py#L203-L225
- https://github.com/python/cpython/blame/v3.10.0/Lib/pathlib.py#L1062-L1088

```pwsh
PS C:\Users\basti\Pictures> Get-Content foo.ts
Get-Content: Cannot find path 'C:\Users\basti\Pictures\foo.ts' because it does not exist.

# py39 - file does not exist
PS C:\Users\basti\Pictures> C:\Python39\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').resolve())"
foo.ts
PS C:\Users\basti\Pictures> C:\Python39\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').absolute())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python39\python.exe -c "import os.path;print(os.path.realpath('foo.ts'))"
C:\Users\basti\Pictures\foo.ts
# py310 - file does not exist
PS C:\Users\basti\Pictures> C:\Python310\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').resolve())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python310\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').absolute())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python310\python.exe -c "import os.path;print(os.path.realpath('foo.ts'))"
C:\Users\basti\Pictures\foo.ts

PS C:\Users\basti\Pictures> New-Item foo.ts

    Directory: C:\Users\basti\Pictures

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          17/12/2023    09:51              0 foo.ts

# py39 - file does exist
PS C:\Users\basti\Pictures> C:\Python39\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').resolve())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python39\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').absolute())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python39\python.exe -c "import os.path;print(os.path.realpath('foo.ts'))"
C:\Users\basti\Pictures\foo.ts
# py310 - file does exist
PS C:\Users\basti\Pictures> C:\Python310\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').resolve())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python310\python.exe -c "import pathlib;print(pathlib.Path('foo.ts').absolute())"
C:\Users\basti\Pictures\foo.ts
PS C:\Users\basti\Pictures> C:\Python310\python.exe -c "import os.path;print(os.path.realpath('foo.ts'))"
C:\Users\basti\Pictures\foo.ts
```

As you can see, the return value also depends on whether the file already exists. `pathlib.Path.absolute()` doesn't normalize the path and doesn't resolve symlinks, so it can't be used as an alternative. `os.path.realpath()` on the other hand however does, so maybe we should switch to it instead. `pathlib` actually uses `os.path.realpath()` internally, after it got refactored in 3.10, as shown in the links above.

So far, all that I can reproduce is the log line with the non-absolute path due to the bad `resolve()` return value on `<=py39`. I don't know though if this could affect the `open()` call which leads to the error, or even `path.parents.mkdir(parents=True, exist_ok=True)` which is called prior. It's very likely though that the core issue here is the unresolved input path.

@lumynou5 Could you please check if you see the same error when setting an absolute path as the `--output` value, for example `%HOME%\Pictures\recording.ts`?

**Comment by lumynou5** [comment]
> Could it be that your username has special characters? I didn't try to reproduce, but I see similar issues in other applications when my userdir is named "Michaël" for example.
> 
> I can't tell here since you censored your username in your log.

My username consists with normal English letters only. Actually it works when output to the home directory.

**Comment by lumynou5** [comment]
> Could you please check if you see the same error when setting an absolute path as the `--output` value, for example `%HOME%\Pictures\recording.ts`?

Yes, I see the same error. (Only `--output` is changed.)
```
error: Failed to open output: C:\Users\***\Pictures\test.ts ([Errno 2] No such file or directory: 'C:\\Users\\***\\Pictures\\test.ts')
```

**Comment by bastimeyer** [comment]
> Remember that Windows treats folders in your home directory special. What this means is that the actual layout on the file system might be different compared to what you're seeing on your desktop. This depends on the system's locale settings and can also be overridden by some registry settings from what I could find according to my Google search results. I don't use Windows, so I don't fully know. There's more info required here.

Please answer this, because it's necessary information. Which system locale is being used? Have these special dirs like Pictures/Videos/etc been altered on your system, meaning do these directories **actually exist on the file system (NTFS)**? These could've been changed by something like OneDrive, etc. I don't know how mount points work on Windows though.

As shown earlier, the error is coming from here:
https://github.com/streamlink/streamlink/blob/6.5.0/src/streamlink_cli/output/file.py#L26-L29
It first creates all parent directories and then opens the file descriptor. The error can only be raised if the parent directories don't exist when opening the path in write-mode. This suggests that something is up with your file system or at least what the OS is making available to Python.

What's the result of this when running it from the Pictures directory?
```sh
python -c "import pathlib,os;p=pathlib.Path(os.getcwd());print(f'{p} {p.exists()}')"
```

----

Please see if this branch on my fork fixes the issue on Python 3.9:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:streamlink:cli/fix-check-file-output
```
pip install git+https://github.com/bastimeyer/streamlink.git@cli/fix-check-file-output
```

Also please try running Streamlink on Python 3.10 or higher. Thanks.

**Comment by lumynou5** [comment]
As far as I know, yes, the "Videos" special folder is located in `C:\Users\***\Videos`.
![screenshot](https://github.com/streamlink/streamlink/assets/84374077/3ece0d6f-a430-425d-ba10-16ac1b3b690d)

---

The output is:
```
C:\Users\***\Pictures True
```

---

Both the fork and Python 3.12.1 didn't work. I also tried in the interactive mode:
```py
>>> p
WindowsPath('C:/Users/***/Pictures/test.ts')
>>> p.parent.exists()
True
>>> f = open(p, "wb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\***\\Pictures\\test.ts'
```

**Comment by lumynou5** [comment]
I think it's not Streamlink or Python's fault after tests, though I haven't found the reason.
