### ISSUE TITLE
MD5 is still in use

### ISSUE THREAD

**Issue by Gax-c** [streamlink/streamlink#5920]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.7.2

### Description

MD5 which is considered unsafe is still in use [here](https://github.com/streamlink/streamlink/blob/master/src/streamlink/utils/crypto.py#L32), switching to a better one like sha256 should be better. 

### Debug log

```text
No available log.
```

**Comment by bastimeyer** [comment]
Completely irrelevant, because the function you've linked was added for a specific plugin which had to re-implement the behavior of the site it was built for:
fa2a6a897ad05d4d4a2ddd0ca855c90ebc918bad

This function is merely used to deobfuscate query string parameters of an HLS URL in the "streann" plugin. It is not security-relevant in any way, shape, or form.
https://github.com/streamlink/streamlink/blob/6.7.2/src/streamlink/plugins/streann.py#L151

Considering the other issues you've opened on other projects on GitHub (according to your GH profile), this sounds like a nonsensical search for specific patterns in public git repos.

**Comment by Gax-c** [comment]
Thanks for your reply. 
Actually, it's not simply searching for specific patterns, but it seems the false positive rate remains high.
