### ISSUE TITLE
Turkuvaz.py

### ISSUE THREAD

**Issue by Benedek789** [streamlink/streamlink#5942]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Turkuvaz.py

### Description

Turkuvaz plugin "Minikacocuk" not working.Please help.

### Debug log

```text
Turkuvaz Minikacocuk not working
```

**Comment by Benedek789** [comment]
Turkuvaz Minikacocuk not working

**Comment by bastimeyer** [comment]
This guy has been spamming me with pushy/needy support emails until I've blocked him.

He doesn't understand that this is the Streamlink project and not the dead and unmaintained Streamlink-27 fork, which is totally unrelated to Streamlink. Python 2.7 is officially dead since 2020, which I've also explained.

I'm going to add a temp ban now, because this person doesn't know how to behave and read. I don't want to waste my time explaining things on and on again.
