### ISSUE TITLE
Kick.com

### ISSUE THREAD

**Issue by fenopa** [streamlink/streamlink#6010]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

I see this request closed more than a year ago: https://github.com/streamlink/streamlink/issues/5238 but I think we can say Kick is an established site at this point.

### Input URLs

https://kick.com

**Comment by gravyboat** [comment]
I'd argue that Kick still violates rule 10 of the [contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests):

> Sites which have no way to determine viewership numbers

> Plugins must not implement websites which are unused or which only have a handful of real/actual users.

As far as I understand the situation Kick still does nothing in regards to the most basic view botting techniques and faking viewer counts. @bastimeyer I'm unsure what our stance on this sort of site should be as there's a lot of other problematic content which leads me to being biased against it so I can't be objective enough.

**Comment by bastimeyer** [comment]
The rule you're talking about is meant for sites which actually don't have any viewers. Yes, they are faking their viewer numbers, but it's not like there aren't any actual viewers (unfortunately).

While I have very strong opinions about kick, its content and partnered streamers, its business model, as well as its owners, I still don't have anything against adding a plugin. We already have plugins for similar sites, so it doesn't matter to me that this site is supported as well, regardless of what it stands for. If I would judge the content which plugins provide, then I would have removed a couple dozens of them already.

I already had a look at a plugin implementation, because it appeared to be rather trivial, which it indeed was.
