### ISSUE TITLE
plugins.twitch: Rewind or "--hls-live-restart" not working for live streams that support it

### ISSUE THREAD

**Issue by superbonaci** [streamlink/streamlink#6090]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 6.8.3

### Description

Some live Twitch streams support the "rewind" or "DVR" to replay it from the beginning or seek to any time. By default the Twitch page doesn't offer the slider, but with the Chrome extension [Twitch DVR player](https://chromewebstore.google.com/detail/iaeibhcmabccclfnafahihdndonfgebo) the slider appears always:

![live](https://github.com/user-attachments/assets/428662ff-6412-4e47-b688-558b5d1128e9)

![seeking](https://github.com/user-attachments/assets/5a7f260a-2ecf-4b38-aa42-3600d73ae597)

Some streams fail to rewind when seeking, the extension displays the errors:

![novod](https://github.com/user-attachments/assets/eb3ac02c-0e4f-4572-978e-6fe3aef391b0)

![subonly](https://github.com/user-attachments/assets/9cc01652-a548-4b70-a96e-58c630cc82f6)

The feature request is if the twitch plugin could be improved to support these streams, and detect the reason when the stream can't be saved from the start when the option `--hls-live-restart` is passed.

### Debug log

```text
$ streamlink --twitch-disable-hosting --twitch-disable-ads --hls-live-restart --stream-segment-timeout 30 --stream-segment-attempts 10 -o glorious_e.mp4 "https://www.twitch.tv/glorious_e" best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/glorious_e
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Writing output to
/data/livestream_scripts/glorious_e.mp4
[plugins.twitch][info] Will skip ad segments
[download] Written 38.13 MiB to /data/livestream_scripts/glorious_e.mp4 (11s @ 3.26 MiB/s)
[download] Written 40.12 MiB to /data/livestream_scripts/glorious_e.mp4 (12s @ 3.38 MiB/s)
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
You are completely misunderstanding how `--hls-live-restart` works and what its intentions are. This option simply makes the `HLSStreamWorker` start from the first available segment in a live playlist instead of starting from the live edge (minus the value of `--hls-live-edge`). The first available segments completely depends on the contents of the live HLS playlist.

Twitch's HLS live streams only include a segment window of a couple of segments, which means you can't rewind back to the start of the stream, because those are missing and not available anymore. Segments which were removed from the live playlist segment window are only available in the VOD playlist, which is then continuously updated in certain time intervals on the VOD playlist, but it's not suitable for live playback via regular playlist polling.

You can't simply merge different HLS playlists. What your browser extension does is just a dirty and ugly hack. There is no guarantee that the bitstream is continuous (discontinuities are very much unsupported by Streamlink) and that the media sequence is properly aligned as well.

https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.3.2
> A client MUST NOT assume that segments with the same Media Sequence Number in different Media Playlists contain matching content

You already got your answer in your previous thread: #5891
