### ISSUE TITLE
plugins.vtvgo: "error: Unable to validate response text: ValidationError(Callable):   iselement(None) is not true"

### ISSUE THREAD

**Issue by HuynhNhan0104** [streamlink/streamlink#6099]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 6.8.3

### Description

The vtv plugin has stopped working, and I think VTV may have changed their website. There is an error response.

### Debug log

```text
streamlink "https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html" --loglevel=debug
[session][debug] Loading plugin: vtvgo
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.0.9 30 May 2023
[cli][debug] Streamlink: 6.8.3
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.2.2
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.24.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.2.1
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin vtvgo for URL https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
error: Unable to validate response text: ValidationError(Callable):
  iselement(None) is not true
```

**Comment by bastimeyer** [comment]
The site has added bot-protection via an AWS WAF challenge, which requires client-side JS execution. It is unfeasible to re-implement this in Python.
https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge.html

Without a valid `aws-waf-token` cookie, the site's HTTP response is empty, which makes the plugin's validation schema fail, as it tries to parse the HTML response and find a stream token embedded in it.

This will require using Streamlink's webbrowser API, so that the cookie can be generated by a locally run Chromium-based web browser which can then be re-used and cached by the plugin.

**Comment by bastimeyer** [comment]
Had a quick attempt at fixing the plugin and got it working again using Streamlink's webbrowser API.

But before I can open a pull request with the necessary changes, it'll probably make sense moving the AWS WAF logic out of the plugin, because it's something that will surely be needed by other plugins in the future. I want a generic solution that can be re-used. I also noticed some small shortcomings in the webbrowser API that'll require an update in a separate PR.

What's unfortunate is that AWS seems to detect headless web browsers, so it can't be run "invisibly" when getting the token.

I'll also need to have a look at the cookie expiration and caching.

**Comment by HuynhNhan0104** [comment]
It seems everything is working well:
streamlink "https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html" --loglevel=debug
[session][debug] Loading plugin: vtvgo
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.0.9 30 May 2023
[cli][debug] Streamlink: 6.8.3+15.g389f8fe1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.2.2
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.24.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.2.1
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
[cli][debug]  --loglevel=debug
[plugins.vtvgo][debug] Restored cookies: aws-waf-token
[cli][info] Found matching plugin vtvgo for URL https://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html
[utils.l10n][debug] Language code: en_US
Available streams: 360p (worst), 480p, 720p (best)
