### ISSUE TITLE
plugins.okru: not working

### ISSUE THREAD

**Issue by Andrew135815** [streamlink/streamlink#6185]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

6.10.0

### Description

Odnoklassniki.ru is a social network where you can find your old friends. Communication, online games, gifts and cards for friends. Come to OK, share

### Debug log

```text
File "/usr/lib/python3.12/site-packages/streamlink/utils/module.py", line 34,
in exec_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3. File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3.12/site-packages/streamlink/plugins/vtvgo.py", line 13
in <module>
from streamlink.plugin.api.webbrowser.aws_waf import AWSWAF
File "/usr/lib/python3.12/site-packages/streamlink/plugin/api/webbrowser/aws_
af.py", line 6, in <module>
import trio
import trio
ModuleNotFoundError: No module named 'trio'
[streamlinksrv][debug] Arguments:
[streamlinksrv][debug] url=https://mobile.ok.ru/video/351615524467
[streamlinksrv][debug] stream=['best']
[streamlinksrv][info] Found matching plugin for URL https://mobile.ok.ru/video
351615524467
351615524467
[streamlinksrv][error] Unable to validate response text: ValidationError(xml_fin
d):
ElementPath query './/a[@data-video]' did not return an element
[streamlinksrv][debug] Send Offline clip
```

**Comment by bastimeyer** [comment]
This is the final time I'm responding to any of your posts.

You are not using Streamlink, you are using a third party fork, called "streamlinksrv". **THIS IS NOT [STREAMLINK](https://streamlink.github.io/)**.

You will have to ask the streamlinksrv maintainers for help. **We do NOT support any kind of fork or downstream project**, because this is out of scope here. According to the error log, the packager/maintainer of that streamlinksrv project failed to properly package streamlink and its dependencies. `trio` is a dependency of Streamlink.

The plugin is working absolutely fine in the latest upstream Streamlink version.

```
$ streamlink -l debug https://mobile.ok.ru/video/351615524467
[cli][debug] OS:         Linux-6.10.10-1-git-x86_64-with-glibc2.40
[cli][debug] Python:     3.12.5
[cli][debug] OpenSSL:    OpenSSL 3.3.2 3 Sep 2024
[cli][debug] Streamlink: 6.10.0+15.gb788b1e4
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.26.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.2
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://mobile.ok.ru/video/351615524467
[cli][debug]  --loglevel=debug
[cli][debug]  --player=/usr/bin/mpv
[cli][debug]  --webbrowser-headless=True
[cli][info] Found matching plugin okru for URL https://mobile.ok.ru/video/351615524467
[utils.l10n][debug] Language code: en_US
Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
```

> Odnoklassniki.ru is a social network where you can find your old friends. Communication, online games, gifts and cards for friends. Come to OK, share

Also, what is this nonsense gibberish?

----

Now to my actual response...

I've had more than enough with your constant bullshit and harassment.

First, you're spamming me ONCE AGAIN earlier this month with multiple support emails, which I've already told you months ago I'm not going to answer, because it's a waste of my time. I do not exist to do private support for people who are using my free software projects and who are **refusing to read any kindly provided AND REPEATED answers or linked documentation**.

`Andrew135815` is the **fifth** GitHub account you've created now, after your previous four accounts already were banned by me on the streamlink GitHub organization, namely `Ansee0216`, `Qwertz789`, `Benedek789` and `Benedek012`, because as said, you refused to read and continued spamming. You apparently are completely lacking any kind of reading comprehension. I can't explain this otherwise.

So good luck with your issue. This account will land on the ban list as well, and I will also raise the issue tracker requirements, so you won't be able to create a new account, ignore this response and spam once again.
