### ISSUE TITLE
Allow transcoding video in all situations

### ISSUE THREAD

**Issue by someperson** [streamlink/streamlink#6200]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Collaboration

- [X] My request is genuine and in the best interest of the project
- [X] [I will provide feedback should a pull request be opened with a new feature implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Description

I have a little HTTP service set up that takes in a URL, passes it to streamlink, and returns a redirect to Streamlink itself. Streamlink is configured to automatically exit when the client disconnects. I find this pretty handy as a backend service, but I'd like to also be able to transcode the video. I see there are flags to specify options to pass to ffmpeg internally that would make it do this, but these are apparently only used by certain plugins. Is there any chance of this functionality being supported more generally? Piping the output to ffmpeg itself, as mentioned elsewhere, isn't really a solution in this case. Thank you!

**Comment by bastimeyer** [comment]
This has been asked and answered more than a dozen times. Just pipe the stream into ffmpeg, to remux or reencode it on-the-fly. Or record it, and then remux or reencode later, because doing this on the fly can sometimes be problematic depending on the video container. You'll find more info on the issue tracker and discussion forum.
```
streamlink --stdout ... | ffmpeg -i pipe:0 ...
```

The `--ffmpeg-...` CLI arguments and respective session options are only meant for streams which **require** remuxing, like DASH or HLS with additional audio streams, or subtitle streams. This can't be changed currently due to how this was implemented in the past. But with a planned overhaul of the stream selection which will also change the remuxing logic, generic remuxing/reencoding will/might become possible.

Btw, Streamlink's main purpose is playback of live streams, not recording, so if your goal is to record and re-encode stuff, then use a different tool.

**Comment by someperson** [comment]
Yeah, I get it. As I said, piping the output to ffmpeg does not solve my particular use case at all. So I guess I’ll continue scouring the web for another tool that does…

**Comment by mk-pmb** [comment]
> Piping the output to ffmpeg itself, […] isn't really a solution in this case.

Could you explain why? The better the reason, the more motivation someone may have to reconsider your case.

**Comment by someperson** [comment]
What I wanted to accomplish here was having Emby's live TV interface, which can only really take in a URL, connect to a video stream via Streamlink. I built a little HTTP service that takes in a URL and launches Streamlink using `--player-external-http` with `--player-external-http-continuous false`. It then returns a 307 redirect directly to Streamlink, which allows Emby to play the stream, and Streamlink automatically quits when Emby stops streaming. Piping the output to ffmpeg would negate the use of Streamlink's HTTP interface, so I have no obvious way to get the output to Emby and have Streamlink and ffmpeg automatically shut down when the stream is stopped.
