### ISSUE TITLE
(hls) Calculate and add “delay to broadcaster” to debug logging

### ISSUE THREAD

**Issue by spotthecow** [streamlink/streamlink#6281]
### Checklist

- [x] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Collaboration

- [x] My request is genuine and in the best interest of the project
- [x] [I will provide feedback should a pull request be opened with a new feature implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Description

The native twitch player has an option to show the estimated delay to the broadcaster. I don’t see a way to do this with stream link and nothing comes up for me when i search closed/open issues. 

I’m writing a TUI for twitch.tv which relies on streamlink for streaming. I think it would be useful to display delay to broadcaster as a debugging tool as well as affirming the health of the stream. 

My knowledge of hls is limited, but it’s my assumption that a delay can be estimated by using timestamps from the media playlist?

If this feature is technically feasible and is desired, I’m willing to take a crack at a PR.

**Comment by bastimeyer** [comment]
Duplicate of #620 (very old issue from 2017).

HLS segments have the optional `EXT-X-PROGRAM-DATE-TIME` metadata (`HLSSegment.date: datetime | None`), which is always present in Twitch's HLS playlists. However, reading the segment date metadata has nothing to do with when the stream data will be shown by the player.

This kind of feature therefore doesn't make sense for Streamlink, because the actual playback delay depends on the used player, its own internal buffer in addition to Streamlink's buffer, and the presentation time.

The following simple diff lets you log the segment's date (in UTC) just before the segment's HTTP response data is downloaded. The time will only be precise though if `--twitch-low-latency` is true (plugin-specific), if `--hls-segment-stream-data` is true (so data is written to Streamlink's output buffer while the segment is being downloaded), if `--hls-live-edge` is 1, if the data is read by the player immediately, and if the player doesn't use additional caching/buffering, meaning the data has to be decoded and rendered with very little delay. As you can see, this is nothing Streamlink can control.

```diff
diff --git a/src/streamlink/stream/hls/hls.py b/src/streamlink/stream/hls/hls.py
index 473ca311..47c2025f 100644
--- a/src/streamlink/stream/hls/hls.py
+++ b/src/streamlink/stream/hls/hls.py
@@ -274,6 +274,8 @@ class HLSStreamWriter(SegmentedStreamWriter[HLSSegment, Response]):
                 return
 
         else:
+            if segment.date:
+                log.debug(f"segment {segment.num}: {segment.date.strftime('%Y-%m-%dT%H:%M:%SZ')}")
             try:
                 for chunk in result.iter_content(self.WRITE_CHUNK_SIZE):
                     self.reader.buffer.write(chunk)
```
