### ISSUE TITLE
Browser does not work with API

### ISSUE THREAD

**Issue by git-eternal** [streamlink/streamlink#6308]
### Checklist

- [x] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the problem](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 7.0.0

### Description

      
i added this code to my api test with my oauth token. 

```py
session.set_option("api-header", [("Authorization", f"OAuth {oauth_token}")])
session.set_option("webbrowser", True)
session.set_option("webbrowser-headless", False)
session.set_option("webbrowser-timeout", 30.0)
session.set_option("webbrowser-cdp-timeout", 5.0)
```

the viewing itself works but it never launches a web browser to get client integrity token nor validate the oauth (and seemingly authenticate with it at all.) even if i put an invalid oauth token it still watches the stream but never gives any form of error or logging that its even doing anything, which is why i believe it is broken.

the cli actually works with the browser and gives an error for invalid oauth tokens etc such as

"[plugins.twitch][warning] No client-integrity token acquired
error: Unauthorized: The "Authorization" token is invalid."

Note: --twitch-api-header isnt supported in API so i used manual Authorization oauth header

### Debug log

```text
there is no loglevel debug option for API as it seems, or if there is, it does nothing. I cannot provide any more useful info here that my description above did not already provide. Sorry!
```

**Comment by bastimeyer** [comment]
> ```py
> session.set_option("api-header", [("Authorization", f"OAuth {oauth_token}")])
> ```

`api-header` is not a session option. You are looking for a plugin option, which is something completely different.

- https://streamlink.github.io/api/session.html#streamlink.session.options.StreamlinkOptions
- https://streamlink.github.io/api/plugin.html#streamlink.plugin.Plugin

> it never launches a web browser to get client integrity token

Then you're doing something wrong with your implementation, or you don't have any of the supported web browsers installed.
Without the information you've provided, there isn't much to say.

Also, since you're talking about the Twitch plugin (without even mentioning it), the Twitch plugin explicitly requires its `force-client-integrity` option to be set to `True`, or the webbrowser call will only be made if the streaming access token acquirement fails, as it's actually only meant as a fallback mechanic. The option forces the webbrowser call for people who always want to acquire a client-integrity token.

> there is no loglevel debug option for API as it seems, or if there is

You must add a logging handler to the root logger and set the log level accordingly if you're accessing Streamlink's API. Have a look at the Python std lib or `streamlink.logger.basicConfig`. The options you're talking about are for Streamlink's CLI, which properly adds the handler(s).

----

```py
Python 3.13.0 (main, Oct  7 2024, 18:36:34) [GCC 14.2.1 20240910] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> from streamlink import Streamlink
>>> from streamlink.options import Options
>>> logger = logging.getLogger("streamlink")
>>> logger.setLevel(logging.DEBUG)
>>> logger.addHandler(logging.StreamHandler())
>>> session = Streamlink()
>>> plugin_options = Options()
>>> plugin_options.set("force-client-integrity", True)
>>> name, plugin, url = session.resolve_url("twitch.tv/shroud")
>>> twitch = plugin(session, url, plugin_options)
>>> twitch.streams()
```
```
Getting live HLS streams for shroud
Acquiring new client-integrity token...
Launching web browser: /usr/bin/chromium (headless=False)
Waiting for web browser process to terminate
{'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
Language code: en_US
dict_keys(['audio_only', '160p', '360p', '480p', '720p60', '1080p60', 'worst', 'best'])
```
