### ISSUE TITLE
Newest Streamlink.exe reported as virus

### ISSUE THREAD

**Issue by Jumpy91** [streamlink/streamlink#632]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

After compiling the newest version with the portable compiler tool, the generated Streamlink.exe gets removed by Avast Free Antivirus as "Win32:Maleware-gen". After that report i uploaded my generated Exe to VirusTotal an this pages results the same. Please look at the problem. Thank you.

### Environment details (operating system, python version, etc.)
http://www.sysprofile.de/id171882

### Comments, logs, screenshots, etc.
- https://virustotal.com/de/file/d9ba62e5d33c8ff53503f8ec7fe9de7ed881694d6ead0a285529a32e447cf9df/analysis/1488218244/
- https://puu.sh/umrvG/1006b7d5ac.png

**Comment by gravyboat** [comment]
This happens every couple releases because it hasn't been reported enough so it's in their database. There isn't much we can do as far as I'm aware past asking people to send it to them so they mark it appropriately.

**Comment by Jumpy91** [comment]
Oh, okay, i thought you git got compromised or something.
Thanks for your answer and sorry for stealing your time ^^

**Comment by gravyboat** [comment]
No worries. Just to be clear, did you compile from our git repo, or from the portable version that @RosadinTV works on? This is the portable repo: https://github.com/streamlink/streamlink-portable so feel free to browse that code if you have any concerns.

**Comment by Jumpy91** [comment]
I used the program form the repo you linked above. Which also only compiles successfully when Avast is disabled.

**Comment by RosadinTV** [comment]
@Jumpy91 
Interesting, the program itself dont get detected by any antivirus (0/57):
https://virustotal.com/es/file/378f25090ff49aa8c9a39ad837fc5c220e7a49c3d9374ccd34f5e787ce8edb50/analysis/1488232584/
But the Streamlink.exe (compiled on-the-fly) as you pointed is detected (15/58)
Really strange because both source codes (PORTABLE_BUILD.vb and STANDALONE_BUILD.vb) dont have any anomaly in them and are very basic:
https://raw.githubusercontent.com/streamlink/streamlink-portable/master/Streamlink%20for%20Windows%20(Compiled)/Files/Resources/PORTABLE_BUILD.vb
https://raw.githubusercontent.com/streamlink/streamlink-portable/master/Streamlink%20for%20Windows%20(Compiled)/Files/Resources/STANDALONE_BUILD.vb
Anyway i will try to find out why it happens to reduce the false-positives.

**Comment by gravyboat** [comment]
@RosadinTV This happened a couple of releases ago as well and I am pretty sure in many cases it's simply because they don't have it on their records. If you find anything let me know, but don't stress yourself too much over it. All the code is freely available and available to browse, so we know it's clean!

**Comment by gravyboat** [comment]
I'm going to close this out. For anyone that stumbles on this issue Streamlink is sometimes detected as a virus (especially with newer releases) because it isn't on file with many anti-virus providers.

**Comment by RosadinTV** [comment]
Out of curiosity today i tested the latest release (v0.5.0 - Git 6a42453) and Virustotal only detect 0/61
Weird but good news 😄 
https://virustotal.com/es/file/ba4042b0168a7d8daa53077be5db6737cd273d7119274904364d3a7645c7910e/analysis/
