### ISSUE TITLE
Tvplayer.com Not working for me properly

### ISSUE THREAD

**Issue by willbrow** [streamlink/streamlink#654]
----Edit ITV is working now i think it was either because i had fiddler open or because i went on site and entered postcode but it is working now now i only need help and info on the drm side of things please 

Tvplayer.com is not working for me on the below i am also providing email and password 
tvplayer.com/watch/itv or tvplayer.com/watch/five

ITV i think it because on there website you have to enter uk postcode before playing so im guessing that could be integrated and fixed.

Five is stating DRM but i wanted to check this is correct and also ask if drm is possible to bypass by using browser inspect element or fiddler to get DRM key and add to argument but i dont know much about drm so maybe it is not a key i can capture and resend but if someone could explain if this is possible and alittle on how drm works it would help me thanks

**Comment by beardypig** [comment]
I'll look at fixing ITV, I hadn't seen the postcode think. 

Unfortunately it's not possible to bypass the DRM for five, five star, or the premium channels. Getting the DRM tokens is relatively simple, but convincing the DRM system to decrypt the video is not so easy... Maybe one day it will be possible :-)

**Comment by willbrow** [comment]
I think i understand you can get drm token but when it is sent to drm provider the provider is not returning the decryption key is that how it sort of works.Sorry i like to understand technically im just curious :)

**Comment by beardypig** [comment]
OK, well this might be of interest to you...

TVPlayer uses DRM to protect some of their content; Five, 5Star, and all the premium channels. The free channels (some require a login) use HLS adaptive streaming and are not encrypted. 

The channels with DRM use MPEGDASH (mpd) adaptive streaming on the Desktop/Android/Chromecast, which streamlink doesn't support yet, and they use HLS (+DRM) on iPhone. The video presented in the DASH/HLS+DRM streams is encrypted using AES128 with a 16 bytes key (the content key). There are multiple different DRM systems offered as alternatives depending on which platform you are viewing the content from. They offer Widevine, PlayReady, AdobeAcces, and Marlin in the DASH stream and FairPlay in the HLS stream. Depending on which DRM system your player supports one will be chosen. For example in Chrome the player will get the DASH stream and use the Widevine DRM system, and on iPhone the player will get the HLS stream and use the FairPlay DRM system. 

Mostly all of the DRM systems work in the same way; most use a form of [asymmetric encryption](https://en.wikipedia.org/wiki/Public-key_cryptography) with a public and a private component.  They may have a per-user secret stored on the device (individualisation secret) and a site or service specific public key. 

The streaming provider will provide a content key ID, and a challenge token (some opaque blob of data, possibly containing the public site key) and the player will pass this information to the DRM system which will apply some secret process to that data and produce a challenge response token (another opaque blob of data, but presumably it is encrypted and contains the  public component of the individualisation key, details about the platform, etc.). The response token is sent back to streaming provider by the player and, if valid, the provider will send back another opaque block of information containing the content key (encrypted, obfuscated etc.), which the player then passes back to the DRM system. The DRM system will decrypted the content key and store it (possibly encrypted in memory, obfuscated, etc.) and inform the player that it is ready to decrypt content encrypted with that content key (identified by the content key ID). The player then loads the video data from the stream and passes it to the DRM system, which decrypts it and possibly decodes the video data in to raw frames, and then passes that back to player, which in-turn displays it to the user. 

Reverse engineering exactly how that process works is quite complex, because they have specifically designed the system for it to be difficult to reverse engineer. Even if you did work it out, it would be very easy for the DRM provider to change the system a bit and then you'd have to start all over - it would be a game of cat and mouse.

**Comment by karlo2105** [comment]
@beardypig 
Is is worth to implement DRM support to tvplayer.com as it's only available with account ? Will they change it often then after implementation ?

**Comment by willbrow** [comment]
Thanks for the explaining i noticed from the .mpd that the system was using dash. I find this quite interesting and am going to be learning more about this.

One thing im still unsure about and going to investigate futher is  if fiddler can see the traffic and the .ts as they become available would it be possible if playing a stream in the browser in legit way would it not be possible to pull the stream the packets fiddler picks up as the session running would be a legit one and the DRM tokens and keys i would guess would also be valid 

Im probably completly wrong so will research into this more but you have given me a good starting point here mate thanks

**Comment by beardypig** [comment]
@karlo2105 I might get it to work, it is a fun challenge ... I have actually been working on it for months, ever since streamlink reignited my interest :)

**Comment by beardypig** [comment]
I think since #659 has been merged this is good to close.
