### ISSUE TITLE
Feature request: Linux binaries

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#669]
I did this previously in a different application, see:
https://github.com/projectatomic/atomicapp/commit/925fba1b60de59c99b2a6be2ea75e7f8e74298eb

Shouldn't be too hard to do.

Similar to a project such as https://docs.docker.com/compose/install/ it'd be nice to be able to have a single binary to install instead of having to install Python and have the correct version of it running, etc.

Since we already have `pip`, `.exe`'s, it'd be nice to have the appropriate binaries for both Linux + Mac OS X as well.

**Comment by Gfurst** [comment]
By the way, what the requirements right now... I'm getting errors to run streamlink right now, some python backtrace... installed version is 3.6

**Comment by gravyboat** [comment]
This isn't an appropriate issue to ask questions about installation, especially without the output you're seeing or any details on your installation method.

**Comment by Gfurst** [comment]
That's alright, its because I've seen somewhere else it required Py <= 3.3 but I can't find documentation on it anywhere, and instead of posting I tried looking if the was already mentioned somewhere else. 

Since the OP is basically asking on the necessity of python either I thought it might relevant. Anyway, Arch is already distributing pre-compiled packages on the main repos.

**Comment by gravyboat** [comment]
@Gfurst Just looked back through some old issues and realized my comment from March 20th may have come across as somewhat rude, my apologies there.

**Comment by back-to** [comment]
old issue but, this would require some changes.

pyinstaller won't load any default plugins because Streamlink needs a plugin path,
which is not present with the binary method.

https://github.com/streamlink/streamlink/blob/66409146e32df8d68d9339f2a5c293b4fcc882b3/src/streamlink/session.py#L446-L447

`load_builtin_plugins` would need an update without `__path__`

also there are some other minor `from streamlink import ...` issues

---

useful links for pyinstaller

Ref https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point
Ref https://github.com/pyinstaller/pyinstaller/issues/305

**Comment by marcus13345** [comment]
In case anyone is looking for a workaround in the meantime, my solution to this problem, was to download the windows portable version, with the python files exposed, and insert a python shebang on the main streamlink file, set its execution bit, and link its folder in `PATH`. seems to work just like the windows portable, with the exposed plugins folder.

**Comment by callowaylc** [comment]
.. or `pip install streamlink` (its python2); any other way is wrong and if pip doesnt work, don' work around it, find out why a pip install failed. 

a packaged, executable bundle  != binary

**Comment by marcus13345** [comment]
@callowaylc I dont mean to be rude, but a lot of people like to use vendored programs in potentially uncontrolled environments, where they dont necessarily have access to the entire system's configuration.

If i deploy something that requires the end user (or the program, automatically) to install pip and python onto the machine, globally, that could potentially mess with other system configurations. I'd much rather have a black boxed utility with the same functionality.

And to your point that any other way is wrong, I would direct your attention to the windows unpacked "binaries" that already exist. Its not the most elegant solution, however it fulfills the basic need of an application, to run streamlink, without leaking any of its configuration to the local system.

My workaround suggestion, is merely a way to accomplish the same level of portability as the windows portable version. It works like a charm on macos, and im sure it would work just as well on linux.

**Comment by callowaylc** [comment]
`@callowaylc I dont mean to be rude, but a lot of people like to use vendored programs in potentially uncontrolled environments, where they dont necessarily have access to the entire system's configuration.`

Honestly, rudeness is appreciated on my end; the industry tends to be overly saccharine, which has led to hobbyists and amateurs posing as subject matter experts. 
```sh
/ # adduser marcus -D
/ # su marcus
~ $ whoami
marcus
~ $ pip install streamlink --user -q
~ $ ls .local/bin/
streamlink
~ $ PATH=$HOME/.local/bin:$PATH
~ $ streamlink -h
usage: streamlink [OPTIONS] <URL> [STREAM]
```

`If i deploy something that requires the end user (or the program, automatically) to install pip and python onto the machine, globally, that could potentially mess with other system configurations. I'd much rather have a black boxed utility with the same functionality.

And to your point that any other way is wrong, I would direct your attention to the windows unpacked "binaries" that already exist. Its not the most elegant solution, however it fulfills the basic need of an application, to run streamlink, without leaking any of its configuration to the local system.

My workaround suggestion, is merely a way to accomplish the same level of portability as the windows portable version. It works like a charm on macos, and I'm sure it would work just as well on linux.
`

If you are distributing a cli, ala streamlink, the end user already has python/pip if they are running osx/linux - if they do not, they are an outlier. 

What you are describing is a portable, dependency-complete bundle, that runs in isolation, which is fine, just don't call it a binary and realize that the end result of a publishing a workaround is unintended misinformation; using the canonical toolset will give you base upon which to build, instead of a spell book. 

```sh
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
$ docker run -it --rm --entrypoint "" lauwarm/streamlink-recorder sh
/ # which streamlink
/usr/local/bin/streamlink
```

`As well to your second point of binaries vs executable bundles. The argument itself is incredibly semantic, and not something I'm interested in getting in to` 

https://en.wikipedia.org/wiki/Binary_file
https://en.wikipedia.org/wiki/Executable

**Comment by ryankashi** [comment]
> In case anyone is looking for a workaround in the meantime, my solution to this problem, was to download the windows portable version, with the python files exposed, and insert a python shebang on the main streamlink file, set its execution bit, and link its folder in `PATH`. seems to work just like the windows portable, with the exposed plugins folder.

@marcus13345 can you please elaborate further the steps that you did to recreate this? I am trying to do the same however am running into a significant number of issues.

I am currently working on bundling streamlink as part of my application by following your steps, however I am unable to get streamlink working. In addition, I have also tried the pyinstaller solution via:
`pyinstaller $(which streamlink)`

However I after bundling and trying to run streamlink inside of my dist folder I get:
`error: No plugin can handle URL: twitch.tv/<stream_name>`

After I unzip streamlink-portable-1.7.0-py3.6.5-amd64.zip, I modify the shebang inside of streamlink-script.py to add python:
`#!/usr/bin/python` as opposed to `#!python`

and then make it an executable via:
`chmod +x streamlink-script.py`

Next, I get the error:
`ImportError: No module named backports.shutil_which` (via Python2.7, included in the screenshot)

![python27_error](https://user-images.githubusercontent.com/13973467/99732234-fed66080-2a73-11eb-9809-6cd65139724e.PNG)

When I try to use python3 (I have tried python3.6.5, 3.7.x, as well as python3.9), I get:
`OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'`

![python3_error](https://user-images.githubusercontent.com/13973467/99732478-6a203280-2a74-11eb-8b94-7079f5f01194.PNG)

I am trying to package this as part of an electron application, and as such I do not need streamlink to work globally for the user.

Do I have to change any of the directories inside of the streamlink folder? You mention "python files exposed" as well as "plugins exposed," however I am not quite sure what this means. Am I supposed to move the contents of the unzipped folder around in order for it to work properly in Mac? Also I am quite the noob when it comes to programming so I am not quite sure what I need to do path wise. I do not need streamlink to run globally so I am assuming I do not need to do this?

Thank you SO much, I really appreciate it. I am in the final stages of releasing my app (with everything running perfectly on windows), however am running into some mac issues regarding streamlink and packaging.

**Comment by gravyboat** [comment]
@ryankashi Use Python 3. There's an issue [here](https://github.com/streamlink/streamlink/issues/2029), as well as comments that explain why this is occurring as well as solutions. This really wasn't the place to put an off-topic question.

**Comment by ryankashi** [comment]
Has there been any updates on the status of this? I have been trying to create a Mac portable binary/executable to hopefully place a merge for using pyinstaller, however truth be told I am an AWFUL programmer and have made essentially 0 progress :-(.

In addition, Is there any way I can help with this issue?
