### ISSUE TITLE
Plugin request: Aliez.tv to Aliez.me

### ISSUE THREAD

**Issue by wigan77** [streamlink/streamlink#695]
### Checklist

- [x] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Aliez.tv does not exist anymore there is Aliez.me which is actually the same streaming site.

### Reproduction steps / Stream URLs to test

1. http://aliez.me/live/fkpev212/ link im trying to open in player

**Comment by karlo2105** [comment]
Maybe it would be interesting to include in plugin aliez.* instead of aliez.me. That way once they change domain name it won't be required to adapt plugin.

**Comment by morturio** [comment]
streams like https://aliez-stream.gcdn.co/hls/streama60855/index.m3u8 are not supported. could you do that?

**Comment by bastimeyer** [comment]
@morturio Please don't comment on pull requests which have been closed since almost a year ago... If you have a question or bug report to make, please open a new issue.

Regarding your question, direct links to HLS playlists are not meant to be supported by plugins. You need to follow the instructions from here:
https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly
