### ISSUE TITLE
How the ffmpeg.exe and rtmpdump.exe work in streamlink?

### ISSUE THREAD

**Issue by zoux86** [streamlink/streamlink#732]
Hi

How the ffmpeg.exe and rtmpdump.exe work in streamlink  in windows?
I read the source Code , and didn't find how the ffmpeg.exe and rtmpdump.exe work in streamlink?
and I commented out  these  in streamlinkrc 
#ffmpeg-ffmpeg=d:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
#rtmpdump=d:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe

and then i run command line and use streamlink to play stream or save stream, it has no effect.
so i want to know the how the rtmpdump was used in streamlink?

Regards

**Comment by beardypig** [comment]
They are only used for specific stream types. rtmpdump is used for RTMP streams and ffmpeg is used when there are separate video/audio streams that have to be combined (some hls streams use this).

**Comment by gravyboat** [comment]
Going to close this out since Beardypig has provided the details.

**Comment by johnthecracker** [comment]
@beardypig ,

I can do with FFMPEG everything that I can do with RTMPDUMP.

Your FFMPEG works somewhere where your RTMPDUMP fails.

https://github.com/streamlink/streamlink/issues/741

https://github.com/streamlink/streamlink/issues/707

Why you don't dump your RTMPDUMP and use FFMPEG instead ?

I would not say dump your FFMPEG and point users to path where their FFMPEG is because

I have notice that your FFMPEG is compiled in different way that Zeranoe's.

**Comment by beardypig** [comment]
To maintain compatibility would be the main reason. `ffmpeg` and `rtmpdump` have different arguments, so `ffmpeg` could not be used as a drop in replacement. Of course, an `FFMPEGRTMPStream` class (horrible name) could be created to use `ffmpeg` to stream RTMP streams instead of `rtmpdump`.
