### ISSUE TITLE
How do I return WinXP compatibility?

### ISSUE THREAD

**Issue by vadosnaprimer** [streamlink/streamlink#795]
Hi. Since github doesn't have PMs anymore, I'm asking it like this.

I'd just fork this and make it support XP again, but I honestly don't know what commit to revert, and what parts of the code are affected. On top of that, I never touched python.

**Comment by karlo2105** [comment]
With latest Python 2.7.x or the latest Python 3 branch supported on XP, you can install Streamlink development version on Windows XP : 

`https://www.python.org/downloads/release/python-2713/`
`https://www.python.org/downloads/release/python-344/`

You need git too : 
`https://git-scm.com/download/win`

From command line you can install Streamlink development. 
`pip install -U git+https://github.com/streamlink/streamlink.git`

Personally I use Python 2.7.13. Streamlink will work on XP normally.

**Comment by beardypig** [comment]
There is a PR to add an XP compatible installer #680. We should have it sorted soon, or you can do as @karlo2105 suggested :-)

**Comment by kebabkalle** [comment]
@beardypig Is there any update on the xp installer? I checked #680 but I didn't quite get if there was an xp installer available or only test builds. Thank you.

**Comment by gravyboat** [comment]
@kebabkalle We haven't come to a conclusion yet on proper storage of all the extra binaries and such that would have to be provided for an XP build. I am still of the mind that we should not provide support for XP. It's extra work for very little benefit and an extremely small minority of people as we would basically be supporting malware machines due to all the recent compromises found on XP.

**Comment by joe-666** [comment]
I am also trying to run stramlink on XP. This http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide shows that XP is 5% of all windows versions, and is about 3x more used than Linux (in the specific way that they count usage)

My reasons for using XP is that for some machines a Windows upgrade isn't supported by the hardware or would degrade performance too much.

My reasons for running streamlink include avoiding the thick software stack of browser + adode, again for performance (and potentially for better functinality).

My XP PCs are not malware machines, because I am carefull about what I do with them.

**Comment by bastimeyer** [comment]
Closing, since @karlo2105 provided a sensible and working solution, thanks.
WinXP is not supported anymore and not worth the time making the installer work here. Let it die.
