### ISSUE TITLE
way to limit bandwitch or lower quality or any other way to reduce download during a specific time

### ISSUE THREAD

**Issue by jwallet** [streamlink/streamlink#844]
hi

I read it's not possible to change the stream quality once is started.
but I work on a project that we use streamlink to play streams that has ads with no sound. So by detecting the sound level of the media player we know if there is an ad playing and I would like to reduce the downloads for our users during those ads, like doing some bandwidth throttling on the app or something else. Playing one stream can be about 3gb and some users have a download cap per month with their ISP.

thanks for any advice

**Comment by beardypig** [comment]
If you reduce the download speed during ads it will just mean buffering during the ads, the same amount of data will be downloaded only it will take longer. I do not believe it is possible to switch qualities on the fly and still produce a valid output stream (they often have different resolutions).
If you just want to stream and not produce a valid video file at the end you could do it with your own custom player, but they you'd have to write your own stream downloader as streamlink wouldn't be much help.

**Comment by gravyboat** [comment]
In addition to what @beardypig said we aren't going to add logic or support to purposefully avoid ads for people. While this occurs on some streaming platforms due to the way they are configured we do not try to circumvent ads. This is both dishonest of us to not support the platforms that are used by circumventing what may be their only revenue stream, and it opens us up to potential legal action. I'm going to close this. You're welcome to explore possible workarounds but the Streamlink team cannot assist with such an endeavor, supporting the services that provide the streams people watch is important and it would be hypocritical of us to help with this.
