### ISSUE TITLE
Streamlink releases

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#855]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...I am downloading streamlink nightly on daily basis because today's streamlink can do what yesterday's maybe couldn't.

I am forced to download nightly version daily wasting github's resources just to find out which day's nightly is the latest nightly.

There is no way known to me on streamlink's pages to know which nightly is today's nightly before downloading it.

This is the link I get nightly from:

https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe

and it looks like this:

streamlink-latest.exe

not giving me any clue what day's version it is before seeing it on my disk.

This is one example of nightly ( latest release ) from youtube-dl:

https://github.com/rg3/youtube-dl/releases

crystal clear.

Please comment on this post, and direct me to right page if it exists.

This is not the latest release, nightly is.

https://github.com/streamlink/streamlink/releases/tag/0.5.0

**Comment by gravyboat** [comment]
The latest release is the latest stable. The nightly is not guaranteed to be stable and sometimes includes code that may have bugs in it. It's worth considering adding some sort of release tagging to the nightly though, thanks for the report.

**Comment by bastimeyer** [comment]
The nightly builds are hosted independently on S3 and are generated for each commit on the master branch. You're not wasting github's resources, but instead resources of the person who's providing the S3 bin (@beardypig).

I'm strongly against uploading nightlies as regular github releases (even if tagged as a pre release), because it's not well designed for this use case. Most, if not almost all casual users who are downloading Windows installers from the github release pages do not know what they are downloading, because they are not reading the entire page. This means that uploading potentially unstable nightlies, although flagged as a pre release, could lead to bad user experiences if something doesn't work correctly (yet). It's a much better idea to use the github releases for only stable releases with a proper versioning schema and a change log.

As you can see in #167, there's a list of all nightlies named by commit number of the master branch and and shorthand ID of the commit (eg. 7c0db8c: `streamlink-0.5.0-1214-7c0db8c.exe`):
https://streamlink-builds.s3.amazonaws.com/index.html
https://github.com/streamlink/streamlink/commits/master

Btw, you can see the explicit changes in the git log of the master branch, so there's really no need to download nightly builds every day unless it directly affects your usage of Streamlink, which is very unlikely.
If you still really want to install the latest development version every day, you could instead use python-pip and install Streamlink from the git repo and install all of its dependencies automatically:
`pip install git+https://github.com/streamlink/streamlink.git`

On Arch Linux, the `streamlink-git` AUR package can be installed, which is the equivalent of this or the nightly Windows installer. Does chocolatey allow development packages? Maybe this could be another solution for Windows users.

**Comment by bastimeyer** [comment]
An alternative to S3 could be a second repo on github where nightlies get uploaded to as pre releases, so the stable release list doesn't get merged with the unstable one. This way it'd be much clearer. And instead of using a private S3 bin, it would be a free hosting service (this could be against Github's ToS though).

**Comment by johnthecracker** [comment]
https://github.com/streamlink/streamlink/pull/167

As I see, this is still an open issue.


https://streamlink-builds.s3.amazonaws.com/index.html

This sounds good and would be good to me, bus shows no information at all.


https://github.com/streamlink/streamlink/commits/master

Here is some information but no link for me to click to download latest nightly
and no specific information to nightly I am downloading.


About bastimeyer's last post I don't know how streamlink works with github, s3 and rest,
but looking at youtube-dl's page link I posted here and looking like normal visitor looks impressive.

**Comment by gravyboat** [comment]
We provide users the latest stable release on the releases page as @bastimeyer noted. If people want to use the nightly due to a specific PR they're welcome to download it, but we aren't going to promote that on the releases page. There's no reason to do so as the number of users who typically need the nightly build for a specific feature is pretty minimal considering we average a release approximately once a month. The details linked by @bastimeyer are more than sufficient and we expect some technical knowledge or experience if a user chooses to use the nightly build due to the possible instability. If your desire regarding the nightly builds is to review what has changed, then you'll need to look at the commit history which is freely available on GitHub.

**Comment by johnthecracker** [comment]
Windows nightly installer is advertised on your:

https://streamlink.github.io/install.html#windows-binaries



Windows binaries

......

Alternatively, you can download the latest nightly Windows installer.



Now, you can remove this link or try to understand what I want to say:

I want to see exactly what day's nightly I can download, before doing so.

Otherwise, I will download nightly every day you like it or not.

**Comment by beardypig** [comment]
@johnthecracker you are of course free to download the nightly as many times as you want, it costs us (me) $0.002 each time you download it, but that's fine as the total cost for hosting the nightly builds is around $2.00/month. Obviously if this cost goes up dramatically then we'll have to reconsider hosting nightly builds, but for now it's not a problem. 

We could host a file next to the latest installer that describes the changes (git shortlog) since the last release, that way you could check that file to see if you want to get the latest version or not.

**Comment by johnthecracker** [comment]
@beardypig,

If there was any description about file to download I would not be asking here for it.

I want to know what I'm downloading.

If there was a description next to download link like this:

File version 0.5.0.1229

there would be no need for me to proceed with download had I downloaded the same file yesterday.

Your proposal to host a file next to the latest installer that describes the changes
would even go one step further, after reading it I might realize I don't need that particular nightly.

**Comment by beardypig** [comment]
@johnthecracker I know there is no description, it's not something that is very easy to add to the docs. If it were easy then it probably would have been done already. 

Having another file that describes it would be much easier.  I'll take a look at doing that this week, it's labour day tomorrow so I'll probably not have chance to look at until midweek.

**Comment by johnthecracker** [comment]
Thank you for looking at this.

Whatever makes me know what nightly version I'm downloading helps.
