### ISSUE TITLE
Stream DASH format to vlc 

### ISSUE THREAD

**Issue by tayapski** [streamlink/streamlink#870]
This is more of a question than an actual issue with the code. 

I would like to know if it's possible to have streamlink use an adaptive stream and not a fixed quality? I'm trying to study adaptive video streaming so I was wondering if this is possible. I'm imagining something similar to how Youtube videos (on the website) can change qualities while they are playing.

**Comment by gravyboat** [comment]
Right now we don't support DASH. If you look at some of the old issues and search for dash you can see we've discussed this several times before. Regarding adaptive quality we don't support that either (though I am sure you could write a wrapper or something). We don't track or monitor bandwidth, simply report segment failures which are commonly related to bandwidth issues. I'm going to close this out since we've discussed DASH pretty extensively in the past as well as the limitations.
