### ISSUE TITLE
[Non Issue] A simple shell script for streamlink (contributes/enhancements  most welcome)

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#872]
Just thought i'd share this very simple shell script for quickly launching streams, feel free to enhance it, * zenity needs to be installed to use it.

http://paste.debian.net/930459/

**Comment by gravyboat** [comment]
Thanks for providing this, maybe you could add it to your repo: https://github.com/cirrusUK/soptv or create a new one directly associated with this? For now I'm going to close this since it isn't really an issue, but people will be able to find it if they search for shell based keywords in the issues section. Thanks again!
