### ISSUE TITLE
segment-threads not working on twitch

### ISSUE THREAD

**Issue by Julz2k** [streamlink/streamlink#898]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by Julz2k** [comment]
segment-threads not working any longer on Twitch?!
A month a go everything was fine, now it has no affect even if I set the threads to 10 compare to 1 thread.

My ISP has backbone issues so my downstream is limited to 100-300/kbs per connection cause of overload. But I can still get 300Mbit if I just use enough connections.

**Comment by gravyboat** [comment]
We're going to need way more details than what you've provided. What does the command you're running look like? Do you get any sort of output when you run in verbose `-v` and debug `-l debug` mode? What does the output look like in general?

**Comment by bastimeyer** [comment]
@Julz2k, could you please provide a debug log, like @gravyboat has mentioned?

Please be aware that there a different segment-threads parameters. On Twitch, you need to use the HLS one (`--hls-segment-threads`).

I'm going to close the thread, since there hasn't been any response in 17 days. Please feel free to reopen  if this issue persists or if you think that it's a bug in streamlink that needs to be fixed.
