### ISSUE TITLE
How to improve the myfreecams plugin

### ISSUE THREAD

**Issue by horacio9a** [streamlink/streamlink#901]
### Checklist
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
There are so-called "No Mobile Feed" models in the MFC that are exclusively tied to the rtmp protocol and currently almost all MFC Recoders avoid or record them. 
Of course, they can be recorded but not using standard rtmpdump.exe, but using rtmpsuck.exe and most other systems that do not use standard rtmpdump.exe.
I know for sure that this could be done using python-librtmp (0.3.0) https://github.com/chrippa/python-librtmp/tree/master/librtmp

This is an old example. For a script to work, it should have fresh data for a particular "No Mobile Feed" model:

http://www.mediafire.com/file/rot9uc6c60v3jpl/mfcnm.py

I have discovered that so-called "No Mobile Feed" have camserv <840 so it can easily be used to redirect to right method for stream recording

Operating system and version: Windows 7
Streamlink and Python version: 0.5.0 / 2.7.13

**Comment by beardypig** [comment]
You can achieve the same using the standard `streamlink` stream arguments feature:
```
streamlink "rtmp://video483.myfreecams.com/NxServer playpath=vywvjnwtihktlhgymnsmaxhxecrnoykn conn=[\"N:438688409\", \"S:vywvjnwtihktlhgymnsmaxhxecrnoykn\", \"N:19149701\"]" best
```

**Comment by horacio9a** [comment]
Thank you very much for your suggestion. I will try to add this part to the existing Streamlink plugin. 
I've modified this plugin a bit so if someone wants to try start position is this:
http://www.mediafire.com/file/kzgvh9w12otnyeu/MFC.rar
![mfc](https://cloud.githubusercontent.com/assets/17076459/25864422/a79e6c90-34ef-11e7-8655-663c6742e950.jpg)

**Comment by bastimeyer** [comment]
Please don't post links to archives or other files hosted on external websites. Even if you want to help to improve Streamlink, those files can contain literally anything and are not suitable for code sharing, since people have to download it and open it first.

If you want to share your code improvements, you should go the regular way and fork the repo, clone it, branch off, commit your changes, push the branch to your fork and then link it here. Then people will be able to directly see your changes including the diff log and you'll be able to make a pull request if desired. AFAIK, nowadays you don't even need any git knowledge anymore (which is sad) and you can do all this stuff on the github website.

If you don't know how git or github works and if you don't want to go this route, you can also simply use https://gist.github.com/, which is a code snippet tool used for linking larger code files or multiple files together.

And although pictures usually say more than thousand a words, images containing pure text should be posted as text alone.

Sorry for playing a teacher here, but I've seen you (and others) doing this multiple times now and I just want to make sure that this doesn't become a place where code/log is regularly being shared externally or within pictures.

**Comment by distance00** [comment]
@beardypig @horacio9a 
If I want to play "No Mobile Feed" stream with vlc, does this command do the job?
streamlink "rtmp://video483.myfreecams.com/NxServer playpath=vywvjnwtihktlhgymnsmaxhxecrnoykn conn=[\"N:438688409\", \"S:vywvjnwtihktlhgymnsmaxhxecrnoykn\", \"N:19149701\"]" best
I know how to find the server name and the model id but how do I find the playpath and the \"N:438688409\", \"N:19149701\"? 
If the playpath is 'mfc_119149701' ,then the second number is model id? what's the first number? how do I get it? Could somebody enlighten me a little bit?

**Comment by distance00** [comment]
Ok, I installed rtmpdump, found out the playpath and cache_id (the other number?), it didn't work.
streamlink "rtmp://video727.myfreecams.com:1935/NxServer playpath=mp4:mfc_125670731.f4v conn=[\"N:1510384536\", \"S:mp4:mfc_125670731.f4v\", \"N:25670731\"]" best
This didn't work either.
streamlink "rtmp://video727.myfreecams.com:1935/NxServer playpath=mp4:mfc_125670731.f4v conn=["N:1510384536", "S:mp4:mfc_125670731.f4v", "N:25670731"]" best

**Comment by Alexo88** [comment]
its working?

**Comment by martin47574** [comment]
Can anybody please explain to a complete newbie how to stream and record mfc? 

I learn pretty fast, but this is really newland to me. I would be very greatful!

**Comment by gravyboat** [comment]
@martin47574 We've removed this plugin and it is no longer supported. Locking this topic as well since it's old.
