### ISSUE TITLE
Twitch streams on raspberry pi 2 stay frozen when they start

### ISSUE THREAD

**Issue by badf** [streamlink/streamlink#933]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I'm trying to watch livestreams on my netcast lg smart tv since plex won't work and there's no twitch apps for it.

### Expected / Actual behavior

Tried to watch twitch.tv/macmillancancer as a test, but when the stream loads, VLC loads up and it appears but stays frozen (like it's paused) when it's supposed to be playing normally

### Reproduction steps / Explicit stream URLs to test

1. installed streamlink
2. installed vlc
3. ran "streamlink twitch.tv/macmillancancer 360p" on raspberry pi terminal

### Environment details

Operating system and version: Raspbian 4.4
Streamlink and Python version: Both are latest versions

**Comment by gravyboat** [comment]
We're going to need more details, can you run with the `-l debug` and `-v` options?

**Comment by bastimeyer** [comment]
This sounds like a VLC rendering issue to me.
Could you please write the stream to your filesystem (by using the `-o "recording.ts"` parameter) and analyse it with ffmpeg afterwards (`ffprobe -v error -show_format -show_streams -print_format json recording.ts`), so we can be sure that the stream gets downloaded correctly? If there are no errors, then it's either an issue with piping the data to VLC (unlikely), or a Python / dependency issue, or no Streamlink issue at all and caused by your system instead. But as @gravyboat already said, a debug/player log would be appreciated.

**Comment by badf** [comment]
I ended up not using streamlink but instead installing osmc and using the twitch addon. Thanks anyway
