### ISSUE TITLE
(VLC) player crashing / freezing on "networkdrop"(?)

### ISSUE THREAD

**Issue by Zanndorin** [streamlink/streamlink#937]
So yeah this started happening around the time I moved and Streamlink was forked / released. 

When I watch a stream (via Streamlink or Twitch GUI) sometimes the stream [chops/greys](http://puu.sh/vX2gY/b37b263299.PNG) and some times starts replaying the last ~5ish seconds over and over again or just stops completely in this state. Interesting part is that the VLC process in this state cant be closed normally but needs to be killed. 

I think this might be related to a network drop of some kind and the link not being able to reconnect to the stream while starting to just replay its cache.

(I have run the same stream simultaneously in Chrome and have not seen any stutters or drops there.)

### Environment details
Operating system and version: Win7 x64
Streamlink and Python version: 0.6 I think I have Python 3.2 but for some reason I can't find the installed path or add it to my environment variables.. If this might be the issue tell me. Twitch GUI / Streamlink runs great in all other aspects.

**Comment by beardypig** [comment]
If you used the Windows installer then Python is bundled with Streamlink, shouldn't be a problem there... Which version of VLC are you using? Twitch (I assume you're watching twitch?) has made some changes to their streams recently, so it is possible another player (mpv, mpc-hc, etc.) or an updated version of VLC might fare better. 

You can try using the `--player-passthrough hls` option to see if the problem persists, if it does then it's likely a player issue rather than a Streamlink issue. `--player-passthrough hls` tells Streamlink to pass the URL of the HLS stream (which is what Twitch uses) to the player, rather than Streamlink downloading the stream and piping the stream data to VLC.

**Comment by Zanndorin** [comment]
Yeah Twitch is my main use case. VLC hasn't really updated their player that much (I'm using the latest version) but I will start trying out different players and the playerpassthrough option (I think I'm actually already using that / tried that with the problem persisting). I'll update in the next days if it's of any interest and not just a player problem.

**Comment by bastimeyer** [comment]
> I think I'm actually already using that

If you're using the Twitch GUI, you're using the `http` passthrough option by default (because some players on Windows don't support piping 😴). The `hls` option completely bypasses streamlink, and works not that well in combination with the GUI, so you need to change it in the settings menu first, which requires enabled advanced settings (Streamlink doesn't terminate the player process when its own process gets terminated, which is a feature and useful when using the CLI, but not useful in the GUI, because it doesn't spawn the player process itself).

**Comment by Zanndorin** [comment]
Yeah I'm aware of that. I'm a developer myself and have had this problem for quite some time so I have played around with a lot of options already before posting it here since I somehow wanted to be able to find out if it is a Streamlink bug, Player bug, or just my network connection (or PC or whatever). I'm just not sure anymore what exactly I have tried and what not. I'll retry and confirm your tips here later today and will update.

**Comment by gravyboat** [comment]
@Zanndorin If you can maybe try running Streamlink directly off the command line and pass the `-l debug` and `-v` options if you haven't done so already just to confirm there isn't anything there.

**Comment by Zanndorin** [comment]
Yeah I was running HLS via Twitch GUI. 

Trying running just by Streamlink --player-passthrough hls -l debug -v now.

**Comment by Zanndorin** [comment]
Well the stream started by Twitch GUI itself crashed. Same result with Streamlink started with default parameters. Streamlink started with player-passthrough hls has not failed yet. 

PS: Twitch GUI starts VLC in 64bit and Streamlink in 32bit.

**Comment by Zanndorin** [comment]
I have been able to introduce similar crashes in Streamlink player-passthrough by throttling the network. It starts the same loop as all other streams (only difference is that you can still close VLC without using the task manager) and also that it tried to reconnect more often than in other cases. Logs are "empty".

**Comment by back-to** [comment]
If you use `--player-passthrough hls`, you are using streamlink only to get the playlist url,
after this the player has to deal with network issues.

That is why `-l debug` is empty, streamlink already did everything it was told to.

Without `--player-passthrough hls`, streamlink will correctly recover.

You might use
https://streamlink.github.io/cli.html#cmdoption-hls-timeout
for a bad connection.

---

Closing.
