### ISSUE TITLE
Freezing / Closing with Dark Souls 3?

### ISSUE THREAD

**Issue by vicjpapa** [streamlink/streamlink#948]
Weird interaction with Dark Souls 3.  The stream works everywhere except when playing this particular game.  It freezes when using MPC-HC (audio still goes through) and VLC outright crashes.  Running a debug log doesn't reveal anything of interest.  Issues appear when using both shell and twitch gui

Environment

Windows 7 x64
Streamlink latest Windows Installer

Thank you

**Comment by gravyboat** [comment]
I have no idea why this would be a problem. I've watched people play Dark Souls 3 as recently as Monday evening without an issue. So you're telling me if you go here: https://www.twitch.tv/directory/game/Dark%20Souls%20III and try any of those streams that VLC immediately crashes for you no matter which stream you select? If that's the case can you run Streamlink off the command line with the `-l debug` and `-v` options?

**Comment by vicjpapa** [comment]
I'm very sorry I think my post wasn't clear.

What I meant is when I PLAY Dark Souls 3 while watching any twitch stream the stream freezes which doesn't happen when I play any other game.

I hope this makes it clearer I apologize for the confusion.

**Comment by gravyboat** [comment]
Oh yeah there's nothing we can do about that unfortunately. That's due to an interaction issue between the game and how the video application typically (it's pretty common for a lot of games when they launch). You can try to tab out, relaunch the stream, and tab back in, or give some of the suggestions here a shot: https://forum.videolan.org/viewtopic.php?t=55041 for VLC at least. I'm going to close this since there's nothing we can do about this. If you Google around for it you'll see this is surprisingly common which sucks.
