### ISSUE TITLE
Support the presence/status system for twitch

### ISSUE THREAD

**Issue by Socialery** [streamlink/streamlink#996]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Support the presence/status system for twitch

### Expected / Actual behavior

When watching a twitch stream, the user's status is expected to update to reflect that, It doesn't

### Reproduction steps / Explicit stream URLs to test

1. authenticate with twitch via `--twitch-oauth-authenticate`
2. watch a stream

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: 0.6.0 on python 3.6

...

### Comments, logs, screenshots, etc.

this thing: ![image](https://user-images.githubusercontent.com/3059973/27011231-b19095c2-4ef6-11e7-96ce-3f4cb99392ee.png)

api url: `https://api.twitch.tv/kraken/users/:id/status`

example post data:

```json
{"session_id":"xxxxxxxxx",
 "availability":"idle",
 "activities":[
    {"type":"watching",
     "game":"Heroes of the Storm",
     "channel_display_name":"Heroes of the Storm",
     "channel_login":"blizzheroes",
     "channel_id":"48937001"}
 ]}
```

I don't know if any non-official api key can access that API, I couldn't find it in the docs.

**Comment by bastimeyer** [comment]
I'm not sure if this kind of logic belongs into Streamlink. Streamlink's only job is to fetch stream data from streaming services and then do some stuff with that data.

I understand that the user activity status serves a purpose on the Twitch website, but it is totally unrelated to the functionality of Streamlink. IMO, this kind of stuff belongs into 3rd party applications. As a suggestion on my side, you could make a feature request on the Streamlink Twitch GUI, but I'm not sure if it's worth implementing it there, since the user activity is tied to the friends and chat system, which is not implemented there.

-----

Regarding a potential implementation:

The API endpoints which are used here are not part of the public Twitch API (v5), which is usually the case for stuff that's not considered stable yet or which changes a lot, since it's not meant for the public to be used. If you want to set a user's activity, you also need to be aware of the user's settings first, which includes two options for disabling updating the activity (user being invisible or prohibiting status updates).
`https://api.twitch.tv/kraken/users/:id/status`
`https://api.twitch.tv/kraken/users/:id/status/settings`

Watching multiple streams at once would also be a bit problematic if it was implemented into Streamlink directly. Each request requires a session ID, which is generated randomly and then SHA1'd and substr'd to a length of 16 chars. Since this session ID can not be shared between multiple streamlink processes, the user's activity would be overwritten by each Streamlink process with different data.

**Comment by gravyboat** [comment]
I agree with @bastimeyer and his response covers the concerns I have thoroughly. We generally try to keep Streamlink exceptionally light with check ins (so much so that we even dropped checking for Streamlink updates automatically!) and that's something I really like about this project. We allow for integrations and wrappers pretty easily but the core portion of Streamlink needs to try and stay tightly focused on what it was originally designed for, otherwise it will quickly become bloated.

**Comment by gravyboat** [comment]
I'm going to mark this as out of scope for the time being and close it since no one has weighed in.
